### ISSUE TITLE
Exclude CSRF protection on GET|HEAD request 

### ISSUE THREAD

**Issue by TseWaiHo** [laravel/passport#1002]
I would like to exclude CSRF protection on GET|HEAD request, or provide a mechanism to do that. 
In main Laravel framework, get|head request is already excluded from CSRF protection. 
Ref: https://github.com/jimrubenstein/laravel-framework/blob/master/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php
line 60.

There was an issue also ask about consume GET api without CSRF protection.
https://github.com/laravel/passport/issues/212

Also, Angular's HttpClientXsrfModule do not send XSRF token on GET|HEAD request for some reason, may be security reason. 

Currently, I put these into AuthServiceProvider as my temporary solution.

```
    public function boot(Request $request)
    {
        $this->registerPolicies();

        if ($request->isMethod('get')) {
            Passport::ignoreCsrfToken(true);
        }
    }
```

**Comment by driesvints** [comment]
Your temp solution is actually valid. At the moment we're not considering adding anymore functionality to disable csrf but would rather make Passport stateless. See https://github.com/laravel/passport/issues/379
