### ISSUE TITLE
I hope I can get the client used by the current user in findForPassport() and validateForPassportPasswordGrant().

### ISSUE THREAD

**Issue by hangzhouyifei** [laravel/passport#1007]
I hope I can get the client used by the current user in findForPassport() and validateForPassportPasswordGrant().

In some more complex applications, users can log in through different clients, but in some cases, the login logic of different clients cannot be the same.

For example, a user can use both WeChat and App customers at the same time, but WeChat uses OpenID to log in, and App uses user name and password to log in. At this time, it is necessary to judge whether the client used when logging in is WeChat or App. It seems that you can only use request('client_id') to make judgments. I hope that Passport can add corresponding methods that can get the current client instance before, such as Passport::getCurrentClient()

**Comment by driesvints** [comment]
Please see https://github.com/laravel/passport/issues/882
