### ISSUE TITLE
message:unathunicated

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [laravel/passport#1009]
hi i install and config passport 7.2 with laravel 5.7
and this is auth.php settings
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ]

after i do login by postman and get the token that generated 
after that i can't do anything with token cause always get message:unathunicated
it is look like there is something with login

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by darvishiyan-mahdi** [comment]
i look all those websites and after 3-4 day of search i come to finally ask from the source
