### ISSUE TITLE
Client - User relation, with custom foreignKey

### ISSUE THREAD

**Issue by T0miii** [laravel/passport#1012]
Hello,

For legacy systems or database schemas where the primary key in the table is not called ID, we need a way to pass the foreignKey to the Client model.

`````
    public function user()
    {
        return $this->belongsTo(
            config('auth.providers.'.config('auth.guards.api.provider').'.model'), 'user_id'
        );
    }

`````

Maybe with a config param or directly from the user model?

**Comment by driesvints** [comment]
Think it's best to get the class from the config and use the `getKeyName` method.

**Comment by driesvints** [comment]
Heya, please see the solution I posted here: https://github.com/laravel/passport/pull/1013#issuecomment-490907489
