### ISSUE TITLE
404 Not Found | Fresh install laravel 5.8

### ISSUE THREAD

**Issue by jeraldpunx** [laravel/passport#1015]
I've follow the guide from laravel documentation https://laravel.com/docs/5.8/passport , but it gave me a 404 not found.

This is my route list, it is listed there `/oath/token` but when I access it on postman, it return me as 404 not found.

[![enter image description here][1]][1]

[![enter image description here][2]][2]

----------

[![enter image description here][3]][3]

This is my current `public/.htaccess`

    <IfModule mod_rewrite.c>
        <IfModule mod_negotiation.c>
            Options -MultiViews -Indexes
        </IfModule>
    
        RewriteEngine On
    
        # Handle Authorization Header
        RewriteCond %{HTTP:Authorization} .
        RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    
        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_URI} (.+)/$
        RewriteRule ^ %1 [L,R=301]
    
        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]
    </IfModule>

  [1]: https://i.stack.imgur.com/XJSkn.png
  [2]: https://i.stack.imgur.com/uXF9p.png
  [3]: https://i.stack.imgur.com/de1mo.png

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jeraldpunx** [comment]
Sorry I need to closed this, it's `oauth` not `oath`

**Comment by Atom-Technologies** [comment]
Solutions? Anybody?

**Comment by webwizard02** [comment]
Hello! Please check your apache's httpd.conf file. Make sure that you enabled t h `LoadModule rewrite_module modules/mod_rewrite.so` by removing the # from the start line of the code.

And also change inside the httpd.conf from Require all denied to Require all granted, AllowOverride All, and Options Indexes FollowSymLinks

Like This:
`<Directory />
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>`

**Comment by hoangngoclam** [comment]
I have a save problem, I run "php artisan serve" and it oke

**Comment by HashmatWaziri** [comment]
> Hello! I also encountered this problem before. Please check your Apache's httpd.conf file. Make sure that you enabled the `LoadModule rewrite_module modules/mod_rewrite.so` by removing the `#` from the start line of the code.
> 
> And also change inside the httpd.conf from Require all denied to Require all granted, AllowOverride All, and Options Indexes FollowSymLinks
> 
> Like This:
> ![Capture](https://user-images.githubusercontent.com/13413228/63312807-2dc3cb00-c335-11e9-827e-86c983773aa9.PNG)

Man, after 6 hours managed to find this solution. Thanks a lot. Worked like a charm.

**Comment by nsadik918** [comment]
[7backpage.com](url)
Most of you might have already have heard about Craigslist, Craigslist is one of the best [backpage ](url)alternative sites. In fact Craigslist was one of the very first sites that have started classified-ads and soon it expanded to many categories. Craigslist remains one of the most visited website in the world, it offers services in over 100+ countries. The good thing about Craigslist is you don’t have to pay a cent or penny to post ads on the website
