### ISSUE TITLE
grant_type not being recognized. 

### ISSUE THREAD

**Issue by pneves001** [laravel/passport#1019]
- Passport Version: #.#.#
"laravel/passport": "^7.2"
- Laravel Version: #.#.#
"laravel/framework": "5.8.*",
- PHP Version: #.#.#
"php": "^7.1.3",
- Database Driver & Version:
pgsql
### Description:
The following parameters are returning the specified error: 

grant_type: password
client_id: 2
client_secret: Dy1hUVkIPM9hWb2dMGrtf6GxpkSzRX6PwGZICYN6
username: KNENbAdYGM@gmail.com
password: secret
scope: * 

Response: 

{
    "error": "unsupported_grant_type",
    "error_description": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check that all required parameters have been provided",
    "message": "The authorization grant type is not supported by the authorization server."
}

### Steps To Reproduce:
I'm using artisan serve on my localhost as the server. I'm just trying to get passport working and I'm following the following youtube video.

**Comment by pneves001** [comment]
https://www.youtube.com/watch?v=isTZTfJV0-I&t=619s

**Comment by pneves001** [comment]
This appears to be some sort of incompatibility with laravel passport and laravel 5.8.  Not sure why its doing it. But I've now tried installing multiple versions of passport and it still doesn't work.

**Comment by Sephster** [comment]
Strange that it says authorization grant type in the error message. Are you sure you are issuing a password grant request?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mviljoen** [comment]
@pneves001 did you ever solve this problem? I'm experiencing the same.

**Comment by pneves001** [comment]
I think I did fix it. I can't remember how though. It's been several months. 

Oh I think it was an issue with my routes file.  

Your route needs to be preceded by the following:

Route::middleware('auth:api')->post('/your-route', 'yourcontroller@yourfunciton'); 


This is the functions you wish to secure with authentication. 

The login function doesn't contain this.  I think you need to assign a name to your routes as well.  

I recall there being something with the header in your request as well. You have to set it to like Bear Token and then add the token.  You can do that in postman to test it.

**Comment by Asjamuar** [comment]
I am facing this exact same issue.

![image](https://user-images.githubusercontent.com/25499043/65960976-40bcd580-e473-11e9-94c0-73485499aa31.png)

Did anyone find a solution?

**Comment by aurigadl** [comment]
Unfortunately, there is no support that really provides a solution to this problem. The solution for my case is to install the latest version of Laravel with the passport version 7.5.1. With this version, it works correctly and this error does not occur.
It is not a problem of bad use of the tool is a bug present in some specific conditions.

{
"error": "unsupported_grant_type",
"error_description": "The authorization grant type is not supported by the authorization server.",
"hint": "Check that all required parameters have been provided",
"message": "The authorization grant type is not supported by the authorization server."
}

**Comment by sokbunthean** [comment]
![image](https://user-images.githubusercontent.com/55421732/74304445-97c2a780-4d8f-11ea-86f9-a0660000fa42.png)
 I'm problem with unsupport_grad_type . did anyone find?

**Comment by sokbunthean** [comment]
laravel V6 last version

**Comment by mohavee** [comment]
i had same problem, be sure you are sending in request header `content-type: application/x-www-form-urlencoded`

working code

```
$data = [
    'username' => 'admin@admin.sk',
    'password' => 'password',
    'client_id' => '2',
    'client_secret' => 'qvH2Ij0vMCx7w4SAW0sB1oUCrYBnNyz8AzNNfeKC',
    'grant_type' => 'password',
];
$request = app('request')->create('/oauth/token', 'POST', $data);
$response = app('router')->prepareResponse($request, app()->handle($request));
```

**Comment by albertosoho** [comment]
I'm having the same problem. The only working solution was to downgrade to 7.5.1 version.

**Comment by markryandelarmente** [comment]
@mohavee It's working. Thanks

**Comment by paulocuambe** [comment]
Thanks @mohavee.

**Comment by gerymeli** [comment]
> $data = [
>     'username' => 'admin@admin.sk',
>     'password' => 'password',
>     'client_id' => '2',
>     'client_secret' => 'qvH2Ij0vMCx7w4SAW0sB1oUCrYBnNyz8AzNNfeKC',
>     'grant_type' => 'password',
> ];
> $request = app('request')->create('/oauth/token', 'POST', $data);
> $response = app('router')->prepareResponse($request, app()->handle($request));

@mohavee thanks It's working for me

**Comment by antonkomarev** [comment]
@mohavee thanks! That saved huge amount of time for me.

**Comment by SnakeO** [comment]
Careful if you're testing in Postman that you're setting the variables in the BODY tab and not the PARAMS tab

**Comment by PetarCehoo** [comment]
In my case i had to register the provider in config/app.php file and then it returned the access token

**Comment by skipzenni** [comment]
i share solution for resolve this problem.
first u need instal auth
laravel 5 down  use make:auth
laravel 5 above use 
~ composer require laravel/ui
~ php artisan ui vue --auth
~ npm install
~ npm run dev

and more important create user using it dont create manualy on db
hope this helpfull

**Comment by Mate38** [comment]
> npm run dev

It's not necessary, but when u add directly on db remember that the password need to be encripted

**Comment by mdashikur9090** [comment]
> i had same problem, be sure you are sending in request header `content-type: application/x-www-form-urlencoded`
> 
> working code
> 
> ```
> $data = [
>     'username' => 'admin@admin.sk',
>     'password' => 'password',
>     'client_id' => '2',
>     'client_secret' => 'qvH2Ij0vMCx7w4SAW0sB1oUCrYBnNyz8AzNNfeKC',
>     'grant_type' => 'password',
> ];
> $request = app('request')->create('/oauth/token', 'POST', $data);
> $response = app('router')->prepareResponse($request, app()->handle($request));
> ```

It's working. Thanks

**Comment by tilakpoudel** [comment]
On my case, (for grant_type, client_credentials) it worked by sending `'grant_type' => 'client_credentials'` in the request independent of content-type.
```
{
    "client_id" : 8,
    "client_secret": "S4zfPzR6mHdbFfDVh9iLU0WEkfJdpEf7HBORByKa",
    "grant_type": "client_credentials"
}
```
