### ISSUE TITLE
username(not email) and password to issue password grant 

### ISSUE THREAD

**Issue by vijaythecoder** [laravel/passport#102]
Right now it is hard coded with email in the 
`passport/src/Bridge/UserRepository.php` line number 42
```php
$user = (new $model)->where('email', $username)->first();
```
how to override it to username?

**Comment by craigpaul** [comment]
There is a method you can include on your model (most likely `User`) that can be used to override that functionality. Right above where you found `->where('email...` there was this.

```
if (method_exists($model, 'findForPassport')) {
    $user = (new $model)->findForPassport($username);
} else {
    $user = (new $model)->where('email', $username)->first();
}
```

All you need to do is add the `findForPassport()` method to your user model and you will be good to go. An example implementation of this could look like this.

```
public function findForPassport($username)
{
    return $this->where('username', $username)->first();
}
```

**Comment by vijaythecoder** [comment]
Thanks it worked!

**Comment by metallurgical** [comment]
Really helped!

**Comment by tobsbola** [comment]
Thanks @vijaythecoder 

To have the flexibility of both username and email,

`
    // to override email and use either email or username to authenticate
    public function findForPassport($username)
    {
        return $this->where('username', $username)->orWhere('email', $username)->first();
    }
`

**Comment by alexeycrystal** [comment]
Yup! Nice solution! Thanks!

**Comment by EdoYogatama** [comment]
How if i use custom table for auth? does it really override the method? i've tried this but, always return sqlstate error
