### ISSUE TITLE
[Feature Request] passport:keys with Load Balancer

### ISSUE THREAD

**Issue by 3alampro** [laravel/passport#1020]
Hello,

when working with load balancer and many application servers we have an issue generating api authentications keys since `php artisan passport:keys` will generate different key files on each server when we deploy our code.

in the latest updates in passport we can specify locations to load keys from path for api authentications keys via `Passport::loadKeysFrom('/secret-keys/oauth')` or store our keys in env variables -this can be huge text in the env var- 

can we have more options out of the box like using Redis as storage for the keys before generating files  this will ensure generating the same files on each application server when we deploy our code

I did create laravel command using Redis to store the keys before generating any files on our app servers to avoid this issue here is the code 

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use phpseclib\Crypt\RSA;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Cache;
use Laravel\Passport\Passport;

class GeneratePassportKeys extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'passport:keys-redis
                                      {--force : Overwrite keys they already exist}
                                      {--length=4096 : The length of the private key}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create the encryption keys for API authentication from redis storage';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @param \phpseclib\Crypt\RSA $rsa
     * @return mixed
     */
    public function handle(RSA $rsa)
    {
        $keys = $rsa->createKey($this->input ? (int)$this->option('length') : 4096);

        list($publicPath, $privatePath, $publicKey, $privateKey) = [
            Passport::keyPath('oauth-public.key'),
            Passport::keyPath('oauth-private.key'),
            Cache::store('redis')->tags(['laravel_passport'])->get('PASSPORT_PUBLIC_KEY'),
            Cache::store('redis')->tags(['laravel_passport'])->get('PASSPORT_PRIVATE_KEY')
        ];

        if (($publicKey || $privateKey) && !$this->option('force')) {
            $this->error('Encryption keys already exist on redis. Use the --force option to overwrite them.');
        } else {
            Cache::store('redis')
                ->tags(['laravel_passport'])
                ->put('PASSPORT_PUBLIC_KEY', Arr::get($keys, 'publickey'));

            Cache::store('redis')
                ->tags(['laravel_passport'])
                ->put('PASSPORT_PRIVATE_KEY', Arr::get($keys, 'privatekey'));

            list($publicKey, $privateKey) = [
                Cache::store('redis')->tags(['laravel_passport'])->get('PASSPORT_PUBLIC_KEY'),
                Cache::store('redis')->tags(['laravel_passport'])->get('PASSPORT_PRIVATE_KEY')
            ];
        }

        file_put_contents($publicPath, $publicKey);
        file_put_contents($privatePath, $privateKey);

        $this->info('Encryption keys saved to storage folder successfully.');
    }
}
```

I think this can be improved and shipped with passport out of the box, many can use it to avoid keys generating issues on many applications server

**Comment by driesvints** [comment]
Heya, thanks for suggesting. I personally don't see why this would be useful besides loading the keys directly. If you just provision the keys on each server and load them in with the default solution why would you still use something like the above instead?

**Comment by 3alampro** [comment]
Hello @driesvints,

when working with multiple application server behind load balancer and use `php artisan passport:keys` this command will generate different keys on each server This means an access token issued on one server might not be accepted on another.

So to fix it we need to store the keys on one location that all server can access something like s3 or cache driver to generate the same key files on all servers so you will not end with issues like 
#802 
#730

So the easiest in my opinion is to store the keys on Redis or any cache driver and use the stored keys to generate the same files on all servers since any one using load balancer with many server architects will use single Redis server or any other cache Service and all applications servers will have access to it for sessions and cache to work properly

storing the keys on cache or db before generating the files will work with both single tier server and multi tier server

**Comment by driesvints** [comment]
But you don't need to use `php artisan passport:keys` on each server separately. You only need to run it once and then use the same keys on each server.

**Comment by 3alampro** [comment]
> But you don't need to use `php artisan passport:keys` on each server separately. You only need to run it once and then use the same keys on each server.

Yes you can but it’s easier to have artisan command to achieve the same result without copying files from one server to many each time you create new server or update it when needed on all servers

We use Laravel Forge to provision servers and link each site with github repo with simple artisan command we can generate or update the files on all servers without accessing any server from our staff or copying files between servers limiting any abuse to these files or leaks also automating the process saves alot of times and prevents future issues forgetting these files like what happened to us on critical project we are working on

**Comment by driesvints** [comment]
I'm sorry but at the moment we aren't considering to add support for this. A best practice is to use the same keys on each server. You may use several solutions for this. I think the `.env` option might work best for you.

**Comment by superern** [comment]
I had same problem when using load balancer in AWS Elastic Beanstalk. There are few solutions but this is the cleanest way I found.

https://stackoverflow.com/a/54517514/4544724
