### ISSUE TITLE
Token expires before time.

### ISSUE THREAD

**Issue by bellalMohamed** [laravel/passport#1021]
- Passport Version: ^7.2
- Laravel Version: 5.7.*
- PHP Version: 7.3.1
- Database Driver & Version: mysql, 5.7.26

### Description:
The token is expired also the expiration time is still one year ahead

### Steps To Reproduce:
I'm using a multi-auth technique in laravel passport by changing the guard provider on the fly to match my desired Model, and it works fine - not sure if that is the problem -, but after couple of a day the token is expired for no reason.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
