### ISSUE TITLE
How to use Passport as a SSO instance?

### ISSUE THREAD

**Issue by ProteanCode** [laravel/passport#1026]
On example Server A is a SMS microservice, Server B is a SSO server

Can I include passport in both server instances (with only one of them calling Passport::routes() method), and instruct them to reuse same database for authentification?

In this way, the SMS Server A could use middleware and scopes out of the box, but requesting the access tokens could be done only through Server B as its the only server with call to Passport::routes() method

Am I going the right way?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
