### ISSUE TITLE
laravel 5.8

### ISSUE THREAD

**Issue by cntoss** [laravel/passport#1027]
- Guzzle Oauth2
- Laravel Version: 5.8

### Description:when i try this below code i got error as:GuzzleHttp \ Exception \ ClientException (400)
Client error: `GET https://login.mailchimp.com/oauth2/token` resulted in a `400 Bad Request` response

### Steps To Reproduce:the code is:

  Route::get('/hello', function () {
     $query = http_build_query([
        'client_id' => 455,
        'redirect_url' => 'http://127.0.0.1:8000/list',
        'response_type' => 'code',
        'scope' => ''
      ]);
     return redirect('http://login.mailchimp.com/oauth2/authorize?'.$query);
  });

  Route::get('/list', function (Request $request) {
    $http = new GuzzleHttp\Client;
    $response = $http->POST('https://login.mailchimp.com/oauth2/token', [
        'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => '45252',
            'client_secret' => 'sdfghjkdfghjkfghj',
            'redirect_uri' => 'http://127.0.0.1:8000/success',
            'code' => $_GET['code'],
        ],
    ]);
    return json_decode((string) $response->getBody(), true);
});

**Comment by driesvints** [comment]
Please fill out the full issue template.
