### ISSUE TITLE
token()->expires_at not properly mocked

### ISSUE THREAD

**Issue by meyer59** [laravel/passport#1031]
-Passport Version: v7.3.0
-Laravel Version: 5.8.19
-PHP Version: PHP 7.3.3-1+020190307202245.32+stretch1.gbp32ebb2 (cli) (built: Mar 7 2019 20:22:46) ( NTS )
-Database Driver & Version: Mysql

### Description:
 If we use  `Passport::actingAs($user)`
and then we try to get the `expires_at`, it will return `false` instead of the expires date.
### Steps To Reproduce:
Assuming you have a Passport oAuth login in place already:
create a test and execute: 
 `Passport::actingAs($user);`
`$user->token()->expires_at; // return false instead of the Date`
Cordially

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. 

Thanks!

**Comment by meyer59** [comment]
Hi
Thanks for your response,
You can reproduce this bug by cloning this repo (see instructions there) [https://github.com/meyer59/laravel-passport-bug](url)

**Comment by driesvints** [comment]
@meyer59 I can't get the MySQL file to import in my local db. Not sure what's going on.

**Comment by meyer59** [comment]
Any errors to show?
The file will create a db `test` so you may have a conflit if you already have one with the same name . You can open the file and copy/paste queries in a fresh db of your choice.
Let me know if i can help

**Comment by meyer59** [comment]
Hi @driesvints
Did you have a chance to review the issue?

**Comment by driesvints** [comment]
@meyer59 no I'm afraid not. Not sure when I'll get to this sorry... bit swamped atm.

**Comment by narwy** [comment]
It's working fine, looks like an issue on your end. Latest version of laravel/passport + Laravel.

`return  $request->user()->token()->expires_at;`
returns `2019-06-24T20:26:04.000000Z`

Try see what data you have in `$request->user()` print it out, if it's null you have an issue passing the token and getting the user data in the request.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by meyer59** [comment]
Hi
I just tested again and the issue is still here and not fixed
Cordially

**Comment by driesvints** [comment]
I took another look at this and I'm afraid this isn't possible. The actual token model isn't used but a mock is used instead. So the token method will return a Mockery mock. And the mock is specifically set to return `false` on any call.

If you call `$user->token()` you'll get a mock back and you can set expectations on it just like in other situations with using mocks from Mockery.

**Comment by meyer59** [comment]
For people searching for the solution here it is: 

`$user->token()->shouldReceive('getAttribute')->with('expires_at')->andReturn(Passport::$tokensExpireAt);`
This should set the `$user->expires_at` to `Passport::tokensExpireIn(...);`

**Comment by lk77** [comment]
@driesvints i bumped into this issue, 
i don't think that currently in passport 11, actingAs is working as expected, because the token is neither a valid model, neither a mock, 
it's an empty token, like if someone did `new Token()`, all attributes are empty in that token,

i have a bit of code that make use of the id of the token, and doing $user->token()->id return null at the moment.

the solution for me was to bypass the actingAs method as such :

```
$user = User::factory()->create([...]);
$token = Token::factory()->create([...]);
$user->withAccessToken($token);
app('auth')->guard('api')->setUser($user);
```
and that worked fine.
