### ISSUE TITLE
Laravel 5.8 passport always return unauthenticated

### ISSUE THREAD

**Issue by abdullah-abunada** [laravel/passport#1033]
Hello,

After installing and configuring as documentation passport on Laravel 5.8, it always return unauthenticated  401.
I notice the api skip passport driver and goes throw token driver, because when I call it it throw database error api_token column not found on user table. 

Thanks!

**Comment by abdullah-abunada** [comment]
Hello,

I found the problem, it is because the app configuration are cached, just I run
`php artisan config:cache  ` 
and every thing are going fine.
Thanks

**Comment by SalahMadih** [comment]
I have the same error,

**Comment by asif-aly** [comment]
In case you are using Apache Server, Add this line to your httpd.conf file.

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
