### ISSUE TITLE
Invalid scope(s) provided when authorizing `*`

### ISSUE THREAD

**Issue by danieldevsquad** [laravel/passport#1035]
- Passport Version: v7.3.0
- Laravel Version: v5.8.26
- PHP Version: 7.3.4
- Database Driver & Version: MySQL

### Description:
When requesting the scope `*` we are assuming that all scopes will be related to that authorization request, however, when protecting the route with the middleware 

```
->middleware([
        'auth:api',
        'scope:users-read'
    ])
``` 

I get an exception `Invalid scope(s) provided.`

### Steps To Reproduce:

```
Passport::tokensCan([
     'users-read'  => 'Read basic information about users',
]);
```

Then protect a route with the middleware  'scope:users-read' and get a token using the `authorization_code` flow asking for the scope `*`.

When accessing the the route you will get the error.

**Comment by alshf89** [comment]
According to Laravel passport documentation `*` only work for `Password Credentials` & `Client Credentials` Grant type and it is not working for `authorization code` Grant type.

Please read these sections:
[Requesting all scopes](https://laravel.com/docs/5.8/passport#requesting-all-scopes)

> When using the password grant or client credentials grant, you may wish to authorize the token for all of the scopes supported by your application. You can do this by requesting the * scope. If you request the * scope, the can method on the token instance will always return true. This scope may only be assigned to a token that is issued using the password or client_credentials grant.

[Assinging scopes to tokens](https://laravel.com/docs/5.8/passport#assigning-scopes-to-tokens)

> When requesting an access token using the authorization code grant, consumers should specify their desired scopes as the scope query string parameter. The scope parameter should be a space-delimited list of scopes.

**Comment by driesvints** [comment]
Please see the docs above.

**Comment by danieldevsquad** [comment]
I understand that, but I wonder why they are accepted in the first place. Passing `*` as a scope for the authorization code flow is as valid as passing `Feb 31, 2020` to a date. 
Any ideas on how to prevent that from happening?
