### ISSUE TITLE
Laravel_token not generating when multiple guards

### ISSUE THREAD

**Issue by MikeJones29** [laravel/passport#1036]
- Passport Version: 7.3
- Laravel Version: 5.8
- PHP Version: 7.3.4
- Database Driver & Version:
Server version: 10.3.14-MariaDB-1:10.3.14
### Description:
Issue is: Laravel_token is not generating when using consume own API
I mentioned more details on: https://stackoverflow.com/questions/56846006/laravel-passport-wont-create-laravel-token-and-then-error-401-unauthenticated-wi

But I believe there is an issue on this function:
`protected function requestShouldReceiveFreshToken($request)
    {
        return $request->isMethod('GET') && $request->user($this->guard);
    }
`
in vendor\laravel\passport\src\Http\Middleware\CreateFreshToken.php line : 81
When consuming our API, there is no user, so it is clearly cannot create cookie, why it reaches to this line?
### Steps To Reproduce:
Mentioned at
https://stackoverflow.com/questions/56846006/laravel-passport-wont-create-laravel-token-and-then-error-401-unauthenticated-wi

**Comment by driesvints** [comment]
Multi-guard isn't supported atm. Please see https://github.com/laravel/passport/issues/161 and https://github.com/laravel/passport/issues/982
