### ISSUE TITLE
Lumen w Passport Application::configurationIsCached() error

### ISSUE THREAD

**Issue by tanthammar** [laravel/passport#1046]
- Passport Version: 7.3.2
- Lumen Version: 5.8.1
- Dusterio Lumen Passport ^5.6
- PHP Version: 7.3.7
- Database Driver & Version: sqlite local db

### Description:
```
In PassportServiceProvider.php line 81:

  Call to undefined method Laravel\Lumen\Application::configurationIsCached()
```

### Steps To Reproduce:
Freshly installed Lumen app, composer require Laravel Passport and dusterio/lumen-passport.
Try to run php artisan list

[Related issue on Dusterio](https://github.com/dusterio/lumen-passport/issues/106)

> It seems the issue is in Laravel Passport, not in my package - this method is called directly from Laravel Passport.

Just found this
https://github.com/laravel/passport/commit/e260c865c218f00e4ad0c445dc45852e254d60c7#commitcomment-34292078

**Comment by driesvints** [comment]
We don’t support Passport integration with Lumen. Please see https://lumen.laravel.com/docs/5.8#compatibility
