### ISSUE TITLE
API Route 404'ing even though it is registered

### ISSUE THREAD

**Issue by b8ne** [laravel/passport#105]
I am developing locally on Homestead

Route/api.php:
`Route::get('/users', 'ApiController@users')->middleware('auth:api');`

Controllers/ApiController.php:

`class ApiController extends Controller
{

    public function users() {

        return response()->json([
            'name' => 'Test',
            'state' => 'State'
        ]);
    }
}

`

php artisan route:list provides:
`api/users                                                 |                                      | App\Http\Controllers\ApiController@users                                             | api,auth:api`

So i am successfully getting a password token via /oauth/token, however I am then unable to use the token in a request to the above, instead I am getting 404'd.

Is anyone aware of this issue, or know of the best way to debug the setup?
Cheers

**Comment by kevindierkx** [comment]
Are you visiting `/users` or `/api/users`? The first one wouldn't work.

**Comment by daeXecutoR** [comment]
@b8ne I have the same problem as you. I solved it by changing it to his:

`Route::get(['middleware' => 'auth:api', '/users', 'ApiController@users')->middleware('auth:api');`

**Comment by b8ne** [comment]
Sorry @kevindierkx only just saw your post.
@daeXecutoR it seems to be working now, it started working after a VM destroy and re init, so must have been something external.
Will close this issue for now.

Just for reference these are the routes im using successfully now.
```php
Route::post('/register', 'ApiRegisterController@register');

Route::post('/sponsors', 'ApiController@sponsors')->middleware('auth:api');
Route::post('/sponsor/{sponsorId}', 'ApiController@sponsor')->middleware('auth:api');
```
