### ISSUE TITLE
Why are there no foreign keys on the user_id columns?

### ISSUE THREAD

**Issue by Helveg** [laravel/passport#1051]
I've noticed that there aren't any foreign keys on the `user_id` columns of for example the `oauth_access_tokens` table. First off, maybe this is already changed? If so, how do I 'republish' the passport migrations if I've upgraded to a newer version? If this is still the case, why aren't the foreign keys included?

**Comment by Helveg** [comment]
Continuing on this: the newer versions of Laravel use a bigInt for the `id` columns. The column type for `user_id` is still a regular int with size 11, again this might be due to my dated passport migrations.

**Comment by drbyte** [comment]
Aside: You can go look at the latest migrations by clicking above, on `Code`, then `database/migrations`.

I can't answer your question about "why" on the foreign keys, other than to surmise that that's being left to you to decide to implement if you want it. 

Others may have deeper insights to offer though.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Helveg** [comment]
@driesvints There's 2 possible bugs I've mentioned but I'm not familiar enough with the package to decide:

* The foreign keys are missing on where there clearly should be some, unless the standard preferred behaviour is to have your database littered with access tokens of deleted users.
* The user_id column type does not match the type of the referenced column for current Laravel versions.

**Comment by driesvints** [comment]
> The foreign keys are missing on columns where there clearly should be some, unless the standard preferred behaviour is to have your database littered with access tokens of deleted users.

I haven't had the need to use foreign keys myself before when using passport. Feel free to publish the migrations and add these yourself. Foreign keys aren't always available in every database language.

> The user_id column type does not match the type of the referenced column for current Laravel versions.

That's true. Feel free to send in a PR or I'll send one in later.

**Comment by clemblanco** [comment]
> Foreign keys aren't always available in every database language.

Does that mean that in general Laravel products don't make use of foreign keys, out of the box, because they are not available with, let's say, SQLite?

But then looking at Jetstream, it seems to be using foreign keys.

https://github.com/laravel/jetstream/blob/28b235c6c6c0ca15987bdc9873ea05a37dce6691/database/migrations/2020_05_21_200000_create_team_user_table.php#L18-L19

I'm happy to publish the migrations and do it myself but was curious to understand.
