### ISSUE TITLE
Private and Provisional URI schemes are disallowed for redirect_uri

### ISSUE THREAD

**Issue by mastacheata** [laravel/passport#1053]
- Passport Version: 7.0

### Description:
Since Passport uses Laravel's own url Validator to check for valid redirect URIs it's impossible to use most private or provisional schemes as recommended by "RFC8252 - OAuth 2.0 for Native Apps" (see:  https://tools.ietf.org/html/rfc8252#page-4) for use with mobile apps or non-web-clients that can't listen on the loopback interface in general. (The latter is recommended for computer software, but isn't possible with the permission structure of modern mobile device operating systems)

The Laravel URL validator is made for forms on websites and will in 99% of all cases be used to validate a web URL. It's not good at all  for private or provisional URI schemes that are either registered with IANA or used in private contexts (like inter-app communication).

### Steps To Reproduce:
Option A: Try to use a valid permanent scheme that isn't hierarchicallly structured and therefore doesn't use the double forward slashes like urn:ietf:params:oauth:grant-type:device_code
You will not be able to pass through any authorization that requires a redirect and will instead see the "One or more redirects have an invalid url format." error-message.

Option B: Use a provisional or private URI scheme not included in the scheme list of the Laravel URL Regex like the android scheme. (see: https://www.iana.org/assignments/uri-schemes/prov/android)
Again you will not be able to pass through any authorization that requires a redirect and will instead see the "One or more redirects have an invalid url format." error-message.

There has been a previous attempt at fixing that behaviour, but I think that went the wrong direction when the author wanted to fix the widely used Laravel URL Validator.

I'd rather fix the broken behaviour of that validation rule separately from simply allowing all kinds of URIs conforming to the scheme set in RFC 3986 for the purpose of redirects.

Here's the corresponding bug report at the main Laravel repo: https://github.com/laravel/framework/issues/29301
There I suggested limiting the current `url` Validator to the most common URI schemes and instead adding a secondary generic URI validator that just checks if the format is valid.
I can see why one wouldn't want a too broad URI validation in the framework when that is used in form validation and stuff like that where one woudl want to prevent website users from doing bad things.
Therefore I would very much welcome it if we could throw the half-hearted URL validator from the main framework out the window in this library and instead use a custom regex to validate just the format.

**Comment by driesvints** [comment]
Isn't the main issue here that we should use a separate "urn" validator for this?

**Comment by mastacheata** [comment]
What definition of URN do you use here?  
1.   The urn-scheme or the general class of URIs that aren't hierarchical or are not included in the too specialized and too generic URL validator of Laravel?  
2.   Or the generic term URN that might apply to private-use schemes and other stuff that isn't covered by the URL validator, but would make sense to use as a redirect_uri nonetheless?  

If we're talking about 2. I'm all with you, I just don't know how to approach this.
I can pretty much see 3 approaches:
A) Suggest/Fix the Laravel URL validator to support the listed schemes and add an option to also allow provisional/private use schemes.
B) Suggest/Add a second validator for generic URI schemes in Laravel that is seperate of the too complex and too limited at the same time URL Validator
C) Suggest/Add a generic validation just for Passport (possibly without using a seperate validator and instead just specifying a generic regex)

Thanks in advance.

**Comment by driesvints** [comment]
Think I'd first try B and then C if B doesn't makes it into the core.

**Comment by grEvenX** [comment]
Have the same issue, do you happen to know a workaround currently @mastacheata ?
It's currently blocking us from upgrading to Laravel 7 since we have OAuth clients that rely on these URL schemes. Example of failing URL: `myapp://oauth/callback`

**Comment by mastacheata** [comment]
You have a different problem than me:
myapp is not a valid URI scheme registered by IANA or mentioned in the Laravel URI validator.

Your URI adheres to the http(s) scheme with the colon and the double-forward-slash, but uses an incompatible name.
My problem is I have a scheme that is mentioned in the Validator, but it's not of the http(s) format (it doesn't have a double-forward-slash, which is not required per RFC 3986) 

Pick one of these instead:
```
(aaa|aaas|about|acap|acct|acr|adiumxtra|afp|afs|aim|apt|attachment|aw|barion|beshare|bitcoin|blob|bolo|callto|cap|chrome|chrome-extension|cid|coap|coaps|com-eventbrite-attendee|content|crid|cvs|data|dav|dict|dlna-playcontainer|dlna-playsingle|dns|dntp|dtn|dvb|ed2k|example|facetime|fax|feed|feedready|file|filesystem|finger|fish|ftp|geo|gg|git|gizmoproject|go|gopher|gtalk|h323|ham|hcp|http|https|iax|icap|icon|im|imap|info|iotdisco|ipn|ipp|ipps|irc|irc6|ircs|iris|iris.beep|iris.lwz|iris.xpc|iris.xpcs|itms|jabber|jar|jms|keyparc|lastfm|ldap|ldaps|magnet|mailserver|mailto|maps|market|message|mid|mms|modem|ms-help|ms-settings|ms-settings-airplanemode|ms-settings-bluetooth|ms-settings-camera|ms-settings-cellular|ms-settings-cloudstorage|ms-settings-emailandaccounts|ms-settings-language|ms-settings-location|ms-settings-lock|ms-settings-nfctransactions|ms-settings-notifications|ms-settings-power|ms-settings-privacy|ms-settings-proximity|ms-settings-screenrotation|ms-settings-wifi|ms-settings-workplace|msnim|msrp|msrps|mtqp|mumble|mupdate|mvn|news|nfs|ni|nih|nntp|notes|oid|opaquelocktoken|pack|palm|paparazzi|pkcs11|platform|pop|pres|prospero|proxy|psyc|query|redis|rediss|reload|res|resource|rmi|rsync|rtmfp|rtmp|rtsp|rtsps|rtspu|secondlife|service|session|sftp|sgn|shttp|sieve|sip|sips|skype|smb|sms|smtp|snews|snmp|soap.beep|soap.beeps|soldat|spotify|ssh|steam|stun|stuns|submit|svn|tag|teamspeak|tel|teliaeid|telnet|tftp|things|thismessage|tip|tn3270|turn|turns|tv|udp|unreal|urn|ut2004|vemmi|ventrilo|videotex|view-source|wais|webcal|ws|wss|wtai|wyciwyg|xcon|xcon-userid|xfire|xmlrpc\.beep|xmlrpc.beeps|xmpp|xri|ymsgr|z39\.50|z39\.50r|z39\.50s)
```

**Comment by grEvenX** [comment]
@mastacheata You are right, the issue for me was something completely else.

**Comment by driesvints** [comment]
I'm going to close this as we haven't gotten too much requests for this yet. Feel free to send prs to the framework and/or passport if you want to get this in.
