### ISSUE TITLE
 Out of range value for column 'user_id' in `oauth_clients`

### ISSUE THREAD

**Issue by reishou** [laravel/passport#1056]
- Passport Version: 7.3.4
- Laravel Version: 5.8.12
- PHP Version: 7.2
- Database Driver & Version:

### Description:
My user_id is a big Integer, so cannot insert to oauth_clients. I can change column type myself. I think all coumn integer in `https://github.com/laravel/passport/tree/7.0/database/migrations` should change to BigInteger for fresh install.

**Comment by driesvints** [comment]
Yep. Feel free to send in a PR.

**Comment by reishou** [comment]
I created a PR for this issue. https://github.com/laravel/passport/pull/1057
Please review it. Thank you.
