### ISSUE TITLE
ClientController: $request->user()->id

### ISSUE THREAD

**Issue by tobiassen** [laravel/passport#106]
Hi,
I have a project where I have changed the User model primary key from "id" to "MemberID" using the following command in my User.php model file:

`protected $primaryKey = 'MemberID'`

This seems to be an issue when using passport because it expects `user()->id` inside ClientController.php.
Changing the two functions to use `user()->MemberID` fixes the issue, but would be overwritten by composer since it is inside the vendor folder.

Is there a way around this that do not involve changing the functions inside ClientController.php?

Best regards
Totto

**Comment by kevindierkx** [comment]
Replacing `$request->user()->id` with `$request->user()->getKey()` in the `ClientController` should resolve your problem.

Or you could try adding mutators to your user model: https://laravel.com/docs/5.3/eloquent-mutators
```
public function getIdAttribute()
{
    return $this->getAttribute($this->getKeyName());
}
```

**Comment by kevindierkx** [comment]
@tobiassen I've made a PR, #107 should resolve your problem without the need of using mutators.

**Comment by tobiassen** [comment]
@kevindierkx Thank you very much for the quick response!
We've used an accessor to fix the issue temporarily.
Hoping the pull request will get approved.

Best regards
Totto
