### ISSUE TITLE
MongoDB - Refresh Token - Trying to get property 'revoked' of non-object

### ISSUE THREAD

**Issue by narwy** [laravel/passport#1061]
- Passport Version: `Latest`
- Laravel Version: `Latest`
- PHP Version: `php:latest`
- Database Driver & Version: `mongodb:latest`

### Description:
When doing a call to `/oauth/token` using the `jenssegers/laravel-mongodb` for MongoDB it will throw this:
`Trying to get property 'revoked' of non-object at /var/www/vendor/laravel/passport/src/Bridge/RefreshTokenRepository.php:80`

### Steps To Reproduce:
1. Fresh install Laravel
1. Fresh install Passport
1. Do a call to get a token/refresh token.
1. Use the refresh token on the `/oauth/token` url

Error should be thrown.

This change did fix the issue: https://github.com/laravel/passport/pull/1060
However failing tests.

**Comment by narwy** [comment]
People also reporting the same issues: https://github.com/laravel/passport/issues/848#issuecomment-517151166

Seem's to be the only thing stopping support for MongoDB, surely we can add this to support an additional driver? It's becoming used more on a daily basis.

**Comment by driesvints** [comment]
Hi there. This has been completely refactored for the next major Passport release: https://github.com/laravel/passport/blob/master/src/Bridge/RefreshTokenRepository.php#L76

We'll probably see a new release in a few months. In the meantime you're free to use dev-master if but be aware that it's not stable yet.

**Comment by narwy** [comment]
> Hi there. This has been completely refactored for the next major Passport release: https://github.com/laravel/passport/blob/master/src/Bridge/RefreshTokenRepository.php#L76
> 
> We'll probably see a new release in a few months. In the meantime you're free to use dev-master if but be aware that it's not stable yet.

Hey, thanks for the response. Will look into it, cheers.

**Comment by narwy** [comment]
> https://github.com/laravel/passport/blob/master/src/Bridge/RefreshTokenRepository.php#L76

@driesvints Any update on this major release? However I'm using the `dev-master` at the moment and It's still throwing issues like `Call to a member function prepare() on null` when using another database driver such as MongoDB, with the full restructure, I might have to fork and do changes for a MongoDB driver support? Or maybe another branch?

**Comment by driesvints** [comment]
Not yet. Haven't found time yet to work on it.

**Comment by narwy** [comment]
@driesvints Just so you are aware of the changes:

I changed this line:
https://github.com/laravel/passport/blob/master/src/Bridge/RefreshTokenRepository.php#L76

To:
```
public function isRefreshTokenRevoked($tokenId)
    {
        return $this->database->table('oauth_refresh_tokens')
                    ->where('id', $tokenId)->where('revoked', true)->exists();
    }
```

This allowed document database structures to work correctly, `revoked` is undefined. If I return a bool it will work fine for MySql and MongoDB. I have updated my package for people to have support for MongoDB for Laravel.

**Comment by Siebov** [comment]
@driesvints are you planing to implement this fix in your versions? 

> @driesvints Just so you are aware of the changes:
> 
> I changed this line:
> https://github.com/laravel/passport/blob/663e720a6d15e8ec70bf5309f774439a110efc89/src/Bridge/RefreshTokenRepository.php#L80
> 
> To:
> 
> ```
> public function isRefreshTokenRevoked($tokenId)
>     {
>         return $this->database->table('oauth_refresh_tokens')
>                     ->where('id', $tokenId)->where('revoked', true)->exists();
>     }
> ```
> 
> This allowed document database structures to work correctly, `revoked` is undefined. If I return a bool it will work fine for MySql and MongoDB. I have updated my package for people to have support for MongoDB for Laravel.
