### ISSUE TITLE
Published migrations being ignored, even with Passport::ignoreMigrations() called

### ISSUE THREAD

**Issue by asiraky** [laravel/passport#1071]
I have published the migrations and modified them (changed some integer id's to uuid).

I have run `Passport::ignoreMigrations();` in my `AuthServiceProvider`'s `boot` method.

Issue: my custom migrations are being ignored, and the ones stored in vendor/passport/... are firing instead.

When I perform a line by line debug of `php artisan migrate`, I can see that the `PassportServiceProvider`'s `boot `method runs before my `AuthServiceProvider`'s `boot` method. This causes the following check:
```
if (Passport::$runsMigrations) {
    // this if block is firing which causes the migrations to be loaded
    return $this->loadMigrationsFrom(__DIR__.'/../database/migrations');
}
```
to register the built in migrations. 

Source of the issue as far as I can tell: I can clearly see that my call to `Passport::ignoreMigrations();` happens _after_ Passport is checking whether it should run it's own migrations. 

My app.php is pretty close to default, My AuthServiceProvider is listed after all the baked in service providers.

FWIW this only started happening today, previously this code was all working and my custom migrations were doing fine. I've cleared every cache I can find, rm -rf my vendor directory and re composer installed. And even git cloned my code on a machine configured by laravel forge, and I still get this same issue.

I am out of ideas.

Please help me!

I am running versions Laravel 5.8 + Passport 7.2 + PHP 7.2 on a vagrant box which appears to use Ubuntu 16.04.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by diego-lipinski-de-castro** [comment]
Im falling into this issue too, laravel 7, passport 8.4, even with Passport::ignoreMigrations, the migrations are running
