### ISSUE TITLE
When authorizing an client, it stores 2 entries in oauth_auth_codes

### ISSUE THREAD

**Issue by HenkMaller** [laravel/passport#1079]
- Passport Version: ^7.4
- Laravel Version: ^6.0
- PHP Version: 7.3.9
- Database Driver & Version:  MySQL 8.0.15

### Description:
When authorizing an client, it stores 2 entries in oauth_auth_codes

### Steps To Reproduce:
Create a client, and authorize it

**Comment by driesvints** [comment]
We'll need more code to reproduce this. Please create a sample app and upload it to a github repo so we can reproduce this.

**Comment by HenkMaller** [comment]
Its a fresh installation of Laravel and Passport
