### ISSUE TITLE
Is this package compatible with 5.1?

### ISSUE THREAD

**Issue by umbertix** [laravel/passport#108]
Hi, is more a question than anything else. Is this package compatible with the Laravel version 5.1? Has anyone tested it in such version?

**Comment by kevindierkx** [comment]
Nope, minimal requirements are set to 5.3: `"illuminate/support": "~5.3",`
Also the `RetrievesAuthRequestFromSession` trait uses the in L5.3 introduced `tap()` helper.

**Comment by umbertix** [comment]
thx.
