### ISSUE TITLE
   ErrorException  : file_put_contents(/secret-keys/oauth/oauth-public.key): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by apachish** [laravel/passport#1080]
vendor/laravel/passport/src/Console/KeysCommand.php:46
    42|             $this->error('Encryption keys already exist. Use the --force option to overwrite them.');
    43|         } else {
    44|             $keys = $rsa->createKey($this->input ? (int) $this->option('length') : 4096);
    45| 
  > 46|             file_put_contents($publicKey, Arr::get($keys, 'publickey'));
    47|             file_put_contents($privateKey, Arr::get($keys, 'privatekey'));
    48| 
    49|             $this->info('Encryption keys generated successfully.');
    50|         }

  Exception trace:

  1   file_put_contents("/secret-keys/oauth/oauth-public.key", "-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvAtqvkM6jyZyptx1IEnc
MSiPPBXw2iJWtgqUTQlJZD4Ty3T+CveOSRrzQQAUN/dQMWHMqq7/Px93fmrBnC54
0EHCzA65wNaREk81KsxioB5NMV4La/wmzjDypJZI2PQkXZMsu0oRhu+MnZZfTlPE
YrtlEKjhLcfvMaayRTESZZ9BCI7EXoZAdeuYWI8LwJe0JOeTznGB5u79X2PJZvY7
7ASgqNbthC1cpq1GZiBfmSFhtas/kgD7I8HmHcne3TYIaVSnCO5ba0Wx0rcz/2iO
9hnvnpkg6AMaERRAf3JPAYNyEwMPUNzjmb1HswQMPDRitkD3L9iuv/B7Vs1dOemK
+ch+iUolpErhQ38AUJBqyigawFkFFg9YB8VvgMJm2AxMeDarG9dZbPhLXhOVB6wN
W9rLcEgpuuIOeRu+1y+pY0+vF36s+yS+nZUbcZ1tyfsqyxW39vxOtYx8qVGoEpKq
zU4kVt0i5RbsO0OXnh68Nz2WdX543i35uLIWEDdQgQbII+GW1K3C07EGkcVbfbt4
nlV1TbJyGu8GGbzXuY4uFGpOP6E2rL0UhRSsa476tpprr5jKwmUAaqZ723Ot2h8X
QjANw96+WlugsUUwVWPpgbQ44usY6Uz4eYiyHUXxo45rVqXSxPPcESqh+4lVOX2v
kQY0vfmY7EjQj+y2eQDfNWUCAwEAAQ==
-----END PUBLIC KEY-----")

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by skydev2020** [comment]
@apachish Did you solve the issue?

**Comment by apachish** [comment]
> @apachish Did you solve the issue?

yes , problem my config

**Comment by aiman1717a** [comment]
what was the problem in your config? i am having the same issue

**Comment by AmeerHamoodi** [comment]
If anyone else is having this problem, remove `Passport::loadKeysFrom(__DIR__.'/../secrets/oauth');` from the `AuthServiceProvider`. This fixed my problem

**Comment by Sagar158** [comment]
> 

Thanks it worked for me

**Comment by AngelAlgo262** [comment]
tanks!!!!!!!!!
