### ISSUE TITLE
Migrations Error

### ISSUE THREAD

**Issue by jointothedarkside** [laravel/passport#1086]
When I run migrations to install passport I get this error:

***************************************

Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value")
      /home/gomatetrix/public_html/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119

  2   PDOException::("SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value")
When running migrations I get this error
 
/home/gomatetrix/public_html/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117

  Please use the argument -v to see more details.

   Whoops\Exception\ErrorException  : Module 'pdo_sqlite' already loaded

  at Unknown:0

**********************************************

I believe it is due to the migrations files that create the OAUTH tables, if I change nullable() to nullable(false) the warning doesn't appear.

I'm using Laravel 6 in Centos 7

**Comment by jointothedarkside** [comment]
Second error just wen't to mysql and removed the null value from user_id in 'oauth_clients' table
Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (?, Laravel Personal Access Client, GtQHojA0oGzR4eHBm7Os0rk81GGiq4qBCpKy9X18, http://localhost, 1, 0, 0, 2019-09-27 02:11:08, 2019-09-27 02:11:08))

**Comment by jointothedarkside** [comment]
While using making a login call to retrieve a token I got this error:
 "message": "SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `oauth_access_tokens` (`id`, `user_id`, `client_id`, `scopes`, `revoked`, `created_at`, `updated_at`, `expires_at`) values (49d9941962d6efee4556a4cbfb0d0f15ae44380a742d04245693ad0de1967909a6b3aa48c381d5f3, 1, 1, [], 0, 2019-09-27 02:38:34, 2019-09-27 02:38:34, 2020-09-27 02:38:34))",

Changed name to be nullable from `oauth_access_tokens` to fix it
CHANGE `name` `name` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jointothedarkside** [comment]
@driesvints Hi there well I believe it has to be a bug I made clean install and migrations were not installing properly, I'm describing the problems and errors I faced to help other if they stumble across the same problem but it also may be helpfull to you to find this problem, tables should not have a null value if the passport:install command leave some fields unfilled OR you can add the null string value to the passport:install command
