### ISSUE TITLE
Api guard is hardcoded

### ISSUE THREAD

**Issue by YWatchman** [laravel/passport#1094]
- Passport Version: *
- Laravel Version: 5.8^
- PHP Version: 7.3
- Database Driver & Version: MariaDB 10.2

### Description:
The api guard is hardcoded in some spots (https://github.com/laravel/passport/blob/7.0/src/Token.php#L80), this wasted +/- 2 hours of my time figuring out why I can't use 2 guards (userapi and frontendapi). I renamed my frontendapi guard back to api.

### Steps To Reproduce:
1. Add another guard, for example 'frontendapi' and set the driver to passport
2. Assign the guard through a middleware
3. Try to authenticatie, response will be that you stay unauthenticated. This is because Passport is explicitly searching for the 'api' guard. that makes that the middleware 'auth:guard' doesn't have any impact.

**Comment by driesvints** [comment]
Atm this isn't a problem because Passport doesn't implement multi auth. But this will indeed need to be made configurable if multi auth is to be supported. Please see https://github.com/laravel/passport/issues/982
