### ISSUE TITLE
unsupported_grant_type 

### ISSUE THREAD

**Issue by sanhar** [laravel/passport#1095]
- Passport Version: 7.5.
- Laravel Version: 6.3.0
- PHP Version: 7.2.22
- Database Driver & Version: 10.4.6-MariaDB 

### Description:
can not login with . '/oauth/token'

### Steps To Reproduce:
laravel new project 
composer require laravel/passport 
php artisan migrate
php artisan passport:install 
php artisan:tinker 
--create users 

--with postman or insomnia ( in my case ) 

I sent the following request with "POST" ( not GET ) .

http://localhost:8000/oauth/token?grant_type=password&client_id=2&client_secret=hE3fsdDjuZCeeofB7FtMVVmRnaZVMQmJZLyHPWIT&username=user02@email.com&password=12341234&scope=*

the error is following : 

{
  "error": "unsupported_grant_type",
  "error_description": "The authorization grant type is not supported by the authorization server.",
  "hint": "Check that all required parameters have been provided",
  "message": "The authorization grant type is not supported by the authorization server."
}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sokbunthean** [comment]
Error "unsupported_grant_type", Please help about that.
