### ISSUE TITLE
passport:client command fails if you change user_id to something else

### ISSUE THREAD

**Issue by daniyum21** [laravel/passport#1096]
- Passport Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
The documentation says you can change user_id to whatever you want after you publish like so 'php artisan vendor:publish --tag=passport-migrations'

However, user_id is hard coded in ClientRepository, therefore the create command always fails.

```
public function create($userId, $name, $redirect, $personalAccess = false, $password = false)
    {
        $client = Passport::client()->forceFill([
            'user_id' => $userId, //THIS IS HARD-CODED, THEREFORE USING USERID FAILS
            'name' => $name,
            'secret' => Str::random(40),
            'redirect' => $redirect,
            'personal_access_client' => $personalAccess,
            'password_client' => $password,
            'revoked' => false,
        ]);

        $client->save();

        return $client;
    }
```

### Steps To Reproduce:

1. change user_id to userID in migration files
2. run the command php artisan passport:client --personal

**Comment by driesvints** [comment]
You can overwrite the default models: https://laravel.com/docs/6.x/passport#overriding-default-models

**Comment by driesvints** [comment]
Hey sorry, I now saw your note about the `user_id` key. This is indeed fixed. We already allow for overwriting the default models but we can only go so far in terms of customization. Unfortunately you'll have to use the `user_id` key in this case.
