### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by divyashrestha2019** [laravel/passport#1100]
[image](https://user-images.githubusercontent.com/53654689/67856965-d06ea600-fb3d-11e9-9567-7a4d94c2726b.png)

![image](https://user-images.githubusercontent.com/53654689/67856998-e1b7b280-fb3d-11e9-9c47-7b21dc633159.png)

**Comment by narwy** [comment]
Update Laravel to v6+

**Comment by driesvints** [comment]
See the upgrade guide: https://github.com/laravel/passport/blob/8.x/UPGRADE.md
