### ISSUE TITLE
ClientCommand Type Hinting Issue

### ISSUE THREAD

**Issue by kourtzaridisr88** [laravel/passport#1108]
- Passport Version: 8.0
- Laravel Version:6.4
- PHP Version: 7,2
- Database Driver & Version: MongoDB 3.6

### Description:
When you change the Client Model ClientCommand not working because of the Client
type hint

### Steps To Reproduce:

In your AuthServiceProvider boot method just change the client model
Passport::useClientModel(Client::class);

**Comment by driesvints** [comment]
You need to extend the original model.

**Comment by uriel2707** [comment]
@kourtzaridisr88 https://packagist.org/packages/webdecero/webdecero-package-laravel-passport
