### ISSUE TITLE
`CreateFreshApiToken` middleware modifies / drops request parameters

### ISSUE THREAD

**Issue by satyago** [laravel/passport#1114]
- Passport Version: v8.0.0
- Laravel Version: 6.5.0
- PHP Version: 7.2.23
- Database Driver & Version: 8.0.17

### Description:
When adding the `CreateFreshApiToken` middleware to the `App\Http\Kernel::class`'s `$middlewarePriority` config, it seems to modify / drop the existing request parameters. That is if it is added prior to any other middleware that is hooking into submitted request parameters.

For it not to break any existing application behavior, it needs to be added as the very last entry.

**Comment by driesvints** [comment]
Hey @satyago. Correct. The middleware needs to be the last one. Please see the docs here: https://laravel.com/docs/6.x/passport#consuming-your-api-with-javascript

```php
'web' => [
    // Other middleware...
    \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
],
```

As well as the note below the code snippet: 

> You should ensure that the EncryptCookies middleware is listed prior to the CreateFreshApiToken middleware in your middleware stack.

**Comment by satyago** [comment]
@driesvints thank you, but I've read these doc entries many times before and they told me nothing. That is until I REALLY took a hard look at the implied order on the example, realizing that this was in fact (not anymore) the last entry in our codebase.

The excerpt from the warning is especially confusing:

> You should ensure that the EncryptCookies middleware is listed prior to the CreateFreshApiToken middleware in your middleware stack.

 This gives the impression it is ok to be placed anywhere, with the exception of `EncryptCookies` having to go first. I feel it lacks detail as to "why" this is the case and also needs to emphasize the fact that it really should be the absolute last entry.

I issued a pull request with what I believe is the only right way to document this.
