### ISSUE TITLE
Able to take grant_type client_credentials client access token with password client data, but unable to use it.

### ISSUE THREAD

**Issue by armenpetrosyan993** [laravel/passport#1121]
- Passport Version: 8.0
- Laravel Version: 6.5.1
- PHP Version: 7.2.12
- Database Driver & Version: mysql

### Description:
I had client middleware and auth:api middleware in my application. I had one password client token  and it was possible to use for client credentials too.
In new version i am able to get access token via grant_type client_credentials but i am not able to use it as it is checked in validation if token is firstParty(). 

### Steps To Reproduce:
Create password grant type 
try to have access to client middleware urls

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by gdebrauwer** [comment]
@armenpetrosyan993 This was changed in 8.0 because of #691. It should not be allowed to use a 'client_credentials' access token, issued with password client, to access a route protected with 'client' middleware. Routes protected with that middleware should only be used for internal machine-to-machine communication.

@driesvints is it not strange that you still can use the 'client_credentials' grant type with a password client? Should that not return an error? Because currently you can request a 'client_credentials' token with a password client, but you can't use that access token.

**Comment by armenpetrosyan993** [comment]
@gdebrauwer thanks. Do you have any idea how it can be done in new version? i have public roues and private routes. but also want that public routes will be available only for our application and no one outside couldn't use them and see data. before as added that routes in middleware client and password grant token can use it too. now can't

**Comment by gdebrauwer** [comment]
@armenpetrosyan993 that's not possible anymore. You will have to remove the 'client' middleware if you want to use the route both as client and as user.

**Comment by armenpetrosyan993** [comment]
@gdebrauwer  okay thank you

**Comment by driesvints** [comment]
> is it not strange that you still can use the 'client_credentials' grant type with a password client? Should that not return an error? Because currently you can request a 'client_credentials' token with a password client, but you can't use that access token.

@gdebrauwer maybe we can do better here. Feel free to send in a pr if you want 👍
