### ISSUE TITLE
Personal Access Tokens 401 unauthorized after updating to Passport 8

### ISSUE THREAD

**Issue by tommiekn** [laravel/passport#1124]
- Passport Version: 8.0.1
- Laravel Version: 6.0
- PHP Version: 7.2.23
- Database Driver & Version: Maria

### Description:
I have an application that make use of the Personal Access Tokens functionality to allow machine-to-machine talks.
We do create users and personal access tokens and give the users the personal access tokens to auth their applications directly with no need to use the whole authentication process.

The problem is that after updating to Passport v8 all requests gives 401 unauthorized.
If i get back to 7.x it works just fine.

### Steps To Reproduce:

1. Configure the personal access tokens:
https://laravel.com/docs/6.x/passport#personal-access-tokens

The only difference i had in my code is that i didnt included:
`Passport::personalAccessClientId('client-id');`

I have added it but however nothing changed.

2. Create new user:

```
$user= new User;
$user['email']=$input['user_email'];
$user['password']=$input['user_password'];
$user['name']=$input['user_name'];
$user['role_id']=2;
$user->save();
```

3. Create a personal token:

```
$token=$user->createToken($name,$scopes);
$personaltoken = $token->accessToken;
```

4. Try to connect to a route:

```
$response = $client->request('GET', 'route-url-something', [
                'curl' => [
                    CURLOPT_INTERFACE => $_SERVER['SERVER_ADDR']
                ],
                'headers' => [
                    'Accept' => 'application/json',
                    'Authorization' => 'Bearer ' . $personaltoken
                ]
            ]);
```

For reference, the route i use is like this:

```
Route::group(['middleware' => 'auth:api'], function () {
Route::get('/route-url-something', 'API\GateSessionController@route-url-something')->name('lgate.check_credentials')->middleware(['client', 'scopes:user.gate-use']);

});
```

Result to this route registered:

`GET|HEAD  | api/route-url-something                  | lgate.check_credentials              | App\Http\Controllers\API\GateSessionController@check_credentials          | api,auth:api,client,scopes:user.gate-use
`

**Comment by driesvints** [comment]
This behavior was changed for the new release and is documented in the upgrade guide here: https://github.com/laravel/passport/blob/8.x/UPGRADE.md#fixed-credential-checking

**Comment by tommiekn** [comment]
@driesvints i have read that upgrade file many times before posting the issue but i am unable to understand why edit affects how i am using personal access feature.

It is very unclear on how to amend the use of it thru docs or either in the update file. Could you advise some extra info here please?

**Comment by driesvints** [comment]
Personal access tokens aren't available for machine-to-machine communication. You're looking for client credentials grant tokens: https://laravel.com/docs/6.x/passport#client-credentials-grant-tokens

**Comment by tommiekn** [comment]
@driesvints  Thanks, that is exactly what i am using, apologize for the missleading machine to machine thing.

Still, i am unable to understand what i need to change here.
In the pull for that edit you referred i see:

> So only those who have issued access token with Client Credentials grant type can go through CheckClientCredential & CheckClientCredentialForAnyScope Middlewares.

How can i give client credentials grant type?
The problem could be i need to re-generate tokens ?

The tokens i use have already scopes associated and i am checking it in my route:
`Route::get('/user-credentials', 'API\GateSessionController@check_credentials')->name('lgate.check_credentials')->middleware(['client', 'scopes:user.gate-use']);`
    	
I have tried some other stuff and now  api.php contains only ONE route that i am testing. Still doesnt work. Either with the scope user.gate-use or not.

`Route::get('/user-credentials', 'API\GateSessionController@check_credentials')->name('lgate.check_credentials')->middleware('client:user.gate-use');`

**Comment by driesvints** [comment]
You can't use the `client` middleware in combination with `'auth:api'`. 

It's probably best if you continue with this on a support channel where you'll get better and faster answers than here: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by tommiekn** [comment]
Ok, just one last thing tho because i missreaded at first what you said, you have mentioned earlier i were looking for client credentials tokens, but actually that is not correct, what i am using are the personal access tokens.

https://laravel.com/docs/6.x/passport#personal-access-tokens

I need to allow users to use bearer tokens they generate to connect directly to the api without the need of any oauth flow. I mentioned machine-to-machine because that token is used by a plugin to auto -retrieve content from the api but itself this is a personal access token as depends on user access.

On passport 7 i could do it with the routes i posted first in this topic.
I have tried to remove auth:api now so routes uses only api and client scopes but anyway no luck.

**Comment by tommiekn** [comment]
The issue was simply to delete "client" from the middleware on each.
