### ISSUE TITLE
Getting unexpected response: {message: "Server Error"}

### ISSUE THREAD

**Issue by jadvillafania** [laravel/passport#1128]
- Passport Version: 8.0.1
- Laravel Version: 6.5.2
- PHP Version: 7.3.7
- Database Driver & Version: 10.3.16-MariaDB

### Description:
Getting unexpected response: {message: "Server Error"} when calling to an api route. It does not happen all the time but maybe 3 of 10 times. I am using password client. Authentication bearer token is properly configured on the axios instance.

### Steps To Reproduce:

1. Follow documentation in implementing Password Grant Passport.
2. Send api request to a route.

![passport error](https://user-images.githubusercontent.com/24929358/69695715-d3a78280-1139-11ea-9933-6077e2129e4b.png)

**Comment by driesvints** [comment]
Did you upgrade from an older version? Or is this a fresh install?

**Comment by jadvillafania** [comment]
This is a fresh install. I checked the Laravel logs and it error was about app key not specified (even though there is already APP_KEY generated by `php artisan key:generate`.

I cached the config and so far not getting the error again.

**Comment by EmileSonneveld** [comment]
This worked for me too on Laravel Framework 5.8.38
`php artisan config:cache`
