### ISSUE TITLE
The Auth pop  up instead of redirecting to the client

### ISSUE THREAD

**Issue by mohamednizar** [laravel/passport#1130]
- Passport Version: v7.5.1
- Laravel Version: v5.8.35
- PHP Version: 7.2
- Database Driver & Version: Mysql:5.7

### Description:
I have Mysql user base and and oAuth redirect to the login page , it's popup auth in loop instead of login.

### Steps To Reproduce:
This is  oAuth config in grfana:

```
[auth.generic_oauth]
name = oAuth
enabled = true
allow_sign_up = true
grant_type = client_credentials
client_id = 2
client_secret = OYbNhwV_porM38Nzdkq1DxmkW2j1AQL0wmtmq44W9vg
client_passsword = OYbNhwV_porM38Nzdkq1DxmkW2j1AQL0wmtmq44W9vg
scopes = openid profile email
#email_attribute_name = email:primary
#email_attribute_path =
auth_url =  http://localhost:3002/oauth/authorize
token_url = http://localhost:3002/oauth/token
api_url = http://localhost:3002/api/user
team_ids =
#allowed_organizations = 1
tls_skip_verify_insecure = false
#tls_client_cert =
#tls_client_key =
#tls_client_ca =
send_client_credentials_via_post = true
```

this is showing up
![Screenshot from 2019-11-29 11-58-49](https://user-images.githubusercontent.com/8711284/69848277-aa086b80-129f-11ea-9535-04bffcc3d0e4.png)

If I canceled the popup, its throw `{"error":"invalid_client","message":"Client authentication failed"}`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
