### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire()

### ISSUE THREAD

**Issue by dmitrirussu** [laravel/passport#1131]
"laravel/framework": "5.8.*",
        "laravel/passport": "^7.5.1",
- PHP Version:7.2.24-0ubuntu0.18.04.1
- Database Driver & Version:

### Description:

Call to undefined method Illuminate\Events\Dispatcher::fire()

src/Bridge/RefreshTokenRepository.php
line: 60
$this->events->fire(new RefreshTokenCreated($id, $accessTokenId));

### Steps To Reproduce:
        $tokenRequest = Request::create(
            '/oauth/token',
            'POST',
            $request->all()
        );
        return \Route::dispatch($tokenRequest);

**Comment by dmitrirussu** [comment]
Temporary fix
`
<?php
namespace App\Providers;


use Laravel\Passport\Events\RefreshTokenCreated;
use League\OAuth2\Server\Entities\RefreshTokenEntityInterface;

class RefreshTokenRepository extends \Laravel\Passport\Bridge\RefreshTokenRepository
{
    /**
     * {@inheritdoc}
     */
    public function persistNewRefreshToken(RefreshTokenEntityInterface $refreshTokenEntity)
    {
        $this->database->table('oauth_refresh_tokens')->insert([
            'id' => $id = $refreshTokenEntity->getIdentifier(),
            'access_token_id' => $accessTokenId = $refreshTokenEntity->getAccessToken()->getIdentifier(),
            'revoked' => false,
            'expires_at' => $refreshTokenEntity->getExpiryDateTime(),
        ]);

        $this->events->dispatch(new RefreshTokenCreated($id, $accessTokenId));
    }
}

`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
