### ISSUE TITLE
Inherited scopes ignored when using actingAs

### ISSUE THREAD

**Issue by Douglasdc3** [laravel/passport#1138]
- Passport Version: 7.5.1
- Laravel Version: 6.6.2
- PHP Version: 7.2.24
- Database Driver & Version: n/a 

### Description:

When using inherited scopes and you attempt to set scope inside `Passport::actingAs($user, ['api'])` the can method returns false when checking scope `api:users:index`

### Steps To Reproduce:

```
    public function test_acting_as_ignores_with_inherited_scopes()
    {
        Passport::$withInheritedScopes = true;

        $user = Passport::actingAs(factory(User::class)->create(), ['api']);

        $this->assertTrue($user->tokenCan('api')); // Works as expected
        $this->assertTrue($user->tokenCan('api:users')); // Fails
        $this->assertTrue($user->tokenCan('api:users:index')); // Fails
    }

    public function test_acting_as_ingores_wildcard()
    {
        Passport::$withInheritedScopes = true;

        $user = Passport::actingAs(factory(User::class)->create(), ['*']);

        $this->assertTrue($user->tokenCan('api')); // Fails
    }
``` 

The issue related to `Passport.php` acting as method:

```
    public static function actingAs($user, $scopes = [], $guard = 'api')
    {
        $token = Mockery::mock(self::tokenModel())->shouldIgnoreMissing(false);

        // This check is different to the logic performed inside the standard token model
        foreach ($scopes as $scope) {
            $token->shouldReceive('can')->with($scope)->andReturn(true);
        }

        $user->withAccessToken($token);

        if (isset($user->wasRecentlyCreated) && $user->wasRecentlyCreated) {
            $user->wasRecentlyCreated = false;
        }

        app('auth')->guard($guard)->setUser($user);

        app('auth')->shouldUse($guard);

        return $user;
    }
```
 
`Token.php` here logic to handle wildcard and inherited scopes is checked

```
    public function can($scope)
    {
        if (in_array('*', $this->scopes)) {
            return true;
        }

        $scopes = Passport::$withInheritedScopes
            ? $this->resolveInheritedScopes($scope)
            : [$scope];

        foreach ($scopes as $scope) {
            if (array_key_exists($scope, array_flip($this->scopes))) {
                return true;
            }
        }

        return false;
    }
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Douglasdc3** [comment]
@driesvints  This issue isn't fixed in v8. Same result in the above mentioned test cases and the code in the `actingAs` method is still the same.

**Comment by driesvints** [comment]
At the moment this doesn't works like this. You'll always need to pass in the explicit scopes you want to check against. We can, however, perhaps add support for this. Feel free to send in a PR.

**Comment by driesvints** [comment]
Gonna close this since we only received one request for this. You're still free to attempt a pr if you want.
