### ISSUE TITLE
AccessTokenRepository does not throw UniqueTokenIdentifierConstraintViolationException exception

### ISSUE THREAD

**Issue by clzola** [laravel/passport#1140]
- Passport Version: 8.0.2
- Laravel Version: 6.7.0
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:
This is more question then bug report (I did not know where to post for the question). So I was examining source code of thephpleague/oauth2-server and this repository, and in class AbstractGrant there is method called issueAccessToken() which tries to create new access token for current request. And there is this code:

```
/**
     * Issue an access token.
     *
     * @param DateInterval           $accessTokenTTL
     * @param ClientEntityInterface  $client
     * @param string|null            $userIdentifier
     * @param ScopeEntityInterface[] $scopes
     *
     * @throws OAuthServerException
     * @throws UniqueTokenIdentifierConstraintViolationException
     *
     * @return AccessTokenEntityInterface
     */
    protected function issueAccessToken(
        DateInterval $accessTokenTTL,
        ClientEntityInterface $client,
        $userIdentifier,
        array $scopes = []
    ) {
        $maxGenerationAttempts = self::MAX_RANDOM_TOKEN_GENERATION_ATTEMPTS;

        $accessToken = $this->accessTokenRepository->getNewToken($client, $scopes, $userIdentifier);
        $accessToken->setExpiryDateTime((new DateTimeImmutable())->add($accessTokenTTL));
        $accessToken->setPrivateKey($this->privateKey);

        while ($maxGenerationAttempts-- > 0) {
            $accessToken->setIdentifier($this->generateUniqueIdentifier());
            try {
                $this->accessTokenRepository->persistNewAccessToken($accessToken);

                return $accessToken;
            } catch (UniqueTokenIdentifierConstraintViolationException $e) {
                if ($maxGenerationAttempts === 0) {
                    throw $e;
                }
            }
        }
    }
```

It will try to generate unique identifier and then try to persist token to permanent storage.
`$this->accessTokenRepository` is instance of `Laravel\Passport\Bridge\AccessTokenRepository`, which does not produces `UniqueTokenIdentifierConstraintViolationException` exception if function 
`generateUniqueIdentifier()` produces identifier that already exists in database. Since the range for this identifier is finite (40 bytes) there is small chance that this will happen, and in that case this while loop ensures another try. However since Passport's `AccessTokenRepository` does not throw this exception if it happens to be generated existing identifier HTTP request will immediately fail. Which is not what creators of thephpleague/oauth2-server excpected.

So is this what Passport Team really intended or they forgot to implement?

### Steps To Reproduce:
1. Use password grant to obtain access token
2. Look into database for newly created access token and copy its ID
3. Go to AbstractGrant.php (vendor\league\oauth2-server\src\Grant\AbstractGrant.php) and edit function `generateUniqueIdentifier` so that it always returns ID that you copied.
4. Go to AbstractGrant::issueAccessToken() method (same file) and in catch clause put dd("test")
5. Execute another request to obtain access token and you will not get dd("test") instead and error telling you SQL query failed indicateting that you are trying to insert access token with same ID.

**Comment by driesvints** [comment]
Hey @clzola. When you attempt to open up a new issue you'll see the list below.

![Screen Shot 2019-12-12 at 11 11 33](https://user-images.githubusercontent.com/594614/70703365-48e58c80-1cd0-11ea-9539-1e9ea5f06231.png)
