### ISSUE TITLE
Validation error on linux

### ISSUE THREAD

**Issue by chrisngure2599** [laravel/passport#1142]
- Passport Version: v7.5.1
- Laravel Version: 6.4.0
- PHP Version: 7.2.0
- Database Driver & Version:

### Description:
 have a Laravel application that I built on Windows. It is an api by passport and frontend by Vuejs and on windows and works perfect. But the problem is now that it is in a Linux server when I am authenticating always returns "Unauthorized error" even though the password and user name is correct!

In the constructor I tried:

$this->middleware('auth:api'); And this on the routes

Route::group(['middleware' => 'auth:api'], function()
{ 
   //Routes here
}
with no difference!.

But when I login I get the tokens. But does not work! when I try the token provided!.

### Steps To Reproduce:
1) Login via postman
2) try another controller with the authorization header!
![token](https://user-images.githubusercontent.com/20776273/70794095-e4006400-1dad-11ea-9093-dd64c829f88b.PNG)
The problem is on windows works and linux does not!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by chrisngure2599** [comment]
Hello if i may ask what "this Version" means is it the php, laravel or passport?

**Comment by driesvints** [comment]
@chrisngure2599 Passport is currently at v8.x
