### ISSUE TITLE
Socialite Support

### ISSUE THREAD

**Issue by YoussF** [laravel/passport#1143]
Hello everyone,

I'm building a REST api exclusively with Laravel 6, and i wanted to know if there is a plan to make Laravel Passwort to work with Socialite in the futur. I think that there is a lot of people in the world that would love to see this feature implemented in the framework without having to use other plugins to be able to achieve this.

Thanks a lot.

**Comment by driesvints** [comment]
Socialite and Passport are two very different libraries with each their own core purpose. We have no plans on making them compatible atm.
