### ISSUE TITLE
Need A way i can access same url with and without access

### ISSUE THREAD

**Issue by mitul69** [laravel/passport#1147]
Hello, 

I want to call same request with or without login. 

Scenario, 
product/list API end point 

Now i want to check if user logged in and added in bookmark  so i will put the condition in code but cant access the same end point with and without login

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
