### ISSUE TITLE
I would like to allow a static token for any request contain token using passport

### ISSUE THREAD

**Issue by niraj-lal-rahi** [laravel/passport#1153]
Sample Code from postman : 

curl -X PUT \
  '{URL}/status?referrer_token=27aysoEVcFAWcqOWYv2H92gj6trR2nzl+Rdrl3i7vf4=' \
  -H 'Accept: */*' \
  
  -H 'Content-Type: application/json' \

  -d '{
    "order": {
        "id": 407,
        "status": "unassigned"
    }
}'

In the above code i m passing token from params but I want passport authorization allow this token from authorization Bearer token like
-H 'Authorization: Bearer 27aysoEVcFAWcqOWYv2H92gj6trR2nzl+Rdrl3i7vf4=

I hope, made my point clear.

Thanks in advance.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
