### ISSUE TITLE
issueToken latency

### ISSUE THREAD

**Issue by Mehrdad-Dadkhah** [laravel/passport#1156]
- Passport Version: 4.0.3
- Laravel Version: 5.5.48
- PHP Version: 3.3.11
- Database Driver & Version: MariDB 10.4.8

### Description:
Sometimes ```Laravel\Passport\Http\Controllers\AccessTokenController@issueToken``` take long time to response/process.

![Screenshot-91](https://user-images.githubusercontent.com/3860685/71776219-ea47c180-2fa2-11ea-8e86-8faa205cc6a9.png)

What's the reason or problem?

In this case our web-server is not  under the presser  and AVG response time of our API is 120 ms, and only this request take long time!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by fabioknoedt** [comment]
@Mehrdad-Dadkhah did you ever find out the issue/reason for that? we are having the same issue on Laravel 8 with Passport, same method: `Laravel\Passport\Http\Controllers\AccessTokenController@issueToken` taking ~500ms where other calls are much faster.
