### ISSUE TITLE
Refresh tokens invalid after upgrade.

### ISSUE THREAD

**Issue by nvelthorst** [laravel/passport#1162]
- Passport Version: 8.2.0
- Laravel Version: 6.10.1
- PHP Version: 7.3.12
### Description:
I'm working on upgrading an application from Laravel 5.3 to Laravel 6, and it seems that refresh_tokens generated with passport 1.0 are not valid for passport 8.

### Steps To Reproduce:
I've created an OAuth app on the older version and via grant_type password I've received a refresh_token, if I try to use this refresh token on the new version the refresh token is invalid. Meanwhile the access_token still is valid. Token use the default expireTime of 1 year.

The resulting error is:
Laravel\Passport\Exceptions\OAuthServerException · The refresh token is invalid

**Comment by driesvints** [comment]
Upgrading from Passport 1 to Passport 8 sounds like quite a steep upgrade path. There's been many changes over the year (including to league/oauth2-server. It will be a bit impossible to determine what would have caused this.

Afaik the current implementation of access and refresh tokens works as expected.
