### ISSUE TITLE
No option to create a password grant token other than writing an additional http call.

### ISSUE THREAD

**Issue by introwit** [laravel/passport#1163]
[Link to current docs for reference](https://laravel.com/docs/6.x/passport#password-grant-tokens)

### Current Issue:
- Currently, to create or generate a password grant token the only option is to make an additional http call inside our project code base.
- An extra unnecessary http call inside the code base can be the source for many issues which can be easily avoided in the first place.

### Hack to solve it:
- We have to extend Passport's `AccessTokenController` and create a child controller with methods that delegate things to passport's internal methods with some pre-work:

```php
public function login(ServerRequestInterface $request)
{
        $parsedBody = $request->getParsedBody();

        $client = $this->getClient($parsedBody['client_name']);

        $parsedBody['username'] = $parsedBody['email'];
        $parsedBody['grant_type'] = 'password';
        $parsedBody['client_id'] = $client->id;
        $parsedBody['client_secret'] = $client->secret;

        // since it is not required by passport
        unset($parsedBody['email'], $parsedBody['client_name']);

        return parent::issueToken($request->withParsedBody($parsedBody));
}
```

### Request:
-  Let passport expose an API that takes the grant type and client name (optional) and returns a password grant token in return.

I am up for a PR to solve this if this idea is approved and if someone familiar with passport's internal code base/architecture can guide me a bit on how to structure it the best way 🙂

**Comment by driesvints** [comment]
This has already been discussed in another issue and rejected. Please see the details here: https://github.com/laravel/passport/issues/1123
