### ISSUE TITLE
Invalid grant_type error message and error code, if credentials are invalid.

### ISSUE THREAD

**Issue by michaelbeers** [laravel/passport#1164]
- Passport Version: 8.8.8
- Laravel Version: 6.2.x
- PHP Version: 7.2.x
- Database Driver & Version: Mysql 5.7

### Description:
The `example.com/oauth/token` call is returning error code 400 instead of error code 401, like previous Laravel Passport version(s)

### Steps To Reproduce:
- Clean Laravel install.
- Clean Laravel Passport install, using the documentation (instead of the `passport:install` command, used `passport:keys` to create certificates).
- Add a new password client into the database (using a seeder).
```
        \Laravel\Passport\Client::create([
            'name'                   => 'Web',
            'secret'                 => 'demo',
            'redirect'               => env('APP_URL'),
            'personal_access_client' => false,
            'password_client'        => true,
            'revoked'                => false,
        ]);
```
- Add a new user into the database (using a seeder).
```
\App\User::create([
                'name'       => 'Demo user',
                'email'      => 'demo@example.com',
                'password'   => xxx
            ]);
```
- Try to login with invalid credentials
- The following message appears:
```
The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
```

**Comment by driesvints** [comment]
This was a change in league/oauth2-server. Please check their changelog.

**Comment by joshhornby** [comment]
@michaelbeers Did you find this fix/change for this?

**Comment by siarheipashkevich** [comment]
@michaelbeers did you find the solution for your problem?

**Comment by michaelbeers** [comment]
@siarheipashkevich Yes i did, since it is an change in the league/oauth2-server package i changed my authentication handler in the project that was connecting my Laravel backend using Passport.
