### ISSUE TITLE
I use #71 found an error 

### ISSUE THREAD

**Issue by myischen** [laravel/passport#1172]
- Passport Version: 8.2.0
- Laravel Version:6.12.0
- PHP Version:7.4.1
- Database Driver & Version:n/a

### Description:
I use  [#71](https://github.com/laravel/passport/issues/71#issuecomment-330506407)     `sendBearerTokenResponse` I found an error. How can I change
### Steps To Reproduce: 
```
 protected function sendBearerTokenResponse($accessToken, $refreshToken)
    {
        $response = new BearerTokenResponse();
        $response->setAccessToken($accessToken);
        $response->setRefreshToken($refreshToken);

        $privateKey = new CryptKey('file://'.Passport::keyPath('oauth-private.key'), null, false);

        $response->setPrivateKey($privateKey);
        $response->setEncryptionKey(app('encrypter')->getKey());

        return $response->generateHttpResponse(new Response);
    }
```

![image](https://user-images.githubusercontent.com/29190298/73268994-eb24e980-4216-11ea-97e0-f2a5da3f614b.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
