### ISSUE TITLE
Create Access and Refresh Token Without Password 

### ISSUE THREAD

**Issue by mortezamoradi72** [laravel/passport#1177]
- Passport Version: 8.3
- Laravel Version: 6.13.1
- PHP Version: 7.2.1
- Database Driver & Version: mysql

### Description:
Hello i want to create access and refresh token with passport for user manually without use password , i searched and people say this message ( #71 comment) is true but problem is this comment not work in laravel 6.13.1 

the error is in line 80 in file PassportToken.php that used in #71 

**$accessToken = new AccessToken($user->id);** 
in this line this method just have 1 argument 

but in this method in _construct it have 3 argument :
$userIdentifier, 
array $scopes,
 ClientEntityInterface $client
```

>     public function __construct($userIdentifier, array $scopes, ClientEntityInterface $client)
>     {
>         $this->setUserIdentifier($userIdentifier);
> 
>         foreach ($scopes as $scope) {
>             $this->addScope($scope);
>         }
>         $this->setClient($client);
>     }

```
How Can i Solve this ? or if you know another way please help me.
i want to use it for register and login user by mobile number and create him access and refresh token.
Thank You.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by daqiaowijiu** [comment]
i have same question,do you have answer?
