### ISSUE TITLE
Add support to change database connection

### ISSUE THREAD

**Issue by kevindierkx** [laravel/passport#118]
Since #113 got rejected I'm opening this issue to discuss a potential addition to change database connections.

Passport currently uses the default database connection configured in the `database.php` config file.

This doesn't work for my use case. I have 2 applications 1 for all the front-end stuff ie. issuing tokens displaying the authorization screen etc. the second is purely an API. The default connection for these applications are different, therefore when using passport the authorization process will break because passport can't reach my oauth tables in 1 of the two applications.

I use this setup to separate my database tables across different databases and to separate my application logic to keep things flexible.

To support these kind of setups laravel/passport would require the database connection name to be configurable.

[lucadegasperi/oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel) supports this by using the `connection()` method. It is possible to use the same method in `laravel/passport`, but it would become a bit messy when working with both eloquent model repositories and bridge repositories talking directly to the DB query builder.

I would suggest using either eloquent model repositories everywhere like #113 introduced or remove the eloquent model repositories altogether and used the bridge repositories primarily. Lastly we could use a static method to set the connection name during registration.

@taylorotwell I'm wondering if this fits the general idea of the package.

I'm open for suggestions.

**Comment by themsaid** [comment]
Closing since there are no plans for this at the moment.

**Comment by kevindierkx** [comment]
@themsaid Any other plans on supporting something 'adaptable' or any suggestions I could potentially integrate in a PR?

Since both #113 and this issue are closed without any additional remarks and support for lucadegasperi/oauth2-server-laravel has been dropped in favour of this package, I'm somewhat running into a brick wall.

I would appreciate some kind of insight.

**Comment by Modelizer** [comment]
@kevindierkx will it solve your problem if database connectivity for passport is specified in `.env`  or `database.php` file for your application?

Because I think refactoring for the repository will be a bigger change to get you up and running.

**Comment by bruno-fernandes** [comment]
@Modelizer that would certainly solve the problem in most cases.

**Comment by kevindierkx** [comment]
@themsaid Refactoring to repositories is actually something Ive proposed in #113, this would add support to swap out models and manage the connection that way. Also it would make all the calls to the database go trough an 'eloquent' repository, now only 2 or 3 entities are resolved trough an 'eloquent' repository.

Using `.env` could work, but would need varying modifications to work on all resources.

The cleanest and if you ask me preferred solution would use the Passport service class.
We could add a static property comparable to the `$cookie` property containing the connection name. Then we should use the `->connection()` method on eloquent models and replace the injected `Connection` instance in repositories talking directly to the connection using the `->table()` method. (This approach is actually comparable to [lucadegasperi/oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/Storage/FluentStorageServiceProvider.php#L128)'s storage setup)

**Comment by Modelizer** [comment]
`Repository` comes into picture when we want to deal with multiple ORMs. In your case swapping, DB connection will solve your problem. Frankly speaking, it looks over overcomplicated! 

As Taylor said in https://github.com/laravel/passport/pull/113 he has no plan to add support for other ORMs in passport which is Okay 👍  

I think it would be better if you propose a PR which will swap connection for passport if user specifies connection in `database.php` file. I think @taylorotwell would accept it 🤔

**Comment by Anahkiasen** [comment]
Is there still no way to do this? We use a graph database on our application so we cannot use Passport at all at the moment which is very problematic. I wouldn't mind having a separate SQL db just for Passport but currently even that is not possible

**Comment by kevindierkx** [comment]
@Anahkiasen Not to my knowledge. Both @taylorotwell and @themsaid didn't have plans to add something comparable or accepts the issued PR's in the near future.

For my project I've ended up using the latest dev-master from [lucadegasperi/oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel). Just before the package deprecated, in favour of passport, they've added Laravel 5.3 support.

With the upcoming release of L5.4 this could get blocking, I've therefore contacted @lucadegasperi asking him about his future plans for the package. He wasn't planning on extending the support and suggested issuing a PR for laravel/passport instead. (That didn't really work out.)

At this point I'm most likely just forking [lucadegasperi/oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel) since it has extended support in  [dingo/api](https://github.com/dingo/api) which we are also using in our projects.

**Comment by Anahkiasen** [comment]
How I solved it on my end is:

1. Set the default connection to `mysql`
2. Create an `AbstractModel` that all my models extend with `protected $connection = 'neo4j';` on it
3. Set the `protected $connectionsToTransact = ['neo4j'];` on `TestCase` (if using the `DatabaseTransactions` trait)
4. Ensure that the one/two straight up calls to `DB::` were changed to `DB::connection('neo4j')`

That seems to work for me without any major change to the codebase. If that can help somebody else landing here from Google

**Comment by tomahock** [comment]
Thanks @Anahkiasen I'm in the same situation, have a graph database as the default and I did the same thing as you. It works!
But I would prefer a straight forward solution. The `.env` one was not that bad and would solve most of the situations.

**Comment by oberoivarun** [comment]
Need this! Any updates?

**Comment by Anahkiasen** [comment]
@oberoivarun I'm not sure you can, that's why I had to set the default connection to the one Passport use, and then make all my models use neo4j which is my actual default connection. :/
