### ISSUE TITLE
Error when trying to publish Passport's Views to customize the authorization approval screen (Unable to locate publishable resources.)

### ISSUE THREAD

**Issue by SuperlativeEntity** [laravel/passport#1183]
- Passport Version: 8.3.1
- Laravel Version: 6.14.0
- PHP Version: 7.2.19
- Database Driver & Version: N/A

### Description:

Error when trying to publish Passport's Views to customize the authorization approval screen (Unable to locate publishable resources.)

### Steps To Reproduce:

php artisan vendor:publish --tag=passport-views
Unable to locate publishable resources.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
