### ISSUE TITLE
Why is publishing of the config file separated from the rest of the assets?

### ISSUE THREAD

**Issue by Ilyes512** [laravel/passport#1184]
- Passport Version: 8.3.1

### Description:
Is there a specific reason for the `offerPublishing`-method located @ https://github.com/laravel/passport/blob/v8.3.1/src/PassportServiceProvider.php#L300-L312

Why can't this be added with the rest of the "publishing": https://github.com/laravel/passport/blob/v8.3.1/src/PassportServiceProvider.php#L42-L56

Am I missing something and is there actually a difference?

**Comment by driesvints** [comment]
No real reason. Afaik it should be done in the boot method as the docs say: https://laravel.com/docs/6.x/packages#publishing-file-groups

Feel free to send in a PR if you want.

**Comment by Ilyes512** [comment]
I will! Thanks
