### ISSUE TITLE
Is the use of a refresh token in multiple requests working correct?

### ISSUE THREAD

**Issue by rsdrsd** [laravel/passport#1185]
- Passport Version: 8
- Laravel Version: 6
- PHP Version: 7.4
- Database Driver & Version: mysql 5.7

When I use password grant type, the result is a short lived access_token, a refresh_token and an expires_in value.

I store the refresh token in a http only cookie.

Now I have an endpoint where I can refresh the access_token, by getting the refresh token from the cookie. For one request to this endpoint it works, but when I have 2 requests to this endpoint, whichever request comes first, gets the new access token and refresh token. The other request tries to retrieve a new access token and refresh token, but since the refresh token is revoked by the first request it can't retrieve it. 

This situation could occur in multiple browser tabs for example.

Is this expected behavior and if so, how to deal with this situation. Because it would be nice that I always have a correct and working refresh token and short lived access token (5 min).

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
