### ISSUE TITLE
Client_id not found when using first party client for authorisation request

### ISSUE THREAD

**Issue by pjotrsavitski** [laravel/passport#1187]
- Passport Version: 7.5.1
- Laravel Version: 5.8.34
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.7.26

### Description:

Authorisation code grant does not seem to be allowed use with First Party clients. At least according to this:
https://github.com/laravel/passport/blob/8.x/src/Bridge/ClientRepository.php#L76

The code in Client class determines any personal access or password client as a First Party client:
https://github.com/laravel/passport/blob/8.x/src/Client.php#L81

It does make sense in a way, but is not mentioned in the documentation and using clients generated by default results in a message telling that such client_id does not exist.

That logic does not seem to have changed between versions 7.x and 8.x. It should either be mentioned in the documentation or a meaningful exception should be logged to indicate that a wrong type of client is being used.

### Steps To Reproduce:

* Install laravel/passport following [documentation](https://laravel.com/docs/5.8/passport)
* Issue [authorisation request](https://laravel.com/docs/5.8/passport#requesting-tokens) using the first automatically generated token

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by pjotrsavitski** [comment]
The issue is not present with Laravel 6.x and laravel-passport 8.4.0.
