### ISSUE TITLE
Things i don't understand about Passport

### ISSUE THREAD

**Issue by Aferz** [laravel/passport#119]
Hi Laravel guys, i need of your wisdom to try to understand few things about this package:

1.-

`php artisan passport:install`

Why is this really needed ? I don't understand the fact that you need some kind of "fake clients" in "oauth_clients" table to generate this type of auth tokens.

2.-

Why do we need user_id column in "oauth_clients" table ? Do we really need the user that added that client ? It's just informative ? This means i can't add a new client without providing an user ? And, if i can, why i need the user_id ? 

Sorry, this is blowing my mind. I'm 100% sure i'm missing something.

Thanks in advance

**Comment by craigpaul** [comment]
Hey @Aferz,

1. The install command does more than just generate your own clients. It also creates the private and public key needed for encryption. Check in `storage` (by default) and you will see `oauth-private.key` and `oauth-public.key`. Now as for them being "fake" clients, that is not true. Those are the clients you can use for your own first party applications (mobile, web, etc).

2. The `user_id` is required as per the oAuth2 spec. What we are doing with these access tokens (for most grant types) is authenticating a user, therefore, we need to have a user record to reference. The only grant type that doesn't need a user is the Client Credentials grant.

Hope that some stuff up for you.

**Comment by Aferz** [comment]
Absolutely clear @craigpaul. Thank you very much.
