### ISSUE TITLE
Made lifetime for auth code easy customizable

### ISSUE THREAD

**Issue by prodigy7** [laravel/passport#1190]
So far I hope understand right, auth code are currently valid for 10 minutes. The OAuth 2.0 spec recommends a maximum lifetime of 10 minutes and I want set a shorter lifetime (30-60 seconds).

So far I understand, the lifetime is set here (passport/src/PassportServiceProvider.php):
```
    protected function registerAuthorizationServer()
    {
        $this->app->singleton(AuthorizationServer::class, function () {
            return tap($this->makeAuthorizationServer(), function ($server) {
                $server->setDefaultScope(Passport::$defaultScope);

                $server->enableGrantType(
                    $this->makeAuthCodeGrant(), Passport::tokensExpireIn()
                );

                $server->enableGrantType(
                    $this->makeRefreshTokenGrant(), Passport::tokensExpireIn()
                );

                $server->enableGrantType(
                    $this->makePasswordGrant(), Passport::tokensExpireIn()
                );

                $server->enableGrantType(
                    new PersonalAccessGrant, Passport::personalAccessTokensExpireIn()
                );

                $server->enableGrantType(
                    new ClientCredentialsGrant, Passport::tokensExpireIn()
                );

                if (Passport::$implicitGrantEnabled) {
                    $server->enableGrantType(
                        $this->makeImplicitGrant(), Passport::tokensExpireIn()
                    );
                }
            });
        });
    }


    /**
     * Create and configure an instance of the Auth Code grant.
     *
     * @return \League\OAuth2\Server\Grant\AuthCodeGrant
     */
    protected function makeAuthCodeGrant()
    {
        return tap($this->buildAuthCodeGrant(), function ($grant) {
            $grant->setRefreshTokenTTL(Passport::refreshTokensExpireIn());
        });
    }
```
When I see it right, i could change the lifetime with Passport::tokensExpireIn($value) but it would also have a impact to other grant types like 'refresh' or 'password'. Is there any easy way, change it for auth code only without leaving default code?
I know, extend/override the service provider replacing the logic in this registerAuthorizationServer method with your own is possible, but also a step more own code only for a simple setting.

So I wish, the auth code has a own method for override default lifetime setting.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by prodigy7** [comment]
Hi driesvints,

I don't agree with you, it is not a question, it's a feature request. Currently the lifetime is set by default to 10 minutes but the oauth specification recommend 30-60 seconds (See https://www.oauth.com/oauth2-servers/authorization/the-authorization-response/) and there is no explicit way, change this auth code lifetime (Which doesn't have to mean that I may have overlooked how you I only change the value via configuration or a single method).

I want a method, for example ``Passport::authCodesExpireIn($value) ``

Thanks.

**Comment by driesvints** [comment]
@prodigy7 it's in the docs: https://laravel.com/docs/6.x/passport#token-lifetimes

**Comment by driesvints** [comment]
Can you explain why you want these tokens to have different lifetimes?

**Comment by JuanDMeGon** [comment]
I think we have a confusion here...
@prodigy7 are you talking about the code that you use to interchange for an access token or you are talking about the access token itself?
Because the link you shared talks about the code (the one you interchange), but the code you show in your first post, is about the expiration times of the access tokens.

**Comment by prodigy7** [comment]
@JuanDMeGon Sorry, when my descriptions was not detailed enough.

Yes, I talk about the auth code I got back when a user accept a request. The auth code, which is used by a service receive the final access token.

**Comment by JuanDMeGon** [comment]
Ok, so in that case, I am afraid it is not currently possible. It will always be 10 minutes.
here is the segment where it is established to 10 minutes: https://github.com/laravel/passport/blob/8.x/src/PassportServiceProvider.php#L158 and it seems it is not configurable.
The good news is... If you really really need this, you can just re-define the PassportServiceProvider with your own class, specifying a different value for the expiration of the authorization codes.
Of course, a PR is valid and may not introduce a breaking change as well.

**Comment by prodigy7** [comment]
Sure, I can re-define the PassportServiceProvider but it's really a lot of overhead for something, should be configurable. 
I would like to stay with the original code as much as possible, so that I have little effort for adjustments in later updates.

**Comment by driesvints** [comment]
We're probably not going to add this ourselves anytime soon. You're free to attempt a pr if you want. Thanks.

**Comment by prodigy7** [comment]
Sorry, but I dont understand why you close my feature request. As JuanDMeGon also wrote, it is not really a good idea generate auth code with that long lifetime. Yes, there is a "workaround" but the RFC (https://tools.ietf.org/rfc/rfc6749.txt - 4.1.2) also describes 10 minutes lifetime as maxium ("A maximum authorization code lifetime of 10 minutes is RECOMMENDED") and for security reasons it would be good, set a shorter lifetime or better made it directly possible to configure it.

If i will find the time, find out what is to do and send a PR next days. In the meantime this request should be open, maybe someone is faster and submit the needed code. Currently I am working with 7.5 branch and have no idea, what have changed to 8.x.

**Comment by Sephster** [comment]
It's recommended that the maximum life time is ten minutes. This is what Passport has set the maximum life time to in line with that recommendation. Passport is following the default guidance. As soon as the auth code is used it is revoked in the system so the risk here is minimal.

**Comment by JuanDMeGon** [comment]
I agree with @Sephster, there is not much need to do these changes and Passport still accomplishing the standard.
Anyway, probably a PR would be easy to "solve" this, but there is no rush at all.

**Comment by Peter-Krebs** [comment]
Creating a child class of `PassportServiceProvider` to override `buildAuthCodeGrant()` seems easy enough.

The default implementation follows the minimum advised security guidelines, however.  
Setting the timeout to 10 minutes is a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) in the code in any case.  
It should become a named constant or configuration with the RFC mentioned as documentation.

**Comment by prodigy7** [comment]
Well, I can live with not being right. But I would like to understand (and learn from) why my intentions should be wrong.
I still find it inconsistent to make values configurable on the one hand, but on the other hand to overwrite them with own methods. Basically, it is the same thing, but different solutions should be applied. Personally, I think it makes sense to have a "red thread" running through a software from beginning to end, which makes it easier to understand. At this point the thread is cut for me.
Yes, it is a small thing but the intention to decide how it was decided interests me.
