### ISSUE TITLE
Authorization Code Grant with PKCE: skipsAuthorization not working

### ISSUE THREAD

**Issue by SuperlativeEntity** [laravel/passport#1196]
- Passport Version: 8.4.0
- Laravel Version: 6.15.0
- PHP Version: 7.2.19
- Database Driver & Version: N/A

### Description:

Authorization Code Grant with PKCE not skipping authorization prompt

### Steps To Reproduce:

Implement custom client as indicated by documentation with skipsAuthorization

When logging in, the redirect callback still displays the authorization prompt  screen

**Comment by driesvints** [comment]
Please provide some code or an app to reproduce.

**Comment by SuperlativeEntity** [comment]
install passport as per usual

run "php artisan passport:client --public" to create an "Authorization Code Grant with PKCE Client"

Create a custom client class as mentioned in your documentation: https://laravel.com/docs/6.x/passport

`<?php

namespace App\Models\Passport;

use Laravel\Passport\Client as BaseClient;

class Client extends BaseClient
{
    /**
     * Determine if the client should skip the authorization prompt.
     *
     * @return bool
     */
    public function skipsAuthorization()
    {
        return $this->firstParty();
    }
}`

use custom client in passport set-up

`use App\Models\Passport\AuthCode;
use App\Models\Passport\Client;
use App\Models\Passport\PersonalAccessClient;
use App\Models\Passport\Token;

/**
 * Register any authentication / authorization services.
 *
 * @return void
 */
public function boot()
{
    $this->registerPolicies();

    Passport::routes();

    Passport::useClientModel(Client::class);
}`

then create a route to test (as per your documentation)

`Route::get('/redirect', function (Request $request) {
    $request->session()->put('state', $state = Str::random(40));

    $request->session()->put('code_verifier', $code_verifier = Str::random(128));

    $codeChallenge = strtr(rtrim(
        base64_encode(hash('sha256', $code_verifier, true))
    , '='), '+/', '-_');

    $query = http_build_query([
        'client_id' => 'client-id',
        'redirect_uri' => 'http://example.com/callback',
        'response_type' => 'code',
        'scope' => '',
        'state' => $state,
        'code_challenge' => $codeChallenge,
        'code_challenge_method' => 'S256',
    ]);

    return redirect('http://your-app.com/oauth/authorize?'.$query);
});`

you will then see after logging in, the authorization prompt screen is not bypassed

**Comment by SuperlativeEntity** [comment]
backend: https://github.com/SuperlativeEntity/laravel6api

custom client:
https://github.com/SuperlativeEntity/laravel6api/blob/master/app/OAuth/OAuthServiceProvider.php

`Passport::useClientModel(Client::class);`

https://github.com/SuperlativeEntity/laravel6api/blob/master/app/Models/Passport/Client.php

`public function skipsAuthorization()`

then run "php artisan passport:client --public" to create client

callback: http://localhost:4200/oauth/callback

Angular SPA (edit environment.ts to point to oauth server, enter client id)

https://github.com/SuperlativeEntity/angularspa

when up and running on http://localhost:4200/, click on log in

enter login details and notice that authorization prompt screen appears when it should actually be skipped

**Comment by driesvints** [comment]
I can't even get the current docs example to work. Getting an infinite loop somewhere. @filipegar since you wrote the docs: are you sure it should work with just the examples in it?

**Comment by driesvints** [comment]
@SuperlativeEntity since you closed this: what went wrong?
