### ISSUE TITLE
Unsupport Laravel 7.0

### ISSUE THREAD

**Issue by hihuangwei** [laravel/passport#1202]
- Passport Version: 8.4.0
- Laravel Version: 7.0.02
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8

### Description:
Exception
Unable to resolve PSR request. Please install symfony/psr-http-message-bridge and nyholm/psr7.

**Comment by developer-ssr** [comment]
Same issue with me :(

**Comment by RomainLanz** [comment]
It seems that the current branch (`8.x`) has the fix available.

Could we expect a release soon?

**Comment by gerardnll** [comment]
To me, this error pops up when using the `CheckClientCredentials` middleware, I guess it happens because it's creating a new `PsrHttpFactory`. Just installing `nyholm/psr7` solves temporarily the problem.

**Comment by driesvints** [comment]
Released v8.4.1 with the dependency changes. Thanks for reporting.

**Comment by pawel-marciniak** [comment]
Can't update to newer version with composer, is it only me?

**Comment by gerardnll** [comment]
I had no problem updating yesterday.

**Comment by pawel-marciniak** [comment]
Strange, for new project it installs v8.4.1 but when I execute `composer show laravel/passport` in my existing project it shows `versions : * v8.4.0`, I even cleared a composer cache and still the same...

**Comment by lk77** [comment]
Hello,

is there a way to use laravel/passport 7.5.1 with laravel 7.5.x ?
