### ISSUE TITLE
Catch Invalid or Expired personal access tokens 

### ISSUE THREAD

**Issue by sage-dev2** [laravel/passport#1204]
I am using personal access tokens for an API. Would like to report different error for invalid and different one for expired tokens. In Handler.php, unauthenticated function returns "Unauthenticated" for both type of errors. How can I catch them separately? Using laravel 5.8

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
