### ISSUE TITLE
Getting a 403 error: The provided auth token for the request is different from the session auth token when using Laravel Passport oauth

### ISSUE THREAD

**Issue by rouve** [laravel/passport#1206]
- Passport Version: ^8.4
- Laravel Version: ^7.0.0
- PHP Version: 7.2.5
- Database Driver & Version: Mariadb 10.4.7

### Description:
I am using Laravel 7 and I am trying to get familiar with passport oauth 2.0 implementation. I have set up everything correctly from my client site:

```
Route::get('/redirect', function () {
    request()->session()->put('state', $state = Str::random(40));
    $query = http_build_query([
        'client_id' => 5,
        'redirect_uri' => 'http://localhost:8001/callback',
        'response_type' => 'code',
        'scope' => '',
        'state' => $state,
    ]);

    return redirect('http://localhost:8000/oauth/authorize?'.$query);
});

Route::get('/callback', function () {
    $state = request()->session()->pull('state');

    throw_unless(
        strlen($state) > 0 && $state === request()->state,
        InvalidArgumentException::class
    );

    $http = new GuzzleHttp\Client;

    $response = $http->post('http://localhost:8000/oauth/token', [
        'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => '1',
            'client_secret' => 'XcxHBsIAPDsmCBTsy0PtAHE7pG9TbbkemVtmAXD8',
            'redirect_uri' => 'http://localhost:8001/callback',
            'code' => request()->code,
        ],
    ]);

    return json_decode((string) $response->getBody(), true);
});
```

I did not really do much configuration to the auth server, I just included the `Passport::routes();` line in the `AuthServiceProvider` class. Nevertheless I have traced the following error coming from the `RetrievesAuthRequestFromSession` trait in the passport package after I approved the request. This is the method:

```
protected function assertValidAuthToken(Request $request)
    {
        dump($request->session()->get('authToken'));
        dump($request->get('auth_token'));
        if ($request->has('auth_token') && $request->session()->get('authToken') !== $request->get('auth_token')) {
            $request->session()->forget(['authToken', 'authRequest']);

            throw InvalidAuthTokenException::different();
        }
    }
```

Additional info; my clients port is 8001. The server is 8000. May anyone please help me with the issue. Thank you in advance.

### Steps To Reproduce:
I followed the steps on Laravels documentation. It happens after i click on approve.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by JoDeveloper** [comment]
@rouve how did you solve this issue ?

**Comment by adi-rebellion** [comment]
@rouve how did you solve this issue ?

@JoDeveloper any leads?
