### ISSUE TITLE
Authorization grant with PKCE is always throwing invalid_client error

### ISSUE THREAD

**Issue by StefanT123** [laravel/passport#1210]
- Passport Version: 8.4.2
- Laravel Version: 7.3.0
- PHP Version: 7.4.4

### Description:
When you call the `oauth/authorize` route and you send the proper query as explained in the passport documentation, it always throws `invalid_client` error.

### Steps To Reproduce:
Just follow the steps in the documentation.

### The problem
Digging deeper, I found out that in `League\OAuth2\Server\Grant\AuthCodeGrant` class in the `validateAuthorizationRequest` method on line 258 this condition exists:
```php
if ($redirectUri !== null) {
    $this->validateRedirectUri($redirectUri, $client, $request);
}
```
If we go to the `validateRedirectUri` method in the `League\OAuth2\Server\Grant\AbstractGrant`, we can see that this method has two conditions, and they both throw an exception, here is the whole method:
```php
protected function validateRedirectUri(
        string $redirectUri,
        ClientEntityInterface $client,
        ServerRequestInterface $request
    ) {
        if (\is_string($client->getRedirectUri())
            && (strcmp($client->getRedirectUri(), $redirectUri) !== 0)
        ) {
            $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
            throw OAuthServerException::invalidClient($request);
        } elseif (\is_array($client->getRedirectUri())
            && \in_array($redirectUri, $client->getRedirectUri(), true) === false
        ) {
            $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
            throw OAuthServerException::invalidClient($request);
        }
    }
```

I don't know if this is intended behavior, but if I change this, I can get to the authorization screen.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
