### ISSUE TITLE
How to generate access token By User  如何通过用户来生成令牌

### ISSUE THREAD

**Issue by nifengfanpan** [laravel/passport#1211]
In version 7.2, the bearertokenresponse method can be used to generate tokens. However, in the latest version, after debugging compatibility for a whole day, the tokens can't be generated finally for help

But in the latest version, it's GG

在7.2版本中，可以使用BearerTokenResponse这个方法生成token，但是在最新版本中，调试了一整天的兼容，最后还是不能生成token，求助

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
