### ISSUE TITLE
Feature Request: `revoked` boolean to `revoked_at` timestamp

### ISSUE THREAD

**Issue by gofish543** [laravel/passport#1214]
I've always listened to Taylor and others discuss the benefits of using a timestamp rather than a simple boolean flag to manage a boolean state.
Example: Email verification for Laravel is done using the `email_verified_at` field rather than just `has_email_verified`

What I propose is renaming the field `revoked` to `revoked_at` (converting it from a boolean to a timestamp) and creating an accessor within Passport's Client model `revokedAttribute` so that, for backwards comparability sake, the `$client->revoked` field is still present, but there is more information stored within the revoked field.

Let me know what you think!

**Comment by gofish543** [comment]
That is what I am still torn about, whether the severity of the breaking change warrants the additional data. 

A simple answer would be to simply set the columns already revoked to be the date the update is made, but this solution feels very naive.

A second solution would be the encoding of a 'special' date which, if encounter, acts as a "no date found, but still revoked" field.

A third solution would be for users to specify a date which the package pulls in and updates against.

In my opinion, the increase in data is worth the change, but I'm also not the one maintaining the repository and dealing with the angry users who don't read patch notes before updating.
I found a use for the field and figured others might have a shared use as well.

In the end it is up to you and the Laravel team to decided if the additional data is worth the massive breaking change. You all have **way** more experience dealing with these kinds of features and updates.

**Comment by driesvints** [comment]
> A simple answer would be to simply set the columns already revoked to be the date the update is made, but this solution feels very naive.

There's no `updated_at` column.

> A second solution would be the encoding of a 'special' date which, if encounter, acts as a "no date found, but still revoked" field.

No actually data is confusing tbh.

> A third solution would be for users to specify a date which the package pulls in and updates against.

Think this would be a little to far fetched to implement this.

I agree that the idea is good but it's probably not worth the breaking change. Thanks for proposing though.
