### ISSUE TITLE
Add new event for when a new client is added

### ISSUE THREAD

**Issue by mgiritli** [laravel/passport#1218]
I needed to have a way to act when a new client is created. So I created a new branch which adds a new event ( "ClientCreated" ) which fires when a new client is added. I thought I should create this first to have any suggestions before a pull request. This is my first ever PR, so please be kind.

My branch is here: https://github.com/mgiritli/passport

**Comment by mgiritli** [comment]
If it is acceptable, I'll add some events for when a token and client are revoked / removed. But first lets see how this goes.

**Comment by driesvints** [comment]
I can see that being useful yeah. Feel free to send in the PR.

**Comment by driesvints** [comment]
Closing this as we haven't had many requests for this. Feel free to PR if you want.
