### ISSUE TITLE
If the parameters of the client callback connection are more than 'code' and 'state', what can I do? The callback connection needs to carry some business parameters

### ISSUE THREAD

**Issue by mr-chen-king** [laravel/passport#1221]
If the parameters of the client callback connection are more than 'code' and 'state', what can I do? The callback connection needs to carry some business parameters

### original callback look like   
https://****/oauth/callback?code=4edb829d6ac45a92d15f12ebc614a5073e5503ebfca29e188a15fe4734d829acac4fb6478b00617ef3fbe6d7a70530633ad0f01ef47fdd01fba34c68666c43fc43c91a05cc6eda5c5c2bdbc0674871284bdd262e03f79be9e03707689db929f745b53a5903c4c647031edb47071ae&state=0.7068255052502914

### but i need this
https://****/oauth/callback?code=4edb829d6ac45a92d15f12ebc614a5073e5503ebfca29e188a15fe4734d829acac4fb6478b00617ef3fbe6d7a70530633ad0f01ef47fdd01fba34c68666c43fc43c91a05cc6eda5c5c2bdbc0674871284bdd262e03f79be9e03707689db929f745b53a5903c4c647031edb47071ae&state=0.7068255052502914&skillId=1234354&token=lkjhyu7ih192332sdf

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mr-chen-king** [comment]
Thank you for your reply.
I use your plug-in in the laravel 5.6 framework. If anyone has the answer, please let me know. Thank you very much
