### ISSUE TITLE
Obtain access token and refresh token without a http request

### ISSUE THREAD

**Issue by Erjavi95** [laravel/passport#1225]
Hi all, I have been researching for almost a month and I have not managed to find the way to do it and then I found this post `https://github.com/laravel/passport/issues/71 `but it turns out that the topic is closed and I cannot ask a question and i wish i could do that with laravel version 7

If anyone can straighten my way I would appreciate it

**Comment by Sephster** [comment]
If this is a requirement, OAuth is probably not the solution.

**Comment by Erjavi95** [comment]
I am making a mobile application and I want to secure it so I am using firebase as a third-party library to do the authentication and when I register/login with the firebase interface I send the token_id to the server to check if it is valid and if it is valid store in my table the mail and the uid and now i would like to protect the other routes of my api through the laravel passport system so i want to generate an access_token and a refresh_token for it in the endpoint

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Myusuf060696** [comment]
i have same question,do you have answer?

**Comment by jackbaron** [comment]
I have a same issue. Do you have a solution?
