### ISSUE TITLE
/oauth/token tries to use database of laravel project sending the request

### ISSUE THREAD

**Issue by execute008** [laravel/passport#1229]
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cms.oauth_clients' doesn't exist` 
This error is returned when I try to call the /oauth/token route via GuzzleHttp like in the documentation.
The strange part is that "cms" is the database of the laravel project sending the request, so technically it shouldn't even know this database.

When i call the route with Postman everything works fine and i get a token returned.

I really don't know what the problem could be, so i ask you for your help.

This is the request i'm sending out:
`        
$http = new \GuzzleHttp\Client;

        $response = $http->post($project->url.'/oauth/token', [
            'form_params' => [
                'grant_type' => 'password',
                'client_id' => $obj->client_id,
                'client_secret' => $obj->client_secret,
                'username' => $obj->username,
                'password' => $obj->password,
                'scope' => '*',
            ],
        ]);`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
