### ISSUE TITLE
Migrations not applied from DatabaseMigrations trait in Laravel

### ISSUE THREAD

**Issue by Francismori7** [laravel/passport#123]
If you happen to have a query from your service provider, in my case I am using this:

```
Passport::personalAccessClient(Client::query()->where('name', 'like', '% Personal Access Client')->firstOrFail()->id);
```

When using PHPUnit, all your tests will fail with an error as such: 

```
SQLSTATE[HY000]: General error: 1 no such table: oauth_clients (SQL: select * from "oauth_clients" where "name" like % Personal Access Client limit 1)
```

That's using DatabaseMigrations as well.

**Comment by ronnievisser** [comment]
Have you solved this? i'm running in the exact same problem at the moment.

**Comment by huntsfromshadow** [comment]
That is odd as it's working fine for my tests.

You have set something like <env name="DB_CONNECTION" value="testing"/> in your phpunit.xml file correct?
