### ISSUE TITLE
After save user is not unauthenticated

### ISSUE THREAD

**Issue by homeoftheunits** [laravel/passport#1232]
- Passport Version: 8.4.4
- Laravel Version: 7.9.2
- PHP Version: 7.3.17
- Database Driver & Version: MySQL 8

### Description:
User Model belongs to another Model, so in the User Model there is an organization_id:
```
public function organization(): BelongsTo
{
    return $this->belongsTo(Organization::class, 'organization_id');
}
```

The other Organization Model has an HasMany Relation:
```
public function users(): HasMany
{
     return $this->hasMany(User::class);
}
```
Then i have an Controller to save the new Organisation, and associate to the user:
```
$this->authorize('create', Organization::class);
$organization = Organization::create($request->validated());
Auth::user()->organization()->associate($organization)->save();
```

After that, the organization_id in the User Model / Table is set to the id of the organization. But when i login again with the User, the User is unauthorized. When i compare the User Model before and after save() with `dd(Auth::user())` i see that the password is an item of the changes array, but the Hash is the same. 

### Steps To Reproduce:

Login a User:
```
$auth = Auth::attempt($request->only('email', 'password'));
return Auth::user()->createToken('App')->accessToken;
```

Create a Organization:
```
$this->authorize('create', Organization::class);
$organization = Organization::create($request->validated());
Auth::user()->organization()->associate($organization)->save();
```

Login the same User again, it returns unauthorised

Things like:
```
User::find(Auth::user()->getAuthIdentifier())->first()->update(['organization_id' => $organization->id]);
```
or
```
Auth::user()->forceFill(['organization' => $organization->id])->save()
```

brings the same effect.

Cheers
Ralf

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by homeoftheunits** [comment]
Sure, but i think it is an Bug. That's why i posted it here. This is an undocumented behavior i think.

**Comment by homeoftheunits** [comment]
@driesvints nobody has answer to my problem, so i think it is an Bug. Please, open it that you can fix it
