### ISSUE TITLE
support for latest guzzlehttp v7.0 

### ISSUE THREAD

**Issue by amitshahc** [laravel/passport#1233]
my php version on server is 7.2.30 which throws error while using guzzle 6.0. that needs to be updated to 7.0. but then there is no support for laravel/passport to this version.

**Comment by driesvints** [comment]
Guzzle 7 isn't even released yet.

**Comment by amitshahc** [comment]
i had upgraded it to 7.0.0-beta.1 version due to this issue. https://github.com/guzzle/guzzle/issues/2620

**Comment by driesvints** [comment]
That's not a stable release.
