### ISSUE TITLE
How to get The authenticated Client for client_credentials grant

### ISSUE THREAD

**Issue by AdmiinX** [laravel/passport#124]
i'm using client_credentials grant type for Authorization to protect some resources and it's working fine,
i need to get id of the authenticated client 
How to do that
thx

**Comment by AdmiinX** [comment]
```
$bearerToken=$request->bearerToken();
$tokenId= (new Parser())->parse($bearerToken)->getHeader('jti');
$client = Token::find($tokenId)->client;
```

**Comment by KristianI** [comment]
For anybody looking, the "Parser" class used here is
\Lcobucci\JWT\Parser

"Token" class used here is:
\Laravel\Passport\Token

( I think?)

**Comment by Megachill** [comment]
FYI this seems to be changed using latest Passport and Laravel 7. getHeaders no longer contains jti, this is moved into payload and can now be retrieved via getClaim().

package versions used are: 
`
"laravel/framework": "^7.0",
"laravel/passport": "^8.0",
`
use Laravel\Passport\Token;
use Lcobucci\JWT\Parser;

$bearerToken = request()->bearerToken();
$tokenId = (new Parser())->parse($bearerToken)->getClaim('jti');
$client = Token::find($tokenId)->client;
return $client;
`

**Comment by diegoflorez** [comment]
@Megachill Your upgraded solution still works on  `"laravel/framework": "^8.12", "laravel/passport": "^10.0",`
Thanks!

**Comment by judge2020** [comment]
With `lcobucci/jwt:^4.0` (check by running `composer show -i Lcobucci/*`), the following code works for me:

```
use Laravel\Passport\Token;
use Lcobucci\JWT\Configuration;


$bearerToken = request()->bearerToken();
$tokenId = Configuration::forUnsecuredSigner()->parser()->parse($bearerToken)->claims()->get('jti');
$client = Token::find($tokenId)->client;
```

**Comment by sharpdressedcodes** [comment]
Update 2023 for Laravel 10.5.1, Passport 11.8.4 and JWT >= 4.3:

The solution provided by @judge2020 still works, but is deprecated https://github.com/lcobucci/jwt/blob/4.3.x/src/Configuration.php#L83 as of `lcobucci/jwt:^4.3` and will break when Passport updates the dependency to v5 because it's been completely removed from v5. JWT is already at v5.1. The composer `-i` option is also deprecated. Use `composer show Lcobucci/*` instead.

New version:
```
use Laravel\Passport\Token;
use Lcobucci\JWT\Configuration;
use Lcobucci\JWT\Signer\Key\InMemory;
use Lcobucci\JWT\Signer\Rsa\Sha256;

$bearerToken = request()->bearerToken();
$tokenId = Configuration::forSymmetricSigner(new Sha256(), InMemory::plainText('empty', 'empty'))
    ->parser()
    ->parse($bearerToken)
    ->claims()
    ->get('jti')
;
$client = Token::find($tokenId)->client;
```

**Comment by krydos** [comment]
You can also do:
```php
auth('api')->client()
```
Just make sure the `api` guard is defined in `auth.php` config (with the `'driver' => 'passport'`)

**Comment by adrianharabula** [comment]
> You can also do:
> 
> ```
> auth('api')->client()
> ```
> 
> Just make sure the `api` guard is defined in `auth.php` config (with the `'driver' => 'passport'`)

I have been searching this for all day!!! Many thanks!!

**Comment by Stephan-MC** [comment]
> You can also do:
> 
> ```
> auth('api')->client()
> ```
> 
> Just make sure the `api` guard is defined in `auth.php` config (with the `'driver' => 'passport'`)

This is the simple and shortest answer i will ever get for something that caused me so much trouble 🤦🏾‍♂️
