### ISSUE TITLE
Laravel 7.5.2 (Passport Api) + Vuejs Error : Undefined index: aud , \vendor\laravel\passport\src\Guards\TokenGuard.php

### ISSUE THREAD

**Issue by mhabib555** [laravel/passport#1243]
- Passport Version: 9.0
- Laravel Version: 7.5.2
- PHP Version: 7.4.0
- Database Driver & Version: 
- Database client version: libmysql - mysqlnd 7.4.0

### Description:
I am using Laravel 7.5.2 with Vuejs. I am using passport for api authentication. I am getting the following error when sending ajax request to api

```
{
"message": "Undefined index: aud",
"exception": "ErrorException",
"file": "E:\\laravel\\vendor\\laravel\\passport\\src\\Guards\\TokenGuard.php",
"line": 140,
"trace": [
    {
...
}
]
```

### Steps To Reproduce:

I have followed passport installation instruction on laravel website.

- Has run composer require laravel/passport, php artisan migrate and php artisan passport:install
- Has added HasApiTokens in user model
- Has added Passport::routes() in AuthServiceProvider
- Has added \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class in App\Http\Kernel web middlewareGroups
- Has changed Api driver to passport in config/auth.php
 

The cookie named "laravel_token" is getting generated and sent with ajax request as I can see in developer tool.

In my controller I have included api middleware as

```
public function __construct(){
    $this->middleware('auth:api');
}

```

**Comment by TullariS** [comment]
Same here

**Comment by MUHAMMADSiyab** [comment]
Facing the same issue

**Comment by Zae** [comment]
Having the same issue but with laravel 6 and passport 9.

**Comment by joelennon** [comment]
I suspect it might be due to the removal of old `php-jwt` versions in this merged PR?

https://github.com/laravel/passport/commit/ceecafa6b034569cb727791b086678adf8d3ee3a

Reverting to 8.x branch resolved the issue for me.

`composer require laravel/passport:^8.0`

**Comment by lcobucci** [comment]
> I think I might have found the issue.
> 
> Looks like `/vendor/laravel/passport/src/ApiTokenCookieFactory.php:77` sets the index `sub` into the JWT token
> 
> But when decoding the cookie and trying to find the corresponding user `\Laravel\Passport\Guards\TokenGuard::$clients` tries to use the index `aud` to find the user.
> 
> However, the indexes have been like that for a LONG time now, so I'm not sure why this is suddenly a problem?

The problem isn't with the `sub` claim but the `aud` one. Which is being used to identify the client (while the `sub` is meant for the user). The audience is just not being configured.

**Comment by lcobucci** [comment]
Looking at the diff, [this](https://github.com/laravel/passport/compare/8.x...v9.0.0#diff-b6e03e0afee276198cebfa6dbfa4ced7R111-R114) seems to be the culprit (as it apparently assumes that `aud` claim is always there).

@driesvints do you have any idea on how can we solve this?

**Comment by driesvints** [comment]
@lcobucci your link only shows all the commits between 8.5 and 9.0. Can you link to the specific file or pr that changed this?

**Comment by driesvints** [comment]
Did everyone here read the upgrade guide and added the new provider column to the clients table?

https://github.com/laravel/passport/blob/9.x/UPGRADE.md

**Comment by lcobucci** [comment]
I've updated it already, sorry

**Comment by lcobucci** [comment]
@driesvints column is there in my case (I'm doing a clean `php artisan passport:install -n` btw)

**Comment by joelennon** [comment]
Hey @driesvints yeah this was happening for me on a fresh project, `provider` column is there.

**Comment by driesvints** [comment]
It's mentioned that people are here using vue but I don't see any vuejs install steps in the steps to reproduce. Can anyone please post *very* specific steps to replicate this?

**Comment by akizor** [comment]
Hey, I'm on a fresh install also. On version `9.0` I'm encountering the same error, while reverting to `8.5` solves it. Not using `vue` but old plain XHR request with following headers.

```
'X-Requested-With': 'XMLHttpRequest',
'X-CSRF-TOKEN': THE_CSRF_TOKEN
```

**Comment by driesvints** [comment]
If anyone can please post *very* specific steps to reproduce we can figure this out. Atm we can't reproduce this.

**Comment by billriess** [comment]
```
/**
     * Get the user for the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function user(Request $request)
    {
        if ($request->bearerToken()) {
            return $this->hasValidProvider($request) ? $this->authenticateViaBearerToken($request) : null;
        } elseif ($request->cookie(Passport::cookie())) {
            return $this->authenticateViaCookie($request);
        }
    }
```

This may be the fix needed but I can't reproduce the error. Seeing how there is no client in case this makes sense logically but I need to verify. Can someone please give details steps as @driesvints has mentioned.

**Comment by joelennon** [comment]
In my instance I'm using React.

1. `laravel new test --auth`
2. `cd test`
3. ` composer require laravel/passport`
4. `php artisan migrate`
5. `php artisan passport:install`
6. Add `HasApiTokens` to `User` model
7. Change `api` guard to `passport` in `config/auth.php`
8. Add `Passport::routes()` to `AuthServiceProvider`
9. Add `\Laravel\Passport\Http\Middleware\CreateFreshApiToken::class` to `web` middleware group in `app/Http/Kernel.php`
9. `php artisan ui react --auth`
10. In `home.blade.php` add `<div id="example"></div>`
11. Replace `resources/js/components/Example.js` with the following code:

```
import React, { useEffect } from 'react';
import ReactDOM from 'react-dom';

function Example() {
    const load = async () => {
        const data = await axios.get(`api/user`);

        console.log(data);
    }

    useEffect(() => {
        load();
    }, []);

    return null;
}

export default Example;

if (document.getElementById('example')) {
    ReactDOM.render(<Example />, document.getElementById('example'));
}
```

13. `npm install && npm run dev`
14. Open app in browser, create account, look in network requests and you'll see a 500 error

```
{
    "message": "Undefined index: aud",
    "exception": "ErrorException",
    "file": "/Users/joe/Code/Web/test/vendor/laravel/passport/src/Guards/TokenGuard.php",
    "line": 140,
    "trace": [
        {
            "file": "/Users/joe/Code/Web/test/vendor/laravel/passport/src/Guard
...
```

**Comment by billriess** [comment]
Thanks, @joelennon for the detailed write-up. This was a great help in tracking this down. I have submitted a PR to resolve this. Please look at https://github.com/laravel/passport/pull/1246

**Comment by driesvints** [comment]
Thanks @joelennon, that was helpful 👍

**Comment by driesvints** [comment]
Released v9.0.1 which should fix this.

**Comment by lcobucci** [comment]
Thanks everyone, fix works nicely :+1:

**Comment by driesvints** [comment]
Thanks to everyone who reported this!

**Comment by mhabib555** [comment]
Thanks everyone

**Comment by driesvints** [comment]
If anyone here who has upgraded to v9 already and is using the new secrets hashing, please read https://blog.laravel.com/passport-v91-breaking-changes and https://github.com/laravel/passport/issues/1252

**Comment by kbellpostman** [comment]
Ugg this cost me a lot of time earlier this week, happy to read I'm not crazy :)

**Comment by AbdullahiAbdulkabir** [comment]
I still can't resolve this in my case. I have a new laravel installation with the latest passport package installed.
