### ISSUE TITLE
Personal Access Tokens errors

### ISSUE THREAD

**Issue by hihuangwei** [laravel/passport#1248]
- Passport Version: 9.0.4
- Laravel Version: 7.10.1
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8

### Description:
`League\OAuth2\Server\Exception\OAuthServerException `
`Client authentication failed`

### Steps To Reproduce:
$token = $user->createToken('Token Name')->accessToken;

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
Also: Passport 9.0.4 doesn't exists.

**Comment by hihuangwei** [comment]
error write 9.0.4 
is 9.0.1

**Comment by andrefigueira** [comment]
@hihuangwei experiencing the same issue, did you find a solution anywhere? I've asked in Laracasts forum.
