### ISSUE TITLE
Personal Access Tokens errors

### ISSUE THREAD

**Issue by hihuangwei** [laravel/passport#1249]
- Passport Version: 9.0.1
- Laravel Version: 7.10.1
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8

### Description:
`League\OAuth2\Server\Exception\OAuthServerException `
`Client authentication failed`

### Steps To Reproduce:
$token = $user->createToken('Token Name')->accessToken;

**Comment by driesvints** [comment]
Please use a support channel like I asked in the previous issue.
