### ISSUE TITLE
Unable to hash secrets on Vapor

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel/passport#1250]
- Passport Version: 9.0.x
- Laravel Version: 7.x
- PHP Version: 7.4.x
- Database Driver & Version: MySQL 8

### Description:
We are currently unable to run the passport:hash command on our vapor instances due to the required confirmation interaction. If a --force flag or something similar was added to the command to override the prompts, we'd be able to migrate our existing clients to use the new hashed storage.

**Comment by driesvints** [comment]
Guess a force flag makes sense in this situation. Feel free to send in a PR.
