### ISSUE TITLE
Bug editing a client with the Client.vue component

### ISSUE THREAD

**Issue by marcosdipaolo** [laravel/passport#1253]
- Passport Version: 9.0.1
- Laravel Version: 7.10.3
- PHP Version: 7.2.30
- Database: mysql 5.7.25

### Description:
When you edit a client using the `Client.vue` component and you save your changes, it gets duplicated in the client list.

### Steps To Reproduce:
On a fresh installed laravel project, install passport, publish the vue components. Once in a view with the  Client.vue` component working, create a client and then try to edit it. 

### Fix
Replace `this.clients.push(response.data)` by `this.getClients()` at `line 340` and that's it. 
If you agree, i hace a branch ready to be merged.

**Comment by driesvints** [comment]
Heya, thanks for reporting this. I've pushed a commit onto the 9.x branch and we'll do a release for this somewhere today.
