### ISSUE TITLE
Ambiguous/misleading description of auto prune feature

### ISSUE THREAD

**Issue by dusterio** [laravel/passport#126]
Laravel Passport documentation describes auto pruning feature in inaccurate way. Also, API is offering a misleading method name. 

Take a look:

> Pruning Revoked Tokens
> 
> By default, Passport does not delete your revoked access tokens from the database. Over time, a large number of these tokens can accumulate in your database. If you would like Passport to automatically delete your revoked tokens, you should call the pruneRevokedTokens method from the boot method of your AuthServiceProvider:
> 
> Passport::pruneRevokedTokens();

Both documentation paragraph and method name make you expect that only revoked (read - ones that already have their 'revoked' field set to true) will be pruned. However, what really happens is 1) all other access tokens of the same user will be deleted, we can call them previous tokens 2) access tokens will never be marked as revoked.

It may not be a major issue, but it's definitely misleading and could be improved. 

Something like Passport::prunePreviousTokens() and Passport::revokePreviousTokens() would be more accurate and self-describing.

**Comment by taylorotwell** [comment]
We recently had a PR on this issue https://github.com/laravel/passport/pull/181 ... I feel like we are going round and round about this and it's really annoying me and I want to get it fixed. First, I'm not sure why you would ever really want to delete tokens from the table unless you are having major storage issues. If you *do* want to delete tokens I'm not sure Passport should even be responsible for that. I would almost rather remove anything that automatically deletes tokens from Passport entirely.

**Comment by dusterio** [comment]
@taylorotwell yes, even removing token deletion logic completely is better than having a method that promises to do one thing and does a completely different thing :) Just to be clear, this issue is not about deleting or not deleting tokens, it's about misleading naming

**Comment by themsaid** [comment]
Thank you, we've already removed the functionality from passport and fire events instead for users to listen to and do what needs to be done :)
