### ISSUE TITLE
Remove personalAccessClientId and personalAccessClientSecret methods

### ISSUE THREAD

**Issue by driesvints** [laravel/passport#1262]
Remove these so the developer doesn't has to set these anymore in their AppServiceProvider and just read out the values from the config.

**Comment by marcosdipaolo** [comment]
Actually from the docs 
```php
Passport::personalAccessClientId(
        config('passport.personal_access_client.id')
    );

    Passport::personalAccessClientSecret(
        config('passport.personal_access_client.secret')
    );
```
and according to my IDE `personalAccessClientSecret` does not exist!!??

**Comment by driesvints** [comment]
@marcosdipaolo I added those methods to the docs for v9 myself :-)

This issue is for a next major release to remove them because it's a bit of a redundant step for the end user.

> and according to my IDE personalAccessClientSecret does not exist!!??

Did you upgrade to v9.1.0?

**Comment by driesvints** [comment]
Sent in a PR here: https://github.com/laravel/passport/pull/1325

**Comment by marie1st** [comment]
I read the manual for passport personal client need to use method,
Passport::personalAccessClientId('client-id') from laravel manual in AuthServiceProvider, but it could not define the method personalAccessClientId(), how could I fix this issue, are they reallly removing these method, and how could I register myself a new Personal Access Client Id.

**Comment by SkyCrew-g** [comment]
> I read the manual for passport personal client need to use method, Passport::personalAccessClientId('client-id') from laravel manual in AuthServiceProvider, but it could not define the method personalAccessClientId(), how could I fix this issue, are they reallly removing these method, and how could I register myself a new Personal Access Client Id.

https://github.com/laravel/passport/pull/1325#issuecomment-1018622707
