### ISSUE TITLE
[9.x] oauth/token endpoint cannot accept requests of application/json type

### ISSUE THREAD

**Issue by antonkomarev** [laravel/passport#1263]
- Passport Version: 9.0.1
- Laravel Version: 7.10.3
- PHP Version: 7.4.5

### Description:

Once you have created a password grant client, and trying to request an access token by issuing a `POST` request to the `/oauth/token` route with `Content-Type: application/json` header you will get an exception that authorization grant type is not supported by the authorization server.

But it is working with `Content-Type: application/x-www-form-urlencoded`.

I've seen a lot of issues related to it, one of them: #1019

### Steps To Reproduce:

```php
$http = new GuzzleHttp\Client;

$response = $http->post('http://your-app.com/oauth/token', [
    'form_params' => [
        'grant_type' => 'password',
        'client_id' => 'client-id',
        'client_secret' => 'client-secret',
        'username' => 'taylor@laravel.com',
        'password' => 'my-password',
        'scope' => '',
    ],
    'headers' => [
        'Accept' => 'application/json',
        'Content-Type' => 'application/json',
    ],
]);

return json_decode((string) $response->getBody(), true);
```

> [2020-05-09 12:52:31] local.ERROR: The authorization grant type is not supported by the authorization server. {"exception":"[object] (Laravel\\Passport\\Exceptions\\OAuthServerException(code: 2): The authorization grant type is not supported by the authorization server. at /home/passport-sandbox/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php:26)
> [stacktrace]
> #0 /home/passport-sandbox/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(65): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->withErrorHandling()

**Comment by driesvints** [comment]
You're providing `form_params` in your request which is used by `application/x-www-form-urlencoded` while telling the server that you're passing JSON (which isn't correct). You should simply pass the key/values from the `form_params` when passing JSON.

**Comment by driesvints** [comment]
http://docs.guzzlephp.org/en/stable/request-options.html#json

Try this:

```php
$http = new GuzzleHttp\Client;

$response = $http->post('http://your-app.com/oauth/token', [
    'json' => [
        'grant_type' => 'password',
        'client_id' => 'client-id',
        'client_secret' => 'client-secret',
        'username' => 'taylor@laravel.com',
        'password' => 'my-password',
        'scope' => '',
    ],
    'headers' => [
        'Accept' => 'application/json',
        'Content-Type' => 'application/json',
    ],
]);

return json_decode((string) $response->getBody(), true);
```

**Comment by antonkomarev** [comment]
@driesvints you are totally right.
