### ISSUE TITLE
update laravel passport to v 9.0 from v 8.0

### ISSUE THREAD

**Issue by sajad2176** [laravel/passport#1269]
- Old Passport Version: 8.0.0
- Passport Version: 9.0.0
- Laravel Version: 6.2.0
- PHP Version: 7.2.0
- Database Driver & Version:

I have a project which has 3000 users and I update my laravel passport to v 9.0 and after this update, all of the users get the

```
{
'error' : "Unauthenticated."
}
//status 401
```

response from api.
what should I do to reslove this problem ?

**Comment by driesvints** [comment]
Did you read the upgrade guide? https://github.com/laravel/passport/blob/9.x/UPGRADE.md

**Comment by sajad2176** [comment]
@driesvints

The project's passport version at the server is 8.0 and I create a token by logging and after that I export the db and use it in my localhost for testing . in the localhost my passport's version is up to date and I try to access the protected routes with the token which was created at the server and I get the Unauthenticated error  so it means all of my users have to login again for re-generate their tokens

according to upgrade guide first of all I run the command :
```
php artisan passport:client --personal 
```
after get the new personal access token , I edit the .evn and AppServiceProvider like this :

```
PASSPORT_PERSONAL_ACCESS_CLIENT_ID=5
PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET=OljtqgxvkVN9uBKQaNV6ojZOxYuNaobDjGSxUhbg

    public function boot()
    {
        Passport::personalAccessClientId(config('passport.personal_access_client.id'));
        Passport::personalAccessClientSecret(config('passport.personal_access_client.secret'));
    }
```

and when I try to use the old token for protected routes I get the Unauthenticated error agian

**Comment by driesvints** [comment]
You didn't read the upgrade guide correctly. You don't need to create a new personal access client. You need to place your old client secret and id in the env file. Once you hash your secrets they're irreversible gone (as mentioned several times in the guide). If you create a new client and use that secret and id then your old tokens won't work anymore.

**Comment by driesvints** [comment]
> according to upgrade guide first of all I run the command :
> 
> php artisan passport:client --personal 

There is no such step in the upgrade guide.

**Comment by sajad2176** [comment]
@driesvints
I read about it in laravel blog
https://blog.laravel.com/passport-v91-breaking-changes

**Comment by sajad2176** [comment]
@driesvints 
the "PASSPORT_PERSONAL_ACCESS_CLIENT_ID" is the id of client at oauth_clients table?

**Comment by driesvints** [comment]
@sajad2176 yes but it says the following:

> These steps are only necessary if you have already upgraded to v9 and already hashed your client secrets.

This blog post was specifically for the v9.1.0 update and only for people who already upgraded to v9. If you're newly upgrading to v9 from now on you don't need the steps there.

> the "PASSPORT_PERSONAL_ACCESS_CLIENT_ID" is the id of client at oauth_clients table?

Yes.

**Comment by hotmeteor** [comment]
I have to admit, the instructions are not clear. I'm looking at upgrading from 8.x and I'm not certain if I need to create a new client or set those environment variables. In the migration guide it reads that you only need to do it if you intend to implement hashing, which I do not. But in the docs it reads like you need it if you use personal access tokens at all.

Can the upgrade steps from 8.x to 9 be clarified?

**Comment by driesvints** [comment]
@hotmeteor not sure what isn't clear. Feel free to send in a PR if you want.
