### ISSUE TITLE
passport:hash command double hashes secrets

### ISSUE THREAD

**Issue by corbosman** [laravel/passport#1270]
- Passport Version: 9.2.0
- Laravel Version: 7.11.0
- PHP Version: 7.4.5
- Database Driver & Version: postgres 12.2

### Description:

Passport 9.0 introduced hashed client passwords. To help in migration an artisan command passport:hash was added.  Unfortunately this command does not work as expected.  Because 'Passport::$hashesClientSecrets' has to be on before you run it, both the command code, and Laravel's Client model secret setter hash the secret, resulting in a double hash. 

In the command class HashCommand.php:

```
$client->forceFill([
    'secret' => password_hash($client->secret, PASSWORD_BCRYPT),
])->save();
```

Then in the Client model:
```
    public function setSecretAttribute($value)
    {
        $this->plainSecret = $value;

        if (is_null($value) || ! Passport::$hashesClientSecrets) {
            $this->attributes['secret'] = $value;

            return;
        }

        $this->attributes['secret'] = password_hash($value, PASSWORD_BCRYPT);
    }
```

Probably the most logical fix would be for the command to not hash it and let the model hash it.

### Steps To Reproduce:

- start with unhashed client secrets
- run ```artisan passport:hash```
- secrets wont work because they're double hashed.

**Comment by driesvints** [comment]
Heya, thank you for reporting! I just pushed a commit and new release that fixes this.
