### ISSUE TITLE
How to disable "forClients" and "forPersonalAccessTokens" routes at Passport::routes(); ?

### ISSUE THREAD

**Issue by hihuangwei** [laravel/passport#1273]
How to disable "forClients" and "forPersonalAccessTokens" routes at Passport::routes(); ?

**Comment by driesvints** [comment]
You can't disable these individual. If you want to disable these individual you'll have to overwrite the routes manually.

**Comment by hihuangwei** [comment]
> You can't disable these individual. If you want to disable these individual you'll have to overwrite the routes manually.

How to disable？

**Comment by driesvints** [comment]
@hihuangwei don't add the `Passport::routes()` call

**Comment by hihuangwei** [comment]
@driesvints But only partial routes is disabled.
