### ISSUE TITLE
passport:hash does not work. It seems to be setting the secret values back to whatever the original value is without hashing.

### ISSUE THREAD

**Issue by khan-zia** [laravel/passport#1275]
- Passport Version: 9.2.1
- Laravel Version: 7.11.0
- PHP Version: 7.4.3
- Database Driver & Version: MySql 8

### Description:
I am modifying this issue I created a few hours ago. Initially I thought that this was an issue if **passport::useClientModel()** is used to override the default **oauth_clients** table. But it looks like the command is setting the values of **secret** column back to their original values in the foreach loop. I hope somebody can correct me if I am wrong. Otherwise, I will make a pull request for this. Also, it's worth mentioning that the command is checking **PASSWORD_BCRYPT** algo specifically which kinda strengthens my claim over at #1276 and I believe this should also be changed to consume settings of the main app.

### Steps To Reproduce:
- Setup Passport's mentioned version
- Create a few clients for testing.
- Run **php artisan passport:hash** to hash existing client secrets.

You will see that the secrets have not been hashed.

**Comment by khan-zia** [comment]
#Update
The passport hashing seems to be not working at all with **useClientModel()**. I have tried creating a new oauth client and the **secret** value got stored as plain text.

**Comment by driesvints** [comment]
@khan-zia the secret is already hashed in the `setSecretAttribute` mutator. Did you change the behavior of that method in your own model? Please post your overwritten model.

**Comment by khan-zia** [comment]
@driesvints Alright, my bad, I also noticed that later. I did not account for the changes in the models and that included the `setSecretAttribute` mutator. So, I guess at the end the issue actually was related to having overridden models. I am going to close this issue but I believe you should put this in the upgrade guide for v8 to v9. You can simply have a one paragraph telling people to checkout for changes in all overridden models.
