### ISSUE TITLE
Passport's client secret hashing should use the main application's config for choosing hashing algorithm.

### ISSUE THREAD

**Issue by khan-zia** [laravel/passport#1276]
Quoting from the upgrade guide of passport from v8.0 to v9.0 **"Client secrets may now be stored using a Bcrypt hash."**, It would seem that Passport's client secret hash uses Bcrypt instead of looking up what the main application's configured hashing algorithm is. If this is the case, then this must change as so many people out there including me would wanna use **argon2 and argon2id** instead of Bcrypt.

**Comment by driesvints** [comment]
Sure. Feel free to pr.

**Comment by khan-zia** [comment]
Sure. I will, over this weekend. Thanks!
