### ISSUE TITLE
Config provider not reachable in UserRepository

### ISSUE THREAD

**Issue by willpercey-gb** [laravel/passport#1277]
https://github.com/laravel/passport/blob/0931d75235283d651b767d291a79cafba5d6ce68/src/Bridge/UserRepository.php#L35

`$clientEntity->provider` by default this seems to equate to 'users' meaning when setting up custom authorisation the config option never gets reached, is there a way to override this or is it that this is supposed to be
`$provider = config('auth.guards.api.provider') ?: $clientEntity->provider;` ?

**Comment by driesvints** [comment]
Please repost the issue with the filled out issue template.
