### ISSUE TITLE
Too many SQL requests

### ISSUE THREAD

**Issue by yellenLi** [laravel/passport#1278]
Version information
laravel                 ^7.0
passport             ^9.2

![image](https://user-images.githubusercontent.com/21179164/82645653-cb8e5280-9c45-11ea-8904-06dc7f643a30.png)

file path: src/Guards/TokenGuard.php
![image](https://user-images.githubusercontent.com/21179164/82644239-908b1f80-9c43-11ea-85c8-d2ef3333e052.png)

Too many database requests, not very friendly

**Comment by driesvints** [comment]
Feel free to PR improvements here.
