### ISSUE TITLE
Add optional multi-tenanting support

### ISSUE THREAD

**Issue by atrauzzi** [laravel/passport#128]
Something I'm looking to do is create an authentication and token provider that can function for multiple domains.  Ideally this is done by adding a discriminator of some kind to users and clients.  Usually containing a value representing the tenant like a domain.

Alternatively, if this is something that won't be considered, I'd love some advice on the touchpoints I'll have to interact with to implement it myself without breaking things :)

**Comment by themsaid** [comment]
Hello, any updates on this?
