### ISSUE TITLE
`CreateFreshApiToken` middleware not working in multi auth

### ISSUE THREAD

**Issue by RahulDey12** [laravel/passport#1280]
@billriess will it work with `CreateFreshApiToken` middleware

_Originally posted by @RahulDey12 in https://github.com/laravel/passport/issues/982#issuecomment-633205035_

Multi auth is not working with `CreateFreshApiToken` middleware if there is same user id it is always showing login

**Comment by driesvints** [comment]
If you use it as a route middleware you can specify the guard name on the routes you want to auth:

```php
protected $routeMiddleware = [
    ...
    'api_token' => \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
]
```

```php
Route::group(['middleware' => 'api_token:guard-name'], function() {
     // routes here.
});
```

**Comment by RahulDey12** [comment]
Nothing happened if there is two models with same id it is exposing one another's details

**Comment by billriess** [comment]
Can you try to explain the scenario more and the issues are you facing? Try to be specific.

The original issue I was aiming to solve was based on `Password` grants. In the `Password` grant scenario I was trying to authenticate a specific user "type" (provider) to a `Passport\Client`.  The PR that was merged achieves exactly this. The PR sat open for a while and encouraged additional input but not much was said and once it was tested and vetted from the Laravel staff it was merged.

The provider is being validated for `Bearer Tokens` not `Cookies` so I assume this would be the issue you are facing, is that correct?

**Comment by RahulDey12** [comment]
https://github.com/laravel/passport/blob/0931d75235283d651b767d291a79cafba5d6ce68/src/ApiTokenCookieFactory.php#L74-L82

In this section, nothing is verifying the provider

**Comment by RahulDey12** [comment]
> Can you try to explain the scenario more and the issues are you facing? Try to be specific.
> 
> The original issue I was aiming to solve was based on `Password` grants. In the `Password` grant scenario I was trying to authenticate a specific user "type" (provider) to a `Passport\Client`. The PR that was merged achieves exactly this. The PR sat open for a while and encouraged additional input but not much was said and once it was tested and vetted from the Laravel staff it was merged.
> 
> The provider is being validated for `Bearer Tokens` not `Cookies` so I assume this would be the issue you are facing, is that correct?

Ok, So this feature is also important for consuming own javascript api

**Comment by billriess** [comment]
Check https://github.com/laravel/passport/pull/1282

If you can, try testing this locally and let me know if it works. Comment in the PR your findings. This will help get this pushed.
