### ISSUE TITLE
OAuth server for API only application

### ISSUE THREAD

**Issue by andriiPalko** [laravel/passport#1281]
I'm trying to implement OAuth server in my application using Passport, but my application is API only. In source code, I see the dependency on session storage, but it doesn't exist for my application. Is there some way to use OAuth server for API (stateless) applications?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
