### ISSUE TITLE
The "--uuids" option does not exist

### ISSUE THREAD

**Issue by kuhlaid** [laravel/passport#1286]
- Passport Version: ^8.4
- Laravel Version: ^7.0
- PHP Version: 7.3.9
- Database Driver & Version: SQL Server v14

### Description:
https://laravel.com/docs/7.x/passport#client-uuids says to use the following command to use UUID with passport
``` php artisan passport:install --uuids``` 
...however running this produces the error: ```The "--uuids" option does not exist.```
Is the documentation incorrect or is this a bug?

**Comment by driesvints** [comment]
This is only available on Passport 9 and higher.

**Comment by kuhlaid** [comment]
Thanks. I updated to v9.2.1 and the command worked as advertised.
