### ISSUE TITLE
How can we revoke token.

### ISSUE THREAD

**Issue by Rahul-Giri** [laravel/passport#129]
Hi,
I'm using laravel passport Password Grant Tokens to authenticate my users. but i'm stuck in an issue, when the user logged in my website how can i logout them. for that i need to revoke that token but how can i revoke that token. and also that refresh token at the same time. because even though i revoke access token the refresh token stuck there with pointing to revoked token. sorry if that's dumb question. :)

**Comment by dusterio** [comment]
Usually issues on GitHub are for issue reporting, not for general questions :))

Why don't you just wait for the token to expire? If you set shorter expiration time, your tokens will expire and auto-delete upon next login.

**Comment by Rahul-Giri** [comment]
Okay thanks :)
