### ISSUE TITLE
Allow redirect url pattern

### ISSUE THREAD

**Issue by alditis** [laravel/passport#1293]
I configured my whitelist in `oauth_clients.redirect` in this way:
http://jhon.myappclient.com/user/login.json,
http://peter.myappclient.com/user/login.json,
http://susan.myappclient.com/user/login.json

Optionally it could be established as a pattern similar to: 
http://**{username}**.myappclient.com/login.json ?

Thanks.

**Comment by Sephster** [comment]
You should always use specific redirect urls and not patterns. The latest best practice oauth 2 rfc advises against pattern matching for redirects

**Comment by alditis** [comment]
Thanks for the reply.
So every time I create a new user (For example: **paul**),
Should I concatenate his url with a comma (,http://paul.myappclient.com/user/login.json) in `oauth_clients.redirect` or should I create a new client in `oauth_clients`?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Sephster** [comment]
It depends on the role of your client. If the client is always the same website for example, then just add a new URL to the approved list. I think it would be fine to do that. Hope that helps!

**Comment by alditis** [comment]
Thanks for you comment.
Every time a user registers, a subdomain will be created. So I thought about handling a pattern, but as indicated by oauth2 rfc, it is not a good practice. I think I will just create a client and add the created subdomains to the list.
