### ISSUE TITLE
Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /example/vendor/zendframework/zend-diactoros/src/functions/marshal_headers_from_sapi.php on line 10

### ISSUE THREAD

**Issue by yelnyaface** [laravel/passport#1295]
- Passport Version: ^4.0
- Laravel Version: >=5.5
- PHP Version: 7.2
- Database Driver & Version: libmysql - 5.6.43

Every once a few weeks this error:
```
Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /example/vendor/zendframework/zend-diactoros/src/functions/marshal_headers_from_sapi.php on line 10
```
will surface, and everytime I am use `composer update larave/passport` to fix it, but it will still keep returning, why is this keep happening? and there is like NO post about this here and any laravel related sites about this

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
