### ISSUE TITLE
Bind client IP address with token and validate that.

### ISSUE THREAD

**Issue by darshanadaptit** [laravel/passport#1297]
I am trying to customise your code to bind access token with specific IP and allow to respond if a request comes with same IP and access token else response 403 or 405 but not able to get success is there any way I can achieve this

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by damku999** [comment]
Thank you so much for your guideline I will try to achieve this using Chanel you gave me above.
