### ISSUE TITLE
How can i use laravel builtin throttle login with passport password grant tokens

### ISSUE THREAD

**Issue by Rahul-Giri** [laravel/passport#130]
How can i make use of in builtin laravel throttle login into my laravel passport password grant token.
so if a user hit with wrong email and password for 5 times in ```oauth/token``` route. so laravel will show too many attempts and block the IP for 1 minute (i can send IP from API). Like laravel does with it's typical auth system. Thanks

**Comment by ionutmilica** [comment]
You can create a custom route where you make an internal call to the password grant api then decorate it with the the throttle middleware.

**Comment by Rahul-Giri** [comment]
Okay. thanks, i will do that :)

**Comment by rohitpavaskar** [comment]
Please check following link too much helpful.
https://github.com/laravel/passport/issues/217
