### ISSUE TITLE
Client's authentication always fails when I try to convert authorization code to access token

### ISSUE THREAD

**Issue by spore2102** [laravel/passport#1301]
- Passport Version: "^9.2"
- Laravel Version: "^7.0"
- PHP Version: "^7.2.5"
- Database Driver & Version: MySQL 8.0

### Description:
Client's authentication always fails when I try to convert authorization code to access token. 
I get this in response, though client's ID, redirect and secret are correct.

`
{ "error":"invalid_client",
  "error_description":"Client authentication failed",
  "message":"Client authentication failed"}
`

I suppose the problem may be in Passport\Bridge\ClientRepository.php file on row 81
 `return ! $record->firstParty(); `
as when I removed the negation operator everything worked just fine.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
