### ISSUE TITLE
v9.2.1 get access_token is ok,but dd(Auth::guard('admin')->check()) is false

### ISSUE THREAD

**Issue by anyAdmin** [laravel/passport#1302]
- Passport Version: 9.2.1
- Laravel Version: 7.16.1php 
- PHP Version: 7.4.3

### Description:
when I use the passport v8.5.0,I can get the access_token and the auth info，all is ok
but when I change on v9.2.1,
I can get the access_token not auth info
dd(Auth::guard('admin')->check()) is false

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
