### ISSUE TITLE
Add configurable maximum number of allowable oauth clients

### ISSUE THREAD

**Issue by WarcraftLogs** [laravel/passport#1303]
I run the site https://www.warcraftlogs.com/ and this site has an API powered by Laravel Passport. The site got taken out today by a DDOS where a user created an infinite number of oauth clients. I had assumed there would actually be a cap in the passport implementation.

I am filing an enhancement request to have a configurable cap on allowed oauth clients as part of passport's configuration options. Since adding a client is done through a route we don't control (i.e. implemented by Passport), it seems like a security hole that such an attack was even possible in the first place.

**Comment by WarcraftLogs** [comment]
Or at the very least throttle client creation by default.

**Comment by driesvints** [comment]
This would be a user land implementation.
