### ISSUE TITLE
UserRepository doesn't respect the provider's retrieveByCredentials method

### ISSUE THREAD

**Issue by JonathanGuo** [laravel/passport#1305]
- Passport Version: 9.2.1
- Laravel Version: 7.17.1
- PHP Version: 7.4.4
- Database Driver & Version: PostgreSQL 11.3

### Description:

In the repository's `Laravel\Passport\Bridge\UserRepository@getUserEntityByUserCredentials` method, it loads the provider to resolve the user model class, but it doesn't use the `retrieveByCredentials` method.

This causes the issue when developers have custom authentication logic. 

For example in my case, the project uses PostgreSQL which is case sensitive. The default `EloquentUserProvider` searches users by using ` $query->where($key, $value);`, it generates a query that has a where clause like 
```SQL
WHERE users.email = 'email@example.com'
```

It works perfectly fine for case-insensitive database/datastore like MySQL. However, for PostgreSQL, we'd like to make the query case-insensitive. I'd expect a where clause like 

```SQL
WHERE users.email ILIKE 'email@example.com'
```

So I've created a custom provider to resolve the issue. But it seems like the Passport's `UserRepository` doesn't use it. It checks the model's `findAndValidateForPassport` and `findForPassport` methods instead. I reckon the provider's `retrieveByCredentials` should've been used after checking the existence of method `findForPassport`.

### Steps To Reproduce:

1. Create a custom provider and override the `retrieveByCredentials` method.

2. Register the provider in `AuthServiceProvider@boot`.

3. Update the 'providers.users.driver' key in `config.auth`.

3. Trigger an API request to `oauth/token`.

it expects the custom provider's `retrieveByCredentials` not get invoked.

**Comment by driesvints** [comment]
I can maybe indeed see an opportunity for `retrieveByCredentials` but that would be a breaking change. Given that you can easily solve this atm by implementing `findForPassport` I don't think it's necessary to change this. You're free however to attempt a PR at master to see if Taylor would accept it.
