### ISSUE TITLE
{     "error": "invalid_grant",     "error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",     "hint": "",     "message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client." }

### ISSUE THREAD

**Issue by Anoob007** [laravel/passport#1306]
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
    "hint": "",
    "message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}

### Description:
![Screenshot (51)](https://user-images.githubusercontent.com/54050679/85649029-baf74f00-b6bf-11ea-9baa-1b80342b0c22.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ganeshbala2008** [comment]
@Anoob007 
Hi,
    This works for me 
```
			$data = array(
				'grant_type' => 'password',
				'client_id' => <client id>,
				'client_secret' => <client secret>,
				'username' => $request->username,
				'password' => $request->password,
				'scope' => '*'
			);
			$request = Request::create('/oauth/token', 'POST', $data);
			return app()->handle($request);
```

**Comment by sbn111** [comment]
The same issue happened to me how to resolve it
