### ISSUE TITLE
Do not overwrite the authorization header

### ISSUE THREAD

**Issue by Exotelis** [laravel/passport#1309]
Hi, 

in the TokenGuard the authorization header will be overwritten when the authentication request was invalid

https://github.com/laravel/passport/blob/7ddaa0fa6ff5c100cf755bf85d86886e0edcb0e8/src/Guards/TokenGuard.php#L208

This actually makes sense, if the token does not exist in the database. From my point of view it doesn't make sense if the token is either expired or has been revoked.

In my `Authenticate` middleware, I'd like to check if the token has been revoked. My idea was to get the token from the header, to decrypt it and to get the token from the database by using the `jti` field which is obviously the id of the token.

If there is no other way to check the state of the token, the authorization header should not be overwritten, at least not if it's expired or has been revoked. As far as I can tell, this should not be an security issue.

**Comment by Exotelis** [comment]
https://github.com/laravel/passport/issues/632

Explains why it has been added.

**Comment by Exotelis** [comment]
Is there a reason for closing this issue?

**Comment by driesvints** [comment]
@Exotelis I thought you found the reason above?

**Comment by Exotelis** [comment]
@driesvints I found the reason why it was added, but I think that overwriting the header is a very bad way to fix this bug.

**Comment by driesvints** [comment]
@Exotelis can you pr an alternative fix?

**Comment by Exotelis** [comment]
@driesvints 

The only fix I have in mind would be in the https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Exceptions/Handler.php#L172

I could add a parameter to the context mehtod `protected function shouldntReport(Exception $e = null)` and inside the try catch I could add a if condition:
```
try {
  if ($e instance of \League\OAuth2\Server\Exception\OAuthServerException) {
    return; 
  }
  
  return array_filter([
    'userId' => Auth::id(),
    'email' => Auth::user() ? Auth::user()->email : null,
  ]);
}
```

**Comment by driesvints** [comment]
@Exotelis since we've never had any problems with this and this is the first time someone reported this I'm not too sure about changing things now sorry. If we get more requests for this we might reconsider.

**Comment by Exotelis** [comment]
@driesvints I guess it should not be a matter of how many requests this change gets. From my perspective it's not a very good practice that a third party library, which laravel-passport is in many projects, clears a header that is still going through the middleware stack. I just stumpled over this, because I wanted to print the authorization header and was wondering why it is empty. It took me over 2 hours to find the reason. Especially because it's not mentioned in any documentation. 

If any middleware tries to get the current user with `$request->user();` the `TokenGuard` would clear the authorization header if the token is not valid, and this long before the request would even reach the Authenticate middleware. 

Apart from that the [https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Exceptions/Handler.php#L172](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Exceptions/Handler.php#L172) should never try to resolve the user if the exception has been raised because the user could not be resolved. That's why the infinite loop bug ever happened.

At least from my point of view is it not a very clean solution to keep it as it is.

**Comment by driesvints** [comment]
@Exotelis in that case feel free to attempt a PR to see if Taylor wants to accept it.

**Comment by khan-zia** [comment]
@driesvints Just stumbled upon this issue yesterday and it took my entire day out unlike the issue author who says he spent 2 hours. I totally agree that any vendor code must not just simply decide to overwrite a request header unless there is a very compelling and well-documented reason to do so. IMO, this issue hasn't been reported more frequently because most applications don't need extensive customizations, and things just work for their use cases.

Nonetheless, overwriting a header to stop an infinite loop is a hacky solution in the first place (see #632) and as per your last comment:

> @Exotelis in that case feel free to attempt a PR to see if Taylor wants to accept it.

I will see if I can attempt a PR for a better solution.
