### ISSUE TITLE
DiactorosFactory not found in psr-http-message-bridge v2

### ISSUE THREAD

**Issue by chungnq253** [laravel/passport#1315]
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory' not found in file vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 132

[source - psr-http-message-bridge](https://github.com/symfony/psr-http-message-bridge/tree/master/Factory)

- Passport Version: 9.3
- Laravel Version: 6.2
- PHP Version: 7.2
- Database Driver & Version:

**Comment by huynhan147** [comment]
> Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory' not found in file vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 132
> 
> [source - psr-http-message-bridge](https://github.com/symfony/psr-http-message-bridge/tree/master/Factory)
> 
> * Passport Version: 9.3
> * Laravel Version: 6.2
> * PHP Version: 7.2
> * Database Driver & Version:
> 
> ### Description:
> ### Steps To Reproduce:

Me too

**Comment by driesvints** [comment]
Update your laravel version to the latest 6.x release.
