### ISSUE TITLE
After remigration keys not usable

### ISSUE THREAD

**Issue by Abdulla1995** [laravel/passport#1317]
- Passport Version: "laravel/passport": "^9.3",
- Laravel Version:  "laravel/framework": "^7.0",
- PHP Version: "php": "^7.2.5",
- Database Driver & Version: MYSQL 8.0.15

### Description:
I have used [this article](https://dev.to/stefant123/secure-authentication-in-nuxt-spa-with-laravel-as-back-end-19a9) to create fresh API with laravel-passport. After installation I have successfully registered some users. Then after some coding I have needed to add some columns to existing tables. So after adding these columns I have used fresh command to remigrate all database. 

`php artisan migrate:fresh --seed`

The operation was successfully and all tables(oauth tables also) have been created. **But after this migration process existing passport grant tokens are not usable.** When I register new User I get this error. 

`Undefined property: stdClass::$refresh_token`

I have tried many ways but only after renewing old client and password keys worked.

`php artisan passport:install --force`

### Steps To Reproduce:
After installation passport just install and creating keys and migrate database. So everything will work. Then after remigrate database with command `php artisan migrate:fresh` . Then old keys will not be usable.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
