### ISSUE TITLE
It's possible to retrieve a client credentials token from a password credentials client record.

### ISSUE THREAD

**Issue by hans-w** [laravel/passport#1320]
- Passport Version: 9.3.0
- Laravel Version: 6.11.0
- PHP Version: 7.2.29
- Database Driver & Version: MySQL 5.7

### Description:

It's possible to retrieve a client credentials authorization token using a password credentials client record.

### Steps To Reproduce:

Make a post request to the _token_ endpoint with the _grant_type_ body parameter set to client_credentials, using the _client_id_ and _client_secret_ from a password client record. Omit the _username_ and _password_ parameters.

### Expected Behavior:

Passport should throw an authorization exception because there is no client_credentials client matching the _id and _secret.

**Comment by driesvints** [comment]
@Sephster do you might know if this is the correct behavior or not?

**Comment by Sephster** [comment]
Hey @driesvints. In general, OAuth doesn't say anything about which client can use which type of grant. This is left entirely up to the implementation.

In the backend of Passport, it looks like the only thing differentiating a PasswordClient and Client Credentials client is the `password_client` bool in the DB being set to true.

Code determining which grants can be used by client is listed below:

```
protected function handlesGrant($record, $grantType)
    {
        if (is_array($record->grant_types) && ! in_array($grantType, $record->grant_types)) {
            return false;
        }

        switch ($grantType) {
            case 'authorization_code':
                return ! $record->firstParty();
            case 'personal_access':
                return $record->personal_access_client && $record->confidential();
            case 'password':
                return $record->password_client;
            case 'client_credentials':
                return $record->confidential();
            default:
                return true;
        }
    }
```

It looks like as long as the client is confidential, _any_ client can use the client credentials grant. This makes sense to me and I don't think the implementation should change but it might be worth clarifying this in the docs. 

Hope that helps.

**Comment by hans-w** [comment]
Thank you for the referral @driesvints. And thank you for the clarification @Sephster.

**Comment by driesvints** [comment]
@Sephster thanks for the explanation! : )
