### ISSUE TITLE
TokenGuard suddenly not decoding JWT Token cookie

### ISSUE THREAD

**Issue by acmitch** [laravel/passport#1323]
- Laravel Version: 7.0
- Homestead Version: 10.9.1

### Description:
Appears that when using Cookie authentication the decoding of the cookie is suddenly not working within the TokenGuard. Was working fine a few weeks back, I'm assuming something updated with one of the dependencies?

![Screenshot from 2020-07-28 16-59-40](https://user-images.githubusercontent.com/4482055/88726679-c9d48580-d0f3-11ea-9275-4e485bc42481.png)

![Screenshot from 2020-07-28 16-42-19](https://user-images.githubusercontent.com/4482055/88726183-e0c6a800-d0f2-11ea-9e7f-2800b024301a.png)

![Screenshot from 2020-07-28 16-42-31](https://user-images.githubusercontent.com/4482055/88726171-d7d5d680-d0f2-11ea-9e2d-fa43eeeb368c.png)

![Screenshot from 2020-07-28 16-50-26](https://user-images.githubusercontent.com/4482055/88726175-da383080-d0f2-11ea-8bde-e4d545b72806.png)

### Steps To Reproduce:
- Use the cookie authentication
- Within TokenGuard it is not working

**Comment by driesvints** [comment]
Upgrade your Laravel and passport to the latest versions please.

**Comment by acmitch** [comment]
Yeah updating to Passport ^9.3 fixed the issue.

**Comment by trip-somers** [comment]
@driesvints  Is there some kind of explanation for why older minor version updates are now broken? I'm presumably running compatible versions with Laravel 6.18 and Passport 8.5. I don't understand why this would be "suddenly" broken.

**Comment by driesvints** [comment]
@trip-somers yeah we blogged about ti here: https://blog.laravel.com/laravel-cookie-security-releases
