### ISSUE TITLE
Issue with Laravel 6.0 dev channel security updates

### ISSUE THREAD

**Issue by throttlehead** [laravel/passport#1324]
- Passport Version: ^8.3.0
- Laravel Version: ^6.0
- PHP Version: 7.4
- Database Driver & Version:  ---

### Description:

There appears to be an issue with CreateFreshApiToken and the latest Laravel security update. After doing a composer update this morning and getting the latest dev channel updates for Laravel and Passport, the cookie stopped working for the auth:api route middleware. It starts to return only AuthorizationException. I tried incognito and fresh logins to no avail. Hard-coding the previous major release for Laravel 6 (6.18.8) has solved our issue in the meantime but something's definitely up here guys.

### Steps To Reproduce:

Run composer update to get latest dev channel updates from Laravel. Attempt to hit a route using auth:api after getting the cookie from CreateFreshApiToken middleware.

**Comment by throttlehead** [comment]
As a followup, I've now tried Laravel Version: ^6.0 and Passport Version: ^9.0 and this combination works. Going to do the upgrade now today but this issue is probably going to affect lots of people who are still a major version behind on passport.

**Comment by driesvints** [comment]
Passport 8.0 isn't maintained anymore.
