### ISSUE TITLE
Passport Password Grant Client keeps returning invalid client error

### ISSUE THREAD

**Issue by dreferreira** [laravel/passport#134]
I've followed the steps in the [Passport installation and configuration docs](https://laravel.com/docs/5.3/passport) and in the video tutorial, however, the needs of the project I'm working on requires for the use of the password grant for our 1st party client. I've gone through the [Password Grant docs](https://laravel.com/docs/5.3/passport#password-grant-tokens) to create a password grant client BUT when I send a post request to http://localhost:9000/oauth/token I get the following response:

`{"error":"invalid_client","message":"Client authentication failed"}`

**Postman**
![postman](https://cloud.githubusercontent.com/assets/7734800/19314139/0c1b3e4c-9067-11e6-849a-984349d73012.PNG)

When I look inside of the passport vendor code I see the getIdentifier() method is set to "authorization_code" instead of "password". 

**vendor\league\oauth2-server\src\Grant\AbstractGrant.php _See Highlighted section_**

![insidecode](https://cloud.githubusercontent.com/assets/7734800/19313958/54defd9a-9066-11e6-85a2-990647d2b0a6.PNG)

Is there a step that I may have missed or could there be something else happening? 
Any insite to this is appreciated.
Thank you.

**Comment by dreferreira** [comment]
Found that it was merely a setup issue. Not all fields were matching up to what was stored in the database.

**Comment by jurerick** [comment]
I tried it in laravel 5.3 
I experiencing  the same exact error. But im pretty sure the association in database are all correct.
