### ISSUE TITLE
production.ERROR: The resource owner or authorization server denied the request

### ISSUE THREAD

**Issue by mehdirochdi** [laravel/passport#1342]
- Passport Version: ^8.3
- Laravel Version: ^7.0
- PHP Version: 7.4
- Database Driver & Version: pgadmin 4

### Description:
i have API based with Laravel i get error only in prod : log file
`The resource owner or authorization server denied the request
{"exception":"[object] (League\\OAuth2\\Server\\Exception\\OAuthServerException(code: 9): 
The resource owner or authorization server denied the request. at /var/www/clients/client0/web1/web/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:243)`
i use Postman when i want login still loading without any response, i check database, oauth_access_tokens Auth passowrd client is enregistered, but i don't get a response token.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
