### ISSUE TITLE
Personal Access Tokens as API tokens.

### ISSUE THREAD

**Issue by KieronWiltshire** [laravel/passport#1356]
I intended on using Personal Access Tokens as API tokens for users. However, I don't feel like a year is long enough for an API key that may be in use for much longer than that. Would it be possible to change the expiration of specific personal access tokens when creating them?

**Comment by driesvints** [comment]
You can only set it globally for the OAuth2 Server: https://laravel.com/docs/8.x/passport#token-lifetimes

```php
Passport::personalAccessTokensExpireIn(now()->addMonths(6));
```

Anything more granular (specific lifetimes per tokens) aren't possible. You're probably looking more for something like Sanctum for your usecase.

**Comment by KieronWiltshire** [comment]
I need to continue this discussion.

On my application, I allow users to create personal access tokens so that they can also communicate with my API, ideally I'd like for them to be able to set their own sensible expiration time if one is set at all.
![image](https://user-images.githubusercontent.com/4332346/96855133-37265700-1454-11eb-9320-782c6799d987.png)

I still don't understand why this WON'T be supported? I see no reason for it not to be.

**Comment by driesvints** [comment]
@KieronWiltshire it just isn't possible with OAuth2 Server. We need to give the expiration time up front to the authorization server. This is a piece we don't control ourselves.

https://github.com/laravel/passport/blob/10.x/src/PassportServiceProvider.php#L117

You could take this up with the league/oauth2-server repo/team but I suspect that this simply isn't possible.

**Comment by KieronWiltshire** [comment]
@driesvints okay, I understand. I will see what they say
