### ISSUE TITLE
Issue while launching command

### ISSUE THREAD

**Issue by BryanMootoosamy** [laravel/passport#1357]
- Passport Version: last
- Laravel Version: 8.6.0
- PHP Version: 7.4.10

### Description:
When lanching a console command or making a composer dump-autoload when a command exists, I get this error

Symfony\Component\ErrorHandler\Error\FatalError

Type of Laravel\Horizon\Console\ClearCommand::$signature must be string (as in class Illuminate\Console\Command)
In class ClearCommand, signature type is missing on the property

### Steps To Reproduce:
Launch a command created using Command Class on laravel 8

**Comment by driesvints** [comment]
Think you're running into a caching problem somewhere as I don't trigger this error when running the latest Horizon version. Doesn't seems to be Passport related.
