### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by youssefkhouili** [laravel/passport#1372]
- Laravel Version:  v7.29.2
- PHP Version: 7.4.6

### Description:

Problem 1
    - Conclusion: remove laravel/framework v7.29.2
    - Conclusion: don't install laravel/framework v7.29.2
    - laravel/passport 10.x-dev requires illuminate/http ^8.2 -> satisfiable by illuminate/http[8.x-dev, v8.10.0, v8.11.0, v8.11.1, v8.11.2, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].
    - laravel/passport v10.0.0 requires illuminate/http ^8.0 -> satisfiable by illuminate/http[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.10.0, v8.11.0, v8.11.1, v8.11.2, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].
    - laravel/passport v10.0.1 requires illuminate/http ^8.2 -> satisfiable by illuminate/http[8.x-dev, v8.10.0, v8.11.0, v8.11.1, v8.11.2, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].
    - don't install illuminate/http 8.x-dev|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.10.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.11.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.11.1|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.11.2|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.12.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.12.1|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.12.2|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.12.3|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.2.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.3.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.4.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.5.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.6.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.7.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.7.1|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.8.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.9.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.0.0|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.0.1|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.0.2|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.0.3|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.0.4|don't install laravel/framework v7.29.2
    - don't install illuminate/http v8.1.0|don't install laravel/framework v7.29.2
    - Installation request for laravel/framework (locked at v7.29.2, required as ^7.29) -> satisfiable by laravel/framework[v7.29.2].
    - Installation request for laravel/passport ^10.0 -> satisfiable by laravel/passport[10.x-dev, v10.0.0, v10.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by driesvints** [comment]
The answer is in your message above. You need Laravel 8 for Passport 10

**Comment by youssefkhouili** [comment]
yeah thanks i used composer require laravel/passport "^9.0" to install passport 9
