### ISSUE TITLE
Error 404 route post  laravel passport

### ISSUE THREAD

**Issue by congas83** [laravel/passport#1374]
- Passport Version: 9.0
- Laravel Version: 7.29
- PHP Version: 7.2.5
- Database Driver & Version: Mysql

### Description:

when i query api / user test path
returns the user data without any problem,
but when I create a post route inside a controller that I want to return as well
user $ request-> user () always gets me a 404 error.

  Route :    Route::post('valid', 'API\Auth\LoginController@test')->middleware('auth:api');

Controller 

 public function test(Request $request)
    {
        return $request->user();
    }

### Steps To Reproduce:
![error passport](https://user-images.githubusercontent.com/74059144/98967623-af73bb80-24da-11eb-9794-2bf0a2779cbf.PNG)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by congas83** [comment]
I have this same problem with the latest version  
"php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/passport": "^10.0",

**Comment by driesvints** [comment]
@congas83 this seems like a support request. Please try a support channel: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
