### ISSUE TITLE
Unable to create personal access tokens when using hashed client secrets

### ISSUE THREAD

**Issue by keltinMesonjesi** [laravel/passport#1375]
- Passport Version: 10.0.1
- Laravel Version: 8.6.0
- PHP Version: 7.4.12
- Database Driver & Version: MySQL 5.7.22

### Description:

After enabling hashed client secrets (Passport::hashClientSecrets()) when I try to create a new Personal Access Token from Vue App I get 500 (Client authentication failed) response.
When disabling Passport::hashClientSecrets() then it works fine and Personal Access Tokens can be created.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
