### ISSUE TITLE
Return sane error for bad credentials

### ISSUE THREAD

**Issue by jdavidbakr** [laravel/passport#1376]
With the recent change that oauth2-server now throws an invalid_grant instead of invalid_credentials, the error message returned to the user is cryptic and misleading.  I propose that we modify `AccessTokenController::issueToken()` to a try-catch similar to https://github.com/laravel/passport/issues/1113#issuecomment-698813835

**Comment by driesvints** [comment]
I'm not sure this is needed. I'll ping the OAuth2 server maintainer on your PR.

**Comment by jdavidbakr** [comment]
oauth2-server has stated that they are not going to change it, that the message is intentionally obfuscated.

**Comment by driesvints** [comment]
@jdavidbakr we in general follow the path that oauth2-server chooses which is why I want to verify it first with the maintainer. Let's see what he says.
