### ISSUE TITLE
Authenticating web using Laravel Passport Token-Based Authentication

### ISSUE THREAD

**Issue by maqsudinamdar** [laravel/passport#1378]
# Authenticate web using Laravel Passport #

I'm [Redirecting][1] the Response by specifying the access token as a [Bearer token][2] in the `Authorization` header to the route. And getting below error.

>Illuminate\Auth\AuthenticationException: Unauthenticated.

**File:** `Controller.php`
```
        $id = '1';
        $accessToken = 'passport_token_value';
        return redirect('home/id='.$id)->header('Authorization', 'Bearer '.$accessToken);
```
I have assigned [Laravel Passport custom middleware][3] to protect and authenticate different types of users by defining their guard.

**File:** `routes\web.php`
```
Route::get('home/id={id}', 'Controller@index')->middleware('auth:api-custom');
```
**File:** `config\auth.php`
```
'guards' => [   
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport', // set this to passport
            'provider' => 'user', //
            'hash' => false,
        ],

        'api-custom' => [
            'driver' => 'passport', // set this to passport
            'provider' => 'custom', //
            'hash' => false,
        ],
    ],

```

However, the above configuration is working in API through Postman.

Can we use the [Laravel HTTP Client][4] here?

  [1]: https://laravel.com/docs/8.x/responses#redirects
  [2]: https://laravel.com/docs/8.x/passport#passing-the-access-token
  [3]: https://laravel.com/docs/8.x/passport#multiple-authentication-guards
  [4]: https://laravel.com/docs/8.x/http-client#bearer-tokens

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
