### ISSUE TITLE
Got issue when upgrade to laravel 8

### ISSUE THREAD

**Issue by dhha** [laravel/passport#1380]
Hi Guys,

I've just tried to upgrade laravel to 8x from 7x and it require passport 10x, but after successful upgraded i got issue with message
"Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead."

![image](https://user-images.githubusercontent.com/2024314/100200613-73584600-2f31-11eb-840a-c5ac4c622347.png)

can anyone help me to fix it? thanks

**Comment by SHELA** [comment]
Hello,
have the same

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lagbox** [comment]
@driesvints  https://github.com/laravel/passport/issues/1381

**Comment by nvahalik** [comment]
I'm not on Laravel 8. I'm on 7 but I'm getting the same error.

Looks like updating https://github.com/lcobucci/jwt to `3.4.x` from `3.3.0` is also causing this.

Given that 3.4.0 was only released a few hours ago, this seems to be the culprit.

Peg your dependency of `lcobucci/jwt` to `^3.3.0` and then update it again.

**Comment by dhha** [comment]
> I'm not on Laravel 8. I'm on 7 but I'm getting the same error.
> 
> Looks like updating https://github.com/lcobucci/jwt to `3.4.x` from `3.3.0` is also causing this.
> 
> Given that 3.4.0 was only released a few hours ago, this seems to be the culprit.
> 
> Peg your dependency of `lcobucci/jwt` to `^3.3.0` and then update it again.

thanks, it works for me just need to downgrade to 3.3.0 👍

**Comment by devsi** [comment]
Specifically it is [thephpleague/oauth2-server](https://github.com/thephpleague/oauth2-server) that uses this dependency. Is passport. oauth2-server have [lcobucci/jwt](https://github.com/lcobucci/jwt) set to `^3.3.1` and so following closer to semantic versioning, expects `3.4` to not break compatibility. Technically it does not break compatibility, but rather exposes those production servers that have `E_DEPRECATED` in their error_reporting settings, and so they aren't considering it a BC break.
