### ISSUE TITLE
Replicating claims as headers is deprecated and will removed from v4.0

### ISSUE THREAD

**Issue by sahakavatar** [laravel/passport#1382]
- Passport Version:7.3
- Laravel Version: 5.7
- PHP Version: 7.3
- Database Driver & Version:

 Description:
getting this message when calling oauth token 
![image](https://user-images.githubusercontent.com/18184278/100232300-a0acf000-2f41-11eb-8ba5-6ea8ac2b8074.png)

Replicating claims as headers is deprecated and will removed from v4.0. Please manually set the header if you need it replicated.

 Steps To Reproduce:

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by driesvints** [comment]
Also please see https://github.com/laravel/passport/issues/1381
