### ISSUE TITLE
Not able to get access token with all correct information Laravel\Passport\Bridge\AccessToken::__toString() must not throw an exception

### ISSUE THREAD

**Issue by damku999** [laravel/passport#1383]
- Passport Version:  9.3.2
- Laravel Version: 7.29.3
- PHP Version: 7.4
- Database Driver & Version:
MySQL 5.7
### Description:
[2020-11-25 14:52:21] local.ERROR: Method Laravel\Passport\Bridge\AccessToken::__toString() must not throw an exception, caught ErrorException: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Method Laravel\\Passport\\Bridge\\AccessToken::__toString() must not throw an exception, caught ErrorException: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. at C:\\wamp64\\www\\apiproject\\vendor\\league\\oauth2-server\\src\\ResponseTypes\\BearerTokenResponse.php:0)
[stacktrace]
#0 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(143): Symfony\\Component\\ErrorHandler\\Error\\FatalError->__construct()
#1 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(130): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->fatalErrorFromPhpError()
#2 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(0): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#3 C:\\wamp64\\www\\apiproject\\vendor\\league\\oauth2-server\\src\\AuthorizationServer.php(202): League\\OAuth2\\Server\\ResponseTypes\\BearerTokenResponse->generateHttpResponse()
#4 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\passport\\src\\Http\\Controllers\\AccessTokenController.php(63): League\\OAuth2\\Server\\AuthorizationServer->respondToAccessTokenRequest()
#5 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\passport\\src\\Http\\Controllers\\HandlesOAuthErrors.php(24): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->Laravel\\Passport\\Http\\Controllers\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\passport\\src\\Http\\Controllers\\AccessTokenController.php:61-65}()
#6 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\passport\\src\\Http\\Controllers\\AccessTokenController.php(65): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->withErrorHandling()
#7 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(48): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->issueToken()
#8 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(196): Illuminate\\Routing\\Route->runController()
#10 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(685): Illuminate\\Routing\\Route->run()
#11 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php:683-687}()
#12 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:126-132}()
#13 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#14 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:143-174}()
#15 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(687): Illuminate\\Routing\\Pipeline->then()
#16 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#17 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(628): Illuminate\\Routing\\Router->runRoute()
#18 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#19 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#20 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): App\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php:162-166}()
#21 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:126-132}()
#22 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#23 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:143-174}()
#24 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\TrimStrings->handle()
#25 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:143-174}()
#26 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#27 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:143-174}()
#28 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#29 C:\\wamp64\\www\\apiproject\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:143-174}()
#30 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#31 C:\\wamp64\\www\\apiproject\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:143-174}()
#32 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\TrustProxies->handle()
#33 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure:C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:143-174}()
#34 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(140): Illuminate\\Routing\\Pipeline->then()
#35 C:\\wamp64\\www\\apiproject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(109): App\\Http\\Kernel->sendRequestThroughRouter()
#36 C:\\wamp64\\www\\apiproject\\public\\index.php(55): App\\Http\\Kernel->handle()
#37 C:\\wamp64\\www\\apiproject\\public\\index.php(0): {main}()
#38 {main}
"} 

### Steps To Reproduce:
The strange thing is that it is was working fine I just update passport ver and stopped working on getting token.

**Comment by plivius** [comment]
@damku999 
Likely cause: https://github.com/lcobucci/jwt/issues/550#issuecomment-733557709
(temporarily downgrade lcobucci/jwt to 3.3)

**Comment by driesvints** [comment]
Please see https://github.com/laravel/passport/issues/1381 and other opened issues.
