### ISSUE TITLE
Target [Lcobucci\JWT\Parser] is not instantiable while building [Laravel\Passport\PersonalAccessTokenFactory]

### ISSUE THREAD

**Issue by Gams101** [laravel/passport#1384]
- Passport Version: 10.0
- Laravel Version: 8.16.1
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 5.7.24

### Description:
First of all I would like to thank you guys for this wonderful authentication package for laravel, it's my first time trying out this package and I followed the installation guide at https://laravel.com/docs/8.x/passport but when this code block in my controller signup action it throws the error in the title:

$token = $user->createToken('authToken')->accessToken;

Here's the snippet of my code for signup action:
![image](https://user-images.githubusercontent.com/52016499/100319908-6011ad00-2ffb-11eb-9479-bb08d6de9346.png)

### Steps To Reproduce:
1. Fresh Laravel 8 installation.
2. Followed Laravel Passport Installation guide.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/passport/issues/1381 and numerous other issues.

**Comment by Gams101** [comment]
> Please see #1381 and numerous other issues.

Following this thread's answers and adding "lcobucci/jwt": "3.3.3" in composer.json, and running "composer update" fixed this issue as well. Thanks!

**Comment by driesvints** [comment]
I've also just released v10.1.0 with support for JWT v3.4

**Comment by Gams101** [comment]
> I've also just released v10.1.0 with support for JWT v3.4
Great! Currently upgraded to v10.1.0 and removed "lcobucci/jwt": "3.3.3" on my composer.json works fine. Thanks again!

**Comment by ALTELMA** [comment]
Hi Guys, v10.1.0 does not support Laravel 6

Sadly :(

**Comment by driesvints** [comment]
@ALTELMA we're looking into bringing PHP 8 support to Passport 9.x: https://github.com/laravel/passport/pull/1387

We're pretty close to that.
