### ISSUE TITLE
install passport issue

### ISSUE THREAD

**Issue by anas-aw** [laravel/passport#1388]
- Passport Version: 10.1
- Laravel Version: 6.20
- PHP Version: ^7.2.5|^8.0

### Description:
>>>>>composer require laravel/passport

Using version ^10.1 for laravel/passport
./composer.json has been updated
Running composer update laravel/passport
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/passport[v10.1.0, ..., 10.x-dev] require illuminate/auth ^8.2 -> found illuminate/auth[v8.2.0, ..., 8.x-dev] but it conflicts with another require. 
    - Root composer.json requires laravel/passport ^10.1 -> satisfiable by laravel/passport[v10.1.0, 10.x-dev].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by driesvints** [comment]
Passport 10 requires Laravel 8
