### ISSUE TITLE
Better Passport install instructions in Laravel Passport docs for L6 LTS

### ISSUE THREAD

**Issue by meredevelopment** [laravel/passport#1391]
Seeing that Laravel 6 is still - at the time of writing - the LTS version, I think the [Laravel Passport docs](https://laravel.com/docs/6.x/passport#installation) should specify the version of Passport that is supported.

If users follow the current docs and do `composer require laravel/passport` they will end up with a "Your requirements could not be resolved to an installable set of packages." error. 

Would it be a good idea to add a note, or suggest that L6 users run `composer require laravel/passport "^9.0"`?
Or is there a better version / way to deal with this? I see a LOT of questions about this problem/error on Stack Exchange, here, Laracasts etc.

Happy to PR the docs, but wanted opinions first please.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/passport/pull/1387

**Comment by meredevelopment** [comment]
Thanks @driesvints, missed that issue/PR. 

So when https://github.com/laravel/passport/pull/1387 is merged, will `composer require laravel/passport` work for L6 installers? Or will they have to specify v9 of Passport still. Sorry I don't know much about dependency trees.

**Comment by driesvints** [comment]
You'll need to require v9

**Comment by meredevelopment** [comment]
Ok thanks, so a tweak to the Laravel v6 Docs is a good idea.

**Comment by driesvints** [comment]
@meredevelopment feel free to PR something.

**Comment by driesvints** [comment]
I've just released v9.4.0 which supports PHP 8
