### ISSUE TITLE
When i call $user->createToken('MyApp')-> accessToken 

### ISSUE THREAD

**Issue by nurkarim** [laravel/passport#1400]
- Passport Version: ^10.1.0
- Laravel Version: ^8.12
- PHP Version: 7.3.5
- Database Driver & Version:

### Description:
{
    "message": "syntax error, unexpected 'Parser' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)",
    "exception": "ParseError",
    "file": "/home/.../vendor/lcobucci/jwt/src/Configuration.php",
    "line": 22,
}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
