### ISSUE TITLE
Laravel/passport installation failed on laravel v. 8.22.1

### ISSUE THREAD

**Issue by ammdsoftdev** [laravel/passport#1402]
@driesvints 

- Passport Version: #.#.#
- Laravel Version: 8.22.1
- PHP Version: 7.4.9
- Database Driver & Version:

I'm trying to implement laravel/passport on my app and run `composer require laravel/passport` and it returns error saying:

> Problem 1
>     - lcobucci/jwt 4.2.x-dev requires ext-sodium * -> the requested PHP extension sodium is missing from your system.
>     - lcobucci/jwt 4.1.x-dev requires ext-sodium * -> the requested PHP extension sodium is missing from your system.
>     - lcobucci/jwt 4.1.0 requires ext-sodium * -> the requested PHP extension sodium is missing from your system.
>     - Conclusion: don't install laravel/passport v10.1.0
>     - Conclusion: remove lcobucci/jwt 3.3.3
>     - Installation request for laravel/passport ^10.1 -> satisfiable by laravel/passport[10.x-dev, v10.1.0].
>     - Conclusion: don't install lcobucci/jwt 3.3.3
>     - laravel/passport 10.x-dev requires lcobucci/jwt ^3.4|^4.0 -> satisfiable by lcobucci/jwt[3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.x-dev, 4.0.0, 4.0.0-alpha1, 4.0.0-alpha2, 4.0.0-alpha3, 4.0.0-beta1, 4.0.1, 4.0.x-dev, 4.1.0, 4.1.x-dev, 4.2.x-dev].
>     - Can only install one of: lcobucci/jwt[3.4.0, 3.3.3].
>     - Can only install one of: lcobucci/jwt[3.4.1, 3.3.3].
>     - Can only install one of: lcobucci/jwt[3.4.2, 3.3.3].
>     - Can only install one of: lcobucci/jwt[3.4.3, 3.3.3].
>     - Can only install one of: lcobucci/jwt[3.4.x-dev, 3.3.3].
>     - Can only install one of: lcobucci/jwt[4.0.0, 3.3.3].
>     - Can only install one of: lcobucci/jwt[4.0.0-alpha1, 3.3.3].
>     - Can only install one of: lcobucci/jwt[4.0.0-alpha2, 3.3.3].
>     - Can only install one of: lcobucci/jwt[4.0.0-alpha3, 3.3.3].
>     - Can only install one of: lcobucci/jwt[4.0.0-beta1, 3.3.3].
>     - Can only install one of: lcobucci/jwt[4.0.1, 3.3.3].
>     - Can only install one of: lcobucci/jwt[4.0.x-dev, 3.3.3].
>     - Installation request for lcobucci/jwt (locked at 3.3.3) -> satisfiable by lcobucci/jwt[3.3.3].
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - C:\xampp\php\php.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> 
> Installation failed, reverting ./composer.json to its original content.

I also tried running composer require `laravel/passport:8.0.0` and `7.5.1`, still results to failed installation with different error this time.

I can't find any passport version that is intended for `laravel 8.22.1`.

How do I do this?

**Comment by driesvints** [comment]
Throw away your vendor and lock file and do a fresh install.
