### ISSUE TITLE
Token is valid for all guards

### ISSUE THREAD

**Issue by ayman-elmalah** [laravel/passport#1404]
- Passport Version: 10.1
- Laravel Version: 8.12
- PHP Version: 7.4
- Database Driver & Version: mysql 5.7

### Description:
When using $model->createToken($token_name), $model can be instance from User model or Admin model
so it create token but the token is available for all guards,  so if i use user token in admin area it will work ok, its not depending on the guard or the provider

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
