### ISSUE TITLE
Security Alert: tokens, is hasMany relation not Morph relation

### ISSUE THREAD

**Issue by admicaa** [laravel/passport#1405]
https://github.com/laravel/passport/blob/d28948c9ff9d71207ad077be221d95f8307eab2b/src/HasApiTokens.php#L33
at the previous line when we get user tokens we return any token that has only user_id **regardless** of the model name, this causes a security problem, for example: 
if we have a driver with an id of 1
and a super admin with an id of 1 
the driver can easily use his token to log in as a super admin. in the super admin panel.
this must be a morphic relationship, thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by admicaa** [comment]
@driesvints excuse me, seems you didn't get my idea, the solution is easy just make a function in the model and ignore it from the trait, but this is a real security issue, where one model can use his token, and act as another model ( when they have the same id )

users, can go to the admin panel and treat as an admin 
they can call admin APIs as admin

**Comment by driesvints** [comment]
Hey @admicaa. First of all, if this is a real security issue you shouldn't be publicly disclosing this on an issue tracker ([see our readme](https://github.com/laravel/passport#security-vulnerabilities)).

Furthermore I don't see how this can be a security issue.
