### ISSUE TITLE
Support urn:ietf:wg:oauth:2.0:oob as redirect uris

### ISSUE THREAD

**Issue by h3poteto** [laravel/passport#1407]
When I provide `urn:ietf:wg:oauth:2.0:oob` as a redirect uri, the application try to redirect after authorize, as a result the application does not show any tokens.

Popular OAuth2 library are supporting `urn:ietf:wg:oauth:2.0:oob` as redirect uris. When the URI is specified as a redirect uri, I expect the behavior to display the token on the screen without redirecting after authorize.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
