### ISSUE TITLE
Call to undefined method Illuminate\Support\Facades\Auth::extend()

### ISSUE THREAD

**Issue by paligiannis** [laravel/passport#1408]
- Passport Version: v10.1.0
- Laravel Version: 8.27.0
- PHP Version: 7.4.15
- Database Driver & Version: MYSQL@5.7

### Description:

I have tried everything about changing some core files, find any collision between packages and investigate any issues of the package or code we have developed by ourselves and nothing. 

What seems to work:
1. I have changed the core file PassportServiceProvider.php 
2. Change 
```
Auth::resolved(function ($auth) {
            $auth->extend('passport', function ($app, $name, array $config) {
                return tap($this->makeGuard($config), function ($guard) {
                    $this->app->refresh('request', $guard, 'setRequest');
                });
            });
        });
```
to
```
Auth::resolved(function ($auth) {
            **Auth::extend**('passport', function ($app, $name, array $config) {
                return tap($this->makeGuard($config), function ($guard) {
                    $this->app->refresh('request', $guard, 'setRequest');
                });
            });
        });
```

## Additional Info
When I make this amended change, web page and api works correctly. When I use the initial format without any change only the api of passport works.

Has any seen this issue before? I read some issues #1224 and checked all pull requests and merges.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by paligiannis** [comment]
@driesvints I debugged the code and I can't figure out what's happening. Service providers bag seems clean! No duplicate registered providers no collision with other packages. Also, $auth is an instance of AuthManager, seems to work correctly, https://prnt.sc/10361fh

**Comment by arukompas** [comment]
For me personally, the issue was me trying to inject `Auth` into form validation `rules()` method signature like so:
```php
    public function rules(Auth $auth)
    {
        if ($auth->check()) {...
        ...
    }
```

instead of injecting it, I used the facade directly and it worked:
```php
    public function rules()
    {
        if (Auth::check()) {...
        ...
    }
```
