### ISSUE TITLE
Laravel Nova and Laravel Passport cannot install together, if done in the wrong oder.

### ISSUE THREAD

**Issue by addgod** [laravel/passport#1409]
- Passport Version: 10.1.0
- Laravel Version: 8.28.1
- PHP Version: 7.4.15

### Description:
Cannot install Laravel Passport along side Laravel Nova, if done in the wrong order. So if nova is installed first then passport, it will not work. But if passport is installed first, and then nova. Then it will work.

Laravel Nova and Laravel Passport both uses phpseclib/phpseclib. Passport uses it directly, where nova it is quite deeply nested in its dependencies. But when installing both in a fresh install of laravel, composer complains because of the version mismash shown below.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/passport[v10.1.0, ..., 10.x-dev] require phpseclib/phpseclib ^2.0 -> found phpseclib/phpseclib[2.0.0, ..., 2.0.x-dev] but the package is fixed to 3.0.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel/passport ^10.1 -> satisfiable by laravel/passport[v10.1.0, 10.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

```

### Steps To Reproduce:
Install Laravel.
Install Laravel Nova
Install Laravel Passport

**Comment by driesvints** [comment]
What version of Nova are you using? I'll see if I can get passport to update to phpseclib/phpseclib v3.0

**Comment by driesvints** [comment]
We'll do a new release next Tuesday for phpseclib v3 support
