### ISSUE TITLE
Move routes to dedicates routes file

### ISSUE THREAD

**Issue by driesvints** [laravel/passport#1414]
Passport is probably one of the oldest first party package we have. It still uses the old way of setting up routes through a dedicated routes method on the Passport class. It's best that we move it to a new `routes/web.php` file in similar fashion as all the other first party packages.

**Comment by HassanYA** [comment]
I second this. I have installed laravel passport very recently and have no idea what the endpoints to begin with and cannot write my api documentation

**Comment by driesvints** [comment]
Will land in Passport v11
