### ISSUE TITLE
Revert phpseclib v3 update PR

### ISSUE THREAD

**Issue by smujaddid** [laravel/passport#1416]
- Passport Version: 10.1.0
- Laravel Version: 8.29.0
- PHP Version: 7.4.15
- Database Driver & Version:

### Description:
I'm using `"league/flysystem-sftp": "^1.0",` for my project and I can not update `laravel/passport` to latest version (10.1.1) because of `phpseclib`. Both `league/flysystem` and `league/flysystem-sftp` are still using phpseclib v2 for their 1.x and 2.x library versions. But, `laravel/passport` 10.1.1 locked the phpseclib to v3, so it causing dependecy conflicts when I was trying to update.

I suggest to revert PR #1410 for 10.x because if there are any future updates for 10.x then anyone, who are using `league/flysystem-sftp` 1.x and Laravel 8.x, will not be able to update their `laravel/passport` package..

Unless there is a way to support both phpseclib v2 and v3, then this could be a problem.
Another way is to wait until `league/flysystem` update their phpseclib dependency to v3, but I doubt that it will happen soon.

### Steps To Reproduce:
`composer require laravel/passport:"^10.1.1" -W`

```shell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/passport v10.1.1 (conflict analysis result)
    - Conclusion: don't install phpseclib/phpseclib 3.0.4 (conflict analysis result)
    - Conclusion: don't install phpseclib/phpseclib 3.0.5 (conflict analysis result)
    - google/apiclient is locked to version v2.9.1 and an update of this package was not requested.
    - Conclusion: don't install phpseclib/phpseclib 2.0.28 (conflict analysis result)
    - Conclusion: don't install phpseclib/phpseclib 2.0.29 (conflict analysis result)
    - Conclusion: don't install phpseclib/phpseclib 3.0.1 (conflict analysis result)
    - Conclusion: don't install phpseclib/phpseclib 3.0.2 (conflict analysis result)
    - Conclusion: don't install phpseclib/phpseclib 2.0.30 (conflict analysis result)
    - Conclusion: don't install phpseclib/phpseclib 3.0.3 (conflict analysis result)
    - Root composer.json requires laravel/passport ^10.1.1 -> satisfiable by laravel/passport[v10.1.1, 10.x-dev].
    - league/flysystem-sftp is locked to version 1.0.22 and an update of this package was not requested.
    - league/flysystem-sftp 1.0.22 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.0, ..., 2.0.x-dev].
    - You can only install one version of a package, so only one of these can be installed: phpseclib/phpseclib[2.0.0, ..., 2.0.x-dev, 3.0.0, ..., 3.0.x-dev].
    - laravel/passport 10.x-dev requires phpseclib/phpseclib ^3.0 -> satisfiable by phpseclib/phpseclib[3.0.0, ..., 3.0.x-dev].
    - Conclusion: don't install phpseclib/phpseclib 3.0.0 (conflict analysis result)
```

**Comment by driesvints** [comment]
Thanks. This report indeed convinces me we should backport support for v2 in Passport v10. I've sent in a PR for that here: https://github.com/laravel/passport/pull/1418. We'll remove support for v2 in Passport v11.
