### ISSUE TITLE
AuthManager Authorization header not working in production

### ISSUE THREAD

**Issue by newtoniumx3** [laravel/passport#1423]
- Passport Version: 10.1.1
- Laravel Version: 8.12
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 5.7

### Description:

I'm not sure if this is a potential bug or my environment problem but.

The Authorization header passport system is not working in the production environment. The same exact code works on my localhost. I debugged production to make sure the token was being received intact and it in fact is, the value is correct and received in middlewares. However in production app('request')->user() always resolves to null no matter what.

### Steps To Reproduce:

<img width="797" alt="123" src="https://user-images.githubusercontent.com/43615639/110951620-49296900-8313-11eb-8bef-5fb88dc0dceb.PNG">

**The process is rather simple.** 
1. Send a login request and receive back an access_token
3. Send a second request with the access_token in the header as: Authorization: Bearer ...

---

**In production**
- Step 1 works I receive back the access_token
- Step 2, I always get back a null user session. I checked in production and the Authorization header does arrive intact and the value is also correct. But then why would it not process this properly like in localhost?

Could the issue have something to do with subdomains? My ingress controlled redirects all requests to https://www.... so www.mysite.com would be different than mysite.com? Although I don't know if this is relevant given that the token doesn't seem to have any of that information baked in and the value is going through alright.

I'm still trying to debug in production but right now here is what I got. AuthManager is what properly initiates the session on localhost but always resolves to null in production.

![1234](https://user-images.githubusercontent.com/43615639/110951983-b0dfb400-8313-11eb-863a-e6ffd13cb953.jpg)

  [1]: https://i.stack.imgur.com/qaxoz.png
  [2]: https://i.stack.imgur.com/gq4r5.jpg

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
