### ISSUE TITLE
Invalid grant error

### ISSUE THREAD

**Issue by sbn111** [laravel/passport#1424]
- Passport Version: used this -> joselfonseca/laravel-api from github
- Laravel Version:  8
- PHP Version: 7
- 
### Description:
Receiving this response,
Response,
{
"error": "invalid_grant",
"error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
"hint": "",
"message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}

### Steps To Reproduce:
Receiving this error in postman while trying to send the below details,
URL -  /oauth/token
Data - {
  "grant_type": "password",
  "client_id": "8",
  "client_secret": "fuM0n5q1ufEjAyYRvrR32Knv6IHswlGmjx36cnw1",
  "username": "jose@example.com",
  "password": "Password123**"
}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
