### ISSUE TITLE
Unauthenticate response

### ISSUE THREAD

**Issue by sbn111** [laravel/passport#1426]
- Passport Version: 
- Laravel Version: 8
- PHP Version: 7

### Description:

I have passed authorization header but receiving this response, 
{
    "message": "Unauthenticated.",
    "status_code": 401
}

### Steps To Reproduce:
Run this url in post man get method to retrieve list of user - http://127.0.0.1:8000/api/users
I have sent authorization header with bearer token. But it showing unauthenticate.

Pls help me to solve this issue. thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
