### ISSUE TITLE
Unauthenticated response

### ISSUE THREAD

**Issue by sbn111** [laravel/passport#1427]
- Passport Version: used in joselfonseca/laravel-api
- Laravel Version: 8
- PHP Version: 7
- Database Driver & Version: Mysqli

### Description:
Included bearer token but receiving response as unauthenticated,
Response,
{
    "message": "Unauthenticated.",
    "status_code": 401
}

### Steps To Reproduce:
Tried this link to get list of users - http://127.0.0.1:8000/api/users
And I have included authorization header with bearer token in post man. but I can't get the result.
Pls help me to solve this issue

**Comment by driesvints** [comment]
Stop opening these please and use a support channel
