### ISSUE TITLE
Value is not in the allowed date format

### ISSUE THREAD

**Issue by rashmiranjanrrs** [laravel/passport#1437]
- Passport Version: 10.1.3
- Laravel Version: 8.12
- PHP Version: 7.4
- Database Driver & Version:
- - lcobucci/jwt: 4.1.4

### Description:
I have done everything but unable to solve the bug by updating it to the latest version. Anyone, please help me on this issue.

### Steps To Reproduce:
Only on the live server It's throwing this Error not in local.
![ice_screenshot_20210409-131924](https://user-images.githubusercontent.com/54047909/114147356-416edb80-9936-11eb-98a8-c15d98b802fa.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rashmiranjanrrs** [comment]
@driesvints Ofcourse it's a bug
