### ISSUE TITLE
Installing Passport removes parallel testing capabilities in Laravel >= 8.25

### ISSUE THREAD

**Issue by joelbutcher** [laravel/passport#1438]
- Passport Version: v10.1.3
- Laravel Version: v8.36.1
- PHP Version: 8.0.3
- Database Driver & Version: MySQL

### Description:
When installing Laravel Passport, composer removes the `brianium/paratest` package required for the parallel testing feature of Laravel >= 8.25.

### Steps To Reproduce:
- Scaffold a fresh Laravel app using Laravel >= 8.25.
- Install run `php artisan test --parallel` and follow this instructions to install `brianium/paratest`
- Install Laravel Passport at the latest version (v10.1.3 at time of reporting)
- See composer removing `brianium/paratest`

**Comment by driesvints** [comment]
Think there's something really specific going on for your use case because it works fine for me with the steps from above.
