### ISSUE TITLE
[Feature request] Supporting laravel/sanctum

### ISSUE THREAD

**Issue by lk77** [laravel/passport#1439]
Hello,

it seems that when using both sanctum and passport in same project, 
passport does not recognize the sanctum token and disconnect the user, which prevents sanctum from handling the request as expected.

The only way to make it works is to define sanctum guard before passport guard in config/auth.php,
but i think it would be great for passport and sanctum to work together out of the box.

To reproduce this, install both sanctum and passport, and define passport before sanctum in auth.php, login works but bearer token gets rejected by passport, because it's a sanctum token.

thanks.

**Comment by driesvints** [comment]
Heya. Atm we have no plans for this. It's intended that you use either Sanctum or Passport for your authentication and not both.

**Comment by lk77** [comment]
Well we need token based api for user/clients and another oauth2 api for iot devices, i don't think passport alone can handle that.

**Comment by ReArmedHalo** [comment]
Perhaps I am misunderstanding your use case (javascript frontend? and / or other means of consuming) but doesn't Passport have this functionality built-in? https://laravel.com/docs/8.x/passport#consuming-your-api-with-javascript

**Comment by lk77** [comment]
There is two ways of consuming, a first party iot device api, and third party users api,
users should be able to get a token and use that to develop their own software in any language they see fit, like node/php/java or anything else.
