### ISSUE TITLE
How does the Passport Package check that the third-party client really has the scope it claims in the redirect request?

### ISSUE THREAD

**Issue by enaeim** [laravel/passport#1440]
- Passport Version: 10.1.3
- Laravel Version: 6.20.16
- PHP Version: 7.4.14
- Database Driver & Version: 10.5.8-MariaDB

### Description:
We are using the 'Authorization Code Grant Token'  for our project. Everything works fine. However, how does the passport check the scope that the third party client claims in the redirect request really belongs to him or not? Maybe he is lying.

To explain further, I will give 2 examples:
Example 1: Suppose our application has one third-party client. We give him access to 10 scopes and he can request token access with them. After a while, we want to deprive him of access to 3 of the scope and do not allow him to access these 3 scopes. In this case, how does the passport package verify this?
Example 2: Suppose we have two third-party clients. The first client has access to 10 of our scope and the second client has access to 7 of our scope. If the second client achieves the scope that the first client has, it can request us with unauthorized scope and receive an access token. In this case, how does the passport package verify this?

Our main question is what is the logic used to implement the scope in the passport? And the next question is how the truth or falsity of the third party client in using the scope is checked by the passport?

Thanks in advance for your guidance.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
