### ISSUE TITLE
Passport drivers usage causes invalid token

### ISSUE THREAD

**Issue by gharbat** [laravel/passport#1441]
- Passport Version: 10.0
- Laravel Version: 8
- PHP Version:  7.4.0
- Database Driver & Version: MySQL 5.7

### Description:
Laravel responded with 401 unauthenticated once we use access token with driver other that the default one 

### Steps To Reproduce:

- let us create a new client ID and client secret  via passport command
 ``` php artisan passport:client  --password  --provider=developers```
- now we got our client ID and client password, also we have created a developer account in Developer table
- Lets call the oauth/token endpoint to generate access token
```
$http->post(env('app.url') . 'oauth/token', [
            'form_params' => [
                'grant_type' => 'password',
                'client_id' => $clientId,
                'client_secret' => $clientSecret,
                'username' => $userEmail,
                'password' => $password,
                'scope' => $scopes,
            ],
        ]);
```
- this will output an access token for us, lets try to call a previously prepared end point with auth:api middleware 
- this will result a 401 response

lets do some debugging using Laravel telescope, we will see it break on oauth_clients table

<img width="932" alt="Screen Shot 2021-04-17 at 1 40 31 AM" src="https://user-images.githubusercontent.com/32633162/115090507-bc7b5780-9f1d-11eb-9139-4a24fdf0d8c9.png">

yet if we copied the same exact query and ran it inside MySql CLI 
<img width="716" alt="Screen Shot 2021-04-17 at 1 41 59 AM" src="https://user-images.githubusercontent.com/32633162/115090598-edf42300-9f1d-11eb-9ca5-6cb7a9469567.png">

now let us try to do the same steps, but this time without the developers provider, it will work, and here is the query stack from Telescope

<img width="915" alt="Screen Shot 2021-04-17 at 1 43 49 AM" src="https://user-images.githubusercontent.com/32633162/115090682-2f84ce00-9f1e-11eb-97ac-c632d19c407f.png">

notice how it looks for the sub claim in users tables (which is the default provider)
summary: when the provider something other than null, the access token will not work.

reference:
my auth.php

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [

        //-- To authorize the access to apps
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],

        //-- To manage and authorize apps
        'developers' => [
            'driver' => 'session',
            'provider' => 'developers',
        ],

        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'partner' => [
            'driver' => 'session',
            'provider' => 'partners'
        ]
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],

        'developers' => [
            'driver' => 'eloquent',
            'model' => App\Models\Developer::class,
        ],

        'partners' => [
            'driver' => 'eloquent',
            'model' => Partner::class,
        ]
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

**Comment by gharbat** [comment]
i thinks the issue is here
https://github.com/laravel/passport/blob/a5e4471dd99b7638ab5ca3ecab6cd87cf37eb410/src/Guards/TokenGuard.php#L98

why we compare the provider name from auth.php here ?
if the request in another provider (other than the one in the auth.php then it will fail, we shall check if the provider valid within the keys of `providers` array in auth.php) ?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by gharbat** [comment]
Hey @driesvints, already discussed this issue in the Discord server, and it is appear its a valid bug in passport, once the provider is set in the client we must validate it against array of the keys of the providers array in auth.php, and not the default provider.

thanks !

**Comment by gharbat** [comment]
@driesvints any updates on this ?

**Comment by driesvints** [comment]
These changes were introduced in https://github.com/laravel/passport/pull/1220. @billriess can you maybe shed some light on this?

**Comment by billriess** [comment]
I can try to take a look at this over the weekend but I've been fairly busy lately so no promises.

This was working when it was merged in though.
