### ISSUE TITLE
Remove Firebase JWT dependencies in favour of Lcobucci JWT

### ISSUE THREAD

**Issue by peterfox** [laravel/passport#1452]
To put it simply, the `firebase/php-jwt` package is a dependency of Passport. Passport has a dependency of `league/oauth2-server` which depends upon `lcobucci/jwt` which has the functionality to encode and decode JWT tokens the same as the Firebase package.

I'm happy to do the work on the changes so `firebase/php-jwt` can be removed so the package only relies on the `lcobucci/jwt` package but would prefer a maintainer to sign off on it before putting the work in if there's a reason why the Firebase package is preferred over using Lcobucci.

**Comment by driesvints** [comment]
I've actually been thinking of that as well. We could do that for the next major release maybe. Although I don't know the exact implications atm. If you're willing, feel free to work on a PR for master to check if we can drop it. Thanks!

**Comment by peterfox** [comment]
In theory it might not even need a major release as from a quick glance the code using Firebase isn't used in any parameters etc and it's just array/objects being returned so as long as the code for Lcobucci is doing the same it could be a swap out. Doesn't seem to reference the exceptions thrown by encode/decode. The package mostly references Lcobucci classes.

The problem I guess would be those using the firebase JWT classes in their apps but haven't added it to their own composer dependencies though.

**Comment by driesvints** [comment]
@peterfox technically that indeed shouldn't be an issue. They should have added firebase to their own dependencies in that case. Maybe try a pr to current stable branch and if we feel it's too much of a breaking change we could still swap to master.

**Comment by driesvints** [comment]
I'm gonna close this one for now. If you're willing, feel free to send in a PR.
