### ISSUE TITLE
BadMethodCallException: Call to undefined method App\Models\User::token() 

### ISSUE THREAD

**Issue by caixingyue** [laravel/passport#1455]
- Passport Version: 10.1.3
- Laravel Version: 8.46.0
- PHP Version: 8.0.7
- Database Driver & Version:

### Description:
HI~
  When I use middleware to check the scope of the token, there is an exception. Remove the "! $request->user()->token()" in the middleware and it is normal. May I ask if I have not configured anything, thank you

### Steps To Reproduce:
1、I logged in and got a token
  event(new Registered($user = User::find(1)));
  $client = DB::table('oauth_clients')->where('password_client', 1)->first();
  $request->request->add([
            'username' => $user->email,
            'password' => $request->password,
            'grant_type' => 'password',
            'client_id' => $client->id,
        'client_secret' => $client->secret,
        'scope' => 'place-orders'
  ]);
  $proxy = Request::create('oauth/token', 'POST');
  $data = Route::dispatch($proxy);

2、Add middleware
  'scopes' => \Laravel\Passport\Http\Middleware\CheckScopes::class,
  'scope' => \Laravel\Passport\Http\Middleware\CheckForAnyScope::class,

3、Added scope check for visited route
  Route::get('user', [PassportController::class, 'details'])->middleware('scope:place-orders');

4、Postman request, the following error message occurred
BadMethodCallException: Call to undefined method App\Models\User::token() in file \vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php on line 50

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
