### ISSUE TITLE
OAuth2 authorization error on cancel button pressed

### ISSUE THREAD

**Issue by KevinYobeth** [laravel/passport#1456]
- Passport Version: 10.1.3
- Laravel Version: 8.46.0
- PHP Version: 7..4.11
- Database Driver & Version: mySQL version 5.0.37

### Description:
I'm making an OAuth2 application using Laravel Passport. I use it to login user using their account on the OAuth2 application. It all went well, except, when the user click the cancel button, it will throw the error (attached). I did not modify any form field. 

My auth screen
![screenshot](https://user-images.githubusercontent.com/10485985/122020880-5876f180-cdef-11eb-9fb7-98a29e0e48c8.jpg)

Error Log
https://flareapp.io/share/Vme6dNAP#F61

### Steps To Reproduce:
- Install laravel passport
- Send POST request to `/oauth/clients` client with `name` and `redirect`
- Send POST request to `/oauth/authorize` with `client_id`, `redirect_uri`, `scope`, `response_type`, and `state`
- Gets redirected to authentication app, and prompt `authorize` or `cancel`
- Press `cancel` button

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
