### ISSUE TITLE
Upgrading to the lastest version of Laravel (clean project) fixed my problem.

### ISSUE THREAD

**Issue by NICANDIAS** [laravel/passport#1459]
Upgrading to the lastest version of Laravel (clean project) fixed my problem. 

_Originally posted by @stepri in https://github.com/laravel/passport/issues/452#issuecomment-411418446_

**Comment by NICANDIAS** [comment]
I am using the latest version of laravel and i am still having the same issue.

**Comment by driesvints** [comment]
Please don't reopen locked issues and try a support channel instead.
