### ISSUE TITLE
Laravel Passport Use Custom Token Failed to Save

### ISSUE THREAD

**Issue by blpraveen** [laravel/passport#1460]
- Passport Version: 10.0
- Laravel Version:8
- PHP Version: 7.4
- Database Driver & Version:Mysql 8

### Description:
I am using custom Token `use MongoPassport\Mongodb\Passport\Token;`

`Passport::useTokenModel(Token::class);`

Laravel\Passport\TokenRepository

       public function save(Token $token)
       {
            $token->save();
       }

Failed when I use Custom Token

`TypeError: Argument 1 passed to Laravel\Passport\TokenRepository::save() must be an instance of Laravel\Passport\Token, instance of MongoPassport\Mongodb\Passport\Token given, called in D:\laragon_new\www\salesbot\vendor\laravel\passport\src\PersonalAccessTokenFactory.php on line 80 in file D:\laragon_new\www\salesbot\vendor\laravel\passport\src\TokenRepository.php on line 76`

### Steps To Reproduce:
Use Laravel MonogoDB Wrapper package

composer require vangaurd/mongodb-passport

And attempt to Authenticate using

        $data = [
            'email' => $request->email,
            'password' => $request->password
        ];
  
        if (auth()->attempt($data)) {
            $token = auth()->user()->createToken('PassportToken')->accessToken;
            return response()->json(['token' => $token], 200);
        } else {
            return response()->json(['error' => 'Unauthorised'], 401);
        }
My User Model

        namespace App\Models;

        use Illuminate\Contracts\Auth\MustVerifyEmail;
        use Illuminate\Database\Eloquent\Factories\HasFactory;
        use MongoPassport\Mongodb\Auth\User as Eloquent;
        use Illuminate\Foundation\Auth\Access\Authorizable;
        use Illuminate\Auth\Passwords\CanResetPassword;
        use Illuminate\Notifications\Notifiable;
        use Laravel\Passport\HasApiTokens;
        use Jenssegers\Mongodb\Eloquent\Model;
        use Maklad\Permission\Traits\HasRoles;
        use Illuminate\Auth\Authenticatable;
        use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
        use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
        use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

        class User extends Eloquent implements AuthenticatableContract,AuthorizableContract, CanResetPasswordContract
        {
            use Authenticatable, Authorizable, CanResetPassword, Authorizable, HasFactory, Notifiable, HasRoles;

**Comment by driesvints** [comment]
See my reply to your PR.

**Comment by uriel2707** [comment]
@blpraveen https://packagist.org/packages/webdecero/webdecero-package-laravel-passport
