### ISSUE TITLE
Collection of clients that are not from the model relation, when it is multi guard

### ISSUE THREAD

**Issue by FuriosoJack** [laravel/passport#1462]
- Passport Version: v10.1.3
- Laravel Version: v8.0.0
- PHP Version: 7.4.16

### Description:

When multiple guards are being used for authentication and each guard has a different model provider, the model when implementing the HasApiTokens trait, the clients reaction method is returning clients that are not from it but from the other model because it does not have the where of the provider

### Steps To Reproduce:

auth.php

```
<?php

use App\Models\Admin\UsuarioAdmin;

return [ 

    'guards' => [       
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
            'hash' => false,
        ],
        'apiAliados' => [
            'driver' => 'passport',
            'provider' => 'aliados',
            'hash' => false,
        ]       
    ],
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => UsuarioAdmin::class,
        ],
       
        'aliados' => [
            'driver' => 'eloquent',
            'model' => \App\Models\Aliados\AliadosModel::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
];
```
Database

![image](https://user-images.githubusercontent.com/26976637/124338933-3cee4380-db70-11eb-83e9-c6dc1b16cc99.png)

**Model UsuarioAdmin**

```
use Illuminate\Support\Str;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class UsuarioAdmin extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use HasApiTokens;


    protected $table = "usuario";
```

**Modelo AliadosModel**

```
<?php

namespace App\Models\Aliados;

use App\LogicaNegocio\Admin\Aliado\InfraStructure\GeneradorUrlFotoLogoAliado;
use App\Models\Clientes\InmobiliariaModel;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Laravel\Passport\Passport;

class AliadosModel extends Authenticatable
{
    use SoftDeletes, HasApiTokens, Notifiable;
   protected $table = "aliados";
```

If the query is executed

```
//this user has the id 1
$model = \App\Models\Aliados\AliadosModel::first(); 

$clients = $model->clients

```
In the variable $clients there are also all the clients with user_id 1 that will be returned by clients that are from other providers and from other models but with the same user_id.

And the problem apparently lies in how they are obtained in the trait hasapitokens

```
<?php

namespace Laravel\Passport;

use Illuminate\Container\Container;

trait HasApiTokens
{
    /**
     * The current access token for the authentication user.
     *
     * @var \Laravel\Passport\Token
     */
    protected $accessToken;

    /**
     * Get all of the user's registered OAuth clients.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function clients()
    {
        return $this->hasMany(Passport::clientModel(), 'user_id');
    }
```

**Comment by driesvints** [comment]
Multi guard only works with the password grant client:

https://laravel.com/docs/8.x/passport#multiple-authentication-guards

![Screen Shot 2021-07-03 at 13 54 00](https://user-images.githubusercontent.com/594614/124353329-21357c80-dc06-11eb-93d6-1d765aa1347e.jpg)

**Comment by FuriosoJack** [comment]
> Multi guard only works with the password grant client:
> 
> https://laravel.com/docs/8.x/passport#multiple-authentication-guards
> 
> ![Screen Shot 2021-07-03 at 13 54 00](https://user-images.githubusercontent.com/594614/124353329-21357c80-dc06-11eb-93d6-1d765aa1347e.jpg)

Thanks for the answer, indeed I know that in version 10 this functionality is present. But what I report is that the model to which the hasApiToken trait is implemented when the clients relation is called, is returning all the clients including those that are not of that model because it is not filtering by provider

**Comment by driesvints** [comment]
I'm sorry but I don't really see any bug. If you're willing, feel free to send in a PR with a fix you're proposing.

**Comment by waney** [comment]
me too...
