### ISSUE TITLE
Not support with mongodb

### ISSUE THREAD

**Issue by himanshutecstub** [laravel/passport#1467]
Hello,

I am try to install laravel password with mongodb database using lumen-8.
It's working fine with mysql database but when i change to mongodb than shown error as 
`In Connection.php line 479: 
Call to a member function prepare() on null `

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
