### ISSUE TITLE
Is Passport compatible with web + api at the same time ?

### ISSUE THREAD

**Issue by SwiTool** [laravel/passport#147]
I'm providing an API for my clients so they can have acess to the same functionnalities as my website does.

While logging, do I need to generate an access token for my website and use it for every requests (and how if it's not by a cookie)?
Or can I directly use protected - oauth middlewared - resources ?

My fatal question to this is : 

> Do I need to make an API controller and a Web controller, if they basically do the same thing but the authorization process?

**Comment by nikkuang** [comment]
this might help [https://laravel.com/docs/5.3/passport#consuming-your-api-with-javascript](url)

**Comment by Rkallenkoot** [comment]
You don't need separate controllers, you can consume your API via the 'web' guard as well after adding the follow middleware:
```
'web' => [
    // Other middleware...
    \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
],
```
Your clients however, do need an Access Token to access your API. You can use the Password Grant Client or generate a personal access token for every client if you don't want them to go through the procedure of generating an access token.

This is also explained [in the link posted by](https://laravel.com/docs/5.3/passport#consuming-your-api-with-javascript) @nikkuang.

Does this answer your question?

**Comment by SwiTool** [comment]
Completely. Thank you @Rkallenkoot

**Comment by DelphiWorlds** [comment]
Not sure if I misunderstand the answer, or whether my situation is different. 

Consider a Laravel app started from scratch, and Passport is installed. When the home page (accessed via a web route) is shown, I want the home link to show only if the user has authenticated with Passport, and the Login/Register links to show only if they're not authenticated via Passport.

Actually, I'd like to be able to show/not show other links based on the Passport authenticated user, but home and login/register would be a good start :-)
