### ISSUE TITLE
can't use costume Token

### ISSUE THREAD

**Issue by brahimrizqHireme** [laravel/passport#1471]
- Passport Version: ^10.1
- Laravel Version: ^8.40
- PHP Version: 7.4
- Database Driver & Version: mongodb-1.9.0

### Description:
can't use custom Token model class from auth service provider. Currently, I am having this issue. i
i think the type hint of the method save preventing other costume classes to override `Laravel\Passport\Token`  

### Steps To Reproduce:
i tried to override it in `AuthServiceProvider` 

`Passport::useTokenModel(\App\Models\CostumeToken::class)`

got this error
***
`` Argument 1 passed to Laravel\\Passport\\TokenRepository::save() must be an instance of Laravel\\Passport\\Token, instance of MongoPassport\\Mongodb\\Passport\\Token given, called in /var/www/vendor/laravel/passport/src/PersonalAccessTokenFactory.php on line 81,``

**Comment by driesvints** [comment]
We don't support mongo db.

**Comment by uriel2707** [comment]
@brahimrizqHireme  https://packagist.org/packages/webdecero/webdecero-package-laravel-passport
