### ISSUE TITLE
A more flexible tokensCan

### ISSUE THREAD

**Issue by Wiruu** [laravel/passport#1472]
I've been going around in circles for a while now thinking of ways to write permissions for single model entries and I'm kind of limited/confused by the TokensCan() method in the boot section since I wanted my scopes to be formatted in a "model:{id}:ability" type way, and that would mean that the array that populates the passport scopes variable depends on the Permissions table and thus I would have to query the permissions table on the boot method of the AuthServiceProvider... Now that just seems wrong to me, but maybe Im wrong. Then I though of writing a php file that holds an array with all the permissions and its re-written constantly, triggered by events of user's giving other user's permissions to access stuff but that just seems like a very long misplaced file with a lot of sensitive data.
So im kind of lost, I really wish it were as simple as writing 
```
Passport::tokensCan([
...,
'articles:*:update',
...,
])
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Wiruu** [comment]
@driesvints hello, 

I'm sorry I'm kind of new to git and wanted to request if this could be a feature... but then I kinda suspected all I needed was to come up with a custom solution, which in turn I did not manage to come up with until now.

it is still in the rough but it is getting me where I want to be, I still have a question though and while I'm at it if you could help me I would be for ever grateful;

I ended up modifying the Passport::hasScope() method, since this failing is what triggered the error, but I modified it in the vendors folder directly. I know it's a noob question but where could I re write the hasScope method without touching the original package... thank you very much

**Comment by Wiruu** [comment]
@driesvints hello there,

yes I figured out it was more of a custom problem/custom solution type thing... only thing is, I ended up changing the Passport::hasScope() method and I really can't figure out how to re-write it within my app, had to re-write the package vendor's code and to my understanding that is not recommended since it will erase on update... 

I have been reading about forking the project and modifying my composer.json file, but I'm a total noob on git (and coding per se); so If you'd know any other way? I would be for ever thankful.

have a nice day...
