### ISSUE TITLE
Type of Laravel\Passport\Client::$hidden must be array (as in class Illuminate\Database\Eloquent\Model)

### ISSUE THREAD

**Issue by illia-code-care** [laravel/passport#1473]
- Passport Version: 10.1.0
- Laravel Version: 8.4.0
- PHP Version: 7.4
- Database Driver & Version: 8

### Description:

When you try to make "php artisan passport:install" you get the error "Type of Laravel\Passport\Client::$hidden must be array (as in class Illuminate\Database\Eloquent\Model)". This only happens with php 7.4 >.
Solutions:
1. Downgrade php version to 7.3.
OR
1. Go to vendor/passport/src/Client.php. Add "array" type before $hidden on 33 line.

### Steps To Reproduce:

1. Install all of the requirements.
2. Make "composer require laravel/passport".
3. Run "php artisan migrate".
4. Finally run "php artisan passport:install".

**Comment by driesvints** [comment]
I managed to run this just fine on PHP 7.4:

![Screen Shot 2021-08-10 at 09 24 22](https://user-images.githubusercontent.com/594614/128825590-1e7ceef4-14cf-473e-bb01-d450c5c50c66.jpg)

**Comment by illia-code-care** [comment]
@driesvints Did you installed versions of the requirements?

**Comment by driesvints** [comment]
I used the latest Laravel version.

**Comment by illia-code-care** [comment]
@driesvints Thanks a lot. Yes, it can be easily installed with php7.4 >. But if you will switch in PHPStorm PHP language to 7.4 for example, you will see an error in vendor/laravel/passport/src/Client.php on 33 lines. Here is a predefined array type in trait HideAttributes. But here on the 33 lines, there is no type. That's why it throws a fatal errors.

**Comment by ludo237** [comment]
@illia-code-care did you manage to solve this aside from the ones that you have suggested? Apparently this is still an issue on a Docker environment running the latest version of Laravel and PHP 8.0.

Same issue with Token model and every other models

**Comment by driesvints** [comment]
@ludo237 this isn't a support channel. Please try a forum like Laravel.io or laracasts or discord.
