### ISSUE TITLE
What happens to the access token in the multiple auth of Laravel passport

### ISSUE THREAD

**Issue by thecoma8x** [laravel/passport#1474]
` "name": "laravel/passport",
"version": "v10.1.3",`

Configure the auth.php config file as below:
```

    'guards'    => [
        'web'   => [
            'driver'   => 'session',
            'provider' => 'users',
        ],
        'admin' => [
            'driver'   => 'session',
            'provider' => 'admins',
        ],

        'api'   => [
            'driver'   => 'passport',
            'provider' => 'users',
        ],
        'admin-api'   => [
            'driver'   => 'passport',
            'provider' => 'admins',
        ],
    ],
```
I successfully generate access_token for both user and admin.

However, if I get the user's access_token to access the api admin route (`'middleware' => 'auth:admin-api'`), it succeeds. 
The information received by request()->user() is the admin account with the same id as the user.
Same thing happens when I use admin token for user access and api.

**Note:**

This scenario only happens when admin and user have the same ID value.

What is going on, or did I do something wrong?
I guess the scenario that happened was as follows:

**Step 1:** user's access_token passes `'middleware' => 'auth:admin-api'`.

**Step 2:** The oauth_access_tokens.user_id value is returned

**Step 3:** From user_id will return the corresponding admin.

So it happens only when user.id and admin.id are same.

Help me clarify this issue. Thanks

If i want to prevent this, what should I do?
Obviously users shouldn't access the admin account-only api

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
