### ISSUE TITLE
Refresh tokens becoming invalid if the user closes the tab and navigates to it again

### ISSUE THREAD

**Issue by reisnobre** [laravel/passport#1475]
- Passport Version: 10.1.0
- Laravel Version: 8.54.0
- PHP Version: 7.3.29
- Database Driver & Version: mysql  Ver 8.0.23 for osx10.15 on x86_64 (Homebrew)

### Description:

On chrome, I can use my refresh token indefinitely as the documentation says, but if I close the tab open a new one and navigate to the page of the project, the refresh_token becomes invalid and expired. 

Is this an intended behaviour or something like this?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by reisnobre** [comment]
Thank you and sorry for the inconvenience. I tried gitter and no one answered there, I'll try slack 😄
