### ISSUE TITLE
error on $this->issueToken after upgrade of Laravel/Passport

### ISSUE THREAD

**Issue by nicolasvahidzein** [laravel/passport#1476]
Hello,

Because of the linked lcobucci/jwt package i now get with version 7.5 of passport an error on login attemps:

Replicating claims as headers is deprecated and will removed from v4.0. Please manually set the header if you need it replicated. {"exception":"[object] (ErrorException(code: 0): Replicating claims as headers is deprecated and will removed from v4.0. Please manually set the header if you need it replicated.

How can i fix this please?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
