### ISSUE TITLE
Passport auth in queue jobs

### ISSUE THREAD

**Issue by albertovincenzi** [laravel/passport#1477]
Hello,
we are facing an issue and seems no one thought about that.
If you implemented queued jobs in your laravel app, you might want, during the execution of that jobs, to have some behavior dependent on the auth user that dispatched the job.

Currently, it's not possible to do that so you have a completely different behavior if your jobs run on queue or "sync".

The only possibility we found is using `actingAs` method but it's provided by a testing library so I suppose its better to not use that.

Some might say that queued jobs must be agnostic to authenticated users: I found out that its not true.

Then, the idea might be to provide a method within passport library that works the same way as `actingAs` method. What do you think?

**Comment by driesvints** [comment]
> Some might say that queued jobs must be agnostic to authenticated users: I found out that its not true.

I think the above is true. Queued jobs are stateless and therefor no authenticated state for a user is available. You'll have to find a different solution, sorry.

**Comment by albertovincenzi** [comment]
Hi @driesvints and thanks for your precious time.
I would be happy to agree with you that jobs are stateless but I figured out that once the applications start to be more "structured" its not true: consider that to comply to DRY principle, you use the service layer to call a method which is invoked from many other places. Normally, you might have many logic depending to logged user (especially if you use custom validators instead of custom requests). Moreover, global model scopes are most of time dependant to logged user.

So I would say: in simple applications, job can be stateless due to simple logic but as far as things gets more complicated, 90% of the times, this is not true.

Maybe I can share the solution we found and you can have a look:

```
<?php

namespace Api\Jobs;

use Api\Http\Middleware\ApiData;
use Api\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Support\Facades\Auth;
use Laravel\Passport\Token;

/**
 * Class BaseApiJobQueue
 * @package Api\Jobs
 */
abstract class BaseApiJobQueue extends BaseApiJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * @var User|null
     */
    protected $authUser;

    /**
     * @var Token
     */
    protected $authUserToken;

    /**
     * BaseApiJobQueue constructor.
     * @param array $data
     */
    public function __construct(array $data)
    {
        $this->checkAuth();

        parent::__construct($data);
    }

    /**
     * @return array
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    public function middleware(): array
    {
        if ($this->isAuth()) {
            $this->authenticate();
        }

        return [
            app()->make(ApiData::class)
        ];
    }

    /**
     * @return bool
     */
    protected function isAuth(): bool
    {
        return !!$this->authUser;
    }

    /**
     *
     */
    protected function checkAuth()
    {
        $this->authUser = Auth::user();

        if ($this->isAuth()) {
            $this->authUserToken = $this->authUser->token();
        }
    }

    /**
     *
     */
    protected function authenticate()
    {
        $this->authUser->withAccessToken($this->authUserToken);

        if (isset($this->authUser->wasRecentlyCreated) && $this->authUser->wasRecentlyCreated) {
            $this->authUser->wasRecentlyCreated = false;
        }

        app('auth')->guard('api')->setUser($this->authUser);
        app('auth')->shouldUse('api');
    }
}

```

If I'm right, the queue job will be executed in the same way of a non-queue job.
