### ISSUE TITLE
Why Remove personalAccessClientId,Some scenes need it

### ISSUE THREAD

**Issue by tomiaa1926** [laravel/passport#1478]
Now i need to specify different personalClientId for Createtoken of user
```php
    public function createToken($name, array $scopes = [])
    {
        return Container::getInstance()->make(PersonalAccessTokenFactory::class)->make(
            $this->getKey(), $name, $scopes
        );
    }
```
But it has been injected into the container,
```php
    public function createToken($name, array $scopes = [])
    {
        $clients = new ClientRepository('9466f475-de2d-47fc-9f14-ec8c1fed7f8d');
        $pr = Container::getInstance()->make(PersonalAccessTokenFactory::class);
        $refObject = new \ReflectionObject($pr);
        $refProperty = $refObject->getProperty( 'clients' );
        $refProperty->setAccessible( true );
        $refProperty->setValue($pr, $clients);
        return $pr->make(
        $this->getKey(), $name, $scopes
        );
    }
```
What should I do like this

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
