### ISSUE TITLE
Passport not longer work on laravel 8

### ISSUE THREAD

**Issue by razavistag** [laravel/passport#1479]
- Passport Version: ^10.1
- Laravel Version: #.#.#
- PHP Version: "^7.3|^8.0",
- Database Driver & Version:

### Steps To Reproduce:

I have working with laravel passport for many years but on laravel 8 I am facing a new issue which is `Unauthenticated`. when login with the correct credentials its bring me the `access_token`, `expires_time`, and necessary information but when I try to access other API using the access token it brings me the 401 status with `Unauthenticated` message

**Comment by tomekpryjma** [comment]
@razavistag Sounds like an issue I was having recently. If you haven't already, try putting in `auth:api` into `api` in the `$middlewareGroups` variable inside `app/Http/Kernel.php`.

**Comment by razavistag** [comment]
changing auth:api in kernal as follows brings the error 

` "message": "Target class [api] does not exist.",`, 
` "exception": "Illuminate\\Contracts\\Container\\BindingResolutionException",`

```
protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'auth:api' => [
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

when I changed the ` 'throttle:api',` into `auth:api` i got the same issue 401

```
'api' => [
            'auth:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
```

@tomekpryjma how did you solved it?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by chyeteck** [comment]
In RouteServiceProvider file,
check that boot method the api is called before web.
/**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::prefix('api')
                ->middleware('api')
                ->namespace($this->namespace)
                ->group(base_path('routes/api.php'));

            Route::middleware('web')
                ->namespace($this->namespace)
                ->group(base_path('routes/web.php'));
        });
    }
