### ISSUE TITLE
Call to a member function getAuthIdentifier() on null

### ISSUE THREAD

**Issue by J-Brk** [laravel/passport#1482]
- Passport Version: 10.1.3
- Laravel Version: 8.33.1
- PHP Version: 8
- Database Driver & Version:

### Description:
Authorize URL returns fatal exception
`Call to a member function getAuthIdentifier() on null {"exception":"[object] (Error(code: 0): Call to a member function getAuthIdentifier() on null at /vendor/laravel/passport/src/TokenRepository.php:117)`

### Steps To Reproduce:
I haven't tried to reproduce it in a fresh environment. My installation has 2 auth providers; where only one is used in combination with Laravel passport
2. I followed the installation procedure as documented

https://github.com/laravel/passport/blob/0ee9586e72d87b78e4e43c53a62f189373e6ac79/src/Http/Controllers/AuthorizationController.php#L67-L70

`$request->user()` is returning null resulting in the issue.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
