### ISSUE TITLE
Generated token is not verified by earlier version in a short duration (~ 1 second)

### ISSUE THREAD

**Issue by mojtabaahn** [laravel/passport#1493]
- Provider Passport Version: 10.1.3
- Provider **Laravel** Version: 8.67.0
- Provider PHP Version: 8.1
- Consumer Passport Version: 7.5.1
- Consumer **Laravel** Version: 5.8.38
- Consumer PHP Version: 7.4
- Database Driver & Version: Postgre

### Description:
Hi, We're using a Laravel micro-service for managing our authentication logic (token provider), and using its tokens in another Laravel 5.8 app for authentication (token consumer)  and both apps are connected to same database.

It turned out tokens generated by provider service are not authorized in consumer app just in first second after generation but if we put a delay around 1 second they will be authorized. we also tested tokens in provider project and all generated tokens work well and get authorized with no delay.

This problem is really wired and we have no clue to where and what to search for. would love to hear your thoughts.

**Comment by driesvints** [comment]
If you need to use Passport please consider switching to Laravel.

**Comment by mojtabaahn** [comment]
@trevorgehman  No we're not using replication.

It turnes out it's a problem with versions of passport. When we updated our consumer service passport to higher version (v7) the problem completely disappeared!

Thanks anyways
