### ISSUE TITLE
Pass custom data in JWT payload along with `sub`

### ISSUE THREAD

**Issue by aagjalpankaj** [laravel/passport#1502]
Provision to pass custom data in JWT payload along with `sub` and `scopes`.
e.g.
```
{
  "aud": "9420abb1-1470-4895-8666-a702b415cb59",
  "jti": "1dd56723fa5ac4421ebb7cb9a0222686f368de22760d9ac7038b8a3a696ac12069b84e2434ea9d75",
  "iat": 1635772661.715073,
  "nbf": 1635772661.71508,
  "exp": 1635774461.676158,
  "sub": "8707e4a1-a920-40dc-a472-b71b62343dca",
  "user_id": 123,
  "sites": { "78": 1, "60": 3 }
  "scopes": []
}
```

In the above payload "user_id" & "sites" is the custom data. How to pass such custom data in laravel/passport? We can do this in "tymon/jwt-auth" - https://medium.com/geekculture/restrict-jwt-token-with-ip-address-using-laravel-77ce5ae3671a

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
