### ISSUE TITLE
PHP 8 support added in 9.4.0 breaks support for lower versions

### ISSUE THREAD

**Issue by satyago** [laravel/passport#1503]
- Passport Version: 9.4.0
- Laravel Version: 7.30.4
- PHP Version: 7.4
- Database Driver & Version: N/A

### Description:

The dependency `lcobucci/jwt` requires `lcobucci/clock` which in turn has a minimum dependency of php `^8.0`.
Adding support for PHP 8 therefore drops support for older versions, which IMHO should not happen on a minor version update.

### Steps To Reproduce:

Require Laravel Passport 9.4.0 in a PHP 7.4 environment.

**Comment by driesvints** [comment]
Lock in older versions if you need this. We can't control what third party libraries do. In general we recommend you to upgrade to the latest Passport version.

**Comment by satyago** [comment]
@driesvints I agree on that statement, however it should concern you, which is why I reported it here.
You need to go as far back as `7.*` with Passport to get a working release, since this is breaking with `league/oauth2-server` in version `8.*` and only `7.*` is still safe to use.

I'm not sure who to go to at this moment, to be fully transparent, as upgrading currently is not an option for us.

**Comment by driesvints** [comment]
@satyago we can't help you with that I'm afraid. Please upgrade to the latest Passport release.

**Comment by satyago** [comment]
Sure. Referencing the issue on the package causing this https://github.com/lcobucci/clock/issues/400, for anyone else looking at this.

**Comment by itofficeeu** [comment]
Web systems and sites often have dependencies to other software. Especially the big (important).There are a ton of reasons to be backward compatible. Ignoring these factual reasons, will hinder the adoption of newer versions. Hence making new versions of Passport and Laravel not usable (for bigger sites). - I have the above challenge too in PHP 7.4. Other requirements - in our case Ioncube not having provided support for PHP 8 yet, and will not do it until end 2022 - hinder an update to PHP 8.0. - I am very okey to ignoring that many companies still run PHP 5.6. They must update of quite obvious reasons. But not supporting something like PHP 7.4 in Passport?... Well, that is your choice.
