### ISSUE TITLE
I think I met something similar

### ISSUE THREAD

**Issue by liuxingyuxia** [laravel/passport#1504]
I think I met something similar

I dynamically switch the database

Trying to get user information prompts me to get user information

Is it settled now

Please forgive me for using translation software to translate the text

_Originally posted by @liuxingyuxia in https://github.com/laravel/passport/issues/1487#issuecomment-962464243_

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
