### ISSUE TITLE
Unable to determine authentication model from configuration when using custom user provider

### ISSUE THREAD

**Issue by ArondeParon** [laravel/passport#1505]
- Passport Version: 10.2.0
- Laravel Version: 8.68.1
- PHP Version: 8.0.12

### Description:

When looking at the [documentation](https://laravel.com/docs/8.x/passport#customizing-the-user-provider), I am under the assumption that I should be able to create a custom user provider as documented [here](https://laravel.com/docs/8.x/authentication#adding-custom-user-providers), but when calling my `/oauth/token` endpoint, I receive the following error:

> Unable to determine authentication model from configuration.

I have the feeling that I am most likely overlooking something obvious, but cannot figure out what it is.

### My use case

My back-end should give auth access tokens to a SPA (using the password grant). My back-end should _also_ validate incoming authentication requests with another third party service that is responsible for storing the original user information. I figured implementing a custom user provider would be the way to go, since it would allow me to check the third-party back-end transparently.

It seems like the `PasswordGrant` is calling the `UserRepository` which requires the existence of a `auth.providers.[provider].model`, but in this case, I do not need it right away.

Am I missing something?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
