### ISSUE TITLE
Ability to set a cookie domain different than the sessions.

### ISSUE THREAD

**Issue by ctadlock** [laravel/passport#1506]
Here is the setup; two websites:
* Admin: `admin.domain.com`
* API: `api.domain.com`

Admin has standard web login , API is Passport OAuth; both Admin and external apps use the API.

I would like for the `session` and `XSRF-TOKEN` cookies to be only for admin (admin.domain.com) and the Passport token `laravel_token` to also work for the API, which means setting a domain of `.domain.com`.

Right now `ApiTokenCookieFactory` gets the domain from the session config:

![image](https://user-images.githubusercontent.com/1539397/142975825-d274dfa0-74a6-4427-b492-31df29310a57.png)

To work around this I overrode `ApiTokenCookieFactory`'s `make` to get the domain from a separate config/env.

![image](https://user-images.githubusercontent.com/1539397/142975906-1f885219-e4ad-4b5a-9ac5-301c9cd18ef8.png)

This works fine but seems better to just include as a part of this package.

**Comment by driesvints** [comment]
The `laravel_token` is only then you consume your api inside your app, not if you're placing it on a separate domain. If you need a token based API that's separate from your app then we recommend using Sanctum.

**Comment by ctadlock** [comment]
I need passport because other 3rd party apps need oauth. Why would i implement both?

**Comment by driesvints** [comment]
Because the part here: https://laravel.com/docs/8.x/passport#consuming-your-api-with-javascript is only meant as a very basic way to consume your API on the same app/domain.

**Comment by ctadlock** [comment]
The above code work fine. Its similar to setting the session cookie's domain to `.domain.com`. This is just constraining the scope even further than that. Is there a security issue? I don't see the objection other than "this isn't how we thought it would work when we designed it".

So if not this design, then what is the recommended design for this situation (which seems very common). To use both Passport and Sanctum? How exactly would that work?

**Comment by driesvints** [comment]
It was indeed not our intention to be used that way. 

> To use both Passport and Sanctum? How exactly would that work?

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
