### ISSUE TITLE
Allow to use multiple clients to generate personal tokens

### ISSUE THREAD

**Issue by gabrielpeixoto** [laravel/passport#1507]
In my project, I use 2 clients to generate personal tokens. I was able to set at runtime which token I would use in a specific route.

After the removal of the personalAccessClientId method, I couldn't do it anymore

Example:
```php
$user = User::find(1);

Passport::personalAccessClientId(3);
$token = $user->createToken('Token Name')->accessToken;
```

How can I work around this issue after this change?

**Comment by driesvints** [comment]
It was never expected that multiple personal access clients were available in a single app. Therefor we cannot offer support for this, sorry.

**Comment by driesvints** [comment]
Btw, from the looks of it, you'd much more benefit from a package like Sanctum. Personal access tokens in Passport are only very basic while Sanctum offers a much more modern approach.

**Comment by gabrielpeixoto** [comment]
Ok! Thanks @driesvints !
