### ISSUE TITLE
Possible Password Grant Bug: user_id won't store in database when a issuing access/refresh Token

### ISSUE THREAD

**Issue by dreferreira** [laravel/passport#151]
**Notice:**
I've done some fairly decent debugging so far so please be understanding that this is a VERY long post but fairly detailed as to what I've done and where I've been. ANY and ALL guidance is extremely appreciated on this as I've been at this for a week now. Yet, I'm not sure if this is by design or if there's a legitimate bug.

**Description:**
As the title suggests, I'm having some serious difficulty with storing the user_id in the database when the Password Grant type is put to use. I do not want to make a secondary query to the database just to store the user_id because the passport system doesn't seem to recognize the user as being authenticated. At the same time that would just add unnecessary code to the structure. 

**Setup:**
- In my console I performed:

`php artisan passport:client --password`

- Gave the Client a name:

`Password Grant Client`

**database result:**

![the_client](https://cloud.githubusercontent.com/assets/7734800/19564604/1da88c72-96b2-11e6-9511-2f312ea4f75d.PNG)

- Then in the docs it mentions making this request:

```
$response = $http->post('http://your-app.com/oauth/token', [
    'form_params' => [
        'grant_type' => 'password',
        'client_id' => 'client-id',
        'client_secret' => 'client-secret',
        'username' => 'taylor@laravel.com',
        'password' => 'my-password',
        'scope' => '',
    ],
]);

return json_decode((string) $response->getBody(), true);
```

- Currently I'm making the **same** request with the following body:
```
'grant_type' => $data['grant_type'],
'client_id' => $data['client_id'],
'client_secret' => $data['client_secret'],
'username' => $credentials['email'],
'password' => $credentials['password'],
'scope' => null,
'user_id' => $user['acct_id'], <---Trying to pass in the user_id so it will store in the database 
```

- Which results in this for an access token:
**Database resulting access token record**
![access_token](https://cloud.githubusercontent.com/assets/7734800/19564633/36cd1506-96b2-11e6-969b-a1155f252dc6.PNG)

When I try to make a get request to 'api/user' to get the authenticated user as follows: 

![request](https://cloud.githubusercontent.com/assets/7734800/19565698/cf5a629e-96b5-11e6-8683-0ce2d9d07332.PNG)

I get an Unauthorized error. I've tried nearly every fix/adjustment on multiple resources from github to stackoverflow to stackexchange to laracast community even to Windows upgrading php from 32bit to 64bit and nothing worked. (**Yes I've set the expiration date and modified P100Y**). I was left with no choice but to dive into the vendor. 

**Diving in the rabbit hole for 'Issuing an access token':**
I did some investigation into this specific situation and have found that inside of the **BearerTokenValidator.php** file, line 73: 

```
return $request
                ->withAttribute('oauth_access_token_id', $token->getClaim('jti'))
                ->withAttribute('oauth_client_id', $token->getClaim('aud'))
                ->withAttribute('oauth_user_id', $token->getClaim('sub')) <-- Line 73 Located HERE
                ->withAttribute('oauth_scopes', $token->getClaim('scopes'));
```

That noted line is not getting the 'sub' (subject) claim. This claim, from what I see, is suppose to be the userIdentifier. Either the Id or the email or something to identify the user which is used to store in the database at some point and also help associate the user to this access token. I'm trying to locate where the claim is set and maybe see if I can come up with a proper way of adding it into the request body.

**Rabbit hole of Authenticate Via Bearer Token??????**
Here I went into the laravel\passport\src\Guards\TokenGuard.php class and dd()'d the contents of the "psr" variable as seen below:

![ddpsr](https://cloud.githubusercontent.com/assets/7734800/19565609/6662c8b2-96b5-11e6-83e1-8c4a94f27e89.PNG)

I obtained this by going to line 110 and dd()'d the following:

```
$psr = (new DiactorosFactory)->createRequest($request);

        try {
            $psr = $this->server->validateAuthenticatedRequest($psr);
            
            //dd($psr); <--- Results are in the above image

            // If the access token is valid we will retrieve the user according to the user ID
            // associated with the token. We will use the provider implementation which may
            // be used to retrieve users from Eloquent. Next, we'll be ready to continue.
            $user = $this->provider->retrieveById(
                $psr->getAttribute('oauth_user_id')
            );
            dd($user); <------Returns Null
```

**Diving down the rabbit hole of 'Is this user authorized?'**
Keep in mind this is for the Password Grant type. Looking into this matter I've come across some possible issue. The system attempts to check if the user is authenticated, or authorized, with this token by cross referencing the client with the credentials passed in, noted in the following code:

**League\OAuth2\Server\Grant\PasswordGrant.php**

```
$user = $this->userRepository->getUserEntityByUserCredentials(
            $username,
            $password,
            $this->getIdentifier(),
            $client
        );
//dd($user); < ------ Returns NULL!
```
When I dd() the $user variable, the result is 'null'. 
However, looking into the construct of this class, the '$this->userRepository' ALSO returns null if I try to dd() it's contents as noted below:

**League\OAuth2\Server\Grant\PasswordGrant.php**

```
 public function __construct(
        UserRepositoryInterface $userRepository,
        RefreshTokenRepositoryInterface $refreshTokenRepository
    ) {
        $this->setUserRepository($userRepository);
        $this->setRefreshTokenRepository($refreshTokenRepository);
        //
        //dd($this->setUserRepository($userRepository)); <---------------- Returns NULL!
        //
        $this->refreshTokenTTL = new \DateInterval('P1M');
    }
```

However this issue was resolved when I went into the **League\oauth2-server\src\Grant\AbstractGrant.php** class and went to line 121 to found the setUserRepository function and simply returned it's contents just to see what happened:

```
/**
     * @param UserRepositoryInterface $userRepository
     */
    public function setUserRepository(UserRepositoryInterface $userRepository)
    {
        $this->userRepository = $userRepository;
        return $this->userRepository; <--Added this in and it began to return what was missing.
    }
```

**Questions: @taylorotwell  **
How do I properly pass in the user_id to store it in the database?
How do I get the passport system to recognize that the user is authenticated with this access token through the password grant type?

**Comment by dreferreira** [comment]
#81

**Comment by themsaid** [comment]
> How do I properly pass in the user_id to store it in the database?

It gets stored for you, you only need to provide a username and a password. I couldn't replicate your issue, issuing an access token using the Password grant results a `user_id` to be saved in the DB, all the other issues are related to the fact that user_id is null at your end.

Is it a fresh laravel 5.3 installation? can you please share your user model class?

**Comment by dreferreira** [comment]
Firstly, thank you for your response.
It is a fresh laravel 5.3.15 installation. My user model class has been shared below.
So, last night I discovered what was causing the issue. In my case my primary id for the user's table/model is not "id" or "user_id". It's "acct_id". Please see below:

Below is an image of some of the structure within my user's table
**Database User's Table:**
![databasetable](https://cloud.githubusercontent.com/assets/7734800/19602201/4fed77ec-977a-11e6-8163-94d8b3df2c97.PNG)

Below is a snippet of my User Model Class
**User Model:**
```
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The primary connection for the model.
     * @var [string]
     */
    protected $connection = 'tipr_core';

    /**
     * [$table preset the access table ]
     * @var string
     */
    protected $table = "dim_acct_user";

    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'acct_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fname', 'lname' , 'email', 'password', 'password_confirmation','age'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'password_confirmation' ,'remember_token',
    ];
}
```

Below is where I found the issue:
**Vendor\Laravel\passport\src\Bridge\UserRepository.php**
![internalcode](https://cloud.githubusercontent.com/assets/7734800/19602312/cd9f4558-977a-11e6-9293-a1cf1ace3660.PNG)


Inside of the above code I noticed where it gets the user model and assigns the user model's id to a new instance of a UserEntity. This entity is then checked to see if what's returned is an instance of the UserEntityInterface. However, when a user is returned the primary id field's name is "acct_id" and not "id". So when a User Instance is returned, it will return null since there is no field in either the model or database with a title of "id". So, illustrated above, I modified it to say:

`return new User($user->acct_id);` 

**Followup question:**
Is there a proper way of keeping the code as is where:

`return new User($user->id);`

will seek out the primary id field of the user model instead of trying to default to looking for a field of just "id"??? 
OR
Is there already a way to do that and I just missed it somewhere along the way???

**Comment by themsaid** [comment]
I think your version of Passport is very old, please upgrade to `v1.0.8 ` and your problem will vanish :)

**Comment by dreferreira** [comment]
I will do that right now and close this issue as soon as it's concluded.
