### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present when getting access token

### ISSUE THREAD

**Issue by marvinhosea** [laravel/passport#1510]
- Passport Version: 10.2
- Laravel Version: 8.74
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Access to XMLHttpRequest at 'http://demo12.test/oauth/token' from origin 'http://app.demo12.test' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource when trying to get token access from Reactjs app.

### Steps To Reproduce:
Implement passport as per Laravel guide, 
add 'oauth/*' to ``` paths=['oauth/*']``` on cors config

Passport path ``` Passport::routes(null, ['middleware' => [\Fruitcake\Cors\HandleCors::class]]); ```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
