### ISSUE TITLE
Conclusion: remove laravel/framework v6.20.43

### ISSUE THREAD

**Issue by suhasini-smy** [laravel/passport#1514]
- Passport Version: #.#.#
- Laravel Version: 6.0
- PHP Version: 7.4.26
- Database Driver & Version:5.6

### Description:
 Problem 1
    - Conclusion: remove laravel/framework v6.20.43
    - Conclusion: don't install laravel/framework v6.20.43
    - Conclusion: don't install laravel/framework v6.20.42
    - Conclusion: don't install laravel/framework v6.20.41
    - Conclusion: don't install laravel/framework v6.20.40
    - Conclusion: don't install laravel/framework v6.20.39
    - Conclusion: don't install laravel/framework v6.20.38
    - Conclusion: don't install laravel/framework v6.20.37
    - Conclusion: don't install laravel/framework v6.20.36
    - Conclusion: don't install laravel/framework v6.20.35
    - Conclusion: don't install laravel/framework v6.20.34
    - Conclusion: don't install laravel/framework v6.20.33
    - Conclusion: don't install laravel/framework v6.20.32
    - Conclusion: don't install laravel/framework v6.20.31
    - Conclusion: don't install laravel/framework v6.20.30
    - Conclusion: don't install laravel/framework v6.20.29
    - Conclusion: don't install laravel/framework v6.20.28
    - Conclusion: don't install laravel/framework v6.20.27
    - Conclusion: don't install laravel/framework v6.20.26
    - Conclusion: don't install laravel/framework v6.20.25
    - Conclusion: don't install laravel/framework v6.20.24
    - Conclusion: don't install laravel/framework v6.20.23
    - Conclusion: don't install laravel/framework v6.20.22
    - Conclusion: don't install laravel/framework v6.20.21
    - Conclusion: don't install laravel/framework v6.20.20
    - Conclusion: don't install laravel/framework v6.20.19
    - Conclusion: don't install laravel/framework v6.20.18
    - Conclusion: don't install laravel/framework v6.20.17
    - Conclusion: don't install laravel/framework v6.20.16
    - Conclusion: don't install laravel/framework v6.20.15
    - Conclusion: don't install laravel/framework v6.20.14
    - Conclusion: don't install laravel/framework v6.20.13
    - Conclusion: don't install laravel/framework v6.20.12

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by suhasini-smy** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.
