### ISSUE TITLE
Error  error:04088003:rsa routines:RSA_setup_blinding:BN lib when trying to login LARAVEL 6.14 php 7.3.2

### ISSUE THREAD

**Issue by vitorhugosg** [laravel/passport#1524]
- Passport Version: 7.4
- Laravel Version: v6.14.0
- PHP Version: 7.3.2
- Database Driver & Version: 5.7.28-0ubuntu0.16.04.2

### Description:

Hello, all right, I have a system that works well for a long time, but from yesterday to today without any existing update, it started to return this message:

exception: "InvalidArgumentException"
file: "/home/admin/web/admin.levantelab.com.br/public_html/vendor/lcobucci/jwt/src/Signer/OpenSSL.php"
line: 27
message: "There was an error while creating the signature: error:04088003:rsa routines:RSA_setup_blinding:BN lib"
trace: [{,…},…]

![image](https://user-images.githubusercontent.com/17458174/151560548-794367e8-d1ce-4853-8a44-faa48f6e22fc.png)

It is giving this error, when I try to login to the platform. Has anyone gone through something similar?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
