### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by mxsxs2** [laravel/passport#1527]
Every time a request is sent to our API a user needs to be authenticated from the token. This causes 2-3 database calls on every single request.

It would be nice if we would be able to optionally cache frequent requests to the database which comes from passport. Similar to what https://github.com/overtrue/laravel-passport-cache-token the package does.

However, in our case that package is not enough as we would like to cache results in PassportUserProvider and ClientRepository too.

Are there plans for this or were that plans that got scrapped?

**Comment by driesvints** [comment]
We have no plans for this sorry. This seems something that should be solved in user land.
