### ISSUE TITLE
Display Login form and Redirect user when they are not logged in

### ISSUE THREAD

**Issue by jgodstime** [laravel/passport#1528]
https://laravel.com/docs/8.x/passport#approving-the-request
![image](https://user-images.githubusercontent.com/18240409/153257479-fe4a6eb4-052a-4e3e-ad32-3a26470bcb66.png)

If the user is not logged in, there is no implementation to:
**1 . Display the login screen for the user to log in or register** 
2.  Then display a template to the user allowing them to approve or deny the authorization request after login or register. 
3. And redirect back to the redirect_uri that was specified by the consuming application.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by komen205** [comment]
If the user is not logged in then Auth middleware will be used, you can implement your logic there.
As for redirecting to the page you might use `return Redirect::intended();`
