### ISSUE TITLE
Auth Code (w/ PKCE) for clients without a resource owner (user)

### ISSUE THREAD

**Issue by AlastairDewar** [laravel/passport#1535]
Hi,

I'm looking at giving access to a SPA in order to interact with our API, and the flow appears to work as expected when a username and password is provided with the initial /authorization request.

We also have the ability for guests to use our application, and still want to protect our API resources behind OAuth. Typically I would use a Client grant in this situation, but this requires the use of a secret that would be visible in the SPA's source.

When I attempt the same Auth Code (w/ PKCE) flow without supplying a username and password, but still sending the challenge - Passport throws some exceptions in the `AuthorizationController`'s `authorize` method as it is routed through the `auth` middleware which requires a valid username and password.

The code thereafter also references the user bound to the request which wouldn't exist in my proposed scenario.

I have extended the client to allow the skipping of Authorization if the redirect is part of a predefined company domain name. This then allows for it to approve the request - but again fails here as it expects a user to be defined.

I can't see anything in [the RFC](https://datatracker.ietf.org/doc/html/rfc7636) that says a resource owner must be specified.

Is there a different type of flow I should be using that will allow me to authenticate a client without the use of a secret or would you consider a change to the package in order to allow this scenario?

Similar/related issues:
https://github.com/laravel/passport/issues/600

**Comment by driesvints** [comment]
I don't think it makes sense to use Passport on endpoints that are used by guests, sorry.
