### ISSUE TITLE
use Octane  ， Passport cannot authenticate 

### ISSUE THREAD

**Issue by lovemintblue** [laravel/passport#1536]
- Passport Version: ^10.3
- Laravel Version: 9.0
- PHP Version: 8.0
- Database Driver & Version:

### Description:
{
    "message": "Unauthenticated."
}
Passport cannot authenticate 

What should I do？

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lovemintblue** [comment]
Thanks for your reply, I understand!&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dries ***@***.***&gt;; 
发送时间: 2022年3月14日(星期一) 下午5:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [laravel/passport] use Octane  ， Passport cannot authenticate  (Issue #1536)





 
Hi there,
 
Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
  
Laracasts Forums
 
Laravel.io Forums
 
StackOverflow
 
Discord
 
Larachat
 
IRC
  
However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
 
Thanks.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by M9snikFeed** [comment]
@driesvints, Have you solved the problem?

**Comment by M9snikFeed** [comment]
@lovemintblue have you solved the problem?
