### ISSUE TITLE
Dockerized laravel app exits on passport:keys artisan command

### ISSUE THREAD

**Issue by Sanguigui** [laravel/passport#1537]
- Passport Version: 10.3.3
- Laravel Version: 8.83.5
- PHP Version: 7.3
- Database Driver & Version:

### Description:

Upgrading to version 10 of passport causes my docker container to exit because the command `passport:keys` returns a 0 or a 1.

In docker a return of 0 means "Absence of an attached process in the foreground" and 1 means "failure due to application error".
It seems this has been added as part of a PR [#1509](https://github.com/laravel/passport/pull/1509) to update tests and wasn't present in the previous version.

### Steps To Reproduce:

I unfortunately couldn't show any code but you could try:

- Dockerize a Laravel v8 app
- Add Passport v10 to it
- Follow documentation's instruction up until deploying passport and running the artisan command `passport:keys`

**Comment by driesvints** [comment]
Unsure what you mean as I've always knows 0 to be a success code and 1 to be a failure. The current code seems correct to me.

**Comment by driesvints** [comment]
I really don't see an issue sorry.
