### ISSUE TITLE
A compatible error by missing return type declarations

### ISSUE THREAD

**Issue by Geek-justin** [laravel/passport#1539]
- Passport Version: ^10.1.0
- Laravel Version: ^8.65
- PHP Version: ^8.1
- Database Driver & Version:

### Description:
The function has no return type declarations, which will cause "PHP Fatal error:  Declaration of Laravel\Passport\HasApiTokens::tokens() must be compatible with ..." when using this trait in a subclass that with parent class defined function tokens with return type declarations.

```php
// BaseModel\User.php

public function tokens(): \Illuminate\Database\Eloquent\Relations\HasMany
{
    return $this->hasMany(\App\Models\Token::class, Token::COLUMN_USER_ID, self::COLUMN_ID);
}
```

**Comment by driesvints** [comment]
These methods does not have a return type in Passport. Unfortunately the way PHP works is that you can't type these in userland.
