### ISSUE TITLE
Authorization code has been revoked

### ISSUE THREAD

**Issue by gotexx1** [laravel/passport#1541]
- Passport Version: 10.4
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Database Driver & Version: Postgresql 13

### Description:
Following the documentation, the remote application (other.tld) makes a GET request to my application (website.tld) on the URI website.tld/oauth/authorize?client_id=1&redirect_uri=https://other.tld/oauth2/callback&response_type=code&scope=*

I authorize access to the client and am redirected to the following URI:
https://other.tld/oauth2/callback?code=*the generated code*

Then other.tld has to make a POST request with the generated code to get an access token from my application.

Unfortunately, when requesting the access token, I get the following error in my application logs:
```
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. { "exception":"[object] (Laravel\Passport\\Exceptions\OAuthServerException(code: 3): The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. at /home/forge/website.tld/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php:26)
```

If I make the request via Postman, I get the following return:

[![https://i.imgur.com/HeHZH3W.png][1]][1]

I can't figure out what the problem is.

  [1]: https://i.stack.imgur.com/IbAaL.png

### Steps To Reproduce:

Create a Laravel project with Passport
My project: https://github.com/gotexx1/komimo/

**Comment by gotexx1** [comment]
Same error with Laravel 8

**Comment by driesvints** [comment]
The linked example repo doesn't exists.

**Comment by karneaud** [comment]
@gotexx1  did you figure this out? I'm having the same issue. Every time the client tries to get the token on the user's behalf it is being revoked!
