### ISSUE TITLE
Support Non-URL redirection URIs (e.g., for native apps with custom schemes)

### ISSUE THREAD

**Issue by victorbalssa** [laravel/passport#1542]
I'm currently working on mobile native application which use OAuth2 flow with `laravel/passport`.

The redirection URI is something like `scheme://home-dashboard`, which is a valid URI but is not a URL.

The `RedirectRule` accept multiple URLs but does not accept URIs like `scheme://home-dashboard`.

https://github.com/laravel/passport/blob/10.x/src/Http/Rules/RedirectRule.php:

```php
/**
 * {@inheritdoc}
 */
public function passes($attribute, $value)
{
    foreach (explode(',', $value) as $redirect) {
        $validator = $this->validator->make(['redirect' => $redirect], ['redirect' => 'url']);

        if ($validator->fails()) {
            return false;
        }
    }

    return true;
}
```

Do you think that I can create a PR to support the URI scheme as well?

**Comment by driesvints** [comment]
Yes I think that makes sense. It's referenced in https://www.oauth.com/oauth2-servers/oauth-native-apps/redirect-urls-for-native-apps/ so we should support this. Feel free to PR 👍
