### ISSUE TITLE
Support for JWKS endpoint with rolling public / private keys

### ISSUE THREAD

**Issue by hussainanjar** [laravel/passport#1546]
Support for JWKS endpoint will add a lot of value.

This will allow microservies written in any language to verify if the token is valid or not.

https://is.docs.wso2.com/en/latest/learn/json-web-key-set-endpoint/#:~:text=The%20JSON%20Web%20Key%20Set,signatures%20from%20the%20Identity%20Server.

Also to support this we can have a configuration for rolling public / private keys for enhance security.

**Comment by driesvints** [comment]
I don't think we'll add this sorry. Not sure what it has to do with OAuth 2.0
