### ISSUE TITLE
Cannot assign the "*" (all) scope to authorization code flow

### ISSUE THREAD

**Issue by Sammyjo20** [laravel/passport#1547]
- Passport Version: v10.4.1
- Laravel Version: v8.83.11
- PHP Version: 8.1.5
- Database Driver & Version: MySQL

### Description:

Hi there, I just wanted to raise this one again. I know it's an old issue but we're experiencing it again currently. (#516)

For some background, there's a bit of code in Passport that strips out the '*' scope if provided. I don't really understand why this is blocked/removed as you said previously @driesvints but I was wondering if you or someone could still take a look.

There is a file In `Passport/Bridge` called `ScopeRepository` 

https://github.com/laravel/passport/blob/10.x/src/Bridge/ScopeRepository.php

Inside the file, there is this method which has been overwritten:

```php
/**
 * {@inheritdoc}
 */
public function finalizeScopes(
    array $scopes, $grantType,
    ClientEntityInterface $clientEntity, $userIdentifier = null)
{
    if (! in_array($grantType, ['password', 'personal_access', 'client_credentials'])) {
        $scopes = collect($scopes)->reject(function ($scope) {
            return trim($scope->getIdentifier()) === '*';
        })->values()->all();
    }

    return collect($scopes)->filter(function ($scope) {
        return Passport::hasScope($scope->getIdentifier());
    })->values()->all();
}
```

This method appears to strip out the * scope. It would be great if we either could have an option to disable this or remove this all together as I think it should be up to the developer to restrict the scopes, not the package - as the original Oauth 2 server by The PHP League does not restrict the scopes. I also cannot find any information in the Oauth 2 RFC recommending this.

### Steps To Reproduce:

- Step through the Client Credentials flow
- Provide "*" scopes
- Scopes are stripped out onto access token

**Comment by driesvints** [comment]
@Sammyjo20 I'm not sure I understand. You say you're using the client credentials flow but as you can see in the method the stripping of the `*` is clearly bypassed. Are you sure you're using the client credentials flow?

**Comment by Sammyjo20** [comment]
Sorry! I mean the "authorization code" flow. Monday moment.

**Comment by driesvints** [comment]
I've tried to find references of this in https://oauth.net/2/scope/ but couldn't find any. I believe a wildcard is a Passport concept rather than a OAuth 2.0 concept. As such, it seems to me the restriction is intended. I think the best course of action here for you would be to send in a PR to attempt to remove the restriction and thoroughly explain to Taylor why you need it. Also provide references to the above issues as well as Andrew's remarks. Thanks
