### ISSUE TITLE
Can't authenticateViaBearerToken with user_id = 0

### ISSUE THREAD

**Issue by meesudzu** [laravel/passport#1552]
- Passport Version: 10.4.1
- Laravel Version: 8.83.10
- PHP Version: 8.0
- Database Driver & Version:

### Description:
I can't `authenticateViaBearerToken` with `user_id = 0`.
Inside my `users` table, I use `user_id` with negative, zero (0) value for my business logic.
I found the code that makes it not work with user_id = 0 in 
https://github.com/laravel/passport/blob/10.x/src/Guards/TokenGuard.php#L160

Do you have any ideas for this case?
Thanks for reading.

**Comment by driesvints** [comment]
We unfortunately don't support ID's with 0 or negative.
