### ISSUE TITLE
Works perfect on localhost in different ports but `Client authentication failed` on cpanel hosting production

### ISSUE THREAD

**Issue by Ign0r3dH4x0r** [laravel/passport#1555]
- Passport Version: 10.4.1
- Laravel Version: 9.19
- PHP Version: 8.1
- Database Driver & Version: libmysql - mysqlnd 7.4.30

### Description:

I have my both oauth and consumer server live on a same machine and in different subdomains (it's a cpanel shared hosting). My both application works well on localhost in different ports but when I deploy the oauth server returns the following error. I have checked everything more than 20 times and spent 2 days on it and tried all possible solutions that I found on issues and other communities. Somebody says that `passport won't work if they are on the same machine.`. So how can I host these 2 applications on my cpanel hosting? 
```
^ {#1251 ▼
  +"error": "invalid_client"
  +"error_description": "Client authentication failed"
  +"message": "Client authentication failed"
}
```

### Steps To Reproduce:

Create a oauth server and a consumer server with everything setup as the docs and then try to deploy them to a single cpanel hosting account.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
