### ISSUE TITLE
Option to customize middlewares for passport route groups (e.g. clients' routes)

### ISSUE THREAD

**Issue by Eldair** [laravel/passport#1556]
Hi,

Would it be useful to have an options (config or boot method) to customize (or extend) middlewares applied to Passport route groups? I see that it is possible to pass options to `Passport::routes` method but it would apply to all routes.

**Comment by driesvints** [comment]
Passport v11 will allow you to publish the routes file so you can do whatever you want: https://github.com/laravel/passport/blob/master/routes/web.php

**Comment by Eldair** [comment]
Oh, than great! Thanks!
