### ISSUE TITLE
Bearer token logs in multiple (wrong) guards

### ISSUE THREAD

**Issue by brecht-vermeersch** [laravel/passport#1573]
- Passport Version: 
- Laravel Version: 8.83.23
- PHP Version: 10.4.1

### Description:
A token generated for a user also logs in a company with the same ID.

### Steps To Reproduce:

* create two guards (api-users and api-companies) with the passport driver
* create a route with the auth:api-users middleware
* make a request to the route with the bearer token of the user
* dump both auth('api-users')->user() and auth('api-companies)->user()
* both will be set, while companies should be null

### Related issue

https://github.com/laravel/passport/issues/1474

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
