### ISSUE TITLE
Access token as Bearer logs in multiple (wrong) guards

### ISSUE THREAD

**Issue by brecht-vermeersch** [laravel/passport#1574]
I tried reaching out to the support channels, but didn't get a reply. I could reproduce the bug in the latest laravel version.

- Passport Version: 11.1.0
- Laravel Version: 9.29.0
- PHP Version: 8.1.9
- Database Driver & Version: Mysql 8

### Description:
My application has multiple web guards (api-users and api-companies). I have a route with the 'auth:api-users' middleware. When making a request with an access token, both the web-users and web-companies guard is logged in. This only happens if there is a user and a company with the same id.

This behaviour is different when using Sanctum.

### Steps To Reproduce:
1. create two guards (api-users and api-companies) with the passport driver
2. create a route with the auth:api-users middleware
3. make a request to the route with the bearer token of the user
4. dump both auth('api-users')->user() and auth('api-companies)->user()
5. both will be set, while companies should be null

### Related
https://github.com/laravel/passport/issues/1573
https://github.com/laravel/passport/issues/1474

**Comment by driesvints** [comment]
Can you link to the threads on the forums where you asked?

**Comment by brecht-vermeersch** [comment]
https://discord.com/channels/297040613688475649/540190697962340363/1017335630050635816

**Comment by brecht-vermeersch** [comment]
Probably related to this https://github.com/laravel/passport/issues/1420

**Comment by brecht-vermeersch** [comment]
This is my current fix

```php
class MultiClientPersonalAccessTokenFactory extends BasePersonalAccessTokenFactory
{
    /**
     * @see make
     *
     * @param $userId
     * @param string $name
     * @param string $clientName
     * @param array $scopes
     * @return PersonalAccessTokenResult
     */
    public function makeForClient(string $clientName, $userId, string $name, array $scopes = []): PersonalAccessTokenResult
    {
        $response = $this->dispatchRequestToAuthorizationServer(
            $this->createRequest($this->getClient($clientName), $userId, $scopes)
        );

        $token = tap($this->findAccessToken($response), function ($token) use ($userId, $name) {
            $this->tokens->save($token->forceFill([
                'user_id' => $userId,
                'name' => $name,
            ]));
        });

        return new PersonalAccessTokenResult(
            $response['access_token'], $token
        );
    }

    protected function getClient(string $name): ?Client
    {
        return Client::firstWhere('name', $name);
    }
}
```

```php
class Company extends Authenticatable
{
    use HasApiTokens, HasFactory;

    public function createToken($name, array $scopes = [])
    {
        /** @var MultiClientPersonalAccessTokenFactory $factory */
        $factory = app(MultiClientPersonalAccessTokenFactory::class);

        return $factory->makeForClient('Company Personal Access Client', $this->getKey(), $name, $scopes);
    }
}
```
![Screenshot 2022-09-13 at 14 34 12](https://user-images.githubusercontent.com/20967950/189902241-1206e013-5501-49ef-900c-f80a7994c166.png)

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
I'll reopen this one a repo is provided.
