### ISSUE TITLE
Laravel\Passport\Bridge\UserRepository assumes that the underlying user has a password

### ISSUE THREAD

**Issue by huntsfromshadow** [laravel/passport#158]
In the case where the user system does not have a traditional password (eg password check is done by another framework further down) the password grant won't work.

The function assumes that the findForPassword or where will return something that has a password that can be checked, and a password that is checked via hasher.

Probably would be better to have the User model validate the password itself and simply return a true or false.  That way Passport is completely independent of the low level model implementation.

**Comment by huntsfromshadow** [comment]
I have gone ahead and submitted a pull request to solve this issue.

https://github.com/laravel/passport/pull/173

**Comment by salarAsadi** [comment]
I have the same issue.
The validation logic must be customized via a function on the User model. right now by using "findForPassport" function we can only specify the username.

**Comment by huntsfromshadow** [comment]
@salarAsadi  The catch with that is it sill has to do the hasher check.
In my use case (see Pull Request I linked above) we don't have a hashed password available to the model
as my lower level layer just returns a 'true' or 'false' when I give it a username or password. (We aren't using the laravel user model at all).

Pull Request I put in adds another findForPassport like function to do validation.

**Comment by huntsfromshadow** [comment]
The issue this solves has been merged.

As a side note figured this out this morning while reading up on containers.
You can also put this before the Passport comes online before the Passport::routes() call and override the UserRepository.

app()->bind(\Laravel\Passport\Bridge\UserRepository::class, YourCustomPassportUserRepo::class );
