### ISSUE TITLE
PDOException(code: 22P02): SQLSTATE[22P02]

### ISSUE THREAD

**Issue by arttiger** [laravel/passport#1580]
- Passport Version: 10.4.1
- Laravel Version: 8.83.23
- PHP Version: 7.4
- Database Driver & Version: PostgreSQL JDBC 42.5.0

### Description:
If we use UUID as the primary key value of the Passport Client model and while receiving the access token, we pass an invalid UUID value in the client_id key, we will get a database error:

[2022-10-07 15:58:44] local.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: "1"
CONTEXT:  unnamed portal parameter $1 = '...' (SQL: select * from "oauth_clients" where "id" = 1 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: \"1\"
CONTEXT:  unnamed portal parameter $1 = '...' (SQL: select * from \"oauth_clients\" where \"id\" = 1 limit 1) at /oauth2/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
