### ISSUE TITLE
Routes customization: documentation missing, could be made easier

### ISSUE THREAD

**Issue by levu42** [laravel/passport#1589]
I'm working on a project where users have a flag whether they are allowed to create apps or not. For that, I need to register a middleware for the `/oauth/clients` routes and realized, that there is no documentation about the whole topic. The `Passport::ignoreRoutes` function is not documented and it's also not possible to use `php artisan vendor:publish` for the route file to easily then customize it.

Is there a reason for it? If not, before I put any work into a PR to change that: would a PR that fixes that be merged?

**Comment by driesvints** [comment]
I've sent in a PR for that: https://github.com/laravel/docs/pull/8316. We still very much recommend against overriding these routes.

**Comment by driesvints** [comment]
Can't you create a global middleware and detect the `POST /oauth/clients` call?

**Comment by levu42** [comment]
@driesvints I didn't think about that yet, sounds like a good approach, thanks for your help :)
