### ISSUE TITLE
Passport changes, get user information ( id, name ) with the personal access_token it is not working

### ISSUE THREAD

**Issue by murilolivorato** [laravel/passport#1590]
- Passport Version: 11.3
- Laravel Version: 9.19
- PHP Version: 8.1.11
- Database Driver & Version: mysql:8.0.1

### Description:
I can see that passport class had some changes -
https://github.com/laravel/passport/pull/1464

before , in my AuthServiceProvider class , I used to add this code -

```
Passport::routes();
```

and now I dont  add any more  with those changes .
I dont know If I have to add in other place, the passport routes .

well . but my question  is , I have  a personal token that I get like this -

first I create the access token -
```
php artisan passport:client --personal
```
then I log in -
```
$user = User::find(1);
return $user->createToken('the_persona_ access_client_name')->accessToken;

```

so it returns a access token .

with this token I make a request to get the user information , like this -

```
request to - myap.com/api/user-info
header - Bearer my_token_goes_here

```

in the user info Controller -
```
public function user_info(Request $request)
    {
 return ['user' => auth()->user()];
}
```
it is returning  null -
```
{
    "user": null
}
```
It is not returning any more my user .

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by murilolivorato** [comment]
sorry @driesvints , my mistake .
I forgot to add this in the route -

```
Route::get('/user', function () {
    //
})->middleware('auth:api');
```
