### ISSUE TITLE
Authenticate user via its ID

### ISSUE THREAD

**Issue by zeshan77** [laravel/passport#1596]
We've a similar functionality in session guard where we can authenticate a user via its ID [Auth::loginUsingId(userID)](https://laravel.com/docs/9.x/authentication#authenticate-a-user-by-id)
However similar functionality is not there in Passport.

Is there a way to achieve similar functionality in `Laravel Passport`?

**Comment by driesvints** [comment]
No, this is not really how Passport works. If you need to auth by an identifier then just use that method.
