### ISSUE TITLE
Redirecting issue after adding "Support prompting login when redirecting for authorization"

### ISSUE THREAD

**Issue by adrorocker** [laravel/passport#1598]
- Passport Version: 11.3.0
- Laravel Version: 9.39.0
- PHP Version: 8.1.12
- Database Driver & Version: N/A

### Description:

[This commit](https://github.com/laravel/passport/commit/741595738b80f64ec35ad82de477adee925fff7e) introduced a change in behavior. When the Laravel Application does not use the default `login` named route (or even Laravel to log the user in) the login flow gets broken, now by default passport will redirect you  to that `login` route.  If the applications does not have the login route it will throw an error complaining that the login route is not defined.

Prior this commit the redirection was handle by the [Authenticate](https://github.com/laravel/laravel/blob/040d548810dd2d517bbd5cc792818b5d0429a0fc/app/Http/Middleware/Authenticate.php#L18) middleware and not the [AuthorizationController](https://github.com/laravel/passport/blob/741595738b80f64ec35ad82de477adee925fff7e/src/Http/Controllers/AuthorizationController.php#L218) 

I'm assuming that this is not an intended behavior since now the request gets passed the `Authenticate` middleware. This is not letting us customize the redirection url since the controller lives in the vendor dir. 

I found 3 solutions to this:

1. Create a redirection route

```php
Route::redirect('/login', 'https://another-auth-system.com/auth/login')->name('login');
```

2. Move the [/autorize](https://github.com/laravel/passport/commit/741595738b80f64ec35ad82de477adee925fff7e#diff-193e04aa1705f6f3e484d7efca8f45fe4d19d0ece3b6e6880d3ea070938a1fad) route back to group that uses the `['web', 'auth']` middlewares (Not sure what the implications of doing this will cause on what [this](https://github.com/laravel/passport/pull/1577) PR was suppose to addressed)

3. Add a config in the passport config file that let you customize where the exception should redirect . Something like 

[src/Http/Controllers/AuthorizationController.php](https://github.com/laravel/passport/pull/1577/files#diff-9fc1a4ecd0d38e60fac1081388d782df71dd7a5eb72d1e1cd9586df4dfd889ac) 

```php
    /**
     * Prompt the user to login by throwing an AuthenticationException.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @throws \Illuminate\Auth\AuthenticationException
     */
    protected function promptForLogin($request)
    {
        $request->session()->put('promptedForLogin', true);

        throw new AuthenticationException(redirectTo: config('passport.login.url'));
    }
```

### Steps To Reproduce:

1. For rapidly testing the issue, In a new laravel project install, lets say, laravel breeze and then change the name of the `login` route to something else. 

2. Install and setup laravel passport.

3. Visit the authorize route. Example:

```
http://laravel-app.here/oauth/authorize?client_id=1&redirect_uri=https%3A%2F%2Fexample.com%2Foauth2%2Fcallback&response_type=code
```

I chose the first option to work around this change in behavior but I think this is not something that should happen. 

I'll gladly create a PR with the 3rd option but I would like to know if you guys will consider refactoring or reverting that PR in the first place. 

Thanks for the awesome work you do!

**Comment by taylorotwell** [comment]
@adrorocker for now I suggest defining a `login` route for your application that goes where you want.

**Comment by adrorocker** [comment]
@taylorotwell Thanks, that is exactly what I end up doing. I'll wait to see what @hafezdivandari decides before I create any additional PR.

**Comment by hafezdivandari** [comment]
@adrorocker That's the way Laravel handles `AuthenticationException` by default, check this:

https://github.com/laravel/framework/blob/7392f1beb710d021c6e1e0749b06911e8faa6943/src/Illuminate/Foundation/Exceptions/Handler.php#L470-L475

**Solution**: You may override the `unauthenticated` method of your application's `App\Exceptions\Handler` class:

```php
namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    // ...

    /**
     * Convert an authentication exception into a response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Auth\AuthenticationException  $exception
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function unauthenticated($request, AuthenticationException $exception)
    {
        return $this->shouldReturnJson($request, $exception)
                    ? response()->json(['message' => $exception->getMessage()], 401)
                    : redirect()->guest($exception->redirectTo() ?? route('whatever_you_want'));
    }
}
```

**Comment by adrorocker** [comment]
@hafezdivandari Thanks for pointing out another solution to work around the change in behavior.

May I ask what was the use case or the reasoning behind the motivation for your PR? 

I ask because by the title of the PR it seems you wanted to add a way to redirect to the login page if the user was not authenticated when the visit the authorize route. 

Laravel already gives you a way to do just that with the `Authenticate` middleware, it is a more intuitive way since that is how that works for the rest of the application and also is already working like that for passport. 

Your solution as well of my 1st and 3rd ones are more obscure in the sense that they are not documented and not visible on the skeleton application.

Even though I suggested adding a config on the passport config file I don't like it that much since it is adding a duplicate configuration that will instruct passport to behave the same way the rest of the application is.

**Comment by rickycheers** [comment]
I'd add that, letting the auth middleware process the route still allows for the exception handler to handle unauthenticated errors, with the added benefit of being able to customize the redirection route the way the framework has always encouraged to:

https://laravel.com/docs/9.x/authentication#redirecting-unauthenticated-users

**Comment by hafezdivandari** [comment]
@adrorocker I sent 3 PR (#1567, #1569 and #1577) to support `prompt` parameter when redirecting for authorization, you may check the 1st one that I explained the problem in detail: #1567 

We can't use your 2nd solution, because it breaks `prompt=login` when redirecting for authorization, you may check `AuthorizationController` to know why.

I think you have to override the `unauthenticated` method of your application's `App\Exceptions\Handler` class, because as you see `route('login')` is hardcoded there and you want to change the default way of handling `AuthenticationException`.

Your 3rd solution works fine, the `Authenticate` middleware also throws `AuthenticationException` with a `redirectTo` param:
https://github.com/laravel/framework/blob/daf094441404d0c51084abb6c03a64da1391a798/src/Illuminate/Auth/Middleware/Authenticate.php#L80-L85

**Comment by hafezdivandari** [comment]
Another approach is to send a PR to `laravel\framework` and `laravel\laravel`, to add `auth.login.url` instead and change both these hardcoded `route('login')` to use that config param:

* https://github.com/laravel/laravel/blob/040d548810dd2d517bbd5cc792818b5d0429a0fc/app/Http/Middleware/Authenticate.php#L18
* https://github.com/laravel/framework/blob/daf094441404d0c51084abb6c03a64da1391a798/src/Illuminate/Foundation/Exceptions/Handler.php#L474

**Comment by adrorocker** [comment]
@hafezdivandari Thanks for taking the time to point me in the right direction to see why the change was made. 

I do like your suggestion of not hardcoding the login route, but I would like @taylorotwell input before I proceed on creating such PR. 

If implementing that change is not possible maybe documenting the change in behavior and the possible work arounds for it would be good enough for now. I'll gladly document it if necessary.

**Comment by adrorocker** [comment]
@hafezdivandari perhaps we could implement something like [this](https://github.com/laravel/fortify/blob/27941f2c55c0d59a530a289212d3b0f953122a94/src/Fortify.php#L84) where we can search for several possible options.

**Comment by hafezdivandari** [comment]
@adrorocker you may just send a PR with a change you suggested earlier:

```php
    protected function promptForLogin($request)
    {
        $request->session()->put('promptedForLogin', true);

        throw new AuthenticationException(redirectTo: config('passport.login_url'));
    }
```

Then if `passport.login_url` is not customized/defined by user it will fallback to default `route('login')` on `authenticated` method. Using config params is not a new thing on Passport, e.g. it also has other hidden configs like this one: https://github.com/hafezdivandari/passport/blob/741595738b80f64ec35ad82de477adee925fff7e/src/PassportServiceProvider.php#L141

Then Taylor will check your PR and if it wasn't merged, you may send a PR to document the workaround (overriding the `unauthenticated` method).
