### ISSUE TITLE
Bypass auth screen if we already have a token

### ISSUE THREAD

**Issue by jbrooksuk** [laravel/passport#16]
Unless the token has expired, the consumer has explicitly requested re-auth or the scopes have changed, we shouldn't need to continue showing the auth screen.

**Comment by marcoscoelho** [comment]
Same question..

**Comment by geodeveloper** [comment]
@taylorotwell can you take a look at this issue ? This seems problematic when an app it's depending only on oAuth server to authenticate users. And it's annoying to ask each time the user to authorize (even if previously has approved the request).

**Comment by nerfe** [comment]
Does anybody have a workaround on this yet? What i am planning is 

-Store Authorization Code of the user (in my own REST api)
-Create an endpoint to use Authorization Code of user to generate new token and continue login
-If authorization code is expired then show the authorization page

I am using Laravel Passport with my own REST api services.
