### ISSUE TITLE
Refresh Tokens Showing as revoked when they are not

### ISSUE THREAD

**Issue by rtconner** [laravel/passport#1605]
- Passport Version: 11.3.1
- Laravel Version: 9.43.0
- PHP Version: 8.1.1
- Database Driver & Version: Postgres

### Description:

I expect when I generate an access token twice in a row using the same refresh_token

Related discussion : https://github.com/thephpleague/oauth2-server/issues/1025

### Steps To Reproduce:

1. Generate a brand new refresh token
2. Generate a new access token : 
  ```
  curl --request POST \
    --url https://server.test/oauth/token \
    --header 'Content-Type: application/json' \
    --data '{  "client_id": "id-here",  "client_secret": "secret-here",  "grant_type": "refresh_token",  "refresh_token": "string-of-token" }'
  ```
3. Immediately generate another access token with the exact same refresh token : 
  ```
  curl --request POST \
    --url https://server.test/oauth/token \
    --header 'Content-Type: application/json' \
    --data '{  "client_id": "id-here",  "client_secret": "secret-here",  "grant_type": "refresh_token",  "refresh_token": "string-of-token" }'
  ```

Expected Behavior: Receive a new access token

Actual Behavior: 401 Response {"hint": "Token has been revoked", "message": "The refresh token is invalid."}

**Comment by driesvints** [comment]
I don't think you can expect to use a refresh token twice. If you actually think that's wanted then please attempt a PR with a thorough explanation why that would be the case and link to resources proving that's correct. Thanks

**Comment by rtconner** [comment]
because http packet failures happen.
