### ISSUE TITLE
Laravel Passport login not redirecting properly with Jetstream Inertia

### ISSUE THREAD

**Issue by proxAdmin** [laravel/passport#1608]
I have implemented an OAuth system with Laravel Passport, but the login and all authentication for this system is handled by Laravel Jetstream with Inertia.

When I want to request a code (using the Authorization Code Grant), my application redirects me to my OAuth server, this server asks me for login before continue, this screen is the screen generated by Laravel Jetstream login using Inertia (Vue). When I'm logged in, it redirects me to the authorization page, but this redirect is weird because this page is shown inside a Vue (Inertia) page, the URL in the browser doesn't update, and if I accept the authorization request it redirects me back to my application, but the redirect is inside the same Vue page, I mean, the URL is the same as my OAuth server login, but the view is my app who requested the code.

I think that there's a problem with redirections in Vue because the authorization page isn't using Inertia (is the default authorization page of Laravel Passport), and I don't know how to fix it, can you help me?

Here is an image:

![6CDB1E7E-682D-4C16-B7EB-B93CF9A34F6A](https://user-images.githubusercontent.com/18560186/208228039-83245d4b-fb89-4bad-bf14-5f094209b73e.png)

As you can see, it seems to be in a modal, but is an Inertia error page, and inside is showing the authorization page, is an redirect error that I don't know how to fix

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
