### ISSUE TITLE
encounteringt old issue with Laravel 7

### ISSUE THREAD

**Issue by justageek** [laravel/passport#1611]
- Passport Version: 8.5.0
- Laravel Version: 7.30.6
- PHP Version: 7.4.1
- Database Driver & Version: Mysql 5.6

### Description:

We are encountering the issue described here:
https://github.com/laravel/passport/issues/1384

Any ideas on how to fix this, we appear to be running lcobucci/jwt 4.2.1

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
