### ISSUE TITLE
StatefulGuard didn't bind when using extending class AuthorizationController

### ISSUE THREAD

**Issue by mell810125** [laravel/passport#1612]
- Passport Version: 11.3.1
- Laravel Version: 9.39.0
- PHP Version: 8.1.10
- Database Driver & Version: MySQL 8.0.30

### Description:

After I extends `AuthorizationController` to make some custom changes, I got this error:
>  Target [Illuminate\Contracts\Auth\StatefulGuard] is not instantiable while building [App\Http\Controllers\Passport\AuthorizationController].

According to the code:
https://github.com/laravel/passport/blob/78c9d3a0f38fa28b9be9dbf0282cc766354e0e52/src/PassportServiceProvider.php#L139-L141

And I added these line to my `AuthServiceProvider` solved the problem:
```php
$this->app->when(\App\Http\Controllers\Passport\AuthorizationController::class)
            ->needs(StatefulGuard::class)
            ->give(fn() => Auth::guard(config('passport.guard', null)));
```

### Steps To Reproduce:

1. Create a Controller
```php
<?php
namespace App\Http\Controllers\Passport;

class AuthorizationController extends \Laravel\Passport\Http\Controllers\AuthorizationController
{}
```
2. Ignore Passport routes and add authorize route
```php
Passport::ignoreRoutes();
```
```php
Route::get('/oauth/authorize', [\App\Http\Controllers\Passport\AuthorizationController::class, 'authorize'])
  ->middleware('web')
  ->name('authorizations.authorize');
```
4. Accessing the authorize route `/oauth/authorize?client_id=...&redurect_uri=...&response_type=code`

**Comment by hafezdivandari** [comment]
I see no problem here, as you said:

> And I added these line to my `AuthServiceProvider` solved the problem:
>    ```php
>    $this->app->when(\App\Http\Controllers\Passport\AuthorizationController::class)
>            ->needs(StatefulGuard::class)
>            ->give(fn() => Auth::guard(config('passport.guard', null)));
>    ```

That's the correct way.

But instead of that, you may add `auth:web` middleware to your route if you are not using [`prompt` parameter when redirecting for authorization](https://laravel.com/docs/9.x/passport#requesting-tokens-redirecting-for-authorization):

```diff,php
Route::get('/oauth/authorize', [\App\Http\Controllers\Passport\AuthorizationController::class, 'authorize'])
+  ->middleware(['web', 'auth:web'])
-  ->middleware('web')
  ->name('authorizations.authorize');
```

**Comment by driesvints** [comment]
Thanks @hafezdivandari
