### ISSUE TITLE
add more claims to jwt token

### ISSUE THREAD

**Issue by chaotic98** [laravel/passport#1614]
I need to add more details on my jwt token.
currently these decoded informations are in my token:
token_id, user_id,  expecting  ,start_at_unix, start_at,  incorrect , created_at_unix, expired , expires_at, error, errors ,valid
I'm not sure whether there is a feature to customize it

**Comment by driesvints** [comment]
Right now we don't offer anything like that sorry. If the PR is small and not complex we could consider one.
