### ISSUE TITLE
failed Tokens request returns 200 https status instead of 400

### ISSUE THREAD

**Issue by chaotic98** [laravel/passport#1618]
- Passport Version: 11.5.0
- Laravel Version: 9.19
- PHP Version: 8.2.0
- Database Driver & Version: MySQL 8

### Description:
when requesting to convert authorization code to access tokens, if the validation fails instead of showing 400 http status, it shows 200.

### Steps To Reproduce:
request token like this 
https://laravel.com/docs/9.x/passport#requesting-tokens
 and then convert authorization code to Access Tokens like the link below:
https://laravel.com/docs/9.x/passport#requesting-tokens-converting-authorization-codes-to-access-tokens
if validation fails to any reason the http status will be 200 instead of 400
![Screenshot 2023-01-18 172310](https://user-images.githubusercontent.com/61518809/213189627-948b7f54-c1e9-4383-a9a1-7169fc5e53f5.png)

**Comment by hafezdivandari** [comment]
I couldn't reproduce the issue:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/56585913/213318461-46f933a7-78b3-45f7-8327-6c214d8db537.png">
