### ISSUE TITLE
Personal Access Token expiration can't be set and it fails to check the Y2K38 bug.

### ISSUE THREAD

**Issue by fgoni** [laravel/passport#162]
Using the Passport facade to set the Expiration time for Authorization Code and Password Grant you can avoid the dreaded Y2K38 bug but Personal Access Tokens are hardcoded to last another hundred years from now, which puts it well beyond 2038.

This is a problem because on most Windows environments the tokens will never match and never authenticate the user.

The only way to bypass this is to modify the vendor files and do it every time Passport is upgraded.

**Comment by nugrahawahyu** [comment]
Yeah I always get negative value of expires_in ( -1477799197  ) and the only way to fix it is to modify the vendor files.

**Comment by zsimple** [comment]
Yes, I just wasted one day to find this problem, It happend only happend on 32bit php.

For now, maybe we need modify passport/src/Passport.php @190, `new DateInterval('P100Y')` --> `new DateInterval('P1Y');`.

100 Years is really too long :-D

**Comment by badknight** [comment]
> Yeah I always get negative value of expires_in ( -1477799197 ) and the only way to fix it is to modify the Vendor files.

@nugrahawahyu you can simply change the [token-lifetime](https://laravel.com/docs/5.3/passport#token-lifetimes) - it solved my problems

```php

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();
        
        Passport::routes();
        Passport::tokensExpireIn(Carbon::now()->addDays(30));
    }
```

**Comment by fgoni** [comment]
TokensExpireIn 'only' works for Authorization Code and Password Grant tokens, not for personal   access tokens.

**Comment by themsaid** [comment]
a PR was submitted to solve the issue: https://github.com/laravel/passport/pull/185

**Comment by diegcode** [comment]
To change the expiration date of a PersonalAccessToken could create a class that extends from the original class of passport. for example: To add 15 minutes

<?php

namespace App;

use Carbon\Carbon;
use Laravel\Passport\PersonalAccessTokenFactory as PersonalAccessTokenFactoryPassport;
use Laravel\Passport\PersonalAccessTokenResult;

class PersonalAccessTokenFactory extends PersonalAccessTokenFactoryPassport
{
    public function make($userId, $name, array $scopes = [])
    {
        $response = $this->dispatchRequestToAuthorizationServer(
            $this->createRequest($this->clients->personalAccessClient(), $userId, $scopes)
        );

        $token = tap($this->findAccessToken($response), function ($token) use ($userId, $name) {
            $this->tokens->save($token->forceFill([
                'user_id' => $userId,
                'name' => $name,
                'expires_at' => Carbon::now()->addMinutes(15)
            ]));
        });

        return new PersonalAccessTokenResult(
            $response['access_token'], $token
        );
    }
}


And in the User class you must rewrite the method that calls that Factory. For example:

public function createToken($name, array $scopes = [])
    {
        return Container::getInstance()->make(PersonalAccessTokenFactory::class)->make(
            $this->getKey(), $name, $scopes
        );
    }

**Comment by diazemiliano** [comment]
Hi guys, I've set the `expires_at` date to `one year` before now. But it seems Passport isn't checking expiration dates on `personal access tokens`. That's a default behavior? Thanks.

**Comment by hlorofos** [comment]
@diazemiliano in my case it doesn't validated at all, no matter which type of client I'm used.

**Comment by chrisgillis** [comment]
My password granted tokens seem to be expiring much more quickly than Carbon::now()->addDays(1)... they seem to last about 2 hours max

**Comment by DiegoGutman** [comment]
$as = app()->make(\League\OAuth2\Server\AuthorizationServer::class);
        $as->enableGrantType(
            new PersonalAccessGrant, new DateInterval('PT1M')
        );

        return JsonResponse::create(
            $user->createToken(
                $user->getAttribute('name') . " " . Carbon::now(),
                $scopes = [implode(" ", $user->roles()->get()->pluck('name')->toArray())]
            ),
            JsonResponse::HTTP_OK
        );

**Comment by DevTTL** [comment]
十分感谢 @DiegoGutman 的方案完美解决了我的问题 ,向你致敬

**Comment by vivektakrani** [comment]
One can simply update the expiry time for Personal token using personalAccessTokensExpireIn method in AuthServiceProvider's boot method.
Check [https://stackoverflow.com/a/54196090/3535399](url)

**Comment by netwons** [comment]
You are trying to create Personal Access Token.

// Passport::tokensExpireIn(now()->addDays(15));
// Passport::refreshTokensExpireIn(now()->addDays(30));


# Get or set when personal access tokens expire.
`Passport::personalAccessTokensExpireIn(now()->addHour(1));`
Result :

> array:2 [
>   "token" => "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9...."
>   "ExpireTime" => "59 minutes from now"
> ]

**Comment by abdullah-ds** [comment]
This will work  💯% 
In AuthServiceProvider, copy this below line into your boot method;

Passport::personalAccessTokensExpireIn(now()->addMinutes(10));

**Comment by Prefix20192** [comment]
Yes, it works, but how do I make it so that it is not issued globally?

For example, in `AuthServiceProvider.php ` we register the lifetime for all personal tokens, but how do we do this for a specific method in the controller, for example, the recovery method
