### ISSUE TITLE
Error creating a user's personal access token

### ISSUE THREAD

**Issue by lucaspanik** [laravel/passport#1623]
- Passport Version: v10.4.1
- Laravel Version: v9.10.1
- PHP Version: 8.0.21
- Database Driver & Version:  mysqlnd 7.4.9

### Description:

Good morning, good afternoon, good evening dear.

#### [TL;DR]

Disparity between the sent id and the column used to search the DB for the client.

In my oauth_clients table I have the ID column auto incremented by the database and another column called client_id which is a UUID generated by config `config('passport.client_uuids')`.

PersonalAccessTokenFactory@createRequest uses the `->id` column forcibly instead of using the `->getKey()` method  (line 100)
https://github.com/laravel/passport/blob/8d9e2e385da0a05c524b0b63655f537eebfe6fd1/src/PersonalAccessTokenFactory.php#L86-L105

ClientRepository@find uses the `->getKeyName()` method to get the primary column defined in the client model.
https://github.com/laravel/passport/blob/8d9e2e385da0a05c524b0b63655f537eebfe6fd1/src/ClientRepository.php#L10-L21

---

Today I had an issue with manual token generation for a user.

https://laravel.com/docs/9.x/passport#managing-personal-access-tokens
```php
$user->createToken('Token Name')->accessToken
```

In my oauth_clients table I have the ID column auto incremented by the database and another column called client_id which is a UUID generated by config `config('passport.client_uuids')`.

My problem is in the PersonalAccessTokenFactory#100 file where it obtains the client model (\Laravel\Passport\Client) and defines that it will use the value of the id column `->id` instead of obtaining the value of the primary column with the method `->getKey()`
https://github.com/laravel/passport/blob/9.x/src/PersonalAccessTokenFactory.php#L100

Then there is client validation in PersonalAccessGrant.php
https://github.com/laravel/passport/blob/9.x/src/Bridge/PersonalAccessGrant.php#L21

Which in turn uses the `find()` method of the ClientRepository.php class; in this method, `->getKeyName()` from the client model is used instead of forcing the ID column as mentioned above, causing a disparity between the id sent and the column used to search for the client in the DB.
https://github.com/laravel/passport/blob/9.x/src/ClientRepository.php#L20

I believe that changing the way to get the primary_key value of the client model from `$client->id` to `$client->getKey()` in PersonalAccessTokenFactory@createRequest the problem will be fixed.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by lucaspanik** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.
> 
> Thanks! Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.
> 
> Thanks!

Thanks for the quick reply @driesvints , but I don't understand about "Unfortunately we don't support this version anymore."

Anyway, I updated the links in the comment above for passport version 11 and the bug is still in the code.

---
![image](https://user-images.githubusercontent.com/7035554/215137481-db86bd06-dc43-45da-b5d0-838b198b7603.png)

**Comment by driesvints** [comment]
Hi @lucaspanik. You seem to have missed this sentence from the docs:

<img width="832" alt="Screenshot 2023-01-30 at 11 09 14" src="https://user-images.githubusercontent.com/594614/215448117-80d69c9e-ab7b-443a-8270-ee0cc9fc4ea1.png">

We only support the latest major version of a package.
