### ISSUE TITLE
Unable to install Laravel Passport on PHP 8.2.1

### ISSUE THREAD

**Issue by the-zalox** [laravel/passport#1625]
- Passport Version: ....
- Laravel Version: 9.11
- PHP Version: 8.2.1
- Database Driver & Version: 

### Description:

Unable to install

  Problem 1
    - phpspec/prophecy v1.15.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.1) does not satisfy that requirement.
    - phpunit/phpunit 9.5.20 requires phpspec/prophecy ^1.12.1 -> satisfiable by phpspec/prophecy[v1.15.0].
    - phpunit/phpunit is locked to version 9.5.20 and an update of this package was not requested.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require phpspec/prophecy-phpunit:*" to figure out if any version is installable, or "composer require phpspec/prophecy-phpunit:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Steps To Reproduce:

run: composer require laravel/passport  

You get: 
![image](https://user-images.githubusercontent.com/68165721/215287758-ca54dc02-dba9-4285-8ea5-fa066ff6465f.png)

**Comment by driesvints** [comment]
Right now we can install Passport on Laravel v9 and PHP 8.2 so we have no reason to believe this wouldn't work. Most likely this is something specific to your app. 

https://github.com/laravel/passport/blob/11.x/.github/workflows/tests.yml#L19

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
