### ISSUE TITLE
php artisan key:generate command uses another command __construct

### ISSUE THREAD

**Issue by Damzoneuh** [laravel/passport#1631]
- Passport Version: 10.2.0
- Laravel Version: 8.77.1
- PHP Version: 7.4.33
- Database Driver & Version:
Sqlite

### Description:
When I launch `php artisan key:generate` it uses the `__construct` of another custom command

### Steps To Reproduce:
- Before database migration
- Create custom command with `__construct`
- Inject third party service in the `__construct`
- Launch `php artisan key:generate`
- In my case it throws an sql exception `SQLSTATE[HY000] [2002] Connection refused`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
