### ISSUE TITLE
laravel10 The Eloquent model's deprecated $dates property has been removed.

### ISSUE THREAD

**Issue by TonyWong9527** [laravel/passport#1635]
- Passport Version: 11.7.0
- Laravel Version: 10.0.3
- PHP Version: 8.1.0
- Database Driver & Version: mysql & 5.7

### Description:
laravel 10 update:
![image](https://user-images.githubusercontent.com/33448724/219588858-b5c68382-875d-4411-8594-fc476e0208b7.png)

passport token model problem:
![image](https://user-images.githubusercontent.com/33448724/219589446-75ae9940-eef5-4836-8c56-b34666765143.png)

**Comment by driesvints** [comment]
I'll fix this.

**Comment by driesvints** [comment]
Ah you sent in a PR. Thanks
