### ISSUE TITLE
Got time out when call POST: /oauth/token

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/passport#1641]
- Passport Version: 11.8.2
- Laravel Version: 9.52.4
- PHP Version: 8.2.3
- Database Driver & Version: postgresql 15

### Description:
Got time out when call `POST: /oauth/token`. And it still create access_token in database after return timeout, But response timeout.

Although I set timeout in `Http` for 3 seconds it still got timeout, And access_token still appear in database 

<img width="1680" alt="Screen Shot 2566-02-25 at 20 21 56" src="https://user-images.githubusercontent.com/6513358/221360144-36ed55a6-02ca-48b4-856a-0ff0e6a3d8b8.png">

### Steps To Reproduce:

Run your server with `php artisan serve`. You will get this error.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
