### ISSUE TITLE
the first query of passport to begin authenticate the user  it tooks very slow

### ISSUE THREAD

**Issue by atrialabir** [laravel/passport#1652]
- Passport Version: ^11.8
- Laravel Version: ^10
- PHP Version: 8.1
- Database Driver & Version: MySQL latest

everything is  fine in localhost but in the server, with 16 GB memory ram and 12 core CPU the first query of passport which want to authenticate the user takes a very long

Based on the Laravel telescope 

![image](https://user-images.githubusercontent.com/125481824/230168332-61880339-a078-4ba9-a62b-b627feebd279.png)

notice the oauth_access_tokens has 26 rows and doesn't have a lot of rows and this query which is my first query to the database in all requests
it took between 80 to 150 ms on average

I increase the InnoDB buffer pool size in MySQL to 512MiB and the memory limit for PHP is 256MB
but It does not improve it

**Comment by driesvints** [comment]
We'd welcome PRs to make this faster, thanks.
