### ISSUE TITLE
Laravel Passport 11.8.6

### ISSUE THREAD

**Issue by zucandu** [laravel/passport#1657]
### Passport Version

11.8.6

### Laravel Version

9.52.7

### PHP Version

8.1.13

### Database Driver & Version

10.3.38-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

### Description

Hello,

I'm using multiple guards from Laravel Passport. For the new version, I can't login to my admin panel, it shows the error message: "Unauthenticated".

Then I tested it with 2 old versions of Laravel Passport:

11.3.1 and 10.4.1 and all works fine so I think there is some problem with the new version of Laravel Passport.

Best regards,

Chu

### Steps To Reproduce

This is a closed source so I can't share it however I can provide any info if you need.

**Comment by driesvints** [comment]
Ping @michaelnabil230

**Comment by driesvints** [comment]
@zucandu does 11.8.5 work for you?

**Comment by michaelnabil230** [comment]
Hello,

Based on the information you provided, it seems that there might be an issue with the latest version of Laravel Passport. However, to help you better, I would need more details on how you are using multiple guards with Laravel Passport, and whether you are using a custom function for login or not.

And if you can create a new repository for your code example make that

Please let me know if you have any further questions or if you need any more assistance.

**Comment by zucandu** [comment]
Hello Mike,

Thank you for replied. I will make a details.

Before, I tried to install again with 11.3.1 and it works. I will try to install with 11.8.5 and show you, too.

I will update you after a few hours.

Best regards,

Chu

**Comment by zucandu** [comment]
Hello,

I tried to install the Laravel Passport 11.8.5 and it works well. I attached 3 images files so that you can check it. If you need more information, please let me know.

I will try to install again with the latest Laravel Passport and show you the result.

![1](https://user-images.githubusercontent.com/114129264/235040759-4e3c700b-e7da-4038-9087-0104a706e5f6.png)
![2](https://user-images.githubusercontent.com/114129264/235040768-62478906-a9b6-489f-a066-d8e221576b02.png)
![3](https://user-images.githubusercontent.com/114129264/235040773-ccb4aea3-6bc5-4593-98cb-2771fd2a4074.png)

**Comment by zucandu** [comment]
11.8.6 not working. I attached the images for more information.
![4](https://user-images.githubusercontent.com/114129264/235042159-91552f74-a62e-4ccc-b6c0-d921c6ee5ed2.png)
![5](https://user-images.githubusercontent.com/114129264/235042167-696bb993-d92b-4445-9280-641c68ec0ed5.png)

**Comment by michaelnabil230** [comment]
Hello,

However, you can try using `api-apps` as the provider and see if it works for your use case. If you encounter any issues or errors, please provide more details so that I can assist you better.

And can take a screenshot of table `oauth_clients` can be helpful in identifying any issues related to you.

If you have any further questions or concerns, please feel free to let me know.

Best regards,

Michael

**Comment by zucandu** [comment]
Thank you Mike,

For the api-apps, I did not try however I tried to use with admin and customer. When I login, it does not work. When I try to register a new account, it does not work, too. The same error with admin: Unauthenticated.

I will show you the oauth_clients table. 

I have an example website, you can use it here

https://6dep.com/admin/
cvhainb@gmail.com
EWL8FtHm

You can try to create a new customer account at https://6dep.com/register

Best regards,

Chu

**Comment by michaelnabil230** [comment]
I'm fixed this issue and now can test the multi auth

Follow the example application with PR: https://github.com/michaelnabil230/multi-auth-laravel-passport

**Comment by driesvints** [comment]
We've reverted the PR for now.
