### ISSUE TITLE
user authentication not detected on non-API routes in Laravel and Vue SPA

### ISSUE THREAD

**Issue by saeeddarestany** [laravel/passport#1661]
### Passport Version

11.08

### Laravel Version

10

### PHP Version

8.1.4

### Database Driver & Version

mysql 8

### Description

I have Laravel and Vue.js project. The frontend is implemented as a single-page application (SPA) accessible via the route panel.foo.com, while the login route is api.foo.com/login and belongs to the api middleware group. When a user  login successfully, a token is received and stored in the SPA, and there is no issue with that. However, when I go to the main page with the URL foo.com that non spa just blade, which belongs to the web middleware group  the login user not detected, and the laravel_token cookie is not created.

I have added the CreateFreshApiToken::class middleware to the web middleware group, but it didn't solve the problem. In the controller of the main page, I have used
` dd(auth()->check(),auth('api')->check())
` 
and both return false.
I have checked the middleware group, and CreateFreshApiToken::class exists in the web middleware group. However, when using the panel APIs, which belong to the api middleware group, the CreateFreshApiToken::class is not executed to create the laravel_token cookie. When I go to the main page, and CreateFreshApiToken::class is executed, it reaches $request->user($this->guard), and it is null. Therefore, the laravel_token cookie is not created.

Here are my auth configuration settings:

session_domain set to .foo.com

```
'defaults' => [
'guard' => 'web',
'passwords' => 'users',
],

'guards' => [
'web' => [
'driver' => 'session',
'provider' => 'users',
],
'api' => [
'driver' => 'passport',
'provider' => 'users',
],
],
```

And here is my kernel.php file:

```
protected $middlewareGroups = [
'web' => [
\App\Http\Middleware\EncryptCookies::class,
\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
\Illuminate\Session\Middleware\StartSession::class,
\Illuminate\View\Middleware\ShareErrorsFromSession::class,
\App\Http\Middleware\VerifyCsrfToken::class,
\Illuminate\Routing\Middleware\SubstituteBindings::class,
\Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
],

'api' => [
    \Illuminate\Routing\Middleware\ThrottleRequests::class . ':api',
    \Illuminate\Routing\Middleware\SubstituteBindings::class,
],
];

```
What could be the issue here?

### Steps To Reproduce

.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
