### ISSUE TITLE
Composer dependency conflict on fresh laravel 10

### ISSUE THREAD

**Issue by zerosdev** [laravel/passport#1663]
### Passport Version

^11.8

### Laravel Version

^10.8

### PHP Version

8.1.3

### Description

I have fresh installed laravel 10 with `composer create-project --prefer-dist laravel/laravel`

Then i tried to install passport with `composer require laravel/passport` but got this error

 Problem 1
    - laravel/passport[v11.8.5, ..., v11.8.7] require league/oauth2-server ^8.5.1 -> satisfiable by league/oauth2-server[8.5.1].
    - laravel/passport[v11.8.0, ..., v11.8.4] require league/oauth2-server ^8.2 -> satisfiable by league/oauth2-server[8.2.0, ..., 8.5.1].
    - league/oauth2-server[8.2.0, ..., 8.5.1] require psr/http-message ^1.0.1 -> found psr/http-message[1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel/passport ^11.8 -> satisfiable by laravel/passport[v11.8.0, ..., v11.8.7].
    
Tried to use --with-all-dependencies option but it looks like psr/http-message downgraded to 1.1 so idk what the side effect

### Steps To Reproduce

1. `composer create-project --prefer-dist laravel/laravel`
2. `composer require laravel/passport`

**Comment by driesvints** [comment]
Use `composer require laravel/passport -W`

**Comment by driesvints** [comment]
Use `composer require laravel/passport -W`

**Comment by mreall** [comment]
Thanks @driesvints. Perhaps the docs should be updated to include the '-W' flag so developers don't waste time trying to figure this out.
