### ISSUE TITLE
is not installed in a newly created project

### ISSUE THREAD

**Issue by yottybyte** [laravel/passport#1668]
### Passport Version

11.8.7

### Laravel Version

10.2.2

### PHP Version

8.2.4

### Description

1. created a project via `laravel new api`
2. `cd api`
3. `composer require laravel/passport`

got this error:
<img width="1495" alt="Снимок экрана 2023-05-27 в 12 49 00" src="https://github.com/laravel/passport/assets/39698457/b8bd3cd3-fd40-49d5-992f-b0b9bfa4a931">

### Steps To Reproduce

1. created a project via `laravel new api`
2. `cd api`
3. `composer require laravel/passport`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by robbanl** [comment]
I just got the same problem doing a fresh install on a new project. I manually ran `sail composer require league/oauth2-server` but then it starts to complain about Guzzle 6 not being there.
