### ISSUE TITLE
Upgrade underlying library: thephpleague/oauth2-server

### ISSUE THREAD

**Issue by Smoggert** [laravel/passport#1673]
### Passport Version

11.*

### Laravel Version

10.*

### PHP Version

8,2~

### Database Driver & Version

N.A.

### Description

Updating `thephpleague/oauth2-server` to 8.5.2 would allow for a smoother passport install.
L10 tries to fix dependency psr/http-message to 2.*
Oauth 8.5.1< tries to fix it 1.*

The new release allows use of 2.* creating a smoother compose for L10.
https://github.com/thephpleague/oauth2-server/releases/tag/8.5.2

### Steps To Reproduce

Fresh install L10.
Composer require passport. Composer asks to:

`Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

**Comment by driesvints** [comment]
Thanks but you should already be able to install this version. I'll merge your PR though
