### ISSUE TITLE
Create token issue

### ISSUE THREAD

**Issue by irmuunM** [laravel/passport#1675]
### Passport Version

^10.0

### Laravel Version

^8.0

### PHP Version

8.0.13

### Database Driver & Version

5.7.41

### Description

Call to a member function forceFill() on null

$user->createToken('foo-bar')->accessToken;

contains error which is 

$token = tap($this->findAccessToken($response), function ($token) use ($userId, $name) {
    $this->tokens->save($token->forceFill([
        'user_id' => $userId,
        'name' => $name,
    ]));
});

there sometimes gives error commonly working fine but sometimes gives error is there any good solution except retry

### Steps To Reproduce

$token = tap($this->findAccessToken($response), function ($token) use ($userId, $name) {
    $this->tokens->save($token->forceFill([
        'user_id' => $userId,
        'name' => $name,
    ]));
});

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
