### ISSUE TITLE
Error Method Laravel\Passport\Guards\TokenGuard::attempt does not exist When using 'api' guard

### ISSUE THREAD

**Issue by Mohdk911** [laravel/passport#1681]
### Passport Version

11.8.8

### Laravel Version

10.19.0

### PHP Version

8.1.22

### Database Driver & Version

MySQL 8.0.34, SQLite 3

### Description

Error Method Laravel\Passport\Guards\TokenGuard::attempt does not exist when use Passport::actingAs with 'api' guard when do login user via Auth::attempt()

### Steps To Reproduce

Error Method Laravel\Passport\Guards\TokenGuard::attempt does not exist when use Passport::actingAs with 'api' guard when do login user via Auth::attempt()

**Comment by Mohdk911** [comment]
@crynobone 
But it seems that it's a bug with the library it self since it's working with guard 'web' but it's not working with guard 'api'

**Comment by crynobone** [comment]
What you describe is the expected behaviour, you can learn more by asking in any support channels as suggested.
