### ISSUE TITLE
Some tables does not meet Laravel standards

### ISSUE THREAD

**Issue by nastoychev** [laravel/passport#1685]
In whole Laravel Ecosystem the tables start with id of type bigIncrements and have by default timestamps. 
Here this convention is not followed. 
The problem what I have is reduced combability with Laravel Nova beacuse the action_events table does not support id of type varchar(100).

The tables are: 

- oauth_auth_codes: no id of type bigIncrements, no timestamps
- oauth_access_tokens: no id of type bigIncrements
- oauth_refresh_tokens: no id of type bigIncrements, no timestamps

In my opinion, the problem applies both to this project and to a Laravel/Nova one that does not allow support for other types of Ids.

**Comment by driesvints** [comment]
Welcoming PRs, thanks.
