### ISSUE TITLE
Test Refresh Token Fails on Google Home Test Suite

### ISSUE THREAD

**Issue by w1lldone** [laravel/passport#1691]
### Passport Version

^11.8

### Laravel Version

^10.0

### PHP Version

8.1

### Description

Hello everyone, i've been using oauth2-server, along with Laravel Passport to build an integration for Google Home Cloud to Cloud. We have encountered a test failure within the Google Home Test Suite:

![image](https://github.com/laravel/passport/assets/19965509/796dae63-f84e-4b97-8501-df4341f5d49e)

> Error happened during refresh with invalid token. This is likely because partner didn't return invalid_grant with 400. Please check Cloud log if this provider has been associated with cloud project id.;Refresh token has been rotated. This is not forbidden, however we do not see much benefit that rotating the refresh token can provide but the potential problem it has. We also tried to refresh token with the old refresh token after it has been rotated. Refresh didn't work, this means partner invalidated the old refresh token right after the rotation. Partners shall only invalidate the old refresh token after seeing we use the new one to ensure we got it successfully.;: expected 'FAIL' to not equal 'FAIL'

Is anyone else experiencing this issue?

### Steps To Reproduce

Do a test suite for Google Home Cloud to cloud integration.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
