### ISSUE TITLE
Return revokeRefreshTokensByAccessTokenId result

### ISSUE THREAD

**Issue by aminkhoshzahmat** [laravel/passport#1692]
I was trying to check if the refresh token was revoked successfully, but the corresponding method `revokeRefreshTokensByAccessTokenId` doesn't return anything in `RefreshTokenRepository.php`

```php
public function revokeRefreshTokensByAccessTokenId($tokenId)
{
    Passport::refreshToken()->where('access_token_id', $tokenId)->update(['revoked' => true]);
}
```

Would it be possible to return the statement result?

**Comment by driesvints** [comment]
Looks like you already sent in a PR so let's see how it goes 👍

**Comment by aminkhoshzahmat** [comment]
@driesvints Thanks.
