### ISSUE TITLE
Guard API support in laravel passport

### ISSUE THREAD

**Issue by ezequidias** [laravel/passport#1694]
I believe there should be two more options in the laravel passport settings! one for driver giving the possibility to choose between session, redis, database!
And another to enable views!

One of the biggest problems with laravel passport today is that it is 100% dependent on standard web systems (this is based on sessions and laravel blade views)

but it is extremely important that the laravel passport is independent of the web guard!

`config/passport.php`
`views = true` `return \Laravel\Passport\Contracts\AuthorizationViewResponse`
`views = false,` `return Illuminate\Http\Resources\Json\JsonResource`
![Screenshot_select-area_20231027200132](https://github.com/laravel/passport/assets/25870781/e9759d07-3b07-457b-a687-00abb346095b)

With these new improvements it is possible to use Laravel Passport 100% as an API and be able to work on the client side with frameworks (Vue.js, Nuxt.js, Next.js, React.js, Angular.)

`driver => 'session', // session, redis, database` for example
![Screenshot_select-area_20231027200930](https://github.com/laravel/passport/assets/25870781/c2a34d96-1f32-4641-9399-053596324289)

**Comment by ezequidias** [comment]
@taylorotwell

**Comment by driesvints** [comment]
Right now we don't have any plans to make big changes here sorry.
