### ISSUE TITLE
Wrong Callback URL Domain

### ISSUE THREAD

**Issue by mimbar** [laravel/passport#1700]
### Passport Version

11.10

### Laravel Version

10.32.1

### PHP Version

8.1.20

### Description

My main apps is have passport with different domain.

production domain:
main: main.domain.ac.id
passport: gate.domain.ac.id

local domain:
main: sintesys.test
passport heimdall.test

in local development, everything going smooth. after redirect on main apps, it goes to passport and callback to redirect_uri. 

But when in production, after redirect on main apps, it goes to passport and then callback to passport domain with same callback path as main apps.

this is wrong:
main.domain.ac.id -> gate.domain.ac.id -> gate.domain.ac.id/callback-of-main-domain

it should be like this:
main.domain.ac.id -> gate.domain.ac.id -> main.domain.ac.id/callback-of-main-domain

### Steps To Reproduce

1. request redirect
2. login in passport
3. redirect to redirect_uri callback

But when in production, after redirect on main apps, it goes to passport and then callback to passport domain with same callback path as main apps.

this is wrong :
main.domain.ac.id -> gate.domain.ac.id -> gate.domain.ac.id/callback-of-main-domain

it should be like this:
main.domain.ac.id -> gate.domain.ac.id -> main.domain.ac.id/callback-of-main-domain

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
