### ISSUE TITLE
While actingAsClient add a bearer token

### ISSUE THREAD

**Issue by SuperDJ** [laravel/passport#1703]
When testing I ran into an issue with the `actingAsClient` method not setting a bearer token. The issue is that `$request->bearerToken()` is always empty when using `actingAsClient`. I think automatically setting a bearer token when using `actingAsClient` could help. If it shouldn't be set automatically perhaps it can be set with a parameter. Either by providing a bearer token or a boolean.

**Comment by driesvints** [comment]
Thank. Feel free to attempt a PR 👍
