### ISSUE TITLE
Authorization header with small b in "Bearer"

### ISSUE THREAD

**Issue by salarAsadi** [laravel/passport#171]
I have been sending my access tokens to server, using small b in "Bearer "and I received 
{"error":"Unauthenticated."}
It is crazy!!!!!
please fix. it should not be case sensitive.

**Comment by Rkallenkoot** [comment]
Not sure if this helps, but according to the OAuth 2.0 RFC6750, "Bearer" is **case-sensitive**. So it makes sense that a small b "bearer" doesn't work.

see [here](https://tools.ietf.org/html/rfc6750#page-5)

**Comment by craigpaul** [comment]
"Unless otherwise noted, all the protocol parameter names and values are case sensitive"

Agreed @Rkallenkoot, all the parameter names are case sensitive so this issue should be closed.

**Comment by jbrooksuk** [comment]
Weirdly though, HTTP headers should be case insensitive according to RFC 7230-7237.
