### ISSUE TITLE
whenever i try to install passport, laravel latest application

### ISSUE THREAD

**Issue by muhammadsanwarulislam** [laravel/passport#1713]
![Screenshot (225)](https://github.com/laravel/passport/assets/29992994/0aaea069-aace-4946-8dd5-8622a641afa5)

**Comment by rojtjo** [comment]
It looks like it tries to install Laravel Passport 11 which only has support for Laravel 9 & 10.
Try installing version 12 explicitly like this: `composer require laravel/passport:^12.0@dev`

**Comment by muhammadsanwarulislam** [comment]
![Screenshot (227)](https://github.com/laravel/passport/assets/29992994/4447dad3-480a-4e4b-bfff-fa552d220ed4)

**Comment by rojtjo** [comment]
With all the deprecation warnings it feels like you're running an old version of composer. Try updating your composer using `composer self-update` and then running the same command again.

**Comment by muhammadsanwarulislam** [comment]
It's work for to execute `composer require laravel/passport dev-master`

**Comment by crynobone** [comment]
Laravel Framework 11 has not been officially released yet.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
