### ISSUE TITLE
no install the passport with laravel 19

### ISSUE THREAD

**Issue by theEngMansour** [laravel/passport#1718]
### Passport Version

10.0.1

### Laravel Version

10.4.1

### PHP Version

8.1.4

### Database Driver & Version

mysql local

### Description

![التقاط](https://github.com/laravel/passport/assets/73757452/238e1bf0-6809-418b-afa6-cef20706bc2b)
no install passport with laravel

### Steps To Reproduce

no install passport with laravel

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
