### ISSUE TITLE
api_token column not found in users table.

### ISSUE THREAD

**Issue by ak-incaendo** [laravel/passport#172]
QueryException in Connection.php line 769:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'api_token' in 'where clause' (SQL: select * from `users` where `api_token` = {key} limit 1)

I am getting the above error in postman after /api/user api hit. 

referring: https://laravel.com/docs/5.3/passport

**Comment by Modelizer** [comment]
I'm quite sure `api_token` will not be present.

Please give us more details what are you trying to achieve?

**Comment by ak-incaendo** [comment]
Hi I want to achieve authentication of api on web (using vue js). I followed the laracast tutorials + laravel official website to configure the passport in my application. 

The installation was successfully completed, no error occurred. Then I created a personal access token which gives me a long encoded string. Then I use the same string to access the default api provided by laravel, with following details, in postman:

URL: {base_url}/api/user
Headers:  Authorization: Bearer {key}, Accept: application/json

But it returns 'api_token' not found exception.

**Comment by craigpaul** [comment]
@ak-incaendo Did you switch the line in `config/auth.php` for your api guard driver?

```php
...
'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],
    'api' => [
        'driver' => 'token', // this should say passport
        'provider' => 'users',
    ],
],
...
```

The only reason `api_token` should be getting checked is if you are using the `token` driver instead of `passport`. Hope that fixes your problem.
