### ISSUE TITLE
Passport Failed Install In Laravel 11

### ISSUE THREAD

**Issue by deyan-ardi** [laravel/passport#1737]
### Passport Version

Default Laravel 11

### Laravel Version

11.3.1

### PHP Version

8.3.2

### Description

![gambar](https://github.com/laravel/passport/assets/60816261/5f8a3da6-da7d-48e4-aaa9-693cb8454d05)
Failed to install laravel 11 using `php artisan install:api --passport` using php 8.3.2, please help. Thanks you

### Steps To Reproduce

1. Set php to 8.3.xx
2. Install laravel 11 `composer create-project laravel/laravel <name project>`
3. run `php artisan install:api --passport`
4. im get the error

**Comment by taftse** [comment]
You need to install the sodium extension (ext-sodium) for PHP please see [https://www.php.net/manual/en/sodium.installation.php](https://www.php.net/manual/en/sodium.installation.php)

**Comment by deyan-ardi** [comment]
Okay thanks for information
