### ISSUE TITLE
Adding Middlware that runs before Passport routes

### ISSUE THREAD

**Issue by huntsfromshadow** [laravel/passport#174]
Is their anyway to install a custom middleware to run
on all the Passport routes? 

I would like to do some preliminary filtering (disabling certain grants, checking for some other things) before the request goes through to passport.

**Comment by huntsfromshadow** [comment]
Found out how.

        Route::group(['middleware' => "mycustom"], function() {
            Passport::routes();
        });

**Comment by corbosman** [comment]
Just for future reference you can also do:

`
Passport::routes(null, ['middleware' => 'mycustom']);
`
