### ISSUE TITLE
Token Revocation Notifications

### ISSUE THREAD

**Issue by bitcookr** [laravel/passport#1754]
Currently, when an access token or refresh token is revoked in Passport, clients are unaware of this change until they attempt to use the revoked token and receive an error.
Can you add a feature like sending notifications to clients when an access token or refresh token is revoked?
This can be implemented using Laravel's event system to dispatch events upon token revocation, and allowing clients to register listeners for these events.

**Comment by crynobone** [comment]
There's no plan for it at the moment I'm afraid
