### ISSUE TITLE
Laravel/Passport Installation Error Cause of HasApiTokens Trait

### ISSUE THREAD

**Issue by alpemreelmas** [laravel/passport#1760]
### Passport Version

12

### Laravel Version

11.9

### PHP Version

8.2

### Database Driver & Version

10.4.32-MariaDB - mariadb.org binary distribution

### Description

# Receiving error when you try to use User model

## Installation
I've done everything according to documentation. Termınal even said to me to add traits to the user model. 

![image](https://github.com/laravel/passport/assets/62440706/2ffd6f97-1032-47b2-80e7-1cdc907f3e46)

## Error receiving part
When I tried to register it threw me an error

![Screenshot 2024-06-25 211009](https://github.com/laravel/passport/assets/62440706/bd2897eb-ddf7-4172-80cf-f8fbf6aa2e5f)

## My composer file is:

![image](https://github.com/laravel/passport/assets/62440706/7bf2fbeb-6d7a-469b-a962-305fada1cc22)

## Documantation
In the documentation there is nothing more step to install passport. I also tried to install via 
`composer require laravel/passport`
It says that composer requirements are not resolved.

![image](https://github.com/laravel/passport/assets/62440706/08807c49-45dd-4bf8-8c5d-00756c9e3b5e)

### Steps To Reproduce

to reproduce this issue just create a laravel application and just follow documentation of laravel/passport 11.x

**Comment by hafezdivandari** [comment]
The Composer error is clear: Install or enable PHP's sodium extension.

**Comment by alpemreelmas** [comment]
> The Composer error is clear: Install or enable PHP's sodium extension.

But the thing is I installed by myself via composer require laravel/passport 
So this is not in the docs

If code runs this under the hood, it doesn't throw an error

**Comment by alpemreelmas** [comment]
After a couple of tests, enabling the extension doesn't throw an error. But the point is information of the user so you should show a more detailed error response.

**Comment by driesvints** [comment]
I think the issue is clear here. You need the sodium extension. Even after installing passport, sub-dependencies can require new extensions like the case here.

**Comment by alpemreelmas** [comment]
> I think the issue is clear here. You need the sodium extension. Even after installing passport, sub-dependencies can require new extensions like the case here.

Yes because I run the command by myself documentation suggestion composer script doesn't throw an error so the part that you said error is clear, was my research it didn't thrown by the command that documentation says this is more than issue the thing that you have to make clear in the documentation I think
