### ISSUE TITLE
Mongodb support 

### ISSUE THREAD

**Issue by mh97m** [laravel/passport#1765]
I am currently working on a project that uses MongoDB with Laravel. However, I have encountered an issue where Laravel Passport does not support MongoDB out of the box. 

 To make it work, I have to manually replace the Laravel model usages in the `vendor` folder of the package with MongoDB models. This is not an ideal solution as it requires manual intervention and complicates the update process.

**Comment by driesvints** [comment]
Thanks. I'm sorry but MongoDB isn't [an official database engine provided by Laravel](https://laravel.com/docs/11.x/database#introduction) and we currently have no plans to add one.

**Comment by uriel2707** [comment]
Hi, @mh97m  this patch can help you.
https://packagist.org/packages/webdecero/webdecero-package-laravel-passport
