### ISSUE TITLE
your php version (8.0.2) does not satisfy that requirement.

### ISSUE THREAD

**Issue by cgr20171202** [laravel/passport#1779]
laravel/passport could not work on php version 8.0.2？what could I do to solve the problem?
my laravel/framework version is  v9.52.16.
My OS is windows 11 home edition.
When I try to install laravel/passport v10.1.0，the errors are shown below:
```
composer require laravel/passport:10.1.0
./composer.json has been updated
Running composer update laravel/passport
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/passport 10.1.0 -> satisfiable by laravel/passport[v10.1.0].
    - laravel/passport v10.1.0 requires illuminate/auth ^8.2 -> found illuminate/auth[v8.2.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
