### ISSUE TITLE
Repeated migrations created with 'php artisan passport:install ' command without existence check

### ISSUE THREAD

**Issue by Ozckar07** [laravel/passport#1781]
### Passport Version

12.3

### Laravel Version

11.9

### PHP Version

8.2.0

### Description

When executing the php artisan passport:install command in a Laravel project, it generates new migration files without checking if they already exist. As a result, each time the command is run, duplicate migration files are created, leading to multiple copies of the same migrations. This causes errors during the migration process because the migration files already exist and cannot be executed again, leading to database conflicts.

### Steps To Reproduce

1. Set up a fresh Laravel project with Laravel Passport.
2. Run php artisan passport:install once to generate the initial migrations.
3. Run php artisan passport:install again and notice that new migration files are created, duplicating the previous ones.
4. Repeat the command, and each time, new copies of the same migrations are generated.

**Expected behavior:**
The php artisan passport:install command should check if the migrations already exist before generating new ones, preventing the creation of duplicate migration files.

**Actual behavior:**
Each time the command is executed, duplicate migration files are created, causing an error during the migration execution due to the presence of existing migration files.

**Comment by driesvints** [comment]
It's expected to only run this command once.

**Comment by Ozckar07** [comment]
"In previous versions of Laravel, it was possible to run the php artisan passport:install command multiple times without issues, as the command would simply proceed if there were no migrations pending, allowing the generation of new CLIENT_ID values. However, in Laravel 11, running this command more than once leads to the replication of the Passport migrations, as you can see in the output. This is because each time the command is executed, it attempts to publish the migrations again and prompts for running them. If the encryption keys already exist, the command throws an error unless the --force option is used. Therefore, this command should now only be run once, unless there's a specific reason to overwrite the existing keys or re-migrate, to avoid unnecessary duplication or errors."


`PS C:\Users\app> php artisan passport:install

   ERROR  Encryption keys already exist. Use the --force option to overwrite them.

   INFO  Publishing [passport-migrations] assets.

  Copying directory [C:\Users\app\database\migrations]  DONE

 Would you like to run all pending database migrations? (yes/no) [yes]:
 > y

   INFO  Nothing to migrate.

 Would you like to create the "personal access" and "password grant" clients? (yes/no) [yes]:
 > y

   INFO  Personal access client created successfully.

  Client ID ........................................................ 3
  Client secret ............. nvAmoD4GraSdSaSI1M5cBK49PiR0NgVEGLI86Uo5

   INFO  Password grant client created successfully.

  Client ID ........................................................ 4
  Client secret ............. Vhm4ehQPZMxFBtj6wk672CcIvNvs2MZijprXFi3b
PS C:\Users\app>`

**Comment by Ozckar07** [comment]
This command is executed every time a project is initialized on the server because it's the fastest way to run the migrations and generate the client_id. However, once I already have the code with the migrations ready, including the Passport migrations, running this command again causes the migrations to be duplicated and will always result in errors, since the migrations already exist in the project.
