### ISSUE TITLE
This line must be added in the docs to prevent empty or null user beeing returned in the callback route when using the library with socialite

### ISSUE THREAD

**Issue by SantosVilanculos** [laravel/passport#1800]
### Passport Version

12

### Laravel Version

11

### PHP Version

8.2

### Database Driver & Version

MySQL 8 - Debian 12 

## Issue
Developers may accidentally remove a critical authentication route.
This route is essential for Socialite Passport provider functionality.
Removal breaks user authentication mechanisms.

## Solution

On `api.php`

```php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

// WARNING: Don't remove, socialite passport provider relies on this route to get user
Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:api');
```

## Prerequisite Setup

1.  A Laravel application with Laravel Passport
2.  A second Laravel application with Laravel Socialite and  Socialite Passport  provider driver package installed
2.1. [Socialite Passport  provider driver configured](https://socialiteproviders.com/Laravel-Passport/)

## Expected Results
- Successful user authentication
- [Retrieval of authenticated user object on callback route](https://laravel.com/docs/11.x/socialite#retrieving-user-details) 

---

### 1. Remove or Comment Out Critical User Route
// PROBLEMATIC: Removing this route breaks authentication
// Route::get('/user', function (Request $request) {
//     return $request->user();
// })->middleware('auth:api');

### 2. Attempt Authentication Flow
- Use Socialite to initiate login
- Verify user retrieval endpoint
- Check for null or empty user returns

## Actual Results
-- Authentication failure
-- Null or empty user object returned
-- Potential login process interruption

**Comment by crynobone** [comment]
Hi there,

We don't maintain https://socialiteproviders.com/Laravel-Passport/ and is not able to provide support. Please submit the report to https://github.com/SocialiteProviders/Providers
