### ISSUE TITLE
How can I delay token revocation?

### ISSUE THREAD

**Issue by ServiceTo** [laravel/passport#194]
I'm writing a chatty ember-cli front-end app and I'm finding that it's sending multiple requests asynchronously to my Laravel back-end and what's happening is the token is being revoked in the same second as another request comes in so the new token hasn't made it back to the front-end for use yet.  This provides an exception on the second request and the user has to log in again.

What is the best way to delay these lines from running in RefreshTokenGrant.php from respondToAccessTokenRequest()  (without forking, if possible)
```
// Expire old tokens
$this->accessTokenRepository->revokeAccessToken($oldRefreshToken['access_token_id']);
$this->refreshTokenRepository->revokeRefreshToken($oldRefreshToken['refresh_token_id']);
```

Thanks in advance for any advice

**Comment by craigpaul** [comment]
Hey @ServiceTo, that functionality has already been deprecated as of this pull request #186.

Update to the newest version and you will be able to control when tokens get revoked using the new events that Passport fires off. Hope that solves your problem.

**Comment by craigpaul** [comment]
What type of grant are you using and what did you use for the following `$expiry` variables in your AuthServiceProvider.

```
Passport::tokensExpireIn($expiry);

Passport::refreshTokensExpireIn($expiry);
```

Your tokens shouldn't be expiring that quickly unless you set a small time period here.

**Comment by ServiceTo** [comment]
Hey @craigpaul, I had tokens set for 15 minutes and refresh for an hour.  I like your first reply better, going to jump up to master branch and see what damage I can do.

**Comment by ServiceTo** [comment]
Looks like my code in question is a result of thephpleague/oauth2-server.

Their suggestion is to make the front-end app back-off and come back, which is what I tried initially but couldn't get resolved.  Back to the drawing board...
