### ISSUE TITLE
isRefreshTokenRevoked is not working with MongoDB

### ISSUE THREAD

**Issue by giorgosavgeris** [laravel/passport#204]
I use Passport and moloquent as database driver.

However, `isRefreshTokenRevoked` queries with revoked 1 but 1 does now work with MongoDB and  I think should be changed to true.

**Comment by craigpaul** [comment]
I believe there were previous PRs about this same thing but they must have missed some off them. Feel free to make a quick PR, very likely it will get accepted pretty easily.

**Comment by giorgosavgeris** [comment]
Thank you @craigpaul. I have created a PR.

**Comment by craigpaul** [comment]
Awesome @giorgosavgeris! Don't forget to close this issue, thanks!
