### ISSUE TITLE
[feature-request] Make key paths configurable

### ISSUE THREAD

**Issue by RyanThompson** [laravel/passport#208]
Overall Laravel makes it pretty easy for a stack like Pyro to run multiple "apps" on one install. We prefix paths a lot. Mostly due to being able to configure paths among other things.

IMO the storage path for the private / public keys should be configurable to continue allowing this kind of flexibility that's found across the framework.

For example, in our case, we'll want keys per app within the Pyro installation and as it is now there would be a TON of overriding in order to just provide our own keys from an alternate path.

**Comment by craigpaul** [comment]
Hey @RyanThompson that was actually added already. Check [here](https://github.com/laravel/passport/blob/1.0/src/Passport.php#L276) for the `loadKeysFrom()` method.

**Comment by RyanThompson** [comment]
Fantastic, thanks for the heads up!
