### ISSUE TITLE
Token Request : Additional User Model Conditions

### ISSUE THREAD

**Issue by gauravmak** [laravel/passport#225]
I am building an API for mobile application using _Password Grant Tokens_. When user tries to login to the application, client sends a request for the access token.

It is possible that the user has not verified his account using the link sent to his email. I wish to add an additional condition to the query and provide error response accordingly. Currently, as Passport manages token part, I can't do it directly.

How can this be solved? How can I dive in the token request and send custom response if there are any issues with user account? And continue sending token otherwise.

**Comment by etelford** [comment]
If I understand you correctly, I solved this as follows:

I made my own `oauth/token` route and put it in an `oauth.php` file within `/routes`:

```php
Route::post('/oauth/token', [
    'uses' => 'Auth\CustomAccessTokenController@issueInvestorToken'
]);
```

Then I have my `CustomAccessTokenController.php`:

```php
<?php

namespace App\Http\Controllers\Auth;

use Psr\Http\Message\ServerRequestInterface;
use Laravel\Passport\Http\Controllers\AccessTokenController;

class CustomAccessTokenController extends AccessTokenController
{
    /**
     * Hooks in before the AccessTokenController issues a token
     *
     *
     * @param  ServerRequestInterface $request
     * @return mixed
     */
    public function issueInvestorToken(ServerRequestInterface $request)
    {
        $httpRequest = request();

        // 1.
        if ($httpRequest->grant_type == 'password') {
            // 2.
            $user = \App\User::where('email', $httpRequest->username)->first();

            // Perform your validation here

            // If the validation is successfull:
            return $this->issueToken($request);
        }
    }
}
```

**Comment by themsaid** [comment]
@gauravmak please take a look at @etelford comment, I believe it's a very good solution to your problem.

**Comment by gauravmak** [comment]
Yes, thanks @etelford and @themsaid.

**Comment by gauravmak** [comment]
@etelford Do I have to name the new route file to be **oauth.php**? And how to connect that with _Passport_?

**Comment by gauravmak** [comment]
And @themsaid, when is the next release schedules? Waiting for few things which are already added to master.

**Comment by etelford** [comment]
@gauravmak You don't have to, but this is what I chose to do to keep it separate from my `web` and `api` routes. You can just as easily put it in `web.php`.

**Comment by gauravmak** [comment]
Thanks.

**Comment by ederb11c** [comment]
Hello all, i tested this solution but i get a TokenMismatchException. any solution for this?

**Comment by mohamedrasvi** [comment]
Hi
is there way with access token send a extra value or parameter?
What I want is, when I issue a access token I want to send  an other value to identify this token belongs to this campaign so only user can access to particular campaign area

**Comment by vahed-mrv** [comment]
Hi
When we use this solution, other `grant_type`s except `password grant type`  should be implemented in `issueUserToken` function by adding another conditions to it.
Is there any way to extend default passport function?

**Comment by DanielaGenerali** [comment]
> ```
> Route::post('**/oauth/token**', [
>     'uses' => 'Auth\CustomAccessTokenController@issueUserToken'
> ]);
> ```

Right, but i think the route has to be like this:
Route::post(**'token**', [
    'uses' => 'Auth\CustomAccessTokenController@issueUserToken'
]);

Thank you very very much @etelford, it is the perfect solution!

**Comment by javidsapand** [comment]
I get this error after calling issueToken function
Call to a member function respondToAccessTokenRequest() on null

**Comment by michelvambattu** [comment]
> Hi,
> I get this error after calling issueToken function
> Call to a member function respondToAccessTokenRequest() on null

Have you got any solution?

**Comment by taylanunutmaz** [comment]
If you are usign refresh token with oauth. You should move `return $this->issueToken($request);` part to the if conditions outsite.

`<?php

namespace App\Http\Controllers\Auth;

use Psr\Http\Message\ServerRequestInterface;
use Laravel\Passport\Http\Controllers\AccessTokenController;

class CustomAccessTokenController extends AccessTokenController
{
    /**
     * Hooks in before the AccessTokenController issues a token
     *
     *
     * @param  ServerRequestInterface $request
     * @return mixed
     */
    public function issueUserToken(ServerRequestInterface $request)
    {
        $httpRequest = request();

        // 1.
        if ($httpRequest->grant_type == 'password') {
            // 2.
            $user = \App\User::where('email', $httpRequest->username)->first();

            // Perform your validation here
        }
     // If the validation is successfull:
    return $this->issueToken($request);
    }
}
`
