### ISSUE TITLE
Check for userId not empty causes failure for user_id = 0

### ISSUE THREAD

**Issue by wayne5w** [laravel/passport#227]
The change below causes the guard to return and fail if user_id 0 is used.

https://github.com/laravel/passport/commit/f2a8af3a48adac02288779f59de95f46fef69b7a

**Comment by themsaid** [comment]
Hope you managed to get around this, a user with id 0 is pretty odd though :)

Please refer to this comment: https://github.com/laravel/passport/commit/f2a8af3a48adac02288779f59de95f46fef69b7a#commitcomment-20343596

**Comment by wayne5w** [comment]
User_id 0 has special meaning in my system. I don't see why it is either odd or invalid as per the other comment. Shouldn't the check be for null - which is truly invalid?
