### ISSUE TITLE
Question about migrations

### ISSUE THREAD

**Issue by diogoazevedos** [laravel/passport#23]
Why the passport migrations don't have foreign keys? It's a good practice don't have foreign keys in migrations?

**Comment by chrisbratherton** [comment]
I find this to be an interesting question as I have also seen a few packages now ditching them.

**Comment by jbrooksuk** [comment]
Tables which have foreign keys can be hard to rollback, which can be especially annoying in development.

**Comment by diogoazevedos** [comment]
@jbrooksuk Yeah I know, but without foreign key we need to manually garbage collect the unreferred rows.

**Comment by diogoazevedos** [comment]
@themsaid Do you have any answer for this question?

**Comment by themsaid** [comment]
It's just a convention, you can change that in your application if you like :)
