### ISSUE TITLE
There are no commands defined in the "asset" namespace. 

### ISSUE THREAD

**Issue by summermick** [laravel/passport#235]
```
composer require laravel/passport
Using version ^1.0 for laravel/passport
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
> php artisan asset:publish vendor/package

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "asset" namespace.         
                                                                  

Script php artisan asset:publish vendor/package handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

```

I am using laravel5.3 and tried 
`composer require laravel/passport
`

**Comment by alexvanzyl** [comment]
@summermick Seems to me the problem is this command here "php artisan asset:publish vendor/package" there is no artisan command like that unless of course this was manually created. If you check your composer.json under scripts try removing that command.

**Comment by themsaid** [comment]
I think you mean `vendor:publish`:

```
php artisan vendor:publish --tag=passport-components
```

There's no asset:publish command in laravel.

**Comment by newelement** [comment]
I'm having this same issue with fresh Laravel 5.4 install. PHP 7. DigitalOcean server Ubuntu 16.04. Even reset the vendor items, cleared all laravel caches and composer cache. 

php artisan passport:install

[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "passport" namespace.

**Comment by craigpaul** [comment]
@newelement Did you forget to add the service provider to `app.php`
