### ISSUE TITLE
Password Grant, not authenticated response

### ISSUE THREAD

**Issue by skay973** [laravel/passport#240]
Hi,

I just installed passport on my laravel app following the laravel documentation step by step.

My usecase is for a mobile app, consuming my api.
So I created a Password Grant access. I can authenticate a user and get a token and a refresh token. 

I can access api routes protected by auth:api middleware, everything is fine. 

So I tried a call to a protected route without any token in Authorization: Bearer field and as a response I got an html view. More precisely, the html view is the login form of my app... I would like to get a json "Unauthenticated" response or something like that...

What am I missing ? I checked the unauthenticaed exception handler... everything looks fine...

Thanks for you help :)

**Comment by longthanhtran** [comment]
Did you try with non-api routes without token right? If yes then by default, you will be sent back to login form as 'web view' instead of 'api' one.

**Comment by skay973** [comment]
Nope, I tried api routes, without token, to check the response.

**Comment by skay973** [comment]
Ok I figured it out !

I was using Insomnia as a REST client, and I just had to specify the Accept header when sending my http request. With Accept : application/json in headers I know receive a "unauthenticated" json response.
