### ISSUE TITLE
Passport fail to install

### ISSUE THREAD

**Issue by Listen-WebDev** [laravel/passport#245]
i have a message error on install on fresh installation of laravel:

my composer.json
<pre>
<code>

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}

</code></pre>

and my output on command:

`composer require laravel/passport`

output error:

<pre><code>
Using version ^2.0 for laravel/passport
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/passport ^2.0 -> satisfiable by laravel/passport[v2.0.0].
    - laravel/passport v2.0.0 requires illuminate/auth ~5.4 -> satisfiable by illuminate/auth[5.4.x-dev, 5.5.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

</code></pre>

Any ideas?

**Comment by codefuhrer** [comment]
@Listen-WebDev the latest version is for Laravel 5.4, you should use this command:
`composer require laravel/passport 1.0.*`

**Comment by Listen-WebDev** [comment]
yes thx :) it's works

**Comment by zymawy** [comment]
Indeed It Worked

**Comment by MumbaMukendi** [comment]
I think it could just be bad network connection

**Comment by Gman1996** [comment]
It worked for me

**Comment by iproweb** [comment]
it worked for me thanks bro.

**Comment by laratuto** [comment]
[it worked for me thanks bro. sure](https://laratuto.com/passport-install-in-laravel/)
