### ISSUE TITLE
Strange behaviour - auth base popup instead validation

### ISSUE THREAD

**Issue by Listen-WebDev** [laravel/passport#246]
Dear all,
i install passport on laravel 5.3 , passport 1.0.17. I have follow all steps for install an create test cliend-id and client secret, db tables and othres.

I need to test password grant type with RESTED (chrome ext.) this screen

[this is](http://www.listenagency.com/rest.png) my params 

[this is](http://www.listenagency.com/modal.jpg) what i obtain

NOTE: i 'am in local env with no ssl 

any ideas how?

**Comment by lotarbo** [comment]
have same problem

**Comment by Listen-WebDev** [comment]
Solved 

my client_id params was wrong, i need to insert id column value of oauth_clients table not name column

**Comment by lotarbo** [comment]
But i still have problem. I install fresh laravel 5.3 and laravel/passport 1.0 and do all how in docs.
![image](https://cloud.githubusercontent.com/assets/1766890/22285441/b82ef308-e2fc-11e6-9f0e-fc2b6866a16c.png)
![image](https://cloud.githubusercontent.com/assets/1766890/22285454/c13786a4-e2fc-11e6-865d-bcc4773310ce.png)
after try oauth/authorize route, when i login in normal page 
![image](https://cloud.githubusercontent.com/assets/1766890/22285518/04b330f4-e2fd-11e6-9286-be4099b4c42d.png)
i have this popup
![image](https://cloud.githubusercontent.com/assets/1766890/22285490/e18f2b82-e2fc-11e6-8f22-022ed07e7fb7.png)

here is client site code
`Route::get('/', function () {
    $query = http_build_query([
        'client_id' => 1, 'redirect_uri' => 'http://client.dev/callback', 'response_type' => 'code', 'scope' => '']);
    return redirect('http://server.dev/oauth/authorize?' . $query);
    
});
Route::get('/callback', function (Request $request) {

    $http     = new GuzzleHttp\Client;
    $response = $http->post('http://server.dev/oauth/token', [
        'form_params' => [
            'grant_type' => 'authorization_code', 'client_id' => 1, 'client_secret' => '7j8g8yEWDv1EWs95wC1UczZJeVGUhpKHXxWFqySD', 'redirect_uri' => 'http://client.dev/callback', 'code' => $request->code]]);
    return json_decode((string) $response->getBody(), true);

});`
