### ISSUE TITLE
[5.4] Axois and Passport do not work together

### ISSUE THREAD

**Issue by Quezler** [laravel/passport#256]
Original issue https://github.com/laravel/docs/issues/3044
Original pull https://github.com/laravel/docs/pull/3045

@taylorotwell stated the following:
> Axios will automatically send the CSRF token. There isn't any configuration that is needed in that regard.

However, this is not the case.

**To run my example, follow these instructions:**

- clone master branch from https://github.com/Quezler/laravel-xios_csrf
- setup database
- migrate
- npm run watch
(using dev/production will result that switching between broken & working wont change result, since between those branches javascript files get edited)
- switch to **broken** branch
- notice that the welcome page shows 401
- switch to **working** branch
- notice that the welcome page shows 200

**Points of interest:**

[header laravel checks](https://github.com/laravel/passport/blob/1.0/src/Guards/TokenGuard.php#L204)
[axois readme](https://github.com/mzabriskie/axios)
(notice this says **x**srf, while the passport guard checks for **c**srf)
```
  // `xsrfCookieName` is the name of the cookie to use as a value for xsrf token
  xsrfCookieName: 'XSRF-TOKEN', // default

  // `xsrfHeaderName` is the name of the http header that carries the xsrf token value
  xsrfHeaderName: 'X-XSRF-TOKEN', // default
```

And even if you change the Axios config so it uses `XSRF-TOKEN` and `X-XSRF-TOKEN`, it will still not work since the cookie is encrypted.

**Comment by Quezler** [comment]
Oh, and @brunen9 might want to be notified of this thread to :call_me_hand:

**Comment by brunen9** [comment]
@Quezler, you are fully described my own researches

**Comment by Quezler** [comment]
Actually, everything in here i figured out on my own, only once i got it working i made the pull requests, which you then put the links on 😉

**Comment by brunen9** [comment]
@Quezler, what I actually meant is - I am already did same researches as yours and got same results, so I can confirm your conclusion. Not meant that you steal my words or something similar, english is not my native language.

**Comment by Quezler** [comment]
@brunen9 my apologies then, you made it sound as if i claimed your research as my own 😱 

But since multiple people (you, me, others) come to the same conclusion, i think it is safe to say that this needs fixing, contrary to @taylorotwell believing the header gets set correctly by default.

**Comment by maximl337** [comment]
Could this be the reason for this problem?

http://stackoverflow.com/questions/42030727/laravel-5-4-passport-axios-always-returns-unauthenticated?noredirect=1#comment71236227_42030727

**Comment by Quezler** [comment]
100%

Tell them to add the snippet in there, check the referenced pull request at the top ;)

**Comment by maximl337** [comment]
@Quezler What do you mean by "Tell them to add the snippet in there.." ? thanks.

**Comment by Quezler** [comment]
Add this to the axios header config `'X-CSRF-TOKEN': window.Laravel.csrfToken,`

**Comment by monomichael** [comment]
@Quezler @maximl337 I've done that. https://stackoverflow.com/questions/42030727/laravel-5-4-passport-axios-always-returns-unauthenticated/42032593#42032593

**Comment by Quezler** [comment]
Still weird it was overlooked initially

**Comment by maximl337** [comment]
@Quezler You're a life saver! ty.

**Comment by Quezler** [comment]
Just doing my duty as a fellow programmer :D

**Comment by Quezler** [comment]
👍
