### ISSUE TITLE
Doesn't work without Facades

### ISSUE THREAD

**Issue by 4levels** [laravel/passport#260]
Hi,

The title says it all: if you do not enable Facades, this library simply crashes.
I created a PR to fix this https://github.com/laravel/passport/pull/259 but it's being rejected for unknown / invalid reasons

**Comment by 4levels** [comment]
This issue is real! Facade calls are userland helpers, no library code should depend on Facades being enabled or not.

Very disappointed: I did all the research, proposed a PR, got support from other developers and yet this just gets closed??

**Comment by rjmackay** [comment]
@themsaid could you explain why this was closed?
It an issue for people working without Facades, but also just not best practice when building a package to work with laravel.

**Comment by goodevilgenius** [comment]
Still no plan to fix this? This is really disappointing. I'm going to have to go with another OAuth library, or roll my own. I'm not planning on using Facades in my API, but really wanted to use Passport. So very disappointing, @themsaid @taylorotwell
