### ISSUE TITLE
Consuming own API fail

### ISSUE THREAD

**Issue by thimonnn** [laravel/passport#261]
I'm building a SPA with Vue. My front-end and my back-end (Laravel) are in the same codebase. I want to approach my API (that is in my back-end) via the Laravel Passport Middleware *CreateFreshApiToken*. I'm approaching my sign in method in my *AuthController* via *web.php*.

**My problem:**
As soon as I'm successfully signed in via my sign in method I would expect that at this time Passport created the *laravel_token cookie*. This is not the case. The cookie is created after a page refresh. But as I said I'm building a SPA and that's why I don't want to have page refreshes.

**What I want:**
I want to sign in via my sign in method then use the Passport *CreateFreshApiToken* middleware. After that I want to use the (just created in the middleware) *laravel_token cookie* so that I can correctly and safely speak to my own API in my signed-in section of the SPA.

**More information:**

*Kernel.php*

    // Code...
    protected $middlewareGroups = [
    	'web' => [
    	    // other middlewares...
    	    \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
    	],
    ];
    // Code...

*AuthController.php*

    // Code...
    public function login()
    {
        if (Auth::attempt(['email' => Input::get('email'), 'password' => Input::get('password')], true)) {
    
            return response()->json([
                'user' => Auth::user(),
                'authenticated' => auth()->check(),
            ]);
        }
    
        return response()->json(['authenticated' => false], 401);
    }
    // Code...

*Login.vue*

    // Code...
    methods: {
        login: function (event) {
    
            event.preventDefault();
    
            this.$http.post(BASE_URL + '/login', {
                email: this.email,
                password: this.password,
            })
    
            .then(function (response) {
    
                localStorage.user_id = response.body.user.id;
    
                router.push({
                    name: 'home'
                });
            });
        },
    },
    // Code...

**What goes wrong? This:**

*CreateFreshApiToken.php*

    // Code...
    public function handle($request, Closure $next, $guard = null)
    {
        $this->guard = $guard;
    
        $response = $next($request);
    
        // I'm signed in at this point
    
        if ($this->shouldReceiveFreshToken($request, $response)) { // returns false unless you refresh the page. That's why it won't create the laravel_token cookie
            $response->withCookie($this->cookieFactory->make(
                $request->user($this->guard)->getKey(), $request->session()->token()
            ));
        }
    
        return $response;
    }
    
    protected function shouldReceiveFreshToken($request, $response)
    {
    	// both methods below return false
        return $this->requestShouldReceiveFreshToken($request) &&
               $this->responseShouldReceiveFreshToken($response);
    }
    
    protected function requestShouldReceiveFreshToken($request)
    {
    	// $request->isMethod('GET') - returns false because it's a POST request
    	// $request->user($this->guard) - returns true as expected
        return $request->isMethod('GET') && $request->user($this->guard);
    }
    
    protected function responseShouldReceiveFreshToken($response)
    {
    	// $response instanceof Response - returns false
    	// ! $this->alreadyContainsToken($response) - returns false as expected
        return $response instanceof Response &&
                    ! $this->alreadyContainsToken($response);
    }
    // Code...

I assume it is possible what I want to achieve right? If yes, how?

**Comment by craigpaul** [comment]
@thimonnn You should checkout #52, that should provide some insight for you. If you're login is part of the SPA, then you're gonna have a hard time using Passport like this. You could make your login a server rendered page and then once you're logged in you could start using the SPA.
