### ISSUE TITLE
Vue files not rendering

### ISSUE THREAD

**Issue by ampedpublishing** [laravel/passport#268]
I have followed all the steps in the Laravel docs but when I run npm run dev I get the following error:

ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* ./components/passport/AuthorizedCleints.vue

Did you forget to run npm install --save for it?
                                                                    Asset      Size  Chunks                    Chunk Names
  fonts/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1   20.1 kB          [emitted]         
  fonts/glyphicons-halflings-regular.svg?89889688147bd7575d6327160d64e760    109 kB          [emitted]         
  fonts/glyphicons-halflings-regular.ttf?e18bbf611f2a2e43afc071aa2f4e1512   45.4 kB          [emitted]         
 fonts/glyphicons-halflings-regular.woff?fa2772327f55d8198301fdb8bcfc8158   23.4 kB          [emitted]         
fonts/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb     18 kB          [emitted]         
                                                               /js/app.js    1.2 MB       0  [emitted]  [big]  /js/app
                                                             /css/app.css    146 kB       0  [emitted]         /js/app
                                                        mix-manifest.json  66 bytes          [emitted]         

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/keithgosnell/Code/license/npm-debug.log

I have tried:
- Delete my node_modules from my project
- Ensure my package.json file required laravel-elixir ^4.0.4
- Ran NPM install to re-install all my packages.

And still nothing. Any help would be appreciated.

**Comment by longthanhtran** [comment]
looks like you have a typo?

> ./components/passport/AuthorizedCleints.vue

**Comment by ampedpublishing** [comment]
Wow.. ok I feel dumb now... that solved it. Thank you longthanhtran!
