### ISSUE TITLE
Configure Passport::routes()

### ISSUE THREAD

**Issue by SwiTool** [laravel/passport#270]
I migrated to L5.4 while I was on 5.1. I used a now deprecated OAuth lib for Laravel.

Now, I don't want the oauth routes to be changed, because it will break all my applications in production.
For example, mine is `/oauth2/access_token` while the one you provide is `/oauth/token`

I might do a manual redirection also, but it sounds nice to add this feature.
Thanks.

**Comment by nueko** [comment]
then don't use `Passport::routes()` write the routes manually and see [RouteRegistrar.php](https://github.com/laravel/passport/blob/2.0/src/RouteRegistrar.php) for your reference

**Comment by nueko** [comment]
see #271

**Comment by SwiTool** [comment]
Closing this, even if the real problem was not solved.
