### ISSUE TITLE
Error in Implicit Grant Tokens

### ISSUE THREAD

**Issue by aixen** [laravel/passport#308]
Good day, ! i am new to this feature please help me i use this documentation

> https://laravel.com/docs/5.4/passport#implicit-grant-tokens

i already install the laravel-passport for version 5.4

> www.urlname.com/oauth/authorize and i try GET with the PARAMS
client_id=1&response_type=token&redirect_uri =www.urlname.com/api/hello and my preview in POSTMAN is this

i try to do that in POSTMAN 

but the response is this 

 `Call to undefined method Laravel\Passport\Passport::enableImplicitGrant()`

any one knows how to fix that ? thanks in advance

**Comment by SwiTool** [comment]
Are you sure you have laravel/framework's version of 5.4.* ?
Make sure you have it in your composer.json
Also check that you have laravel/passport of version 2.*

then please do this commands;
```bash
composer update
```

**Comment by aixen** [comment]
i will close this since i just re install the laravel and the laravel/passport
