### ISSUE TITLE
client_credentials grant can't get * scope

### ISSUE THREAD

**Issue by chris-moreton** [laravel/passport#319]
Perhaps I'm wrong, but I can't find a reason why a client_credentials grant type shouldn't be allowed to receive the * scope. The finalizeScopes method of ScopeRepository.php prohibits this. I can achieve essentially the same thing by using a "personal_access" grant type but does this mean that * scope can only be provided to grants that are associated with a user id? Indeed, the personal_access grant type will be granted without specifying a user id - it seems that this is the same as a client_credentials grant.

**Comment by themsaid** [comment]
This was recently fixed, sorry for not getting back to you earlier :)
