### ISSUE TITLE
"Authorization code has been revoked" immediately after login

### ISSUE THREAD

**Issue by jorenvh1** [laravel/passport#337]
I get this error message immediately after I login with a user.
This has always worked and I don't know what broke it...

What could be the cause if the token being revoked immediately?

**Comment by matthanley** [comment]
@jorenvh1 what was the cause of this issue? I'm experiencing the same.
Thanks

**Comment by kennybuc** [comment]
@jorenvh1 Did you solve the issue? I have got the same issue.

**Comment by karneaud** [comment]
+1

**Comment by janpantel** [comment]
@jorenvh1 can you recall what the issue was?

**Comment by janpantel** [comment]
If anyone ever stumbles across this, make sure that your client isn't calling the `/oauth/token` multiple times.

Passport only has 1 point in the code where it revokes auth codes and this is when a token was successfully requested.

We had the revoked exception thrown in production quite frequently and eventually found out that there was a poorly implemented client which re-requested tokens with the same code if the user refreshed the page just in time.

**Comment by janpantel** [comment]
If anyone ever stumbles across this, make sure that none of your clients are calling the /oauth/token endpoint multiple times.

Passport only has 1 point in the code where it revokes auth codes and this is when a token was successfully requested.

We had the "revoked" exception thrown in production quite frequently. Eventually we found out that there was a client which re-requested tokens with the same code if the user refreshed their browser just in time. Fixing the faulty client fixed the issue completely.
