### ISSUE TITLE
Laravel 5.4 with passport returns unauthenticate

### ISSUE THREAD

**Issue by cookiejarblush** [laravel/passport#341]
I followed the steps in this video: [What's New in Laravel 5.3: Laravel Passport](https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/13)

In this video it guides you to the step where you authenticate through Postman App by using it's autogenerated Token.

I followed the steps very carefully but i get unauthenticated in Postman App.
My environment is:

- OS: CentOS 7

- Apache/2.4.6 (CentOS)

- PHP 7.0.17

- Composer version 1.3.2

- Node v6.9.5

- NPM 3.10.10

In Postman App, I input 2 keys in the Headers section:

1. Authorization

- Bearer somerandomtokenstringgeneratedfromPersonalAccessTokenfunctionfrompassportvuecomponent

2. Accept

- application/json

In the end of the process i get:
`{
  "error": "Unauthenticated."
}`

Can the steps in the [video](https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/13) be used in Laravel 5.4 for the oAuth Token or is it missing some steps?

Thank You in advance!

**Comment by jorenvh1** [comment]
Did you make sure to put a _space_ between 'Bearer' and the actual token?
Bearer yourrandomtoken

Also what token are you using? You should be using the one you receive after login, not the one id of secret generated for your client.

**Comment by cookiejarblush** [comment]
Thank you for pointing out the space between 'Bearer' and 'token' @jorenvh1 .

Another thing that was missing is:
`RewriteCond %{HTTP:Authorization} ^(.*)`
`RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`

This has to be placed in the conf file if were using Apache Server for it to recognize the headers.

**Comment by bravist** [comment]
with nginx, how to solve it ?

**Comment by sushil173** [comment]
Make sure your local **public/.htaccess** and servers **public/.htacces**s files had same content. This may help.
