### ISSUE TITLE
For Authorization Grant is secret required?

### ISSUE THREAD

**Issue by huntsfromshadow** [laravel/passport#343]
For Authorization grant is secret required?

I'm asking as sending the request to oauth/token without it throws an invalid client.
Trying to implement SMART on FHIR and it doesn't use the secret excpet for confidential apps (which is correct by OAuth2 spec).

Don't know if this question is passport or for the oauth2-server.

**Comment by lloy0076** [comment]
Underlying server doesn't require it:

* https://oauth2.thephpleague.com/authorization-server/auth-code-grant/

Passport makes it a requirement.

**Comment by grEvenX** [comment]
@themsaid Why was this one closed, and _why_ is client secret required? This grant is supposed to be used by mobile apps etc. that can't be trusted and should not use secrets, however because of this requirement it can't really be used, unless there's something very basic I'm missing here.

**Comment by themsaid** [comment]
@grEvenX are you sure you are talking about the authorization code grant?

**Comment by grEvenX** [comment]
@themsaid Yeah, I'm pretty sure. What OAuth flow would you recommend using in clients unable to keep secrets?

Quoting [Aaron Parecki](https://aaronparecki.com):
> Note: Previously, it was recommended that mobile and native apps use the Implicit grant. In the time since the spec was originally written, the industry best practice has changed to recommend using the authorization code flow with no secret for native apps. There are some additional recommendations for native apps that are worth reading as well.

I've seen it specified in a lot of different sources, but this is one of the more trustworthy ones.
The quote is taken from this article: https://aaronparecki.com/oauth-2-simplified/#mobile-apps

**Comment by themsaid** [comment]
I believe you should share this on thephpleague/oauth2-server then as Passport uses it as the authorization server.

**Comment by grEvenX** [comment]
@themsaid thanks, I see that this part of the code seems to be in the thephpleague/oauth2-server component. As a reference, I've created an issue there https://github.com/thephpleague/oauth2-server/issues/1004.

**Comment by sg3s** [comment]
@lloy0076 @themsaid

Just wanted to note that as @grEvenX notes this behaviour is not quite up-to-spec with standards. 

This will be changed in (the not yet released) v8 version of oauth2-server, I left a short upgrade note based on changes in the PR a while back.
https://github.com/thephpleague/oauth2-server/pull/938#issuecomment-452258066
