### ISSUE TITLE
Passport in laravel 5.4 always return error: "Unauthenticated.",

### ISSUE THREAD

**Issue by raksrivastava** [laravel/passport#346]
Passport in laravel 5.4 always return error: "Unauthenticated.", I am calling this api by rest client. I have done all things according to tutorial, But ,always got same error.
![rest](https://cloud.githubusercontent.com/assets/9003512/24939295/ef702aa0-1f59-11e7-9c72-ef4741fc918e.png)

**Comment by cookiejarblush** [comment]
Have u tried [this](https://github.com/laravel/passport/issues/341) solution?
[https://github.com/laravel/passport/issues/341](https://github.com/laravel/passport/issues/341)

**Comment by raksrivastava** [comment]
I am still getting same problem.
![res2](https://cloud.githubusercontent.com/assets/9003512/24986928/abe98bc0-201a-11e7-8a1f-3b465880e551.png)

**Comment by bravist** [comment]
I use laravel 5.4.32 and the api auth middleare not run
