### ISSUE TITLE
[help] how to set customize authentication header?

### ISSUE THREAD

**Issue by ShaneXie** [laravel/passport#355]
e.g. Instead use `authentication` header, I want to use `o-authentication`.
Is there a easy way to setup ?

**Comment by ShaneXie** [comment]
after trace around with the source code I found the place to get the token is inside the laravel http package https://github.com/laravel/framework/blob/5.4/src/Illuminate/Http/Concerns/InteractsWithInput.php#L52
and token validation is at https://github.com/thephpleague/oauth2-server/blob/e091d4812789cdce69dee43d300fd3707548a4aa/src/AuthorizationValidators/BearerTokenValidator.php#L46
hmm, not sure how to make them configureable in both places.

**Comment by craigpaul** [comment]
@ShaneXie That is not possible. Both `laravel/passport` and `thephpleague/oauth2-server` follow the [oAuth2 spec](https://tools.ietf.org/html/rfc6749) which specified the standard HTTP header `Authorization`.

If that is something you absolutely must have, you will need to implement oAuth separate from Passport.
