### ISSUE TITLE
Can't seem to make CreateFreshApiToken work

### ISSUE THREAD

**Issue by Anahkiasen** [laravel/passport#356]
I've followed the documentation and looked at various issues in this repository, forum posts, and so on. My users login through a normal form, the token is indeed generated and I can see it on the response, but when I do an API request from said response it still throws a 401.

If I dig into the `TokenGuard` class it seems that the `Request` instance it receives does not contain any cookies. I'm passing correctly the CSRF headers and so on, is there any additional step or is this a bug?

```php
protected $middlewareGroups = [
    'web' => [
        EncryptCookies::class,
        AddQueuedCookiesToResponse::class,
        StartSession::class,
        ShareErrorsFromSession::class,
        VerifyCsrfToken::class,
        SubstituteBindings::class,
        CreateFreshApiToken::class,
    ],
    'api' => [
        'auth:api',
        'throttle:120,1',
        'bindings',
    ],
];
```

**Comment by craigpaul** [comment]
@Anahkiasen Are you by chance posting to a subdomain? You might need to add the `withCredentials` option.

**Comment by Anahkiasen** [comment]
Hm no this is locally, no subdomain, plain old `theapp.dev` :/

**Comment by craigpaul** [comment]
@Anahkiasen Can you try adding credentials to it? I've not personally used fetch but I'm pretty sure you will have to add it to get the cookie to send from the browser.

```
fetch('/api/search/scrobbling', {
    headers: {
        'X-CSRF-TOKEN': Laravel.csrfToken,
        'X-Requested-With': 'XMLHttpRequest',
    },
    credentials: 'include',
})
```

[Further Reading](https://developers.google.com/web/updates/2015/03/introduction-to-fetch#sending_credentials_with_a_fetch_request)

**Comment by Anahkiasen** [comment]
That worked! I've been using fetch forever and this is the first time I'm reading about that option :o 
Thanks for taking the time to humor my problem and look into it even if it was PEBKAC
