### ISSUE TITLE
error: {"error":"invalid_client","message":"Client authentication failed"}

### ISSUE THREAD

**Issue by Tjoosten** [laravel/passport#36]
Hi i got a strange error. And i think it might be in the package? 

I cant authorize my tokens. 

My current code -> https://gist.github.com/Tjoosten/b1f691bb0b9b4e8be1fce9c7c49166af

**Comment by jbrooksuk** [comment]
Did you run `php artisan passport:install`?

**Comment by frdteknikelektro** [comment]
I think is will help other,

check the client_id and client_secret on databases, which is not belong to any user.

**Comment by seosazi** [comment]
I have tried different ways, in the end I notice that my config cache is old and I use this code and my problem solved

`php artisan config:clear`
