### ISSUE TITLE
why the jti in the header and in the payload ??

### ISSUE THREAD

**Issue by ehababoshehab** [laravel/passport#363]
Hey guys,
I am really new with API authentication, i am using laravel/passport password grant token, after issuing the token i tried to decode it in https://jwt.io/ , i found out the 'jti' in both of header and payload ??? is that normal ???

**Comment by rickshawhobo** [comment]
I agree it shouldn't be in the header. Seems like a waste of space.

**Comment by Fh-jashmore** [comment]
I think [league/oauth2-server](https://github.com/thephpleague/oauth2-server) handles it
https://github.com/thephpleague/oauth2-server/blob/master/src/Entities/Traits/AccessTokenTrait.php#L32

**Comment by alexbilbie** [comment]
Please open a ticket on league/oauth2-server if you believe this is an issue

**Comment by MattiJarvinen-BA** [comment]
It's 120 chars worth of an issue in every request header. It's not much but it's against the JWT spec.

**Comment by rodriigomedeiros** [comment]
Hey, let me open this again. It seems to me that this issue has not yet been seen and nobody he asked in [league/oauth2-server ](https://github.com/thephpleague/oauth2-server) also. I'm right?

**Comment by Sephster** [comment]
@rodriigomedeiros do you believe this is still an issue? If so, I will look into it

**Comment by rodriigomedeiros** [comment]
Not exactly a problem, but as mentioned by @ MattiJarvinen-BA, it is against the specifications of JWT. Some clients are complaining about the size of the token and without this duplication we would save, after encoding in base64, some bytes. What do you think?

**Comment by Sephster** [comment]
Sorry @rodriigomedeiros I wasn't clear in my comment. I meant have you confirmed that this is still an issue in the latest versions of the respective packages? This issue was initially raised back in 2017 so a lot has changed since.

If you don't know, it is no problem. I will take a look into it, but if you have confirmed this is still happening, it would save me some time investigating. Cheers

**Comment by rodriigomedeiros** [comment]
Alright @Sephster , I really did not understand your question. Sorry.

Replying now, yes, it's still a problem in recent versions. Currently, in another project, I'm using Passport v7.3.0 and I still see the duplicate JTI even though I know this is a [league/oauth2-server](https://github.com/thephpleague/oauth2-server) problem. Thank you for fast response. Cheers.

**Comment by Sephster** [comment]
Cool. I will take a look at this today to see if there is an easy solution. Cheers!

**Comment by Sephster** [comment]
The JTI has now been removed from the header. This change will be in version 8 which I'm releasing today. Cheers

**Comment by rodriigomedeiros** [comment]
Great, @Sephster. Cheers.
