### ISSUE TITLE
Status of UUID for client_id

### ISSUE THREAD

**Issue by huntsfromshadow** [laravel/passport#366]
I know this has been talked about for a while,
but what is the current status of using UUID for client ID?

**Comment by fenos** [comment]
We are all waiting for this.

**Comment by JeanLucEsser** [comment]
Indeed we are.

**Comment by donromen** [comment]
Maybe @heisian can answer this.

**Comment by cweiske** [comment]
Duplicate of #14.

**Comment by heisian** [comment]
Sadly I'm in `node` world now since that's what my new occupation uses.. If I have some extra time I'll take a look at my `passport` fork and see what's changed - it's been a while. I wouldn't bank on my fork getting merged in anytime soon, though, unless Taylor sees overwhelming support for it.

**Comment by mosleim** [comment]
i'm waiting for this updates.

**Comment by diadal** [comment]
I create a simple package for this, it convert client id in all the table to Uuid.
https://github.com/diadal/passport

**Comment by mloberg** [comment]
You can use UUIDs by updating the migrations and using model listeners. https://mlo.io/blog/2018/08/17/laravel-passport-uuid/

**Comment by driesvints** [comment]
Gonna close this as it's a duplicate of #14

**Comment by baig772** [comment]
> I create a simple package for this, it convert client id in all the table to Uuid.
> https://github.com/diadal/passport

I am having issues installing this. Will this work with Laravel 5.7 ?

**Comment by Sephster** [comment]
Probably better to ask that question in the diadal/passport repo instead.
