### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by jamiehd** [laravel/passport#37]
Hi,

I've just downloaded the latest rc of 5.3 (using laravel new --dev) and I'm trying to install passport, but I'm getting the following:

  Problem 1
    - Installation request for laravel/passport ^0.2.4 -> satisfiable by laravel/passport[v0.2.4].
    - laravel/passport v0.2.4 requires illuminate/auth ~5.3 -> satisfiable by illuminate/auth[5.3.x-dev, 5.4.x-dev] but these conflict with your requirements or minimum-stability.

Is there some issue with versions that needs to be fixed in the composer.json for either passport or 5.3 or am I just going about this the wrong way?

Thanks,

Jamie

**Comment by GrahamCampbell** [comment]
Please provide your entire composer.json file.

**Comment by jamiehd** [comment]
I actually deleted the folder and recreated it with composer create-project, which seemed to solve the issue. I just went back to replicate it and I don't seem to be getting the error any more, so either someone has changed something in the meantime or it something just went wrong with the initial install. I've included the composer.json for the working version below, but I can't provide the broken one as it is now working. 

If this hasn't affected anyone else it would probably make sense to just close this issue as it may have been a one-off thing.

~~~
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "laravel/passport": "^0.2.4"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
~~~

**Comment by GrahamCampbell** [comment]
Try removing:

```
    "minimum-stability": "dev",
    "prefer-stable": true
```

And set `"laravel/framework": "5.3.*"` to `"laravel/framework": "5.3.*@dev"`. I suspect this is happening because our package subsplit tags have not gone out yet.

**Comment by jamiehd** [comment]
Yep that seems to have done the trick, though I can't tell if it's due to your fix or it just deciding to work as I said above.

Thanks.

**Comment by najathi** [comment]
If like to upgrade Laravel 5.3 to Laravel5.4

You change the laravel/framework: 5.3.* to 5.4.*
You change the phpunit/phpunit: ̴5.7
you chnage the : "laravelcollective/html": "^5.4.0",
Then move to your terminal and run composer update
If it exists, you may delete the bootstrap/cache/compiled.php file. It is no longer used by the framework.
After upgrading all packages, you should run php artisan view:clear to avoid Blade errors related to the removal of Illuminate\View\Factory::getFirstLoop(). In addition, you may need to run php artisan route:clear to flush the route cache.
