### ISSUE TITLE
Implementing a Laravel OAUTH IDP for OPENID Consumers

### ISSUE THREAD

**Issue by oshaggy** [laravel/passport#375]
I've implemented the Laravel Passport package in Laravel 5.4.  The oauth2 flow works testing with Postman and the default scaffolding allowing a regular Authorization Grant and bearer token to be generated.

Ive installed the latest Moodle 3.3 and want to use the new Custom OAuth2 Authentication Services, however, when I try to connect Moodle to an OAuth system account... i get redirected to my IDP to confirm as expected, and then I get this error after being redirected to Moodle:

"error/Could not upgrade oauth token"

Does the Passport package not include "openid profile email" scope handling? I cannot find any information that points me to the next step in handling OPENID as a scope or if it is already contained within this package.

Thank you.

**Comment by xyos** [comment]
I've succesfully implemented laravel passport oauth2 authentication, you must upgrade passport to version 3.0 and latest moodle 33 stable, then you need to create the passport client, and configure a new custom service in moodle, then you need to add the token_endpoint and authorization_endpoint, default routes are `/oauth/token` and `/oauth/authorize`, then you need to add an userinfo_endpoint, something like:
```php

Route::group(['middleware' => 'auth:api'], function() {
  Route::get('/me', function (Request $request) {
    $user = $request->user();
    return response()->json([
      "name" => $user->name,
      "email" => $user->email,
      "picture_url" => $user->pictureURL
    ]);
  });
});
```

and finally you need to map those fields in the userfieldmappings on the service you've created on moodle.

**Comment by Namesonic** [comment]
That function worked for me.  Additionally, I was behind in version updates and needed to ensure the endpoints were configured properly.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
