### ISSUE TITLE
duplicate Authorized Applications

### ISSUE THREAD

**Issue by vietnguyen09** [laravel/passport#380]
I have created an Oauth2 server and consumer app in Laravel by following https://laravel.com/docs/5.4/passport

Repo URL: https://github.com/xparthx/Laravel-Passport---Oauth2

So far it is working fine.

The issue is when I'm assessing the Oauth2 server from the consumer app, it makes duplication for the same OAuth Client. (See **Authorized Applications** section in the attachment)

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/irQie.png

Steps to produce the bug:

1) Run consumer app in browser

2) Visit /redirect URL

3) Login into the site

4) Login into Oauth2 site and check the Authorized Applications sections (There will be a new entry for Consumer app)

**Comment by lawrence615** [comment]
@vietnguyen09 did you get an issue of Unauthenticated before getting this to work?

**Comment by codefuhrer** [comment]
Dupe #250

**Comment by moxx** [comment]
+1 same issue

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
