### ISSUE TITLE
TokenGuard query token twice

### ISSUE THREAD

**Issue by halaei** [laravel/passport#382]
The following sql statement is queried twice during a call to `TokenGuard::authenticateViaBearerToken()` function:

```sql
select * from `oauth_access_tokens` where `oauth_access_tokens`.`id` = ? limit 1
```

**Comment by rdgout** [comment]
I also see this happening on my API using Laravel Passport (v2.0.11)

**Comment by gbdematos** [comment]
Finally found someone with the same "problem", it's driving me nuts to figure out why this is happening. 

I have a simple app to test it, installed passport and made vue make a request to some route with an authorization header. The following queries are executed, in this order:

```
select * from `oauth_access_tokens` where `oauth_access_tokens`.`id` = '[...]' limit 1
select * from `users` where `id` = '1' and `users`.`deleted_at` is null limit 1
select * from `oauth_access_tokens` where `oauth_access_tokens`.`id` = '[...]' limit 1
select * from `oauth_clients` where `oauth_clients`.`id` = '2' limit 1
```

(removed the token for presentation purposes)

**Comment by sylouuu** [comment]
Same issue here.

**Comment by Kolimar** [comment]
still happening

**Comment by hudovisk** [comment]
I am having the same issue here,
the first query is coming from a check to see if the token is revoked: https://github.com/laravel/passport/blob/9dbcc3d6f8f20f1a83cbef73bbb563ce59e43ded/src/Guards/TokenGuard.php#L109

Then the oauth_access_tokens is queried again right after: https://github.com/laravel/passport/blob/9dbcc3d6f8f20f1a83cbef73bbb563ce59e43ded/src/Guards/TokenGuard.php#L125

**Comment by raphaelbadia** [comment]
Same issue here, the fun part is that it's happening in the same try block

**Comment by fannyfan414** [comment]
Same issue, always 2 duplicated request to database

**Comment by CrashXD** [comment]
Same issue

**Comment by pnlinh-it** [comment]
Same issue!

**Comment by calvinmuller** [comment]
Same issue here

**Comment by driesvints** [comment]
Since this is an optimization rather than something blocking, feel free to send in a PR to solve this problem.

**Comment by tylik1** [comment]
@driesvints this is not optimization, it certainly looks like a bug. For me `Auth::user();` calls the query twice, on every single Ajax request i make.
 Can you please reopen, even if it won't be solved now?

select * from "oauth_access_tokens" where "id" = token_id' limit 1

Backtrace:

First request:
```
15. /vendor/laravel/passport/src/TokenRepository.php:32
16. /vendor/laravel/passport/src/TokenRepository.php:108
17. /vendor/laravel/passport/src/Bridge/AccessTokenRepository.php:87
18. /vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php:85
19. /vendor/league/oauth2-server/src/ResourceServer.php:84
20. /vendor/laravel/passport/src/Guards/TokenGuard.php:109
21. /vendor/laravel/passport/src/Guards/TokenGuard.php:89
22. /vendor/laravel/passport/src/PassportServiceProvider.php:272
25. /vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:292
```
Second request:
```
15. /vendor/laravel/passport/src/TokenRepository.php:32
16. /vendor/laravel/passport/src/Guards/TokenGuard.php:126
17. /vendor/laravel/passport/src/Guards/TokenGuard.php:89
18. /vendor/laravel/passport/src/PassportServiceProvider.php:272
21. /vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:292
22. /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223
```

**Comment by driesvints** [comment]
@tylik1 this isn't exactly blocking or causing issues. If you can optimize the process in a clean way which reduces the queries to one feel free to send in a PR.

**Comment by ankurk91** [comment]
It can be easily seen in debugbar

<img width="1283" alt="passport-duplcate-query" src="https://user-images.githubusercontent.com/6111524/51082096-4710f300-1726-11e9-82ca-4e243578dec0.png">

**Comment by ankurk91** [comment]
Thanks but you forgot to re open this.

**Comment by Vatia13** [comment]
That's because laravel passport uses their own revoke check and second one is from league/oauth2-server required package. I think laravel passport should execute their check if token is revoked or find some other solution for it. I`ll show u both calls thet are in /passport/src/Guards/TokenGuard.php line 152 

`        // Finally, we will verify if the client that issued this token is still valid and
        // its tokens may still be used. If not, we will bail out since we don't want a
        // user to be able to send access tokens for deleted or revoked applications.
        if ($this->clients->revoked($clientId)) {
            return;
        }`
![image](https://user-images.githubusercontent.com/8588668/52467497-2e69f080-2b9f-11e9-9894-9d3de74259ba.png)

and /league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php line 88

`            // Check if token has been revoked
            if ($this->accessTokenRepository->isAccessTokenRevoked($token->getClaim('jti'))) {
                throw OAuthServerException::accessDenied('Access token has been revoked');
            }`
![image](https://user-images.githubusercontent.com/8588668/52467482-227e2e80-2b9f-11e9-993b-6f6e3b5573ca.png)

**Comment by ankurk91** [comment]
Thanks @Vatia13 for insights

**Comment by Patskimoto** [comment]
Just did an audit of my SQL queries and notice this is still happening as of Laravel 5.8 - any progress on this?

**Comment by driesvints** [comment]
@Patskimoto We're open to pull requests.

**Comment by msdavid1296** [comment]
is there any way to avoid these repeated queries?

**Comment by colighto** [comment]
in mysql the function `uuid()` generates a unique string key for primary keys that are defined as varchar or char it could also be called using a simple query like `select uuid()` more details are provided about this function on this https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid although there are equivalent functions on laravel that implements this like `\Illuminate\Support\Str::uuid()` and there is another package here as well https://packagist.org/packages/dyrynda/laravel-model-uuid

**Comment by driesvints** [comment]
Can anyone please pinpoint the exact locations where these double calls are made in the current Passport code? Things have changed a bit since and I can't find them. And not inside the TokenRepository I mean. Where the calls to the repository are made.

**Comment by HenkMaller** [comment]
Any update?

**Comment by chadidi** [comment]
Same issue here using `Laravel 5.8` and `Laravel Passport 7.2`

**Comment by driesvints** [comment]
Please stop reporting this or asking when this will be fixed. We need to pinpoint the exact locations where the calls are made (like I've asked above). The comments above don't help to solve the issue at hand.

**Comment by electron93** [comment]
> Can anyone please pinpoint the exact locations where these double calls are made in the current Passport code? Things have changed a bit since and I can't find them. And not inside the TokenRepository I mean. Where the calls to the repository are made.

@driesvints 

L127, begins in `authenticateViaBearerToken($request)`
https://github.com/laravel/passport/blob/5def15db98230dbf859292d7ca6b597c3c58051f/src/Guards/TokenGuard.php#L125-L129

L175, calls [`TokenRepository::isAccessTokenRevoked($id)`](https://github.com/thephpleague/oauth2-server/blob/2eb1cf79e59d807d89c256e7ac5e2bf8bdbd4acf/src/AuthorizationValidators/BearerTokenValidator.php#L87-L90) and then `TokenRepository::find($id)`

[\League\OAuth2\Server\ResourceServer::validateAuthenticatedRequest($request)](https://github.com/thephpleague/oauth2-server/blob/2eb1cf79e59d807d89c256e7ac5e2bf8bdbd4acf/src/ResourceServer.php#L82-L85)
[\League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator::validateAuthorization($request)](https://github.com/thephpleague/oauth2-server/blob/2eb1cf79e59d807d89c256e7ac5e2bf8bdbd4acf/src/AuthorizationValidators/BearerTokenValidator.php#L87-L90)

https://github.com/laravel/passport/blob/5def15db98230dbf859292d7ca6b597c3c58051f/src/Guards/TokenGuard.php#L167-L177

L145, continues in `authenticateViaBearerToken($request)`, calls `TokenRepository::find($id)`
https://github.com/laravel/passport/blob/5def15db98230dbf859292d7ca6b597c3c58051f/src/Guards/TokenGuard.php#L142-L147

**Comment by francsiswanto** [comment]
I need solution for this issue also. I'm still using Passport 5.0 on Laravel 5.6 installed on my client server, and there is no way to upgrade into latest version. I hope somebody can help. Thank you.

**Comment by 0plus1** [comment]
I am currently running a large scale application and this has a severe performance impact as they are all single transactions against the DB.. ended up writing my own TokenRepository to curb this issue. While I agree this isn't a bug, it's a deal breaker on large scale applications.

**Comment by taftse** [comment]
@0plus1 how about sharing how you solved it or sending a pull request

**Comment by overtrue** [comment]
@taftse I create a package: https://github.com/overtrue/laravel-passport-cache-token

**Comment by Miljan9602** [comment]
This bug still happens... Laravel: v7.14.1 and Passport: v8.5.0

**Comment by driesvints** [comment]
I'm gonna close this to prevent more "this is still a bug" comments. Welcoming prs.

**Comment by driesvints** [comment]
Since nobody has attempted any more prs I'm closing this. We're still welcoming prs if anyone wants to take up work on this.

**Comment by driesvints** [comment]
Great news all. It seems there's finally coming a fix for this one in Passport v13: https://github.com/laravel/passport/pull/1751
