### ISSUE TITLE
How to generate token with custom `expires_at` time

### ISSUE THREAD

**Issue by mhipo1364** [laravel/passport#383]
Hey guys

Laravel Passport does set expires_at for access tokens via

    Passport::tokensExpireIn(Carbon::now()->addDays(15));

    Passport::refreshTokensExpireIn(Carbon::now()->addDays(30));

in boot method of `AuthServiceProvider`

But I want to set expires_at for each access_token separately.

Is there any way to do so in Laravel Passport?

**Comment by driesvints** [comment]
No. I'm also not sure why you would do that. Can you elaborate?
