### ISSUE TITLE
[2.0.8] unexpected '=' in KeysCommand.php on line 35

### ISSUE THREAD

**Issue by Scaenicus** [laravel/passport#394]
During composer update I got an error
``
  [RuntimeException]
  Error Output: PHP Parse error:  syntax error, unexpected '=' in .../vendor/laravel/passport/src/Console/KeysCommand.php on line 35
``
I reverted the version to 2.0.7 as I'm currently not able to dig into the problem.

**Comment by msonowal** [comment]
same here

**Comment by msonowal** [comment]
it's fixed now
