### ISSUE TITLE
How to access authenticated user data from OAuth?

### ISSUE THREAD

**Issue by ashutoshpw** [laravel/passport#402]
I have implemented Passport OAuth and was able to generate an access_token but I am not able to get authenticated user data using that token.

/api/user 
is returning null when accessed with header as [Authorization: Bearer my_access_token]

**Comment by georaldc** [comment]
The user() method for the current request should bring back your authenticated user. The user attribute accessed should get populated once an access token is validated, as long as you are using a grant where a user context exists (client credentials grant for example should return null)

**Comment by tharindulucky** [comment]
You just need to do like this

`$current_user = Auth::user();`

This will get the authorized user from the `access_token`

**Comment by Aamirbashir** [comment]
All are asshole no one gave a good answers

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
