### ISSUE TITLE
How to customise passport errors in laravel.log

### ISSUE THREAD

**Issue by d3ce1t** [laravel/passport#403]
I'm using Passport Password Grant Tokens and everything works right. I've set up token expiration time to 15 minutes, so after that time if a client access a protected route he gets an HTTP 401 error as expected. However, this is logged into laravel.log file as the following:

```
[2017-06-09 12:01:41]  local.ERROR: League\OAuth2\Server\Exception\OAuthServerException: The resource owner or authorization server denied the request [...].

Stack trace:
#0 /Users/jpadilla/Git/backend/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(61): League\OAuth2\Server\Exception\OAuthServerException::accessDenied('Access token is...')
#1 /Users/jpadilla/Git/backend/vendor/league/oauth2-server/src/ResourceServer.php(82): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator->validateAuthorization(Object(Zend\Diactoros\ServerRequest))
[...]
```

Every 15 minutes laravel.log file is filled with these errors. Due to this, laravel.log become useless for  a human reading in order to get an overview of what is happening in the application.

Is there any way to avoid this or just not printing stack trace information? How do you manage this  kind of situations?

Thank you very much,

**Comment by alexbilbie** [comment]
In your Laravel exception handler file create a custom handler for the exception that is being thrown that logs more information. On the `OAuthServerException` you can call `getHint()` to get a more specific error.
