### ISSUE TITLE
Middleware on Passport::routes() not working

### ISSUE THREAD

**Issue by kherP** [laravel/passport#404]
I tried to add middleware for Passport::routes with `barryvdh/laravel-cors`
 by using code below:

`Route::group(['middleware' => 'cors'], function() {
  Passport::routes();
});`

but the middleware does not seem to work on oauth/token as when I was trying to get the token from my Angular 2,  it returned CORS header ‘Access-Control-Allow-Origin’ missing

**Comment by alexbilbie** [comment]
I believe the solution here is to manually implement the relevant routes declared in https://github.com/laravel/passport/blob/3.0/src/RouteRegistrar.php to wrap them in `Route::group`
