### ISSUE TITLE
Return access_token if token_id existed instead of creating new one

### ISSUE THREAD

**Issue by SmileYuhao** [laravel/passport#405]
Used the `Password Grant Tokens` (version 2.0.10), everything works perfectly.

But when I looked at the database, I found that in table `oauth_access_tokens`, it creates new token id if user re-login (with same user_id, client_id, scopes), something likes:
![image](https://user-images.githubusercontent.com/6917105/27011630-199ab698-4ec0-11e7-9053-0dbb6765b7ef.png)

Part of code is 

```php
$request->request->add([
            'username' => $request->email,
            'password' => $request->password,
            'grant_type' => 'password',
            'client_id' => $client->id,
            'client_secret' => $client->secret,
            'scope' => '*'
        ]);
$proxy = Request::create('oauth/token', 'POST');
$proxy_response = Route::dispatch($proxy);
```

`client_id` and  `client_secret` are obtained from table `oauth_clients`.

My question is that, how can directly return *access_token* if it already existed instead of creating the new token id in table `oauth_access_tokens`?

PS: I knew I can obtain token_id by using `$user->tokens`, but how can I get access_token, refresh_token through *token_id*? (Maybe I miss something in doc)

Thanks a lot.

**Comment by malutanpetronel** [comment]
I have similar question. Maybe we miss something from the flow

**Comment by alexbilbie** [comment]
This is correct behaviour for OAuth - a new request for an OAuth token results in a new access token

**Comment by SmileYuhao** [comment]
@alexbilbie Thank you so much for your reply.

I understand what you said, but I'm afraid that, in database, it maybe have many redundant data in table `oauth_access_tokens`.

So I would like to know, does it hava any solution to directly generate `access_token` and `refresh_token` by using `token_id` in table `oauth_access_tokens` instead of creating new record?

Thanks

**Comment by malutanpetronel** [comment]
In the mean time in my case I did stored the token in the local storage of the ionic2 app I am developing, and I only refresh it when / before is expiring

**Comment by SmileYuhao** [comment]
@malutanpetronel Thanks for your suggestion. 

But how about that if user logout, and re-login? Do you need remove the toke in LocalStorage and resend a request to fetch access_token?

**Comment by alexbilbie** [comment]
The solution to the redundant data is to write a Console scheduled job to run every day and remove old access tokens

**Comment by datashaman** [comment]
:+1:  also confused by the documentation on this. it gives a pathway for creating an access token after creating the client, but if you logout (with session clear) and in again, it creates new access tokens for each login. So the OAuth status page ends up with an _Authorized Application_ for each login, which doesn't make sense.

![image](https://user-images.githubusercontent.com/59514/27966579-071556b0-6340-11e7-90a2-606d8f1cf28b.png)
