### ISSUE TITLE
Postman Oauth SQL error

### ISSUE THREAD

**Issue by TheSinding** [laravel/passport#414]
Hey, I can get postman to get a token with the client and so on.. 
But if i try and use the token, I get a 
```SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: &quot;&quot; (SQL: select * from &quot;users&quot; where &quot;id&quot; =  limit 1)```

I can see there isent a client ID in the select statement, why is that ? I cant do anything ? 

And yes, i've been googling for like 4 hours, found some results, but nothing works.

**Comment by TheSinding** [comment]
So I changed the DB from pg to mysql, and now it works.. I'm getteting other errors regarding the DB in other parts of the code, like a simple Model::find() method.. 
I guess it has something to do with laravel and the postgres implementation, or my setup .

**Comment by alexbilbie** [comment]
> I guess it has something to do with laravel and the postgres implementation, or my setup .

By the looks of it yes.

Please re-open this issue if you find a bug with the library itself
