### ISSUE TITLE
chmod  Operation failed: Operation not permitted

### ISSUE THREAD

**Issue by aascc** [laravel/passport#416]
Today I update composer and i got this error.
`at Application->Laravel\Lumen\Concerns\{closure}(2, 'chmod(/var/www/app/storage/oauth-private.key): Operation failed: Operation not permitted', '/var/www/app/vendor/league/oauth2-server/src/CryptKey.php', 51, array('keyPath' => 'file:///var/www/app/storage/oauth-private.key', 'passPhrase' => null, 'keyPathPerms' => '777'))`
I was not able to solve this problem.
Thanks for help

**Comment by alexbilbie** [comment]
Can you run `chmod 600 /var/www/app/storage/oauth-private.key` and `chmod 600 /var/www/app/storage/oauth-private.key` using the terminal? That will fix your problem.

**Comment by aascc** [comment]
Thank you @alexbilbie .

**Comment by 17421932** [comment]
@alexbilbie use your, it still wrong, key path "/storage/oauth-private.key" does not exist or is not readable,can you help me.

**Comment by 17421932** [comment]
@alexbilbie it is work in local,but use in center Os service, it is not work.

**Comment by dimitribocquet** [comment]
Same issue for me, even in local environment.

**Comment by Beaudinn** [comment]
Same +1

**Comment by antverse** [comment]
same for online server.  if 777 .key files its not permitted error. if 600 not readable error.

**Comment by 757470062** [comment]
@alexbilbie Do you find reason。

**Comment by alexbilbie** [comment]
Please move conversation to  #441
