### ISSUE TITLE
Throttles

### ISSUE THREAD

**Issue by nueko** [laravel/passport#42]
Hi, I just implement Throttles on my JWT api server, using ThrottlesLogins trait and overriding some method, I think thats good idea if the Passport also has a ThrottlesLogins feature.

**Comment by kebian** [comment]
Yes.  At the moment it's possible to brute force the password grant endpoint.

**Comment by themsaid** [comment]
Thank you, a PR was opened to handle this issue https://github.com/laravel/passport/pull/184
