### ISSUE TITLE
Custom login controller, and view authorization ?

### ISSUE THREAD

**Issue by kelvinhalim13** [laravel/passport#420]
As mention in laravel-passport the login controller is made from php artisan make:auth and in our router web.php would have Auth::routes();

Simple code in our client-site
```
Route::get('/redirect', function () {

    $query = http_build_query([
        'client_id' => 'client-id',
        'redirect_uri' => 'http://client-site/callback-responses-url',
        'response_type' => 'code',
        'scope' => ''
    ]);

    return redirect('http://server-site/oauth/authorize?'.$query);
});
```

If the user is not log in the `http://server-site/oauth/authorize?'.$query` would be redirect to `http://server-site/login`

In any case of that i would like to redirect the login controller to my custom login controller. Then after i done check the use if is true would be show view about authorization request agreement

Simply i have tried to check oauth/authorize and i didnt find any function or controller handle that link. And if given any chance again. I would to know, more about the laravel-passport how the oauth work, and so do i could make the custom authorization view too after the user has login

Any help would be so helpful thank you (:

**Comment by paulmarlonsantos** [comment]
You may want to check out the **unauthenticated ** method in your **app\Exceptions\Handler.php**
