### ISSUE TITLE
OpenSSL AES-256-CTR

### ISSUE THREAD

**Issue by JonasLod** [laravel/passport#430]
I just created a new project locally and got this when I try to get a token: 
_"Cipher method not supported. This is normally caused by an outdated version of OpenSSL (and/or OpenSSL compiled for FIPS compliance). Please upgrade to a newer version of OpenSSL that supports aes-256-ctr to use this library."_
I have been using MAMP Pro 3.5 for all my projects. This new project is using passport 3.0.0 and league oauth2-server 6.0.0. I also tried to upgrade a previously working project, this updated from passport 2.0.6 => 2.0.11 and oauth2-server 5.1.3 => 5.1.5 and it's now throwing me the same error. (Also had to add `$server->setEncryptionKey(env('APP_KEY'));` in the PassportServiceProvider 😕 ) 
I already upgraded my openssl but this didn't change anything. The cipher in my app config is set to AES-256-CBC.
Any help is welcome.. I will be reverting for now.

**Comment by alexbilbie** [comment]
You need to update to update PHP's OpenSSL extension to a new version. Check if there is a MAMP update perhaps?
