### ISSUE TITLE
Oauth file reset owner by it self.

### ISSUE THREAD

**Issue by k1m0ch1** [laravel/passport#435]
Regarding to this issue https://github.com/laravel/passport/issues/418 by simply upgrading to 3.0 or set the right owner for the file : 

storage/oauth-private.key 
storage/oauth-public.key 
bootstrap/app.php
bootstrap/autoload.php 

I'm following the thread to upgrade to 3.0 or set the right owner

but after the couple of minute the file reset the owner by it self..

**Comment by tenstone** [comment]
same problem

**Comment by alexbilbie** [comment]
Please upgrade to Passport `3.0.*` and see if the issue resolves itself.
