### ISSUE TITLE
Can we override the default laravel_token cookie name?

### ISSUE THREAD

**Issue by MrFahey** [laravel/passport#443]
Hi there, just _curious_ to know whether this is possible.

I notice there is a comment regarding this in issue https://github.com/laravel/passport/issues/278, so I am assuming it's not possible.

Considering the normal Laravel session cookie's name is configurable, is there any reason as to why this cookie's name isn't?

Thanks!

**Comment by tjmartin69** [comment]
Passport::cookie('Place Cookie name here');

I use:
Passport::cookie(config('session.cookie') . '_token');

This just adds a suffix of _token to your current session cookie name

**Comment by MrFahey** [comment]
Thanks @tjmartin69!
