### ISSUE TITLE
Specific database access for clients

### ISSUE THREAD

**Issue by aliasdoc** [laravel/passport#444]
I have an application which is a REST gateway for remote PostgreSQL database and I use Passport for authentication.

This app is composed by a local MySQL database for oauth, users, roles, permissions, ... and a remote PostgreSQL with data to serve.

I need to affect a tenant for each clients (personal and password clients) like this:

```
Client A: can fetch data from schema X
Client B: can fetch data from schema Y
Client C: can fetch data from schema X and Y
```

What is the best way to do this.

Thank you.

**Comment by amazzoccone** [comment]
@aliasdoc could you find any solution for this?

**Comment by aliasdoc** [comment]
Hi @amazzoccone, yes I use two connections for database access and specify in my models constructor what connection to use. For tenants, I just make a middleware to set search path in PostgreSQL, it's trivial but work.

**Comment by driesvints** [comment]
Try to use the solution provided here: https://github.com/laravel/passport/issues/630#issuecomment-409436411
