### ISSUE TITLE
Issues with token refresh and revoke

### ISSUE THREAD

**Issue by nicolasvahidzein** [laravel/passport#445]
Hello, can you please help me.

I don't see any documentation on how to revoke a token.

also to refresh a token the route listed in laravel is : post at oauth/token/refresh

but that gives a csrf mismatch error and i discovered i could just do the regular route oauth/token and change the data bindings.

Is that the correct way to refresh a token? The time limit though on the refresh token when i do it this way is the same as a normal token whereas i set a double duration in laravel for the refresh token.

Thank you.

**Comment by aveshnaik007** [comment]
To refresh the token you can use  oauth/token

**Comment by nicolasvahidzein** [comment]
Thank you, and to delete/revoke a token?

**Comment by alexbilbie** [comment]
Token deletion and revocation is a manual process - essentially you just need to expire the token server side (e.g. by deleting the reference to it in the database or black listing the token ID)

**Comment by nicolasvahidzein** [comment]
Hello alex this does not answer the question inam sorry to say. I need to know how. 

And on a side note, how do i cleanup all the expired tokens server side?
