### ISSUE TITLE
Passport 3.0 : Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by dimitribocquet** [laravel/passport#448]
I am trying to update to passport 3.0 with Laravel 5.4.30 (I have the "[oauth-private.key](https://github.com/laravel/passport/issues/418#issuecomment-316461626)" issue with 2.0) but when I try to login, I have this error :

`Malformed UTF-8 characters, possibly incorrectly encoded`

This is what I do (from curl) :

```curl 'http://api.dev/oauth/token' -H 'Pragma: no-cache' -H 'Origin: http://localhost:4200' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:4200/login' -H 'Connection: keep-alive' --data-binary $'{\n  "grant_type": "password",\n  "client_id": 2,\n  "client_secret": "j8M6Zwdw6wJICLToyI24X86zJSpqbMiNgjg5ncQO",\n  "username": "jean.martin@example.com",\n  "password": "secretPassword"\n}' --compressed```

Thanks for your help !

**Comment by alexbilbie** [comment]
Try the request again without `--data-binary` and `--compressed` and the other gzip related flags

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
