### ISSUE TITLE
Key file permissions are not correct

### ISSUE THREAD

**Issue by cringer** [laravel/passport#453]
I am a Windows user and use Git Bash for my development terminal.
I am using PHP version 7.1.7
Default Browser is Chrome Canary or Chrome.

After installing Laravel Passport, when I run `php artisan route:list` I get the following error.

```
[ErrorException]
Key file "file://C:\Users\jschaffer\Code\passport\storage\oauth-private.key" permissions are no
t correct, should be 600 or 660 instead of 666
```

I understand what it is saying, but this is a windows machine and there is no concept of these types of permissions.  I tried changing the NTFS permissions on the file but it doesn't change this outputted error.

![image](https://user-images.githubusercontent.com/835448/28935890-c786cfc8-783a-11e7-891c-e3dfe6fa492b.png)

![image](https://user-images.githubusercontent.com/835448/28935949-f946dfe4-783a-11e7-8159-84bb4b65dfbc.png)

![image](https://user-images.githubusercontent.com/835448/28935991-172d551a-783b-11e7-990e-b3092e707a30.png)

**Comment by valeryan** [comment]
This is because of a change to the oauth package used by passport. https://github.com/thephpleague/oauth2-server/pull/776. 

Passport will have to be updated to be able to provide the new third flag to turn off this check on dev environments. 

If I figure out where that new flag needs to be I will do a PR.

**Comment by cringer** [comment]
Yeah I was just reading over that now.  Didn't realize the check was in league/oauth-2-server and not laravel passport.

**Comment by valeryan** [comment]
@cringer if you want to get your system back up and running modify a PassportServiceProvider.php in vendor/laravel/passport/src/ around line 192 to look like this:

    /**
     * Make the authorization service instance.
     *
     * @return \League\OAuth2\Server\AuthorizationServer
     */
    public function makeAuthorizationServer()
    {
        $private = new CryptKey('file://'.Passport::keyPath('oauth-private.key'), null, false);
        return new AuthorizationServer(
            $this->app->make(Bridge\ClientRepository::class),
            $this->app->make(Bridge\AccessTokenRepository::class),
            $this->app->make(Bridge\ScopeRepository::class),
            $private,
            app('encrypter')->getKey()
        );
    }

    /**
     * Register the resource server.
     *
     * @return void
     */
    protected function registerResourceServer()
    {
        $public = new CryptKey('file://'.Passport::keyPath('oauth-public.key'), null, false);
        $this->app->singleton(ResourceServer::class, function () use ($public) {
            return new ResourceServer(
                $this->app->make(Bridge\AccessTokenRepository::class),
                $public
            );
        });
    }

Passport doesn't currently have any configuration so I didn't make it optional. I just did this to get development back underway until this can be addressed.

**Comment by cringer** [comment]
@valeryan I'll give it a shot.  One thing I am confused with though is why I am getting an error.  The installed version of league/oauth2-server is 6.02 shouldn't it just throw a warning?

**Comment by valeryan** [comment]
No laravel's error handler is converting the user_notice from oauth2 to an exception.

**Comment by adiachenko** [comment]
We should just disable key permissions check by default and be done with it.

**Comment by valeryan** [comment]
I get why the check is being added. I don't agree with fully with the way it was implemented but the security principle behind the check is sound. Passport and the oauth2 package are both authentication and security packages and I think its a good idea that your private and public keys are of a certain permission. However, development environments sometimes have to break rules and skirt around security. Its like how I always turn off ssl verification in Guzzle for local development. 

So I think its important that the security check is able to be toggled by passport. Just my opinion though.

**Comment by cringer** [comment]
I don't think any application should check/set/error unless it's essential to the usage of the application.  Will setting permissions incorrectly prevent the application from working?  No not at all.  At least as a whole, it's the checking that kills the application.  I understand that it is authentication and security package but it is implementing OAuth2 not security best practices.

**Comment by cringer** [comment]
@valeryan I was able to get by the error with your fix.  Thanks for that.

**Comment by adiachenko** [comment]
@valeryan But the check does literally nothing but being the pain in the ass. 

For one, you can't do `chmod` on Docker bind-mounted volumes on Windows. And I am sure there is a whole lot of bunch of other setups broken because of this trigger happy "fix". 

Secondly, @alexbilbie could have simply mentioned this in documentation and everyone would have agreed. And no kittens have suffered. Instead, we have what we have now.

BTW, thanks a lot for the tip from above.

**Comment by maikealame** [comment]
Any other solution for windows without changing vendor files ?

**Comment by cringer** [comment]
@maikealame I'm sure that is it as of now.  Disable file checking was only merged in 6.0.2 which was introduced this morning. 

@valeryan could do a PR for his fix above.  Not sure if he's doing that or waiting until the dust settles a bit.

**Comment by valeryan** [comment]
@maikealame Changing the vendor files is a temporary workaround for people who happen to be using windows to get back to work. I guess it all depends on how precious your time is. For me I needed to get my dev env up and get back to work. 

I created a PR but I would be very supersized if this gets merged this way.  I think it will need a better solution to deal with this change.

**Comment by cringer** [comment]
Well the fix is solid IMO based on the current release of the oauth2-server package.

**Comment by johannesschobel** [comment]
same problem here.. I was wondering what happened.. This is a breaking change in OAuth2-Server - although i see why they did it.. However, the default value should be `false` instead of `true` 😞 

In the current state, passport is not usable on windows machines..

**Comment by alexbilbie** [comment]
We're aware of the issue here and a PR is being discussed in #454

**Comment by maikealame** [comment]
@cringer @valeryan Thanks, I've also edited the vendor for now.

**Comment by andradedpg** [comment]
@valeryan Hi. After changes in PassportServiceProvider.php, key path is not readble more:
![image](https://user-images.githubusercontent.com/17835049/38994204-11cd7ce2-43bc-11e8-8927-d114055ea816.png)

Any idea?

**Comment by ursuleacv** [comment]
On Rocky Linux 10

```
# pick the actual php-fpm user for your pool (often nginx or apache)
sudo chown nginx:nginx storage/oauth-private.key
sudo chmod 600 storage/oauth-private.key

sudo dnf install -y acl
# read access to other users if you want
sudo setfacl -m u:jenkins:r storage/oauth-private.key
# Only do nginx if nginx truly needs to read it
sudo setfacl -m u:nginx:r storage/oauth-private.key
```

**Comment by jamalnasir** [comment]
What if you add `Passport::$validateKeyPermissions = false;` in `\App\Providers\AuthServiceProvider::boot()` method.
