### ISSUE TITLE
oauth-private.key permission issue on windows

### ISSUE THREAD

**Issue by jigarpt** [laravel/passport#455]
Hi All, 
I am using passport on windows 10. Facing an issue while issuing a token. 

Key file \"file://E\\sample-laravel-app\\storage\\oauth-private.key\" permissions are not correct, should be 600 or 660 instead of 666

Same application works fine on Mac. Appreciate any help on this. 

Best regards,

**Comment by valeryan** [comment]
@jigarpt do a composer update. A fix for this was just merged like 3 hours ago.

**Comment by jigarpt** [comment]
@valeryan Thanks a ton, I will test it and update you. 

Best regards

**Comment by kadismile** [comment]
@valeryan YOU saved my day been stuck for 5 days

**Comment by jigarpt** [comment]
This works fine on windows, sorry for late update. 

thanks a ton.

**Comment by pakcybershagufta** [comment]
`composer update` doesn't work for me. Gives me the same error [ErrorException]
Key file "file://D:\wamp64\www\laravel-api-startup\storage\oauth-private.ke
y" permissions are not correct, should be 600 or 660 instead of 666

**Comment by elmasry200** [comment]
and me too like @pakcybershagufta

**Comment by gbelot2003** [comment]
I have the same proble, composer update not working!!!

**Comment by bikash-s-bhandari** [comment]
for solving the issue....change laravel pasport version
"require":
    {
        "php": ">=5.6.4",
        "guzzlehttp/guzzle": "^6.3",
        "intervention/image": "^2.4",
        "laravel/framework": "5.4.*",
        "laravel/passport": "^4.0",
        "laravel/tinker": "~1.0",
        "spatie/laravel-fractal": "4.0"
    },


then composer update.. it works for me

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
