### ISSUE TITLE
Issues with token refresh and revoke - Round 2

### ISSUE THREAD

**Issue by nicolasvahidzein** [laravel/passport#456]
Hello, my issue was closed but no one replied to my question. How do we delete a token please?

What url must we use for laravel 5.4 and what parameters must we pass? If there is proper docs for this i will gladly read through them but there is none i can find. Thanks for pointing me in the right direction and not close this ticket prematurely.

**Comment by yuyenkan** [comment]
check the documents, there is  restful API path "oauth\token\{id}" http method delete to remove issued token.

**Comment by driesvints** [comment]
Hey @nicolasvahidzein first of all: it's a good choice to not actually "delete" tokens. Revoking them should be enough as this will make it invalid for future usage but this way you still have an audit log of all issues ever issued should you ever feel the need for it.

As for revoking: the `Token` model has a `revoke` method which you can call. The route which @yuyenkan described above calls this method underneath.
