### ISSUE TITLE
Multiple callback urls for clients

### ISSUE THREAD

**Issue by Gregorysouzasilva** [laravel/passport#462]
Anyone knows how to enable multiples callback for the same client, perhaps saving a json on the client table and then checking all of them.
Most of the social networks have this option.

Tks

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
