### ISSUE TITLE
Package conflict with firebase

### ISSUE THREAD

**Issue by vaggelis2018** [laravel/passport#466]
When i try to install laravel passport i get this error. I think it comes from google/api. Is there any way to avoid it?

Using version ^3.0 for laravel/passport
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/passport v3.0.1
    - Conclusion: remove firebase/php-jwt v5.0.0
    - Installation request for laravel/passport ^3.0 -> satisfiable by laravel/passport[v3.0.0, v3.0.1].
    - Conclusion: don't install firebase/php-jwt v5.0.0
    - laravel/passport v3.0.0 requires firebase/php-jwt ~3.0|~4.0 -> satisfiable by firebase/php-jwt[v3.0.0, v4.0.0].
    - Can only install one of: firebase/php-jwt[v3.0.0, v5.0.0].
    - Can only install one of: firebase/php-jwt[v4.0.0, v5.0.0].
    - Installation request for firebase/php-jwt (locked at v5.0.0) -> satisfiable by firebase/php-jwt[v5.0.0].

**Comment by fgilio** [comment]
I have the exact same problem, will fork and try bumping the dep

**Comment by vaggelis2018** [comment]
i changed the order from the packages in composer.json and then i added the older version from passport. Then i execute composer update, then added passport 3 and again composer update and worked. But i don't think this is a solution...

**Comment by fgilio** [comment]
Hi @vaggelis2018 , thanks for the steps.  
I ended up not using passport as it was a huge overkill for what I needed.  
I did the fork and updated the dependency but I'm not sure if nothing broke, the auth wasn't working as expected. So I won't make the PR.

**Comment by rattfieldnz** [comment]
@vaggelis2018 What order did you have the packages in - or could you provide your composer.json file? I am having the exact same issue as you, with the same version of laravel/passport and firebase/php-jwt.

My app is not quite ready for public beta/preview; however, I'd like a reliable way to handle my API like laravel/passport does. As my app will definitely expand in the future, I think laravel/passport won't be overkill. I have looked at https://github.com/tymondesigns/jwt-auth as a possible alternative, but I think laravel/passport has more capabilities which will prove very handy for my app.

**Comment by vaggelis2018** [comment]
Sorry for the late response i was on vacations and when i return i had too much work to do. I changed the composer.json many times since then. Sorry mate. I have removed google/api cause i don't need it anymore

**Comment by driesvints** [comment]
Heya. I'm sorry but we don't support Passport working together with this library so we can't help you. Perhaps someone from the below channels can help you with your issue?

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
