### ISSUE TITLE
Call to a member function forceFill() on null when using with jenssegers/mongodb package

### ISSUE THREAD

**Issue by nolanle** [laravel/passport#467]
Hi, 
I have problem with passport when setup in laravel 5.4 and jenssegers/mongodb package has installed.

I got error bellow when I run this code: 
`$user->createToken('Personal Token')->accessToken;`

Error like this
![screen shot 2017-08-11 at 7 11 07 pm](https://user-images.githubusercontent.com/9296903/29212605-b132b0a8-7ec9-11e7-966e-cf070f2f42e9.png)

Anyone help me, please!

**Comment by abdelrahmanbadr** [comment]
did you solve it ?

**Comment by tomothumb** [comment]
@nolanle
How did you solve this problem?
I faced same issue.
It seems that it doesn't depend on MongoDB. I'm using MySQL.
https://github.com/laravel/passport/issues/713

**Comment by nolanle** [comment]
in TokenRepository change
public function find($id)
{
    return Token::find($id);
}
to
public function find($id)
{
    return Token::where('id', $id)->first();
}

This is resoved my problem!
Did you try?

**Comment by NaungYeHtet** [comment]
Any help on this issue?
