### ISSUE TITLE
Get user alway return null without middleware auth:api?

### ISSUE THREAD

**Issue by alinasiri1367** [laravel/passport#468]
I have a route /api/contact but I do not want it uses middleware auth:api, Because it public for anyone. I want to check and retrieve user info if the accessToken correct otherwise returns null.

How retrieve user info without middleware auth:api?

**Comment by alexbilbie** [comment]
You'll need to write your own middleware that extracts the user from the access token if there is one but doesn't throw an error if there isn't an access token
