### ISSUE TITLE
API Authentication Error: {"error":"invalid_request","message":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","hint":"Cannot decrypt the authorization code"}

### ISSUE THREAD

**Issue by wk1025** [laravel/passport#473]
consumer/routes/web.php

```
public function redirect() {
    $query = http_build_query([
        'client_id' => '3',
        'redirect_uri' => 'http://consumer.dev/callback',
        'response_type' => 'code',
        'scope' => '',
    ]);
    return redirect('http://passport.dev/oauth/authorize?' . $query);
}

public function callback(Request $request) {
    $http = new Guzzle();
    $response = $http->post('http://passport.dev/oauth/token', [
        'exceptions' => false,
        'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => '3',
            'client_secret' => 'gkHZlVVexmeAlxzDHjdFCYSu4mf8wkYgWrbIstbJ',
            'redirect_uri' => 'http://consumer.dev/callback',
            'code' => $request->code
        ],
    ]);
    return json_decode((string) $response->getBody(), true);
}
```

I followed the exact steps  [API Authentication (Passport)](https://laravel.com/docs/5.4/passport) to implement API Authentication using Oauth2. 

Asking for help, thank you.

Open in browser http://consumer.dev/redirect. show error

`{"error":"invalid_request","message":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","hint":"Cannot decrypt the authorization code"}`

**Comment by wk1025** [comment]
In the local operating system is win10 platform, there will be such a problem, the project transferred to the production environment, access to normal, access to access_token, I do not know why such a problem in the local

**Comment by aluciffer** [comment]
i have the exact same problem , after following the instructions from laravel to install passport and a client.
Interstingly, when i submit the form manually (authorization_code),  it works,
Only post-ing with guzzle fails into this error!

**Comment by dashty94** [comment]
Any updates on this problem?

**Comment by Empreet** [comment]
How to solve this problem. Is there any way to make it work in the local? Please suggest.

**Comment by matgargano** [comment]
same problem in OSX, works fine in postman

**Comment by luolongfei** [comment]
I have encountered the same problem. Has anyone solved it?

**Comment by SuperlativeEntity** [comment]
I know that this is an old post, but I had to make the consumer APP_KEY the same as the passport.dev app key.

**Comment by mohamedhussieen** [comment]
@SuperlativeEntity  and u solve it by this way ?

**Comment by MehdiJafari395** [comment]
did you solve this problem ? i have this problem now

**Comment by MehdiJafari395** [comment]
(   The request is missing a required parameter, includes an invalid paramet   )

this is my error

**Comment by amirb222** [comment]
did someone solved it?

**Comment by Titi999** [comment]
I have same problem, anyone solved it?

**Comment by manishahcbs** [comment]
I have same problem, anyone solved it?
