### ISSUE TITLE
TokenGuard assumes EncryptCookies middleware is used

### ISSUE THREAD

**Issue by bullenb** [laravel/passport#484]
When `CreateFreshApiToken` is used to produce a JWT, subsequent requests that use the JWT assume it has been encrypted via the `EncryptCookies` middleware and attempt to decrypt it.

In `TokenGuard`:

https://github.com/laravel/passport/blob/c6a23ff4f05543767b2828b582dd9e74cdb9b014/src/Guards/TokenGuard.php#L186-L192

If the `EncryptCookies` middleware is not included then the following method (in the `TokenGuard` class) fails and returns null:

https://github.com/laravel/passport/blob/c6a23ff4f05543767b2828b582dd9e74cdb9b014/src/Guards/TokenGuard.php#L153-L162

This results in a 401 Unauthenticated response

The issue is easily reproduced by setting up a basic Laravel/Passport install and commenting out the `EncryptCookies` middleware in `app/Http/Kernel.php`

Even if this is a necessary requirement for the middleware, the dependency should probably be documented.

**Comment by driesvints** [comment]
Heya. Seems like others have reported this as well. I'll send in a PR to the docs to make this more clear. Thanks for reporting.
