### ISSUE TITLE
restrict users to clients

### ISSUE THREAD

**Issue by aliasdoc** [laravel/passport#485]
Hi,

I need to restruct some users to some clients with different permissions, like this:
    ability to create multiples clients
    some clients are restricted to some users
    users can use one or more clients but with different scopes

Is there a way to achieve this ??

Here a diagram of what I want to achieve: [link](https://pasteboard.co/GH0uzJF.png)

Thank you.

**Comment by paly76** [comment]
?nani??

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
