### ISSUE TITLE
Is multi-factor authentication a planned feature?

### ISSUE THREAD

**Issue by nXu** [laravel/passport#490]
Is the support of multi-factor authentication (such as HOTP/TOTP like the Google Authenticator) a feature that is planned to be supported by Laravel Passport? If so, is it welcomed to implement it and be sent as a PR?

**Comment by taftse** [comment]
@nXu I think that is more something that should be implemented as your applications login flow. I don't think its part of the oauth2 flow as passport redirects the user to the login page that you specify. this page could handle the multi-factor authentication before returning the user back to the oauth flow

**Comment by driesvints** [comment]
Heya. This isn't in the scope of Passport. Passport is solely for API authentication. Like @taftse said, this would be done on the user authentication part before the user is directed to the oauth flow.
