### ISSUE TITLE
Support for OAuth 2.0 Token Introspection (RFC 7662)

### ISSUE THREAD

**Issue by rokde** [laravel/passport#491]
Is it possible to support the OAuth 2.0 Token Introspection?
https://tools.ietf.org/html/rfc7662

I already have a separate [package](https://github.com/ipunkt/laravel-oauth-introspection) for this, but maybe it could be integrated in the Passport core. This would be fine.

I can make a pull request if you are interested in.

**Comment by simonhamp** [comment]
Interesting. Your package feels like it could be split between [thephpleague/oauth2-server](/thephpleague/oauth2-server) and Passport.

The actual introspection I think should happen inside the oauth2-server package, especially if this RFC makes it into the spec. But the route and controller is the Laravel-specific part and could be in Passport.

**Comment by rokde** [comment]
Shall I made an Issue at oauth2-server instead @simonhamp ? What do you think?

**Comment by simonhamp** [comment]
I think your package is fine as a stand-alone, but if you want to see it included in Passport, I think you'll need to justify it by having the underlying functionality inside the oauth2-server package first.

It looks like there has been [some](https://github.com/thephpleague/oauth2-server/issues/579#issuecomment-218992380) [discussion](https://github.com/thephpleague/oauth2-server/issues/641) about it.

It may even be in the package already!

**Comment by driesvints** [comment]
Going to close this as this isn't implemented in oauth2-server yet. If it ever gets into the library we can perhaps see if we can add it to Passport as well.

Here's the PR: https://github.com/thephpleague/oauth2-server/pull/925
