### ISSUE TITLE
Call to undefined method Laravel\Passport\Http\Controllers\AuthorizationController

### ISSUE THREAD

**Issue by poxin13** [laravel/passport#5]
Following through the initial setup on a clean 5.3 install and getting this error when using `php artisian route:list` after adding in Passport::routes() to the AuthServiceProvider.

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Laravel\Passport\Http\Controllers\AuthorizationController::getMiddleware()
```

**Comment by underparnv** [comment]
Fixed in https://github.com/laravel/framework/commit/75d0c16f5e6deaf9f5ac32245f3bdbf51f751fcb

**Comment by poxin13** [comment]
Yup, looks good - closing this
