### ISSUE TITLE
vue components not parsing json in passport demo

### ISSUE THREAD

**Issue by alexkb** [laravel/passport#50]
I'm very new to VueJS so forgive me if I've missed something obvious. I've setup the Laravel passport project in a fresh Laravel 5.3 install, and it's all working great except that the Vue components need to have an explicit JSON.parse() call where ever they do a $http.post(). e.g. Line 260 of [resources/assets/js/components/passport/Clients.Vue](https://gist.github.com/alexkb/1f9b153fc2e2c5ec03abb584bf15e242#file-clients-vue-L260)

```js
getClients() {
  this.$http.get('/oauth/clients')
    .then(response => {
      this.clients = JSON.parse(response.data);
    });
},
```

My guess is, there's some intercepter somewhere that's supposed to do this for you? Maybe I'm missing an npm dependency?

Once I do the JSON.parse fix to the 3 passport Vue components, everything works fine. If I don't do this, I get all sorts of JS errors and weird issues with rendering.

**Comment by Townfolio** [comment]
What version of vue-resource is in your package.json ? Assuming there are no problems with your server side / headers, etc, it might be related to [this issue with vue-resource](https://github.com/vuejs/vue-resource/issues/317).

**Comment by alexkb** [comment]
@Townfolio I'm using 0.9.3 of vue-resource but according to that thread the fix hasn't been released yet anyway. I've just reverted the JSON.parse calls in the Vue components, and added the suggested interceptor to my bootstrap.js and it appears to have fixed the issue. Thanks so much!
