### ISSUE TITLE
Allowed memory size when catch exception

### ISSUE THREAD

**Issue by dantecoding** [laravel/passport#502]
When i try get access with revoked personal token, always im getting Fatal error - allowed memory size in this catch exception. 
Class TokenGuard.  
Laravel 5.5.
Passport 4.0.2

![owrdhs2wrogavhko161b-q](https://user-images.githubusercontent.com/1853220/30190739-f4974cce-9444-11e7-8a38-cd7fab4ad5ff.png)

**Comment by akalongman** [comment]
This issue is related to https://github.com/laravel/passport/issues/440

**Comment by dantecoding** [comment]
@akalongman tnx
