### ISSUE TITLE
Endless recursion when token revoked

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/passport#507]
With the `CreateFreshApiToken` added to `web` middleware group the application goes into an endless recursion if the token is revoked or doesn't exist.

`CreateFreshApiToken` tries to retrieve the user [here](https://github.com/laravel/passport/blob/4.0/src/Http/Middleware/CreateFreshApiToken.php#L80). 
```php
protected function requestShouldReceiveFreshToken($request)
{
    return $request->isMethod('GET') && $request->user($this->guard);
}
```
**Edit:** It doesn't really depend on the middleware. If anywhere during the request I try to fetch the user(eg. in a view) the script goes into the same loop.

If the token is revoked an exception is thrown [here](https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationValidators/BearerTokenValidator.php#L82). 
```php
// Check if token has been revoked
if ($this->accessTokenRepository->isAccessTokenRevoked($token->getClaim('jti'))) {
    throw OAuthServerException::accessDenied('Access token has been revoked');
}
```
Then this exception is caught by Passport `TokenGuard` [here](https://github.com/laravel/passport/blob/4.0/src/Guards/TokenGuard.php#L140).
```php
} catch (OAuthServerException $e) {
    return Container::getInstance()->make(
        ExceptionHandler::class
    )->report($e);
}
```
Next `ExceptionHandler::report()` fires `ExceptionHandler::context()` which tries to fetch the user again and the loop loops.
This loop goes on for about 40 times until PHP runs out of memory(probably) and the request ends with `ERR_CONNECTION_RESET`.

Environment:
- Laravel 5.5.3
- Laravel Passport 3.0.1
- League OAuth2 Server 6.0.2
- PHP 7.1.1

**Comment by dantecoding** [comment]
This issue is related to #440

**Comment by KKSzymanowski** [comment]
So the approved solution is to add the `OAuthServerException` class to `dontReport` list in my exception handler?

**Comment by markkarimov** [comment]
@KKSzymanowski it's not an approved solution, only a workaround until someone submits a PR. :)

**Comment by hsander** [comment]
The same problem!

**Comment by bsmathiasmoser** [comment]
I have also the same Problem - adding the OAuthServerException to the $dontReport Array in App\Exceptions\Handler seems to be a quick workaraound

**Comment by siarheipashkevich** [comment]
The same problem!

**Comment by Kyslik** [comment]
Same problem.

**Comment by driesvints** [comment]
I don't really get how this is possible. JWT tokens created by this middleware aren't stored anywhere. They can't be revoked or "not exist". They simply provide a way for your api calls to be authed through the `laravel_token` cookie. It isn't related to access tokens.

Also: you normally wouldn't use tokens issues by clients on the same app which issues them. You'd use them in a first or third party app. Either use the middleware or the client issued tokens but not both at the same time.

**Comment by MovingGifts** [comment]
@driesvints So when using `CreateFreshApiToken` I understand there is an expiry time, say 2 weeks. If a user logs out after one day, is there any way to disable access for that unexpired token or expire it somehow (say it was stolen/hijacked)? How can we handle this situation, to automatically disable access of that personal access token?
