### ISSUE TITLE
No facade?

### ISSUE THREAD

**Issue by fgambino** [laravel/passport#51]
I'm curious as to why the Passport class is static because mostly everything in Laravel uses facades and the service container. If there isn't a concrete reason, would it be acceptable to create a PR for it?

Thanks!

**Comment by poxin13** [comment]
I'd like some Facades that could be used inside the application to check if they're valid, etc. ```Passport:isValid('access_token');``` etc

**Comment by themsaid** [comment]
It's just how it was built, that's also easier for autocompletion in IDEs.
