### ISSUE TITLE
Cant grant * scopes on Client Credentials grant

### ISSUE THREAD

**Issue by philcross** [laravel/passport#516]
I'm having an issue whereby If I try to grant the scopes `*` on a `client_credentials grant, the `ScopeRepository` is stripping out the scope.

It's referenced in this issue https://github.com/laravel/passport/issues/319 but from the look of it, it seems to have been resolved, but I cant work out how. 

I'm creating an access token with the following:

```
[
    'grant_type'    => 'client_credentials',
    'client_id'     => $client->id,
    'client_secret' => $client->secret,
    'scope'         => '*',
]
```

In `Laravel\Passport\Bridge\ScopeRepository`, in the `finalizeScopes()` method, the `scopes` argument contains an scope instance containing `*`, and the `grantType` property is `client_credentials`.

But it appears this method removes `*` from client credential grants.

As a workaround, I am doing:

```
[
    'grant_type'    => 'client_credentials',
    'client_id'     => $client->id,
    'client_secret' => $client->secret,
    'scope'         => implode(' ', Passport::scopeIds()),
]
```

But I think either the docs should explictly mention that `*` is not allowed on client credential grants, or by adding `client_credentials` to the array of grants which allow `*` to be specified.

**Comment by philcross** [comment]
This test https://github.com/laravel/passport/blob/4.0/tests/BridgeScopeRepositoryTest.php#L33-L35 seems to make you believe that `*` shouldn't be allowed on client credentials?

**Comment by driesvints** [comment]
I'm actually not 100% sure why this is blocked. I'll leave this open for review by Taylor.

**Comment by Sephster** [comment]
For what it's worth, `*` is a valid character for scopes according to the OAuth spec. I checked just in case it was being incorrectly blocked by by the server but note that we don't even have restrictions on the scopes. I'm going to raise an issue to add restrictions so we conform to the spec better.

**Comment by Sammyjo20** [comment]
Hey guys, I understand this is a merged PR but I wanted to bring this back up again because I'm currently trying to use the `authorization_code` grant and realised that I'm not allowed to pass in all scopes. @driesvints, is there a reason why the flows like "authorization_code" are blocked? If there's a specific reason, I'd understand, but I suggest we should remove it entirely, maybe as an enhancement let the clients be the ones to restrict access to scopes.

**Comment by driesvints** [comment]
I have no memory of this. It's been more than 2 years.

**Comment by Sammyjo20** [comment]
Apologies, I have a discussion open here https://github.com/laravel/framework/discussions/40365
