### ISSUE TITLE
Vue Components not showing

### ISSUE THREAD

**Issue by jaythegeek** [laravel/passport#518]
Hi,

Im having some difficulty in making the Vue components render on the frontend. 

Passport has been installed perfectly on a fresh Laravel 5.5.4 install, after compiling I drop the components in to home.blade.php along with the example vue component and only the example one is showing.

This is very confusing and somewhat more frustrating, I cannot for the life of me get vuejs devtools to work. Adding Vue.config.devtools = true; to the app.js does nothing, Ive tried in various positions. Deleted the node modules folder cleared the npm cache etc.

I have deleted and reinstalled from scratch the entire evironment, still nada! 

Please help before I run out of hair to pull out!
Thanks

**Comment by Konafets** [comment]
Did you recompile everything after dropping the components? Best is to start `$ npm run watch` in one terminal and keep it running.

Vue DevTools detect Vue on your page and will be just available, assuming you installed them.

If you need further hints join the Vue slack channel on [Larachat](https://larachat.co/)

**Comment by jaythegeek** [comment]
@Konafets Hey, thanks for your reply, I have tried every which way of recompiling, run watch, run dev. The thing is the example Vue component shows up just fine, so it is definitely something in the Passport setup.

I have removed all node_modules, recompiled, cleared caches of both npm and laravel.

I will join the channel, hopefully someone will be able to help :)

Thanks
J

**Comment by LaughingCabbage** [comment]
Make sure you are placing the vue components with the proper id in your blade file.

from app.js
```
const app = new Vue({
    el: '#app'
});
```

from home.blade.php
```
<div id="app"
   <passport-clients></passport-clients>
</div>
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
