### ISSUE TITLE
Custom Exception The render method has no effect

### ISSUE THREAD

**Issue by sowork** [laravel/passport#526]
I created an exception class and implemented the render method, throwing the exception inside the code, the render method did not trigger
![image](https://user-images.githubusercontent.com/15050765/30851235-97c5d520-a2da-11e7-9b38-14504007ac89.png)

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
