### ISSUE TITLE
CreateFreshApiToken timeout

### ISSUE THREAD

**Issue by xralphack** [laravel/passport#527]
I use CreateFreshApiToken middleware to auth the api,
if I dont reload the page, it will become unauthorized as time goes by,
how can I refresh this JWT, can anyone help?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by gerardojbaez** [comment]
I'm experiencing this myself. Based on [this StackOverflow](https://stackoverflow.com/a/56622469/3204745) post, there seems to be a way to refresh the token by sending a POST request to [this route](https://github.com/laravel/passport/blob/758e143052f0a353df8dff9349f84601579e457d/src/RouteRegistrar.php#L99): `oauth/token/refresh`.
