### ISSUE TITLE
Weird UI Issue along with Console Warnings.

### ISSUE THREAD

**Issue by ChadTaljaardt** [laravel/passport#53]
Hello, 

I tried installing passport and following the tutorial and the first time it all worked fine but later on, I broke something and decided to start fresh. I deleted the database and got a fresh copy of Laravel. 

Now when I tried to follow the exact same tutorial on the Docs and the video Taylor made i get some issues. I don't know what's causing them and I don't know how to fix them.

Here are the issues.

<img width="1920" alt="screen shot 2016-08-26 at 00 01 58" src="https://cloud.githubusercontent.com/assets/13891249/17989463/58a31184-6b25-11e6-85c1-5558c9a84eda.png">

When i click the delete buttons i get this message

<img width="1059" alt="screen shot 2016-08-26 at 00 16 07" src="https://cloud.githubusercontent.com/assets/13891249/17989470/66f699f4-6b25-11e6-92ca-ad4a20ec436d.png">

I have used a new database and i tried in incognito and cleared all my browsers cookies and cache. 

I have asked on IRC but no one can help me.

**Comment by ChadTaljaardt** [comment]
So ive been testing a lot of stuff, i disabled all extensions in chrome and made sure to delete all my cache and storage on browser etc etc, seems to be an issue with chrome. 

I opened the same page after doing a fresh install again in safari and everything worked fine.

<img width="1920" alt="screen shot 2016-08-26 at 01 06 19" src="https://cloud.githubusercontent.com/assets/13891249/17989972/58beeaf4-6b29-11e6-952c-6be70388c181.png">

**Comment by ChadTaljaardt** [comment]
I created a new Personal Access Token on the Safari version of the website and reloaded the page on chrome to see what would happen and here are the results.

<img width="1920" alt="screen shot 2016-08-26 at 01 12 15" src="https://cloud.githubusercontent.com/assets/13891249/17990068/52e57bc4-6b2a-11e6-84ac-14c2ea28233c.png">


It has several hundred iterations of it for some reason.

**Comment by oluijks** [comment]
I have this issue as well. It seems only to occur in Chrome, no issues so far in Firefox. I'm looking into it. Not using browserSync seemed to fix it, but even then these errors pop up sometimes.

**Comment by ChadTaljaardt** [comment]
Firefox works for me too, only chrome issue.

**Comment by fwartner** [comment]
Having the same issue on PHPMap.co and already told @taylorotwell about it. This will hopefully fixed soon.

**Comment by fwartner** [comment]
Any updates on this?

**Comment by ChadTaljaardt** [comment]
not from me :/

**Comment by robinmartin** [comment]
This is not a solution to the problem but turning off SSL makes the problem go away. For some reason when SSL is on, vue resource is stringifying the response which is why you see the error - i.e. length is not a string method.

**Comment by fwartner** [comment]
[Got it working!](https://github.com/laravel/passport/pull/80) 🎉
