### ISSUE TITLE
[4.0.2] Call to undefined method "withCookie"

### ISSUE THREAD

**Issue by BostjanOb** [laravel/passport#530]
This issue is just re-opened issue #489

Somehow this issue was fixed in 4.0.0, then code got lost in 4.0.1+. So if you are using latest version (currently 4.0.2) there is still this fatal error "call to undefined method".

**Comment by heyhoo** [comment]
This is already fixed on the master branch but hasn't been released yet.

**Comment by driesvints** [comment]
Should be fixed by now.
