### ISSUE TITLE
Error in test with PHP 7.2: count() @ CreateFreshApiTokenTest::testShouldReceiveAFreshToken

### ISSUE THREAD

**Issue by edsamonte** [laravel/passport#531]
`CreateFreshApiTokenTest::testShouldReceiveAFreshToken` is failing and throwing
```
count(): Parameter must be an array or an object that implements Countable
```

PHP version: 7.2.0beta3

#### More info on `count()` behavior on PHP 7.2
* https://wiki.php.net/rfc/counting_non_countables

**Comment by Mechazawa** [comment]
Confirmed the error on my local machine, I'll have a look at it.

**Comment by Mechazawa** [comment]
Bug found in Mockery's `Expectation.php` 
`_expectedArgs` can be null so `count()` will throw an exception

**Comment by neomobil** [comment]
We had a problem like this today. On php 7.1 is Ok, but not on 7.2 Laravel Version 5.3

**Comment by hireahenchman** [comment]
confirmed. Same problem but just using php 7.2 

I'm having to change instances of ```count()``` to ```isset()```

**Comment by virusphp** [comment]
same i have error with count()

**Comment by driesvints** [comment]
Seems like this was fixed.
