### ISSUE TITLE
how to create personal access toke while registering a new user.

### ISSUE THREAD

**Issue by kjhatis** [laravel/passport#533]
Please tell me how to create personal access token while adding new User...

Also how to authenticate a user using personal access token?

**Comment by spmsupun** [comment]
Same problem

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
