### ISSUE TITLE
is passport support PKCE ?

### ISSUE THREAD

**Issue by bunnypro** [laravel/passport#534]
currently i'm looking for a way to secure my api that's accessed by my first party mobile app.

in laravel/passport doc suggest to use password grant, but in https://github.com/thephpleague/oauth2-server/issues/758#issuecomment-323199159 said that it should not be used. then it mention to use PKCE, but i don't find any documentation in laravel/passport about it.

is passport support PKCE ? how do i implement it ?

**Comment by hamzashahid91** [comment]
@bunnypro did you find a way to implement PKCE in Laravel? Please help i am also stucked

**Comment by bunnypro** [comment]
what i actually want is a machine-to-machine authentication. if you are also looking for this, you can use client credential https://laravel.com/docs/5.5/passport#client-credentials-grant-tokens
