### ISSUE TITLE
Customizing the token response, adding status, message, custom variable etc

### ISSUE THREAD

**Issue by sandipsapkota1** [laravel/passport#535]
Hi, 
My current login response is like this,

```json
{
    "token_type": "Bearer",
    "expires_in": 31536000,
    "access_token": "eyJ0eWq4Pt2B7M8W5zWwepDNpWqL0FOzdA8sPNiPhfxJcaktCq7GqQJDNLfPCuN5_Cl4",
    "refresh_token": "def50200278e5e6e658f2149489a6d1578ce4cdef1abb80e21df5efa4bbbc7003840df34768a091a57e88c0"
}
```

But i need this response,

```json
{  
   "success":"true",
   "message":"Login Successful",
   "status":"200",
   "data":{  
	 "token_type": "Bearer",
    "expires_in": 31536000,
    "access_token": "eyJ0eWq4Pt2B7M8W5zWwepDNpWqL0FOzdA8sPNiPhfxJcaktCq7GqQJDNLfPCuN5_Cl4",
    "refresh_token": "def50200278e5e6e658f2149489a6d1578ce4cdef1abb80e21df5efa4bbbc7003840df34768a091a57e88c0"
}
```

Can somebody help me how to customize the default token response,
 i am new to passport. Thanks in advance.

**Comment by rafapaulin** [comment]
I would like this info too =)

**Comment by nighthacker** [comment]
Hello, have you solved this issue?

**Comment by driesvints** [comment]
Customizing the response would involve overwriting the `AuthorizationServer` and adding your own implementation of `League\OAuth2\Server\ResponseTypes\ResponseTypeInterface`. Anyway, it's a little out of scope for this package so please try one of the below support channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
