### ISSUE TITLE
Error on post /oauth/authorise

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/passport#54]
I call:

> http://mysite.dev/oauth/authorize?client_id=xyoZZOVmyp1LylNVqJyOM41FDg1LICGpug71SfZX&redirect_uri=http://my-site.com/callback&response_type=code

And view on page:

> SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "xyoZZOVmyp1LylNVqJyOM41FDg1LICGpug71SfZX" (SQL: select \* from "oauth_clients" where "oauth_clients"."id" = xyoZZOVmyp1LylNVqJyOM41FDg1LICGpug71SfZX limit 1)

**Comment by jbrooksuk** [comment]
What database driver are you using?

**Comment by andrey-helldar** [comment]
Здравствуйте!

Ваше письмо принято в обработку. Вам постараются ответить в кратчайшие сроки.

С уважением
     автоответчик

**Comment by andrey-helldar** [comment]
PostgreSQL 9.5.3 x64 on Windows 10 x64 with [OpenServer](http://open-server.ru/)

**Comment by nueko** [comment]
> invalid input syntax for integer

what type of the id column is in your table?

**Comment by andrey-helldar** [comment]
> what type of the id column is in your table?
Default from package - integer`

Schema of table:

> -- Table: public.oauth_clients
> 
> CREATE TABLE public.oauth_clients
> (
>   id integer NOT NULL DEFAULT nextval('oauth_clients_id_seq'::regclass),
>   user_id integer,
>   name character varying(255) NOT NULL,
>   secret character varying(100) NOT NULL,
>   redirect text NOT NULL,
>   personal_access_client boolean NOT NULL,
>   password_client boolean NOT NULL,
>   revoked boolean NOT NULL,
>   created_at timestamp(0) without time zone,
>   updated_at timestamp(0) without time zone,
>   CONSTRAINT oauth_clients_pkey PRIMARY KEY (id)
> )
> WITH (
>   OIDS=FALSE
> );
> ALTER TABLE public.oauth_clients
>   OWNER TO root;
> 
> -- Index: public.oauth_clients_user_id_index
> 
> CREATE INDEX oauth_clients_user_id_index
>   ON public.oauth_clients
>   USING btree
>   (user_id);

**Comment by themsaid** [comment]
That's not a valid client ID>
