### ISSUE TITLE
How to store generated token

### ISSUE THREAD

**Issue by Peter2962** [laravel/passport#545]
I am new to using laravel passport. I already finished setup using some examples found online but now i am trying to store the token that i get. Please code that i am using to get token below:

$user = Auth::user();
$success['token'] =  $user->createToken('NearLocalApp')->accessToken;
return response()->json(['success' => $success], $this->successStatus);

**Please what is the best way to store the token**? Thank you.

**Comment by itsUndefined** [comment]
You don't have to store such a token.
