### ISSUE TITLE
oauth SSO issue on Windows 10

### ISSUE THREAD

**Issue by cbloss** [laravel/passport#548]
Hey! This is a weird issue that is only happening on my local box (yaay Windows! :)), but I thought I'd report it. We have multiple applications using the same system using Passport to carry a session with an API call. Well the API call to the is getting confused which database to look at. For example...

- Parent Application
- Sub application that calls to parent to see if user is logged in.
- Parent returns a 401 error. 

When I added a Log to the BearerTokenValidator.php in the very last catch, I get an error where it's looking for the oauth_access_tokens table in the sub parent database on the parent side. I'm only having this happen on Windows. Linux is just fine. 

`Base table or view not found: 1146 Table 'subparentdatabase.oauth_access_tokens' doesn't exist`

Weird eh? I tried to force it to look at the parent database connection but I think I'm doing it in the wrong spots AND of course no one should change vendor files. Help??

**Comment by cbloss** [comment]
Pump?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
