### ISSUE TITLE
Getting 401 on AWS passport authendication

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [laravel/passport#549]
I'm getting 401 error on accessing AWS API services.
Local package will work fine on local installation.
But, AWS installation have issue on calling API.

Issue : https://stackoverflow.com/questions/47009500/laravle-passport-authentication-issue-on-aws-server

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
