### ISSUE TITLE
Retrieving a personal access token after it's been created

### ISSUE THREAD

**Issue by shinta5150** [laravel/passport#552]
My current workflow is:
1) After user registered, automatically create a Personal Access Token (PAT) to access the API
2) However once the token is created, how are we able to display the PAT again.
`// Creating a token with scopes...
$token = $user->createToken('Pricing Token', ['get-pricing])->accessToken;`

Essentially it would be good for the user, once they have logged in to my secured site to download the Token at any time to use on their own site. Essentially I'm using the PAT to identify the user so don't need the full OAUTH workflow.

Reading through the source code, I'm able to regenerate the Access token, but how are we able to retrieve the original Token generated in Step 2.

**Comment by peyobr** [comment]
+1

**Comment by Mont4** [comment]
+1

**Comment by FrittenKeeZ** [comment]
I created this trait to grab the latest valid token for a user, with the default personal access client.
```php
<?php

namespace App\Models\Traits;

use Laravel\Passport\ClientRepository;
use Laravel\Passport\Token;
use Laravel\Passport\TokenRepository;

trait AccessToken
{
    /**
     * Get personal access token for user.
     *
     * @return \Laravel\Passport\Token|null
     */
    public function getToken(): ?Token
    {
        return app(TokenRepository::class)->findValidToken(
            $this,
            app(ClientRepository::class)->personalAccessClient()
        );
    }
}
```

**Comment by khoude24** [comment]
@FrittenKeeZ  How do you used it?

**Comment by driesvints** [comment]
Hey there. There's a `token` and `tokens` method on the `HasApiTokens` trait. Is this what you need? Please not that these aren't filtered on revoked etc.

**Comment by mikebronner** [comment]
@driesvints it seems those two methods don't include personal access tokens?

**Comment by kevinb1989** [comment]
Is it possible for me to retrieve the ACCESS TOKEN string from a Laravel\Passport\Token object?

**Comment by julesgraus** [comment]
> Is it possible for me to retrieve the ACCESS TOKEN string from a Laravel\Passport\Token object?

I would like to know this too! In passport it is pretty easy to create tokens and clients, but not so easy (not documented well enough) to get tokens after they are created.

**Comment by VishalParkash** [comment]
> Why not acces it from database?

Do you have code for this task ?

**Comment by rddewan** [comment]
I am using Laravel 8 and Passport 10.1 . is there any to retrieve a Personal Access Token after it has been created ?

**Comment by marwan2** [comment]
This thread discussion doesn't reply to who ask to get created Personal Access Token yet ?
I'm having the same concern

**Comment by BourneSuper** [comment]
can not reuse a token in server side, the created token is only save by client. And server saved hash( token ), which is not reverseable.
`    
HasApiTokens.php
    public function createToken(string $name, array $abilities = ['*'], DateTimeInterface $expiresAt = null)
    {
        $plainTextToken = sprintf(
            '%s%s%s',
            config('sanctum.token_prefix', ''),
            $tokenEntropy = Str::random(40),
            hash('crc32b', $tokenEntropy)
        );

        $token = $this->tokens()->create([
            'name' => $name,
            'token' => hash('sha256', $plainTextToken),
            'abilities' => $abilities,
            'expires_at' => $expiresAt,
        ]);

        return new NewAccessToken($token, $token->getKey().'|'.$plainTextToken);
    }
`
