### ISSUE TITLE
I confuse that what the table 'oauth_personal_access_clients' is used to do.

### ISSUE THREAD

**Issue by gavinliu6** [laravel/passport#555]
I think the table 'oauth_personal_access_clients' is redundant, so what is it used to do? @taylorotwell

**Comment by wanghanlin** [comment]
I have the same question on that

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
