### ISSUE TITLE
Missing CORS headers for /oauth/token

### ISSUE THREAD

**Issue by Mechazawa** [laravel/passport#559]
`/oauth/token` routes are missing CORS headers and return a `HTTP 405` response when doing a HEAD request.

**Comment by TimOgilvy** [comment]
you may find this useful https://github.com/barryvdh/laravel-cors 🍻

**Comment by bahadorbzd** [comment]
laravel-cors  not work for me

**Comment by driesvints** [comment]
Try the package mentioned above.

**Comment by danielrangelsa** [comment]
File: config/cors.php

ADD oauth/* from paths

`'paths' => ['api/*', 'oauth/*'],`

**Comment by OzanKurt** [comment]
@danielrangelsa Saved the day!
