### ISSUE TITLE
Consuming own API: EncryptCookies necessary prerequirement

### ISSUE THREAD

**Issue by BillyBoeklunder** [laravel/passport#560]
Hey everybody,
so I had some issues with consuming my own API after following the docs.
The cookie was there, everything's fine but still the response was "Unauthenticated" without any exceptions.

So I started debugging the TokenGuard and found out that there _was_ an exception, a DecryptException to be precise. _By the way it's kind of confusing having no exception when in fact there is one. But this is another topic and I understand why it is like that._

It came out that the cookie could not be decrypted as it was never encrypted (makes sense, huh?).
With this information I looked at my Kernel.php again. Long story short: The EncryptCookies middleware is required for this concept to work. This tiny little information could be interesting for the docs especially because the docs state out that there is nothing more to do. I assume it's because the EncryptCookies middleware is usually already defined, something like this:

```
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
    ];
```

It came out that the EncryptCookies middleware has to be defined for your MiddlewareGroup "web" explicitly.

So my 2 points: 
- A little hint (even though it's kind of obvious) in the docs about this requirement would be useful.
- Can anybody confirm that it has to be defined for the WebGroup explicitly? I'm kind of worried why this doesn't work if the EncryptCookies middleware is defined for all routes instead of the web group? Not really sure if this is related to passport or if it is a concept in Kernel.php that I missunderstood? Or even a bug in laravel itself? This would be weird though.

Any information about your experiences (especially if it's working if you define the middleware for all routes) would be appreciated.

Thanks for your attention.

**Comment by Evertt** [comment]
Seriously, I just wasted hours on this wondering why it wasn't working. My mistake was that I had the CreateFreshApiToken middleware before the EncryptCookies middleware. A hint would be very nice.

**Comment by driesvints** [comment]
Hey everyone. The docs clearly state that the `CreateFreshApiToken` middleware needs to come *after* the other web middleware. Please see here: https://laravel.com/docs/5.7/passport#consuming-your-api-with-javascript
