### ISSUE TITLE
Shorter personal access tkoen

### ISSUE THREAD

**Issue by anbu369** [laravel/passport#561]
I generated a personal access token and the length is 1074 whereas the token stored in database is 80. Is there a way to get a shorter token since I will be giving this to the users for api access and this is too long or is it possible to use the token generated and stored in the database?

**Comment by RezaGhanbari** [comment]
You can change default length in vendor/laravel/passport/src/Console/KeysCommand.php.

`$keys = $rsa->createKey(4096);`

**Comment by anbu369** [comment]
@RezaGhanbari I did try that but still the length is 1071. I did dump-autoload too but no luck

**Comment by RezaGhanbari** [comment]
I hope you find this helpful. 
If you want to just show the first n characters of generated personal access token, try to change `this.accessToken = accessToken to this.accessToken = accessToken.substring(1, n);` in showAccessToken function of PersonalAccessTokens.vue

**Comment by anbu369** [comment]
@RezaGhanbari Thanks but It is not just about displaying the token. I am creating a plugin to sell and the frontend of the plugin is in jquery and the backend API is in laravel. I want to limit the number of calls they make and authenticate the calls. So I will be providing my customers with an access token. This is too big to give as an access key. Would you suggest any other method for this approach? Thanks

**Comment by brunogaspar** [comment]
See if this helps https://github.com/chrisbjr/api-guard @anbu369

**Comment by anbu369** [comment]
@brunogaspar Thanks for that. That was the only good solution. But I wanted to stick with passport and I finally settled with client-credentials. Thanks :)

**Comment by vcc3** [comment]
anbu, i am having the same issue where the token generate is approx 1071 characters. what was the solution to this if there was one?

**Comment by anbu369** [comment]
@vcc3 Hi, there was no solution. The personal access token is always 1071 characters. Like I mentioned above, I started using client credentials. So when a user purchases my API, they get a client_id and client_secret. The user then uses them to get an access token. Then when the access token  is used to access my API, I can retrieve the user information to monitor.

**Comment by awebartisan** [comment]
What if there was no backend language involved and user cannot go through the OAuth flow for creating access tokens? I am creating an API to be consumed in a Shopify theme and every customer who purchase the theme will be given an access token, but personal access token is very long. It will cause issues in ajax request ( get method ). Any other solution to this? Other than Passport? Thanks.

**Comment by anbu369** [comment]
@awebartisan I am afraid not. Not that I know of. I ended up using passport client id and secret. Without using some custom backend logic, I dont think you can achieve that. But let me know if you find one :)
