### ISSUE TITLE
HasApiTokens outside User class

### ISSUE THREAD

**Issue by JValck** [laravel/passport#565]
Is it possible to use the `HasApiTokens` trait outside the `User` class?
Each example I found uses the trait in the `User` class.

Example:
Let's say I want to use my API on a domain base instead of `User` base, so that each entry in the `website` table in the database has its own token.
How should one accomplish this?

**Comment by bkuhl** [comment]
You wouldn't issue tokens to a `Website`, you'd still issue them to a `User` who has access to certain `Website`s

**Comment by driesvints** [comment]
Think this is slightly related to https://github.com/laravel/passport/issues/161?
