### ISSUE TITLE
Every user should use a unique oAuth client?

### ISSUE THREAD

**Issue by yooouuri** [laravel/passport#567]
I am using the following library to login facebook against Passport: https://github.com/danjdewhurst/Laravel-Passport-Facebook-Login

I make the following `POST` request to `/oauth/token` to receive a token.

```
$response = $http->post(url('/oauth/token'), [
     'form_params' => [
          'grant_type' => 'facebook_login',
          'fb_token' => 'token from facebook login',
          'client_id' => '?????',
          'client_secret' => '?????',
     ],
]);
```

What `client_id` and `client_secret` do I need to use? Perform a `POST` to `oauth/clients` and use the returned `client_id` and `client_secret`? But when every time somebody tried to log in, it creates a new oAuth client...

**Comment by Kyslik** [comment]
When deploying to your server, create your own client (for your frontend, lets say angular, or iOS app), and use those "credentials" (`client_id` && `client_secret`, its called proxy, do this only if you own frontend code.

Store these credentials within `.env` file.

**Comment by driesvints** [comment]
Please post this issue on their library.
