### ISSUE TITLE
Error at Create Token and client

### ISSUE THREAD

**Issue by marslanniaz** [laravel/passport#570]
I have installed passport in my laravel project 4-5 days ago. Now I am trying to create token but is showing this error.  
![error](https://user-images.githubusercontent.com/30683178/33060275-896c8c20-ceb9-11e7-857e-69b56b51ca36.PNG)

I have refreshed the migration, run the passport:install and passport:keys command but noting is working.
![create client](https://user-images.githubusercontent.com/30683178/33060404-eb86da14-ceb9-11e7-9678-37e59f649f3a.PNG)

The same issue is with create client.

**Comment by LeonAlvarez** [comment]
Check ur browser console errors.

**Comment by marslanniaz** [comment]
I think i figure out the problem when i run the project with 

> php artisan serve 

the project works normal.
![with serve command](https://user-images.githubusercontent.com/30683178/33360167-692adbc4-d4f4-11e7-949b-749e0db2ec02.png)

When I try to run it directly 

![without serve command](https://user-images.githubusercontent.com/30683178/33360172-7248ca40-d4f4-11e7-987e-ca48615d244c.PNG)

How can I resolve these errors.

**Comment by LeonAlvarez** [comment]
As though its because project running under subdirectory.
You have two options point server to the public folder of your laravel project or fix route in the vue js.

**Comment by marslanniaz** [comment]
Thank you it was really helpful.

**Comment by shofin-islam** [comment]
i cant find route on vuejs ... can you help me @LeonAlvarez

**Comment by LeonAlvarez** [comment]
@shofin-islam /resources/assets/js/components/Clients.vue

**Comment by shofin-islam** [comment]
change it but not works, may be controller not working, i need to change the base url for vuejs. so that all function will work. can you help me to out this. @LeonAlvarez
