### ISSUE TITLE
Please tag a 3.0.2 release

### ISSUE THREAD

**Issue by Jalle19** [laravel/passport#571]
https://github.com/laravel/passport/pull/465 has been merged into the 3.0 branch, but no new release has been tagged. I would rather not upgrade to 4.0 since there is no upgrade guide or CHANGELOG to be found anywhere as far as I can tell.

**Comment by Jalle19** [comment]
Any update on this? @taylorotwell ?

**Comment by driesvints** [comment]
We don't support 3.0 anymore. Please update to the latest release.

**Comment by Jalle19** [comment]
This wasn't about supporting but adding a single tag...

**Comment by driesvints** [comment]
Hey @Jalle19. At the moment the 3.0 branch is failing so we can't tag a release atm. Otherwise people might get a broken build.

**Comment by Jalle19** [comment]
Okay, that's a shame. I don't use this package anymore so to me it's all the same.
