### ISSUE TITLE
Laravel passport gives 401 Unauthenticated error

### ISSUE THREAD

**Issue by NikhilRadadiya** [laravel/passport#574]
I'm using laravel passport for API authentication, it works perfectly when I use it with one db, but gives `401` when using multiple database,

What I'm doing:

 - I have a multi-tenant db, master db have users,roles and all oauth tables. 
 - When I create user with admin role it will create new db with admin name, it will create sub db with users,roles and all oauth table. `oauth_clients` of sub db will copy Password Grant Token and Personal Access Token from master db and insert in sub db, and also insert `client_id` in `oauth_personal_access_clients`.
 - I'm doing all procedures which `passport:install` command do.(If I'm not missing something).

 - I login with credentials from master db it works perfectly, the real problem starts when I login in sub database, Also I can get sub db from a param `client_code` which I input with `email`,`password` while login.
 - It allows me login from sub db but i get `401 Unauthenticated`  error, Also I pass `Authentication` Header with `Bearer`.

 - Don't know what I'm missing here.

**DBConnection Middleware**

DBConnection middleware  sets connection on every request after login,

    public function handle($request, Closure $next)
        {
            if ( $request->method() != 'OPTIONS' ) {            
                $this->access_code = $request->header('access-code'); 
                if ( $this->access_code != '' && $this->access_code != 'sa'  ) {
                    app('App\Http\Controllers\Controller')->setDB(AppHelper::DB_PREFIX.$this->access_code);
                } else {
                    app('App\Http\Controllers\Controller')->setDB(AppHelper::DB_DEFAULT);
                }
            }
            return $next($request);
        }

  `DBConnection` sets default db in `database.php` dynamically, for that I'm calling `setDB` method created on `Controller.php`

**setDB Controller.php**

    public function setDB($database='') {
          $config = app()->make('config');
          $connections = $config->get('database.connections');
          $default_connection = $connections[$config->get('database.default')];
          $new_connection = $default_connection;
          $new_connection['database'] = $database;
          $config->set('database.connections.'.$database, $new_connection);
          $config->set('database.default', $database);
      }

Is it possible to use `passport` with 2 different db for same code?

`Laravel 5.4`
`Passport 4.0`
`Angular 4.4` in front-end

**Comment by sathyas17** [comment]
could you find any solution for this?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
