### ISSUE TITLE
How to Create Multiple Clients and under a client there will be Many Sub-clients 

### ISSUE THREAD

**Issue by kjhatis** [laravel/passport#579]
is is possible to create multilevel clients, like i have 

1. BaseClient1
        a. User-1
        b. User-2
        c. and So On
2. BaseClient2
        a. User-1
        b. User-2
        c. and So On
3. BaseClient3
        a. User-1
        b. User-2
        c. and So On

Like this!

**Comment by driesvints** [comment]
We have no support for that atm and aren't planning on adding support for this anytime soon.
