### ISSUE TITLE
How to create token without passowrd?

### ISSUE THREAD

**Issue by Seaony** [laravel/passport#582]
Hi，how to create token without passowrd？ls there a method like to the following? thanks! ：）
 
```php
$user = User::find(1);
$token => Passport::fromToken($user);
return respone()->json($token);
```

**Comment by fgreinus** [comment]
Hey,

if your user uses the HasApiTokens trait you can use $user->createToken(). See https://imgur.com/a/vp0km.

You get a PersonalAccessToken out of it that contains all you need to continue.

Hope that is what you were looking for!

**Comment by Seaony** [comment]
@fgreinus  going to try. Thanks!
