### ISSUE TITLE
Laravel 5.5 Passport: '401 Unauthorized' on remote host

### ISSUE THREAD

**Issue by Smoke1987** [laravel/passport#587]
I'm using Laravel 5.5 with `"laravel/passport": "^4.0"`, `"barryvdh/laravel-cors": "^0.10.0"`. API authentication is implemented according to [https://laravel.com/docs/5.5/passport](https://laravel.com/docs/5.5/passport). When I develop, I test on the local server. Everything works perfectly. But when tested on a remote server, any route with `middleware ('auth: api')` produces an error `401 Unauthenticated`. Clearly, there is little information, I'm new to this. I am ready to provide any necessary information for understanding the problem. I hope for help.

**Comment by kjhatis** [comment]
what are the headers you are sending with the request?

try Adding: 
`
Content-Type: application/json
Accept: application/json
`

**Comment by Smoke1987** [comment]
These headers are present. There is also a heading `Authorization: Bearer ...access_token...`

![1](https://user-images.githubusercontent.com/26324597/34407198-ec4f81c0-ebde-11e7-9019-30a9aeb069e9.png)

**Comment by kjhatis** [comment]
`Content-Type: application/json `
`Accept: application/json`

Add these two also

**Comment by Smoke1987** [comment]
In the screenshot above you can see that these headers are present ?!

**Comment by Smoke1987** [comment]
I tried to return the request headers, which I make from the client application.

<img width="483" alt="2" src="https://user-images.githubusercontent.com/26324597/34407607-0abe73da-ebe1-11e7-903a-ae02960074b1.png">

Get response:

![3](https://user-images.githubusercontent.com/26324597/34407643-440edd78-ebe1-11e7-919c-0abb2a046e01.png)

Why there is no `Authorization` header in the request object??
