### ISSUE TITLE
Wrong oauth/authorize url

### ISSUE THREAD

**Issue by enx1998** [laravel/passport#591]
Hi,
I have a laravel website installed in a subfolder (eg http://www.domain.com/laravel-app) and when I try the ouath2 authentication process laravel redirect me to wrong oauth/authorize url: http://www.domain.com/oauth/authorize instead of http://www.domain.com/laravel-app/oauth/authorize.

Thanks Vincenzo

**Comment by theredfoxfire** [comment]
```
                         <form method="post" action="/oauth/authorize">
                                {{ csrf_field() }}

                                <input type="hidden" name="state" value="{{ $request->state }}">
                                <input type="hidden" name="client_id" value="{{ $client->id }}">
                                <button type="submit" class="btn btn-success btn-approve">Authorize</button>
                         </form>
```

Found this in laravel passport view at `authorize.blade.php`, maybe the value of action props causing wrong action url. Can we use something like `action="{{ url('oauth_authorize') }}">`?. It's on `"laravel/passport": "4.0",`

**Comment by driesvints** [comment]
This has been updated in the meantime.
