### ISSUE TITLE
How do I create a client credentials client?

### ISSUE THREAD

**Issue by rjmackay** [laravel/passport#601]
I see there are flags for password, and personal access clients. Does a client credentials grant work with any client or does it need a set flag?

**Comment by tomcoonen** [comment]
It seems to work with any type, but I agree this is some documentation missing here..

**Comment by driesvints** [comment]
Here you go: https://laravel.com/docs/5.7/passport#client-credentials-grant-tokens

**Comment by driesvints** [comment]
Ah sorry, I misunderstood what you meant. You can just create a client  [as described here](https://laravel.com/docs/5.7/passport#managing-clients) and use that id an secret to make a request as described here: https://laravel.com/docs/5.7/passport#client-credentials-grant-tokens

**Comment by driesvints** [comment]
I have to apologize again. There is a `--client` flag for the `passport:client` command. I'll try to update the docs with that as soon as I can.
