### ISSUE TITLE
TokenGuard fails to render OAuthServerException

### ISSUE THREAD

**Issue by goodevilgenius** [laravel/passport#602]
When a request is made via a Bearer token to a guarded route, and the provided token is invalid, a response like this is returned:

```
HTTP/1.1 401 Unauthorized
Server: nginx/1.10.3 (Ubuntu)
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, private
Date: Wed, 10 Jan 2018 13:55:53 GMT

Unauthorized.
```

The body of the response is not customizable. This is due to the fact that the `render` method of the Exception Handler is not being called.

`TokenGuard->authenticateViaBearerToken` has the following code:

```php
$psr = (new DiactorosFactory)->createRequest($request);

try {
    $psr = $this->server->validateAuthenticatedRequest($psr);

    // ...
} catch (OAuthServerException $e) {
    return Container::getInstance()->make(
        ExceptionHandler::class
    )->report($e);
}
```

The `report` method is being called, but the `render` method is not, so any exception rendering isn't being done.

If the `try/catch` were removed, Laravel's built-in Exception handling would be utilized, and the desired response would be sent to the end user.

**Comment by goodevilgenius** [comment]
I discovered that this is actually handled by the built-in `auth` middleware, which by default is at `app\Http\Middleware\Auth.php`.

The boilerplate code read:

```php
if ($this->auth->guard($guard)->guest()) {
    return response('Unauthorized.', 401);
}
```

But, I could get the desired behavior by changing this to:

```php
if ($this->auth->guard($guard)->guest()) {
    throw new HttpException(Response::HTTP_UNAUTHORIZED, 'Unauthorized');
}
```

So, no change it needed for `TokenGuard`.

**Comment by xiejohnny** [comment]
what's your laravel and laravel-passport version?

**Comment by goodevilgenius** [comment]
@xiejohnny Lumen 5.6 (although installed at 5.5), with Passport 5.0.3
