### ISSUE TITLE
Documentation doesn't exist

### ISSUE THREAD

**Issue by LMKight** [laravel/passport#604]
There is no documentation of Passport. 
The only documentation-like piece of text found is this:
https://laravel.com/docs/5.5/passport
which does not even mention some parts which are essential for implementing Passport such as:
DELETE oauth/token/{token_id}
The only hints that some parts of Passport even exist are in the source code.

Apart from that, the values needed in most Reqeusts and Respones aren't mentioned at all.

**Comment by driesvints** [comment]
Docs are here: https://laravel.com/docs/5.7/passport

You're always free to send in PRs to https://github.com/laravel/docs if you feel that parts are missing.
