### ISSUE TITLE
How to create token (password grant) for special user (without password)

### ISSUE THREAD

**Issue by makzef** [laravel/passport#613]
Hi, everyone!
First, sorry if such issue is already was. And sorry for my English...
I am newer at laravel and I like it.
Now I learning how to create REST API app and for this I use laravel/passport.
And my target is to make social networks authorize via API. How it should work:

> 1. Client app, for example - mobile app, must send me (my app at laravel) request with Google token (for example).
> 2. From receive token I get the data about user, save it or find already existent.
> 3. After that I must send a token (from my app, not Google one), refresh token and expires_at.

Of course in normal api auth I use password_grant where you must do request with login and password, and it generate token, refresh token,expires_at. But how to do it if you have not password? How to create token, refresh token and expires_at for special user?
I know about personal tokens, but it only 'longlive' token? It make no sense! Why is not exist personal token that go with refresh token and expires_at or password token where you can create it directly?
 Is there are some right solution? Will be solution in a future version of laravel/passport?

I will be very thankful if you can advise some really good solution.

**Comment by seakleng2016** [comment]
this video can help you 
https://www.youtube.com/watch?v=fHkXwGNnJWQ&t=123s

**Comment by seakleng2016** [comment]
let me tell my trick ,do not need write code or any boiler code or any plugin . 
use replace password with access_token or user_id then encrypt it with bcrypt and use user_id replace name or email.

**Comment by adaojunior** [comment]
@makz maybe this can help you: [passport-social-grant](https://github.com/adaojunior/passport-social-grant)

**Comment by springjk** [comment]
@makz maybe this can help you: https://github.com/laravel/passport/issues/71#issuecomment-330506407

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by Devamit2016** [comment]
want to generate the token without password for the third party or api using email only....

**Comment by vahidahmad** [comment]
To create token without password you can use `validateForPassportPasswordGrant()`  method in `User` model, it will override credentials check,  now to work without password just return true inside the function. 

```
 public function validateForPassportPasswordGrant($password)
    {
        return true;
    }
```

[It's in the laravel docs.](url)

**Comment by LaravDev** [comment]
> To create token without password you can use `validateForPassportPasswordGrant()` method in `User` model, it will override credentials check, now to work without password just return true inside the function.
> 
> ```
>  public function validateForPassportPasswordGrant($password)
>     {
>         return true;
>     }
> ```
> 
> It's in the [laravel docs.](https://laravel.com/docs/7.x/passport#customizing-the-password-validation)

Thanks for this, but what if i want to create tokens with and without password?

**Comment by vahidahmad** [comment]
> > To create token without password you can use `validateForPassportPasswordGrant()` method in `User` model, it will override credentials check, now to work without password just return true inside the function.
> > ```
> >  public function validateForPassportPasswordGrant($password)
> >     {
> >         return true;
> >     }
> > ```
> > 
> > 
> > It's in the [laravel docs.](https://laravel.com/docs/7.x/passport#customizing-the-password-validation)
> 
> Thanks for this, but what if i want to create tokens with and without password?

Then you can put some conditions inside the function to do that.

**Comment by Shamzic** [comment]
> > > To create token without password you can use `validateForPassportPasswordGrant()` method in `User` model, it will override credentials check, now to work without password just return true inside the function.
> > > ```
> > >  public function validateForPassportPasswordGrant($password)
> > >     {
> > >         return true;
> > >     }
> > > ```
> > > 
> > > 
> > > It's in the [laravel docs.](https://laravel.com/docs/7.x/passport#customizing-the-password-validation)
> > 
> > 
> > Thanks for this, but what if i want to create tokens with and without password?
> 
> Then you can put some conditions inside the function to do that.

You can't put conditions here because the only field you can access here is the password

**Comment by vahidahmad** [comment]
> > > > To create token without password you can use `validateForPassportPasswordGrant()` method in `User` model, it will override credentials check, now to work without password just return true inside the function.
> > > > ```
> > > >  public function validateForPassportPasswordGrant($password)
> > > >     {
> > > >         return true;
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > > It's in the [laravel docs.](https://laravel.com/docs/7.x/passport#customizing-the-password-validation)
> > > 
> > > 
> > > Thanks for this, but what if i want to create tokens with and without password?
> > 
> > 
> > Then you can put some conditions inside the function to do that.
> 
> You can't put conditions here because the only field you can access inside this function is the password

You have access to `$this`!

**Comment by himalayaahuja** [comment]
> > > > > To create token without password you can use `validateForPassportPasswordGrant()` method in `User` model, it will override credentials check, now to work without password just return true inside the function.
> > > > > ```
> > > > >  public function validateForPassportPasswordGrant($password)
> > > > >     {
> > > > >         return true;
> > > > >     }
> > > > > ```
> > > > > 
> > > > > 
> > > > > It's in the [laravel docs.](https://laravel.com/docs/7.x/passport#customizing-the-password-validation)
> > > > 
> > > > 
> > > > Thanks for this, but what if i want to create tokens with and without password?
> > > 
> > > 
> > > Then you can put some conditions inside the function to do that.
> > 
> > 
> > You can't put conditions here because the only field you can access inside this function is the password
> 
> You have access to `$this`!

We still don't have access to any custom params inside this method, that we could have passed in the token POST request to obtain access token.

**Comment by polopolaw** [comment]
At first you should make you own GrantType extended by \League\OAuth2\Server\Grant\AbstractGrant for example
``` php
use DateInterval;
use Illuminate\Http\Request;
use Laravel\Passport\Bridge\User;
use League\OAuth2\Server\Entities\UserEntityInterface;
use League\OAuth2\Server\Exception\OAuthServerException;
use League\OAuth2\Server\Grant\AbstractGrant;
use League\OAuth2\Server\Repositories\RefreshTokenRepositoryInterface;
use League\OAuth2\Server\Repositories\UserRepositoryInterface;
use League\OAuth2\Server\RequestEvent;
use League\OAuth2\Server\ResponseTypes\ResponseTypeInterface;
use Psr\Http\Message\ServerRequestInterface;

class SocialGrant extends AbstractGrant
{
    public function __construct(UserRepositoryInterface $userRepository, RefreshTokenRepositoryInterface $refreshTokenRepository)
    {
        $this->setUserRepository($userRepository);
        $this->setRefreshTokenRepository($refreshTokenRepository);
        $this->refreshTokenTTL = new DateInterval('P1M');
    }

    /**
     * {@inheritdoc}
     */
    public function respondToAccessTokenRequest(ServerRequestInterface $request, ResponseTypeInterface $responseType, DateInterval $accessTokenTTL)
    {
        // Validate request
        $client = $this->validateClient($request);
        $scopes = $this->validateScopes($this->getRequestParameter('scope', $request));
        $user = $this->validateUser($request);
        // Finalize the requested scopes
        $scopes = $this->scopeRepository->finalizeScopes($scopes, $this->getIdentifier(), $client, $user->getIdentifier());
        // Issue and persist new tokens
        $accessToken = $this->issueAccessToken($accessTokenTTL, $client, $user->getIdentifier(), $scopes);
        $refreshToken = $this->issueRefreshToken($accessToken);
        // Inject tokens into response
        $responseType->setAccessToken($accessToken);
        $responseType->setRefreshToken($refreshToken);

        return $responseType;
    }

    /**
     * {@inheritdoc}
     */
    public function getIdentifier()
    {
        return 'social_grant';
    }

    /**
     * @param  ServerRequestInterface  $request
     * @return UserEntityInterface
     *
     * @throws OAuthServerException
     */
    protected function validateUser(ServerRequestInterface $request)
    {
        $laravelRequest = new Request($request->getParsedBody());
        $user = $this->getUserEntityByRequest($laravelRequest);
        if (false === $user instanceof UserEntityInterface) {
            $this->getEmitter()->emit(new RequestEvent(RequestEvent::USER_AUTHENTICATION_FAILED, $request));

            throw OAuthServerException::invalidCredentials();
        }

        return $user;
    }

    /**
     * Retrieve user by request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return null|\Laravel\Passport\Bridge\User
     *
     * @throws \League\OAuth2\Server\Exception\OAuthServerException
     */
    protected function getUserEntityByRequest(Request $request)
    {
        if (is_null($model = config('auth.providers.users.model'))) {
            throw OAuthServerException::serverError('Unable to determine user model from configuration.');
        }
        if (method_exists($model, 'byOAuthToken')) {
            $user = (new $model())->byOAuthToken($request);
        } else {
            throw OAuthServerException::serverError('Unable to find byLoggedInUser method on user model.');
        }

        return ($user) ? new User($user->id) : null;
    }
}
```

Next extend authoriztion server in you ServiceProvider

``` php
public function register()
{
        $this->extendAuthorizationServer();
}
protected function makeCustomRequestGrant()
    {
        $grant = new SocialGrant(
            $this->app->make(UserRepository::class),
            $this->app->make(RefreshTokenRepository::class)
        );
        $grant->setRefreshTokenTTL(Passport::refreshTokensExpireIn());

        return $grant;
    }
    
 protected function extendAuthorizationServer()
 {   
  $this->app->extend(AuthorizationServer::class, function ($server) {
              return tap($server, function ($server) {
                  $server->enableGrantType(
                      $this->makeCustomRequestGrant(),
                      Passport::tokensExpireIn()
                  );
              });
          });
        }
```


Passport has UserRepository which implement UserRepositoryInterface

You can bind you own Repository and override method getUserEntityByUserCredentials.

In this method you have $username, $password, $grantType. 
You can make you logic upon $grantType value.
