### ISSUE TITLE
Application loop when set default guard to API when passing a invalid token in authorization header

### ISSUE THREAD

**Issue by gleandroj** [laravel/passport#614]
Hi,

I noted that when I set on Auth Config the default guard to API using passport,
When I make a request with a invalid token on authorization header, the TokenGuard class on method authenticateViaBearerToken catch the OAuthServerException and make a instance of ExceptionHandler and call the report method passing the exception then the report method (When I don't set in $dontReport property the OAuthServerException) call's the $this->context() method that internally call's the Auth::user() and it start the process of loop.

**Comment by fgambino** [comment]
It looks like the Auth::user() call is wrapped in a try/catch block. Are you sure that's where the loop is happening?

Added in this commit:
https://github.com/laravel/framework/commit/a5a0f3e7b82a1a4dc00037c5463a31d42c94903a

**Comment by gleandroj** [comment]
Yes. I'm sure.

The try/catch block does not interact with the process loop, because the TokenGuard of passport have a internally a try/catch block that catch the OAuthServerException and call's by itself the ExceptionHandler report method. 
And the exception is never raised for the try / catch block of the context method.
And it start the process infinite loop.

Check on the code:

```
try {
            $psr = $this->server->validateAuthenticatedRequest($psr);

            // If the access token is valid we will retrieve the user according to the user ID
            // associated with the token. We will use the provider implementation which may
            // be used to retrieve users from Eloquent. Next, we'll be ready to continue.
            $user = $this->provider->retrieveById(
                $psr->getAttribute('oauth_user_id')
            );

            if (! $user) {
                return;
            }

            // Next, we will assign a token instance to this user which the developers may use
            // to determine if the token has a given scope, etc. This will be useful during
            // authorization such as within the developer's Laravel model policy classes.
            $token = $this->tokens->find(
                $psr->getAttribute('oauth_access_token_id')
            );

            $clientId = $psr->getAttribute('oauth_client_id');

            // Finally, we will verify if the client that issued this token is still valid and
            // its tokens may still be used. If not, we will bail out since we don't want a
            // user to be able to send access tokens for deleted or revoked applications.
            if ($this->clients->revoked($clientId)) {
                return;
            }

            return $token ? $user->withAccessToken($token) : null;
        } catch (OAuthServerException $e) {
            return Container::getInstance()->make(
                ExceptionHandler::class
            )->report($e);
        }
```

**Comment by driesvints** [comment]
Can't replicate this. Please provide code samples or HTTP request details in order to replicate this.
