### ISSUE TITLE
multi passport guard issue

### ISSUE THREAD

**Issue by yuyenkan** [laravel/passport#615]
I want to declare multiple api guard, but I throwing exception. I can do it with following [https://github.com/laravel/passport/issues/161#issuecomment-299690583](guide) to do that, but it cannot update to latest version. Is there others way to do it and wont affect when update framework?

**Comment by andrewmclagan** [comment]
This is an outstanding issue with Laravel Passport, it does not support multiple guards.

**Comment by driesvints** [comment]
Duplicate of https://github.com/laravel/passport/issues/161
