### ISSUE TITLE
access token expired issue

### ISSUE THREAD

**Issue by yuyenkan** [laravel/passport#616]
I trying to make my access token with lifetime 10 minutes, after 10 minutes and I use the same access to request url, it throw 

Type error: Argument 1 passed to Illuminate\\Routing\\Middleware\\ThrottleRequests::addHeaders() must be an instance of Symfony\\Component\\HttpFoundation\\Response, null given, called in myApp\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php on line 61

instead of Unauthorized Exception.

why it happen and how can I solve it?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
