### ISSUE TITLE
Throttle not resetting 

### ISSUE THREAD

**Issue by zimonline** [laravel/passport#62]
With a fresh install following the https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/13

If you continuously hit an API route every 5 seconds for example the limit is never reset. I am guessing this is a bug as a user will never be idle for 60 seconds.

Many Thanks.

Edit:
I should add. this is using the CreateFreshApiToken.

**Comment by craigpaul** [comment]
Hey @zimonline, think you could provide the version numbers your using for Laravel and Passport. I just tried the `CreateFreshApiToken` and the normal JWT way. Both worked out properly, the rate limiter went down from 60 to 0 and issued the `429` response like it should have.

This was with Laravel `5.3.10` and Passport `1.0.2`.
