### ISSUE TITLE
Laravel\Passport\Client::redirect should be a native array

### ISSUE THREAD

**Issue by sleavitt** [laravel/passport#627]
Issue #621 addressed an issue where the incorrect redirect URL was used if an authorization request was denied, but it brought to light that the underlying issue is that the redirect property of the Client model is not being stored as a native array, and instead the Bridge client explodes that field on commas to create an array. This means that without encoding the URL first, it is impossible to properly store redirect URLs that may contain a comma.

**Comment by sleavitt** [comment]
PR #628 has been updated by me with a comment seeking clarification on what is missing with regard to providing further explanation on breaking impacts.

**Comment by driesvints** [comment]
Isn't the best way to just encode urls with commas? This is unfortunately the way the client bridge works and I don't see this behavior changed anytime soon. Maybe a note to the docs about multiple redirects could be helpful? 

Anyway, going to close this as the solution is fairly simple (encoding the URL).
