### ISSUE TITLE
Ability to configure database connection to read tokens from.

### ISSUE THREAD

**Issue by hfmikep** [laravel/passport#630]
In a replicated Master/Slave DB environment, when a client requests a new Client Grant token, if the slave database server is not caught up, the next request they make using that bearer token fails and returns a 401 response.

It would be useful to have a config option to tell Passport what DB connection to use for looking up tokens. 

It would also solve some other issues I read about with other users that wanted to keep their oAuth tokens in a separate database.

If this would be acceptable, I would be willing to create a pull request that would allow you to set the connection for the Token (and other) models.

**Comment by driesvints** [comment]
Heya, for this you may use the example like @crynobone suggested. Passport is pretty extensible so you can manipulate it in all sorts of ways with these `use` methods.
