### ISSUE TITLE
encrypt credentials

### ISSUE THREAD

**Issue by corbosman** [laravel/passport#641]
One thing that immediately struck me as weird is that passport stores all client credentials in plaintext. This is against common security practices.  As an example of a reason why this is important. You may have database backups someplace else than your main server, and having plaintext passwords in there is just bad form.  It would immediately fail an audit in our company.  Since it can't be hashed, at least just encrypt it. 

In ClientRepository.php

```
        if ($mustValidateSecret &&
            ! hash_equals($record->secret, (string) $clientSecret)) {
            return;
        }
``` 

This could simply decrypt $record->secret, and you can store it with encrypt.  I realise migrating this is a bit of a hassle, but not that bad. Just tell people to run some artisan command that would encrypt all client credentials. 

I looked into using observers do handle it myself, but I cant hook into fetching the credentials without actually extending ClientRepository and registering a replacement with the container. 

Please consider encrypting credentials going forward.

**Comment by hackel** [comment]
I agree, this seems like a potentially huge security hole.  Is there some reason I'm overlooking that storing API keys in plaintext is not a risk?

**Comment by driesvints** [comment]
No plans on adding this atm but you can use https://github.com/ssmulders/hashed-passport for this if you want.
