### ISSUE TITLE
Will the controller how to get client_id

### ISSUE THREAD

**Issue by dingdayu** [laravel/passport#650]
Route:

```
Route::namespace('Send')->group(function () {
    Route::post('/send', 'AnXinJieController')->middleware('client');
    Route::post('/send/axj', 'AnXinJieController')->middleware('auth:api');
});
```

Will the controller how to get client_id?

AS： https://stackoverflow.com/questions/47024861/how-do-i-get-the-client-id-in-a-laravel-app

**Comment by dingdayu** [comment]
Whether there is a better way？

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
