### ISSUE TITLE
Tokens from grand_type:client_credentials

### ISSUE THREAD

**Issue by ajrmzcs** [laravel/passport#652]
These token are valid to access routes with auth:api which are normally accessed with grant_type:password tokens or viceversa?

**Comment by driesvints** [comment]
No, you must implement the `CheckClientCredentials` middleware. Please check https://laravel.com/docs/5.7/passport#password-grant-tokens

**Comment by driesvints** [comment]
Sorry, I meant https://laravel.com/docs/5.7/passport#client-credentials-grant-tokens
