### ISSUE TITLE
$token->id is not set

### ISSUE THREAD

**Issue by kurando** [laravel/passport#660]
nginx: 1.12 (don't use proxy but use Application Load Balancing)
php: 7.0
Laravel: 5.5
Passport: 4.0

Sometimes, $token->id is not set on line 74 in PersonalAccessTokenFactory.php in multiple servers environment.
So I think branch processing required for when $token->id is not set.

How about?
Or is there another approach?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
