### ISSUE TITLE
Can routes protected by client_credential accessible by password grant type token?

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [laravel/passport#662]
token issued by password grant type can access routes protected by `auth:api` but it can also access route protected by `client`, I don't know it's meant to be or bug, 

my case is I don't want to create login form on my side for mobile app, mobile app can request token by client_id, client_password and app user's username and password, so mobile side can create their own login form and save token.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
