### ISSUE TITLE
HI, I think the composer.json should be modified.

### ISSUE THREAD

**Issue by nosent79** [laravel/passport#664]
in v5.0.x

 "require": {
        **"php": ">=7.0",**
        "firebase/php-jwt": "~3.0|~4.0|~5.0",
        "guzzlehttp/guzzle": "~6.0",
        "illuminate/auth": "~5.6",
        "illuminate/console": "~5.6",
        "illuminate/container": "~5.6",
        "illuminate/contracts": "~5.6",
        "illuminate/database": "~5.6",
        "illuminate/encryption": "~5.6",
        "illuminate/http": "~5.6",
        "illuminate/support": "~5.6",
        "league/oauth2-server": "^6.0",
        "phpseclib/phpseclib": "^2.0",
        "symfony/psr-http-message-bridge": "~1.0",
        "zendframework/zend-diactoros": "~1.0"
    },

php version is changing to 7.1.*
because "illuminate/contracts": "~5.6", require php: ^7.1.3

**Comment by AkenRoberts** [comment]
Fixed in #704

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
