### ISSUE TITLE
requestGuard::attempt does not exist in login

### ISSUE THREAD

**Issue by MarkVilludo** [laravel/passport#665]
why is it always, shows this error message?
"Method Illuminate\\Auth\\RequestGuard::attempt does not exist."

Please help. :/

**Comment by hamrant** [comment]
I have same issue, looks like "api" guard not contain attempt method. Changing default guard to "web" fixed my problem.

`config/auth.php`:
```php
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
```

Also you can define guard in your controller with `Auth::guard('web')->attempt($credentials)`

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by AlisonPrietoTello** [comment]
Aro cole
