### ISSUE TITLE
Passport Vue components w/o Jquery?

### ISSUE THREAD

**Issue by curtd59** [laravel/passport#667]
Has anyone else converted the Passport Vue components from Jquery to Bootstrap-vue, or just Vue? Just seems rather undesirable  to add jquery just to display a few modals. If not I'll do it and post the changes here.
Thanks.

**Comment by MatthewSH** [comment]
Well, Bootstrap itself uses jQuery if I can recall so you would have to completely remove Bootstrap altogether. At that point, you'll need to rewrite the entire components anyway.

**Comment by driesvints** [comment]
Yeah since Bootstrap uses jQuery itself I don't think this will change soon. You can always try to send in a PR if you want to propose a better and cleaner way.
