### ISSUE TITLE
Invalid Bearer token redirects to /login route

### ISSUE THREAD

**Issue by cmmarslender** [laravel/passport#668]
#666 caused this, by completely replacing headers rather than just updating the Authorization header.

**Comment by cmmarslender** [comment]
Context:

We know whether to send a 401 or else redirect to /login based on presence of `Accept: application/json` header - by replacing all headers with just Authorization header, we lose the Accept, and try to redirect an api client.

**Comment by nmfzone** [comment]
Just like what I'm thinking about.

**Comment by iget-master** [comment]
My bad, sorry! I said that #666 number is evil.

**Comment by rgarand** [comment]
The method is expected to return null if the user doesn't have a valid token:

`if (! is_null($user = $this->user())) {
            return $user;
        }`

It does return null if the exception handler doesn't cause an infinite recursion as the base ExceptionHandler::report() doesn't have a return statement. However an overridden version might introduce a non-null return value and cause unexpected bugs.

Might it be preferable to do this instead?

`
        } catch (OAuthServerException $e) {
            return null;
`

It seems a little cleaner to have the method always return the right result (and not crash) with no dependencies on modifying the state or knowing other code in the call stack.
