### ISSUE TITLE
Different algorithms for JWT token encoding and decoding

### ISSUE THREAD

**Issue by countbytedown** [laravel/passport#670]
When consuming your API with Passport as described in the [Documentation](https://laravel.com/docs/5.6/passport#consuming-your-api-with-javascript) there is a different type of functionality used for the encoding of the token compared to decoding.

Line 64 of laravel/passport/src/ApiTokenCookieFactory.php
Line 187 of laravel/passport/src/Guards/TokenGuard.php  

One of the functions calls the internal Laravel decrypter function which does not use the urlsafeB64Decode function. For certain combinations this will obviously fail.

Is this intentional? My API requests will constantly fail if the code is not modified.

**Comment by fh-jashmore** [comment]
How will your API fail?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
