### ISSUE TITLE
Is ther any method to disable revoke chaking in laravel passport ? 

### ISSUE THREAD

**Issue by navid-dada** [laravel/passport#672]
I know that laravel-passport use JWT but it checks database per access-token request to check that this token is revoked or not. this break the meaning of JWT which is self-signing without database check. also, this made my RESTfull API stateful and my JWT is a sessionId and not truly an access token.

this checking made my authentication requests slower and is a bottleneck when my API is under pressure.
now I want to know is there any solution to disable revoke checking in laravel-passport? or a better solution such as storing data in cacheDB such as Redis? and if there is no solution in laravel-passport is there any other package to solve my problem?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
