### ISSUE TITLE
Variable scopes for different token types

### ISSUE THREAD

**Issue by NastuzziSamy** [laravel/passport#674]
Hi everyone !

Thx for the work, but i was thinking about an issue, how can i specify an array of scopes destined for Issuing Access Tokens and another array for Client Credentials ?

I know that in the implementation, it could be managed with the different middlewares but what about application who asks the user to access to some scopes, including the one who allows it to access to "all data users" which the original user can't give.

Like i was worried not to be that clear, I put my example in that screenshot: 
![2018-03-20_01-12-47](https://user-images.githubusercontent.com/24639904/37628880-e1258816-2bdb-11e8-9b93-f063ce9271f9.png)

Thx again ! :)

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
