### ISSUE TITLE
Extending token duration

### ISSUE THREAD

**Issue by jonlod** [laravel/passport#677]
I currently have an older project with passport version 1.0. In the AuthServiceProvider this has been defined from the beginning: `Passport::tokensExpireIn(Carbon::now()->addYears(3));`
but when I request a token I still get an expires_in of a year. I just found out that the project using the api is NOT using refresh tokens so I'm worried this will break after a year use (which is coming up quickly). 
Is there a way to extend the tokens post authorization, allow them even when they are expired or just a way to test and see if the tokens will be active for the previously set period.. Decreasing it to a few seconds does not seem to be working so I fear the 3 years neither. 
I know this is not the safest option but it's the only option I currently have.

**Comment by jmarcher** [comment]
Well if you already issued tokens with a 1-year expiry date, there is not much you can do, rather than implementing the refresh mechanism.

**Comment by driesvints** [comment]
I just tested this and you can definitely set the expire date to 3 years or whatever you prefer. Can you upgrade to the latest Passport version and try again? And unless I'm missing something crucial, you can update the `expires_at` column for a token in the `oauth_access_token` table to extend its expire period.
