### ISSUE TITLE
"Message" : "Client authorization failed" - Always

### ISSUE THREAD

**Issue by hari03** [laravel/passport#68]
I followed the exact steps mentioned in the Laracast : What's New in Laravel 5.3: Laravel Passport to implement api authentication using oauth2.

My web.php file in the client/consumer project looks like:
```php
use Illuminate\Http\Request;


Route::get('/', function () {
$query = http_build_query([
     'client_id' => 2,
     'redirect_uri' => 'http://offline.xyz.com/callback',
     'response_type' => 'code',
     'scope' => '',
    ]);

return redirect ('http://api.xyz.com/oauth/authorize?'.$query);
});

Route::get('/callback', function (Request $request){
$client = new GuzzleHttp\Client;

$response = $http->post('http://api.xyz.com/oauth/token',[
    'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => 2 , 
            'client_secret' => 'tUGYrNeWCGAQt220n88CGoXVu7TRDyZ20fxAlFcL' ,
            'redirect_uri' => 'http://offline.xyz.com/callback',
            'code' => $request->code,
        ],
    ]);

return json_decode((string) $response->getBody(), true);
});
```

Not to mention, I have implemented the vue components as well and client with id = 2 exists.

I am getting the permission request page where I need to authorize to allow my client to access the api. But, once I click authorize, I am being redirected to the page where it shows the following message:
`{"error":"invalid_client","message":"Client authentication failed"}`

How to resolve this?

I did not install laravel/passport in the offline project. Am I missing out something? I have followed and implemented what exactly was mentioned in the video tutorial. Do I have to include something else that I'm not aware of? (I have a very basic knowledge on oauth2).

If it helps, I am trying to implement an offline system which will periodically send data to an online system when there is an internet connection. So I thought I can build an api and send post request with information to be stored.

**Comment by geodeveloper** [comment]
Hi @hari03 ,

Did you checked the database table *oauth_clients* if your client which has id 2, has the column *redirect* the value http://offline.xyz.com/callback ? The redirect value must match.

As per Laravel Passport documentation https://laravel.com/docs/5.3/passport#requesting-tokens: 

> When receiving authorization requests, Passport will automatically display a template to the user allowing them to approve or deny the authorization request. If they approve the request, they will be redirected back to the redirect_uri that was specified by the consuming application. The redirect_uri must match the redirect URL that was specified when the client was created.

**Comment by hari03** [comment]
I checked the *oauth_clients* table, the client does have the id = 2 but the *redirect* column has a **different** redirect value. Changing it right now.

Thank you for your time.

**Comment by hari03** [comment]
When I changed it, it threw an `HttpFoudationFactory` not found error. I had to include `"symfony/psr-http-message-bridge": "0.2"` in my `composer.json` and run `composer update` to resolve the error. 

Its working now. :+1:

**Comment by geodeveloper** [comment]
Ok, I'm glad it's working, your main issue was the redirect url didn't match.

**Comment by rabb-bit** [comment]
I've solved the issue by putting quote into the client_id, here's my code below

```
Route::get('/redirect', function () {
    $query = http_build_query([
        'client_id' => '1',
        'redirect_uri' => 'http://client.dev/callback',
        'response_type' => 'code',
        'scope' => ''
    ]);
    return redirect('http://tickettit.dev/oauth/authorize?'.$query);
});

Route::get('/callback', function (Illuminate\Http\Request $request) {
    $http = new \GuzzleHttp\Client;

    $response = $http->post('http://tickettit.dev/oauth/token', [
        'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => '1',
            'client_secret' => 'euwSLAk4UjkaYtKPlQuotL2v5nbyX8qUvGpEnQ49',
             'redirect_uri' => 'http://client.dev/callback',
            'code' => $request->code,
        ],
    ]);
    return json_decode((string) $response->getBody(), true);
});



```

**Comment by faran234** [comment]
hello! 
client Authentication page not found;.......
how to this error .

![untitled](https://user-images.githubusercontent.com/30212965/32776502-96dd5c64-c954-11e7-972d-b3bdc197f009.png)

how i'm authenticate the  client.

**Comment by faran234** [comment]
page that include a Authentication Button 
i have installed npm,guzzlehttp.
