### ISSUE TITLE
actingAs() for Client Credentials Authorization

### ISSUE THREAD

**Issue by rennokki** [laravel/passport#680]
So i'm dealing with the problem of not having actingAs() method to test my API endpoints which do require Client Credentials Token, instead of a Password Grant Token.

I found this so far: https://github.com/laravel/passport/issues/514 but this doesn't help me at all.

**Comment by zanematthew** [comment]
I recently came across this issue. Prior to updating from Laravel 5.5 to 5.6, `Passport::actingAs()`, was working. However, since updating to Laravel 5.6 it is not.


This test;
```
public function testUserCanAccessApi()
{
        Passport::actingAs(
            factory(\App\User::class)->create()
        );

        $response = $this->get('/api/user');
        $response->assertStatus(200);
}
```

Returns;
```
1) Tests\Unit\UserTest::testUserCanAccessApi
Expected status code 200 but received 201.
Failed asserting that false is true.
```

**Comment by rennokki** [comment]
As long as there is no method to help impersonate a Client Credentials Token, i came with a workaround. This requires Guzzle to make a request. What it does, basically makes a new Client Credentials app everytime it is called and it stores a generated token in a class variable (i named it `$oauth_headers`.

I have to carry with that on each request by calling:

`
// Bearer Token should be valid. Expecting 200 (OK)
$this->post(route('v1.user.post'), $this->user, $this->oauth_headers, $this->oauth_headers)->assertStatus(200);
`

This is how the method looks like:

`
. . .
use Laravel\Passport\ClientRepository;

class APITest extends TestCase
{
    protected $oauth_headers = [];
    . . .

    protected function setClientCredentialsToken()
    {
        // Create a Client Repo.
        $clientRepo = new ClientRepository();

        // Create a Password Grant Client.
        $passportClient = $clientRepo->createPasswordGrantClient(null, 'Test App '.str_random(5), url('/'.str_random(5)));

        // Store Client ID & Client Secret.
        $client_id = $passportClient->id;
        $client_secret = $passportClient->secret;

        // Initiate Guzzle.
        $client = new \GuzzleHttp\Client();

        // Create a Client Credentials Token.
        $oauth = $client->post(url('/oauth/token'), [
            'form_params' => [
                'client_id' => $client_id,
                'client_secret' => $client_secret,
                'scope' => '',
                'grant_type' => 'client_credentials',
            ],
        ]);

        // Set the Access Token.
        $this->oauth_headers = [
            'HTTP_Authorization' => 'Bearer '.json_decode($oauth->getBody())->access_token,
            'HTTP_Accept' => 'application/json',
            'HTTP_Content-Type' => 'application/x-www-form-urlencoded',
            'Authorization' => 'Bearer '.json_decode($oauth->getBody())->access_token,
            'Accept' => 'application/json',
            'Content-Type' => 'application/x-www-form-urlencoded',
        ];

        // This return is useless. I just do that in case i need the response, sometimes.
        return json_decode($oauth->getBody());
    }
`

I have used both HTTP_ prefixed and non-HTTP_ prefixed because the requests takes the request headers different, and i don't wanna mess it up. This method i call when i want o set a new Bearer Token in the `$oauth_headers` variable.

Something like that:

`
        // Not having a Bearer Token. Expecting 401 (Unauthenticated)
        $this->post(route('v1.user.post'), $this->user)->assertStatus(401);

        // Setting a Client Credentials Token.
        $this->setClientCredentialsToken();

        // Bearer Token should be valid. Expecting 200 (OK)
        $this->post(route('v1.user.post'), $this->user, $this->oauth_headers, $this->oauth_headers)->assertStatus(200);
`

**Comment by zanematthew** [comment]
@rennokki thanks, I'll try and implement this late tonight.

Have you come across a reason as to why this work around is needed? Prior to updating, the `Passport::actingAs()` was working?

**Comment by zanematthew** [comment]
After looking further into my issue, (which is sort of a non-issue), my confusion is that while unit testing the route `/api/user` returns an HTTP status code of 201, while using Postman the HTTP status code returned is 200. 

Can you weigh in on why there is a difference?

**Comment by rennokki** [comment]
It depends on what's in the controller method behind the `/api/user` route.

Usually, `200` is sent to state that the request was processed while `201` is used to state that the resource was created, in this case, an user (if that's what your method do)

Can you show me a snippet on your method behing `/api/user` route?

**Comment by zanematthew** [comment]
@rennokki its simply this;

```php
Route::group([
    'prefix'     => 'user',
    'middleware' => 'auth:api',
    ], function () {

    Route::get('/', function (Request $request) {
        return $request->user();
    });

    // a few others here.

});
```

If I do a die and dump in the unit test I get this;

```
    #content: "{"name":"Alayna Torphy","email":"terrill.beatty@example.net","updated_at":"2018-04-16 22:54:27","created_at":"2018-04-16 22:54:27","id":1}"
    #version: "1.1"
    #statusCode: 201
```

Which is okay, but what I do not understand is why the status code is 201 vs. 200.

**Comment by rennokki** [comment]
If you want to simulate the 200 response, you can use:

```
return response()->json([
     'user' => $request->user()
], 200);
```
You are basically returning a JSON type and a 200 status.

**Comment by adrian-fjellberg** [comment]
> @rennokki 
> Which is okay, but what I do not understand is why the status code is 201 vs. 200.

If your read the Upgrade Guide for 5.6 under *Returning Newly Created Models* you will se that:

> When returning a newly created Eloquent model directly from a route, the response status will now automatically be set to 201.

My bet is that since you are using `factory(\App\User::class)->create()` or creating the user somewhere else in your tests, Laravel is treating the user you are returing from the route as a newly created model, and therefore returing 201. This will not be the case when using Postman to test the route, since then the user is not created during the application runtinme of that request.

**Comment by rennokki** [comment]
On the request level, Laravel is returning always 200 unless you specify it should return something else either by using a code or the `abort($statusCode)` function. I highly recommend @zanematthew to use Controllers instead of closures in the routes so hopefully it might fix his problem.

But since this problem is really old, i assume it's pointless.
