### ISSUE TITLE
oauth_client <-> user relation

### ISSUE THREAD

**Issue by danisetg** [laravel/passport#684]
Hi, I am building two projects, a frontend using angular and a backend using laravel. In the laravel backend, I'm implementing Passport for the oauth2 authentication. Then, checking out the tables made by the migrations I saw that an oauth_client can be asociated to only one user.
![image](https://user-images.githubusercontent.com/22918525/38365910-5ba24f34-38de-11e8-9b36-39e98a5437f0.png)
So, then is when my doubt comes out, what about if I want to register multiple users from my frontend project? Will I have to create a different client for each one of them??

**Comment by leroy0211** [comment]
That is the user to which the client belongs to.  That user created that specific client. 

So if you follow the documentation completely (with veu.js components), you can login to the passport admin. There you will see the available clients, personal access tokens, and access tokens. They all are scoped to the loggedin user. 

If you create another user, and login with that user, nothing should be displayed.

**Comment by danisetg** [comment]
ok, Thank you very much, I now understand it a little bit better. I was confused, because for example, in symfony that column user_id doesn't exist in the oauth client table. I'm closing this then.
