### ISSUE TITLE
Limit Clients to request access to scopes

### ISSUE THREAD

**Issue by leroy0211** [laravel/passport#685]
Any Client can request access to every scope it wants. 

It would be nice to limit a Client to specific scopes, so it can only request access it's own pre-defined scopes. 

Use Case:
We have multiple API's to read (GET) and write (PUT, POST, DELETE) data. But we don't want every Client to be able to write, only to read. 

I know you can limit that with different scopes like `model:read` and `model:write`, but every Client has the authority to request access to both scopes.

**Comment by driesvints** [comment]
Heya, this is currently being discussed in https://github.com/laravel/passport/issues/691.

**Comment by martindilling** [comment]
> Heya, this is currently being discussed in #691.

Did I miss something?
Wasn't that discussion about password_client and personal_access_client token automatically having access to routes protected with the client middleware?

Right now I have the same issue as described here. Trying to scope access per client, I have multiple apps that need to access this api, but only very few need the destructive rights.
