### ISSUE TITLE
createToken() not generate JWT token

### ISSUE THREAD

**Issue by GergelyLakatos** [laravel/passport#686]
Hi all!

I have a laravel 5.5 backend, with passport. I install passport step by step as a docs said.
When the user logged in got this token:

`$token = $user->createToken('fullaccess')->accessToken;`

and try to get some data via axios (ajax). The middleware is "auth:api". Everytime I get:

> "message": "Unauthenticated."

But the headers contain everything what it needs..

So I started to debug. I figured out that the problem comes from _Lcobucci\JWT\Parser_.
The log says: 

> League\\OAuth2\\Server\\Exception\\OAuthServerException::accessDenied('The JWT string ...')

So the problem is that **$token** is not JWT format, because splitJwt() method of Parser throws the exception.

How can I generate JWT code programatically?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
