### ISSUE TITLE
AuthorizedAccessTokenController->destroy returns void on success

### ISSUE THREAD

**Issue by goodevilgenius** [laravel/passport#687]
https://github.com/laravel/passport/blob/bd5ff54598d461f89cb8eaf803f4906f77b559bf/src/Http/Controllers/AuthorizedAccessTokenController.php#L61

When a token is successfully deleted, a valid response should be returned (probably `new Response('', 204)`.

However, nothing is returned, resulting in an error.

**Comment by goodevilgenius** [comment]
Sorry about this. My frontend guys told me there was an error, and I didn't double-check it. This actually does return a valid response.

**Comment by michaelklopf** [comment]
Similar situation here, Ember expects a response, but the one coming is no fit for Ember.

https://stackoverflow.com/questions/20648372/what-does-ember-data-expect-in-response-to-deleting-a-record

**Comment by driesvints** [comment]
Seems like this is indeed a problem.
