### ISSUE TITLE
php artisan passport:install - unable to write 'random state'

### ISSUE THREAD

**Issue by fzls** [laravel/passport#69]
Hi, I am having a try at passport, but when i use `php artisan passport:install`, some error happened below, do you konw how to solve it?
WARNING: can't open config file: /z/extlib/_2016Q2__/ssl/openssl.cnf
Generating RSA private key, 4096 bit long modulus
.....................................................................++
...................................................++
unable to write 'random state'
e is 65537 (0x10001)
WARNING: can't open config file: /z/extlib/_2016Q2__/ssl/openssl.cnf
writing RSA key

**Comment by baringji** [comment]
@fzls,

http://stackoverflow.com/questions/94445/using-openssl-what-does-unable-to-write-random-state-mean

**Comment by fzls** [comment]
@baringji  Thanks, I am using windows, and use windows powershell(admin) to run the command solve the `unable to write 'random state'` problem, but still has `WARNING: can't open config file: /z/extlib/2016Q2_/ssl/openssl.cnf`, does that matter?
ps: the new output:
`
WARNING: can't open config file: /z/extlib/_2016Q2__/ssl/openssl.cnf
Generating RSA private key, 4096 bit long modulus
........................................................................................................................
........................++
........................................................................................................................
........................................................................................................................
.................................................................................++
e is 65537 (0x10001)
WARNING: can't open config file: /z/extlib/_2016Q2__/ssl/openssl.cnf
writing RSA key
[32mEncryption keys generated successfully.[39m
[32mPersonal access client created successfully.[39m
[32mPassword grant client created successfully.[39m
`
