### ISSUE TITLE
Laravel 5.6 Passport OAuth Max Login Attempts

### ISSUE THREAD

**Issue by ricky2k7** [laravel/passport#693]
I've just created a simple OAuth system with Laravel Passport. This system will be responsible for an external app user registration and authentication. Everything is working as i expect, and now i would like to implement a mechanism to lock users after a predefined number of failed login attempts.

I'm new to Laravel and Passport, is there any built in package that can manage this for me? Or do I have to develop this feature on my own? If so, how can i accomplish such task?
Are there any OAuth2 events that i can use in Laravel for this?

I've been searching all around the interwebs but until now i couldn't find anything regarding Passport OAuth.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by ricky2k7** [comment]
Hi,

I've managed to solve my issue creating a custom authentication controller.
Here's what i've done:

`class AuthController extends AccessTokenController
{
    use AuthenticatesUsers;
    
    /**
     * Handle a login attempt.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return Response
     */
    public function login(Request $request)
    {
        try
        {
            //check if user has reached the max number of login attempts
            if ($this->hasTooManyLoginAttempts($request)) 
            {
                $this->fireLockoutEvent($request);

                return Response::json("to many attempts...");
            }

            //...            
            
            if (Auth::attempt(['username' => $user->username, 'password' => $request->password])) 
            {
                //...

                //reset failed login attemps
                $this->clearLoginAttempts($request);

                return Response::json("hurrray!");
            }
        }
        catch (OAuthServerException $e) 
        {
            //count user failed logins
            $this->incrementLoginAttempts($request);

            return CResponse::error(Messages::AUTH_ERROR_USER_CREDENTIALS, 'invalid_credentials', 200);
        }
    }

    /**
     * Determine if the user has too many failed login attempts.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    protected function hasTooManyLoginAttempts(Request $request)
    {
        $attempts = 5;
        $lockoutMinites = 10;

        return $this->limiter()->tooManyAttempts(
            $this->throttleKey($request),
            $attempts,
            $lockoutMinites
        );
    }
}`
