### ISSUE TITLE
Creating Password Grant Client via API

### ISSUE THREAD

**Issue by valluminarias** [laravel/passport#694]
Is there any way to create Password Grant Client via api call?

I have checked the code, the controller only accept the `name` and `redirect` parameters.

I wanted to add the `password_client` parameter but don't know where to put the code.

Please help.

**Comment by fh-jashmore** [comment]
You can add a new endpoint to your routes/api.php or create a new routes file

**Comment by driesvints** [comment]
Please check my answer here: https://github.com/laravel/passport/issues/814#issuecomment-429782598
