### ISSUE TITLE
Error in render: "TypeError: Cannot read property 'name' of undefined" Laravel Mix/passport

### ISSUE THREAD

**Issue by yacinebelghard** [laravel/passport#695]
Please I need a help .
when i want to generate the access Token .i had this error  

[Vue warn]: Error in render: "TypeError: Cannot read property 'name' of undefined"

found in

---> <PassportPersonalAccessTokens> at resources\assets\js\components\passport\PersonalAccessTokens.vue
       <Root>

and nothing was generating :
![image](https://user-images.githubusercontent.com/30808204/39084290-43866c48-456b-11e8-81fb-fc2c3aca8f9d.png)

I'm using laravel5.4
node -v 
V8.6.0
npm -v
5.1.0
this is my package.json 
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^5.1.4",
    "jquery": "^3.1.1",
    "laravel-mix": "^1.0",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
  }
}
my app.js 

/**
 * First we will load all of this project's JavaScript dependencies which
 * includes Vue and other libraries. It is a great starting point when
 * building robust, powerful web applications using Vue and Laravel.
 */

require('./bootstrap');

window.Vue = require('vue');

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */

Vue.component('example', require('./components/Example.vue'));
Vue.component(
    'passport-clients',
    require('./components/passport/Clients.vue')
);

Vue.component(
    'passport-authorized-clients',
    require('./components/passport/AuthorizedClients.vue')
);

Vue.component(
    'passport-personal-access-tokens',
    require('./components/passport/PersonalAccessTokens.vue')
);
const app = new Vue({
    el: '#app'
});
thank you .

**Comment by josteph** [comment]
Same issue here. Any fix to this?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

Please let me know if this still happens with the latest Laravel and Passport releases.
