### ISSUE TITLE
 Command "stream" is not defined.

### ISSUE THREAD

**Issue by sakuraeverdeen** [laravel/passport#699]
Hello, i have problem when i use this command: <php artisan stream> 
an the results in the following error:   
<Command "stream" is not defined.

  Did you mean one of these?
      make:stream
      streams:cleanup
      streams:compile
      streams:destroy
      streams:index
      streams:publish
      streams:refresh >

i use os : windows10, php7, laravel 5.5

can anyone help me

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
