### ISSUE TITLE
firebase/php-jwt version conflict within passport and google/apiclient 2.0

### ISSUE THREAD

**Issue by serrexlabs** [laravel/passport#70]
Hi Artisans  

We have install laravel/passport and then try to install google/apiclient. Then its gives an error saying.

Problem 1
    - Installation request for google/auth ^0.10.0 -> satisfiable by google/auth[v0.10].
    - Conclusion: remove firebase/php-jwt v4.0.0
    - Conclusion: don't install firebase/php-jwt v4.0.0
    - google/auth v0.10 requires firebase/php-jwt ~2.0|~3.0 -> satisfiable by firebase/php-jwt[2.0.0, v2.1.0, v2.2.0, v3.0.0].

I think laravel/passport or it's foundation use newer version of  firebase/php-jwt (v4). But google/apiclient 
 "satisfiable by firebase/php-jwt[2.0.0, v2.1.0, v2.2.0, v3.0.0]" 

Is there anyway to install both of them withing same project.

**Comment by alexbilbie** [comment]
Not easily no.

Try sending a PR to the Google project to see if they will add support for the newer version their end?

**Comment by serrexlabs** [comment]
Yeah, That's the correct way.

**Comment by JesseObrien** [comment]
I fixed his by getting https://github.com/laravel/passport/pull/82 merged up.
