### ISSUE TITLE
Get oauth client by token??

### ISSUE THREAD

**Issue by abdullah-abunada** [laravel/passport#700]
How can I get client info or ID  by user token?
note: user_id, client_id and token_id stored in same table.

**Comment by Donovan-H** [comment]
@abdullah-abunada

> Add the Laravel\Passport\HasApiTokens trait to your App\User model. This trait will provide a few helper methods to your model which allow you to inspect the authenticated user's token and scopes

The `HasApiTokens` trait will give you access to the `token()` helper, which returns the User's current `accessToken`. 

Use the `accessToken`'s client relationship to access whatever you need from that client.

Something like this `$user->token()->client` should work.

Hopefully that's what you were after, if not, don't hit me! 😄

**Comment by roitto** [comment]
What if i'm using client credentials token? Is there a way to get the client ID?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
