### ISSUE TITLE
Undefined withAccessToken() in TokenGuard.php 

### ISSUE THREAD

**Issue by acondurache** [laravel/passport#701]
What is the main purpose of withAccessToken() in HasApiTokens.php called from TokenGuard.php : 138 ? 

After I get an access code, I pass it to my route `Route::get('/test/{user}', TestController@testApi')->middleware('auth:api');` with header Bearer (Accept: application/json) but I get **undefined withAccessToken()** error below. Not sure if this function is deprecated or what it should return

I have added the use `Laravel\Passport\HasApiTokens;` and use `HasApiTokens` in App\User; 

One thing I noticed is if I comment out the` return $token ? $user->withAccessToken($token) : null; ` on line 138 : TokenGuard.php and simply have `return $token;` it seems to output ok, so seems to be a associated with not being able to access withAccessToken() located in HasApiTokens.php

> { "message": "Call to undefined method Illuminate\\Auth\\GenericUser::withAccessToken()", "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError", "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\passport\\src\\Guards\\TokenGuard.php", "line": 138, "trace": [ { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\passport\\src\\Guards\\TokenGuard.php", "line": 89, "function": "authenticateViaBearerToken", "class": "Laravel\\Passport\\Guards\\TokenGuard", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\passport\\src\\PassportServiceProvider.php", "line": 272, "function": "user", "class": "Laravel\\Passport\\Guards\\TokenGuard", "type": "->" }, { "function": "Laravel\\Passport\\{closure}", "class": "Laravel\\Passport\\PassportServiceProvider", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\RequestGuard.php", "line": 58, "function": "call_user_func" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\GuardHelpers.php", "line": 50, "function": "user", "class": "Illuminate\\Auth\\RequestGuard", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php", "line": 61, "function": "check", "class": "Illuminate\\Auth\\RequestGuard", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php", "line": 41, "function": "authenticate", "class": "Illuminate\\Auth\\Middleware\\Authenticate", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Auth\\Middleware\\Authenticate", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php", "line": 57, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 102, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 661, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 636, "function": "runRouteWithinStack", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 602, "function": "runRoute", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", "line": 591, "function": "dispatchToRoute", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", "line": 176, "function": "dispatch", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 30, "function": "Illuminate\\Foundation\\Http\\{closure}", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\barryvdh\\laravel-cors\\src\\HandleCors.php", "line": 36, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Barryvdh\\Cors\\HandleCors", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\fideloper\\proxy\\src\\TrustProxies.php", "line": 57, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Fideloper\\Proxy\\TrustProxies", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php", "line": 30, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php", "line": 30, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php", "line": 27, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php", "line": 46, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 149, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", "line": 102, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", "line": 151, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", "line": 116, "function": "sendRequestThroughRouter", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\public\\index.php", "line": 59, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }, { "file": "C:\\xampp\\htdocs\\apps\\sound\\server.php", "line": 21, "function": "require_once" } ] }

**Comment by driesvints** [comment]
This is used internally in the `TokenGuard` class and `actingAs` method. It's not documented because with normal Passport usage you wouldn't be using this directly.
