### ISSUE TITLE
Laravel 5.4 AngularJS, API Calls returns 401

### ISSUE THREAD

**Issue by devendragohil** [laravel/passport#702]
I am using `Laravel 5.4` and `AngularJS`. I have created `APIs` which are called by my own web-site's `AngularJS Ajax` methods, also by a `Mobile App` and also by some `Third-party apps`. 

For `API authentication` I am using `Laravel Passport ~4.0`, with `Password Grant`. Every is working OK with the `API` calls, but I am not able to `authenticate` the `API` using `Ajax` calls from my Web-site. 

As per the [Laravel Passport Documentation][1], if I use the provider `\Laravel\Passport\Http\Middleware\CreateFreshApiToken::class`, in `web` middleware group, then I don't need to set the `Authorization Header` for my own `API` calls, `Laravel` will handle it for me. *(See #Consuming Your API With JavaScript Para:2 in the provided link)*

Please review my code implementation below: 

**config/app.php:**

    <?php
    	return [
    		'providers' => [
    			Laravel\Passport\PassportServiceProvider::class
    		]
    	];

**app/models/User.php:**

    <?php
    	namespace App\Models;
    	use Laravel\Passport\HasApiTokens;
    	use Illuminate\Notifications\Notifiable;
    	use Illuminate\Database\Eloquent\SoftDeletes;
    	use Illuminate\Foundation\Auth\User as Authenticatable;
    	use App\Traits\Encryptable;
    
    	class User extends Authenticatable
    	{
    		use HasApiTokens;
    		use SoftDeletes;
    		use Notifiable;
    		use Encryptable;
    
    		protected $table = 'users';
    	}

**app/Providers/AuthServiceProvider.php:** 

    <?php
    	namespace App\Providers;
    	use Laravel\Passport\Passport;
    	use Illuminate\Support\Facades\Gate;
    	use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
    
    	class AuthServiceProvider extends ServiceProvider{
    		
    		protected $policies = [
    			'App\Model' => 'App\Policies\ModelPolicy',
    		];
    		
    		public function boot(){
    			$this->registerPolicies();
    			Passport::routes();
    		}
    	}

**config/auth.php:**

    <?php
    	return [
    		'guards' => [
    			'web' => [
    				'driver' => 'session',
    				'provider' => 'users',
    			],
    			'api' => [
    				'driver' => 'passport',
    				'provider' => 'users',
    			],
    		],
    	];

**routes/api.php**

    <?php
    	header('Access-Control-Allow-Origin: *');
    	header('Access-Control-Allow-Headers: Authorization, Content-Type, mobile-app' );
    	header('Access-Control-Allow-Methods', '*');
    	use Illuminate\Http\Request;
    
    	Route::group(['prefix' => '/v1','middleware'=>['auth:api']], function () {
    		//Some APIs are here which returns JSON
    	});

**routes/web.php:** 

    <?php
    	header('Access-Control-Allow-Origin: *');
    	header('Access-Control-Allow-Headers: Authorization, Content-Type, mobile-app' );
    	header('Access-Control-Allow-Methods', '*');
    	
    	Route::get('/',function(){
    		if(\Auth::check()){
    			return redirect('/dashboard');
    		}
    		return redirect('/login');
    	});
    	
    	Route::group(['middleware' => array('auth')], function(){
    		//Some web routes here which returns html views
    	});	
	
**app/http/Kernel.php**

    <?php 
    	protected $middlewareGroups = [
            'web' => 
    			\Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
    		],
    	];

An Ajax request I am doing using `AngularJS` is as:

    function makeRequest(url, params, method) {
    	var requestUrl = '/' + url;
    	if(params != null){
    	   var requestUrl = '/' + url+'?page=1';  
    	}
    	angular.forEach(params, function(value, key){
    		requestUrl = requestUrl + '&' + key + '=' + value;
    	});
    	return $http({
    		'url': requestUrl,
    		'method': method,
    		'headers': {
    			'accept': 'application/json',
    			'X-Requested-With': 'XMLHttpRequest',
    			'X-CSRF-Token': $('meta[name=csrf-token]').attr("content"), //Here, I am using the CSRF token
    		},
    		'cache': false
    	}).then(function(response){
    		return response.data;
    	}).catch(dataServiceError);
    }

With requesting `/dashboard` page which returns an html `view`, `Request` and `Response` is as: 

    General:
    
        Request URL: http://local.something.com/dashboard
        Request Method: GET
        Status Code: 200 OK
        Remote Address: 127.0.0.1:80
        Referrer Policy: no-referrer-when-downgrade
    
    Request Headers: 
    
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        Accept-Encoding: gzip, deflate
        Accept-Language: en-US,en;q=0.9,gu;q=0.8
        Cache-Control: max-age=0
        Connection: keep-alive
        Cookie: laravel_token=eyJpdiI6IjBxXC9zVUhmKzdZMDZqVVwvM0s2V1Y0QT09IiwidmFsdWUiOiJhMmNmOTBtTEZmZE16N0pDRmVDWURlZURVaHlhSUVaZ003TldrbjhmRmdFWmU2SENMTDVLbHdRMmNRK1dDazBGZnkwaER4QVR4b2doQzliWXVQSzBldU1hMWM0UTVycCtVOU9uMzlNa2IyR3gzektXS1FiQTJXd1dcL2xXeFpNZzNRZWJEVjdDRFZleklheVJsU0FSY1dlZEZQWm1lV3hHV0hHN3JwMSs4MncwTkhjN0RNd1hXVENrcGZFR29tMHZXdGxicks3a1J2TjRhNUlNalhiTG5oem1DVHpZWlRvaHIxQzZrY3pqNytNMEhxSkJwUkMxY0NsZmFBY2s5T0VDYzJGUW5MdEZqYm5Kc09vcDdLU1hWdkE9PSIsIm1hYyI6ImY5YzEyNTMxYzYxMTYyZjQ2OWJkZWU1NTkyYjkzYjQzM2Q4Y2NjMzkyMzk3ZDMzNTllNzQ5NGJmYzI4YmFhZDYifQ%3D%3D; XSRF-TOKEN=eyJpdiI6IlpOcllLTDRkYmsrbmRhTnF6NFQ0Z0E9PSIsInZhbHVlIjoiY2VES3d2VGhIcUlnczdOQmV4VzVISHpnUXRFS1lra2dHTXN5VmR0bEQweEVjejlFTFpRczNEdTNtSGRUdW1TS2IyTU01QVwvZCt2RVVmOHRHUUYrRzlBPT0iLCJtYWMiOiI5ZTZhMjE3ZGE2MTliNmNkMzg4ZTg5ODA0MTEyN2E4YTZhNTgxMWFhYWIwMTFhNTM5YWYzMjViMzMxOTkyNjU2In0%3D; laravel_session=eyJpdiI6IktlNUpPd0s2djRzQXlVakRuUkxUR3c9PSIsInZhbHVlIjoicVwvSmlLaVpWK2hKSytQcUU5WmJCdmJIR2ZPS2JnT1FKbWY2M0VLOVNzYlBcL3pJYnl6c1RrVWFVQVlHWUNodjgzdk92WStRVDl1cHEzUGtPRStMUmhPZz09IiwibWFjIjoiODg4YzhmYjQ0NzE2ZDI2MWY1YmU2MmJiYjUxZjk0NTA5MmNiY2ZkZDEwYjk0OTFjZTY0MTE5ODk0MjZmYjRkMSJ9
        Host: local.something.com
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
    
    Response Headers:
    
        Access-Control-Allow-Headers: Authorization, Content-Type, mobile-app
        Access-Control-Allow-Origin: *
        Cache-Control: no-cache, private
        Connection: Keep-Alive
        Content-Type: text/html; charset=UTF-8
        Date: Mon, 07 May 2018 06:21:59 GMT
        Keep-Alive: timeout=5, max=100
        Server: Apache/2.4.23 (Win64) PHP/7.2.4
        Set-Cookie: XSRF-TOKEN=eyJpdiI6IjVWbGlOekVib1QycWFHMTlVb01ENnc9PSIsInZhbHVlIjoibjQzNXFkME95MmMzekJ4cUNOSldpQXY4dE95YVlxV3dsMFNZc1hGZHQySk9lSE5MTXRiS1FJSVNiXC9cL0V4VEFQb1V0Qnl1V1FFb0RhM0Roa2xCVk9zZz09IiwibWFjIjoiMjJmZGRlNzU0MDBmNzA1MzdhYTRmMWNkMjM5YjBmYjU2YzMwOWM1OGFkNmMwYzQ3YTIwMTYzYzY1M2M5ZGZiMiJ9; expires=Mon, 07-May-2018 08:22:00 GMT; Max-Age=7200; path=/
        Set-Cookie: laravel_session=eyJpdiI6InVPWUplcE1GZnVHNUYxXC9YMWl1UmtnPT0iLCJ2YWx1ZSI6IlQxUkpmVllhb0R2dkpiZDFWd0xlWXg5WGxjQTY5dFY2R3BjdGNvTVhoc1pORnE5b0ttMXhcL2NZbFErOVwvMnUwTDAwcFFLXC9ySzdaMkxSR1wva3NEMW1mUT09IiwibWFjIjoiNGYxYmM2NmNhMjE1NjliNGYzYmFiYTdhZmY2ZWY5NzM1MmI5ZjQ3ZTdlY2JjMDg5ODkxMWQwOTBiNjM2MDQzZSJ9; expires=Mon, 07-May-2018 08:22:00 GMT; Max-Age=7200; path=/; HttpOnly
        Set-Cookie: laravel_token=eyJpdiI6ImYxdDB4SGpnWGptMnBNM3lWc2pvY0E9PSIsInZhbHVlIjoiRDZheEtEeHdPT2EyQWFuZ1NPOHcwSnRtUnZ3aW1jOVhxNGtBRnZQK01OakZaTmNIQ1JVMkJ4MGl3RjdhR0NzR0VVODlaWDNyTXVWOXpjS1lOOWNEeDh0OGxISnBWUnU4V0NwKzdheVN0bGJkSVk2dGNnYng3c1p1OGExVGFKejR1M2JjMGlSVzJ3WElEbEFlVTNUeVA1ODdTZXE5alBqWSs5aXV5UUlZVkRmSGppTm0zSnNZc2tEMEhzTEt2NEZ6K0t4eDI0WDdDUmJGYm44NGc4aXo4akxMRVFySmdZblwvMEtMZDJYVTFYU0pBVDY5RG9SdmhlaDF0REhONEpLNHNJbWppZWxrS1Nhd0ZjU2ZVazJqdCtBPT0iLCJtYWMiOiJkMmE1NTc4YTFhYTRlODFmOWY5YjllNmM1MDA4Nzg4ODg5Njg2NDI1Zjk3MzdkYmFlNzg2YzNkZjI3NzYzOWY0In0%3D; expires=Mon, 07-May-2018 08:22:00 GMT; Max-Age=7200; path=/; HttpOnly
        Transfer-Encoding: chunked
        X-Powered-By: PHP/7.2.4

And An API Request for getting User-data done using `Ajax` is like: 

```
    General:
    
    Request URL: http://local.something.com/api/v1/user/3/data
    Request Method: GET
    Status Code: 401 Unauthorized
    Remote Address: 127.0.0.1:80
    Referrer Policy: no-referrer-when-downgrade
    
    Request Headers:
    
    accept: application/json
    Accept-Encoding: gzip, deflate
    Accept-Language: en-US,en;q=0.9,gu;q=0.8
    Connection: keep-alive
    Cookie: laravel_token=eyJpdiI6ImYxdDB4SGpnWGptMnBNM3lWc2pvY0E9PSIsInZhbHVlIjoiRDZheEtEeHdPT2EyQWFuZ1NPOHcwSnRtUnZ3aW1jOVhxNGtBRnZQK01OakZaTmNIQ1JVMkJ4MGl3RjdhR0NzR0VVODlaWDNyTXVWOXpjS1lOOWNEeDh0OGxISnBWUnU4V0NwKzdheVN0bGJkSVk2dGNnYng3c1p1OGExVGFKejR1M2JjMGlSVzJ3WElEbEFlVTNUeVA1ODdTZXE5alBqWSs5aXV5UUlZVkRmSGppTm0zSnNZc2tEMEhzTEt2NEZ6K0t4eDI0WDdDUmJGYm44NGc4aXo4akxMRVFySmdZblwvMEtMZDJYVTFYU0pBVDY5RG9SdmhlaDF0REhONEpLNHNJbWppZWxrS1Nhd0ZjU2ZVazJqdCtBPT0iLCJtYWMiOiJkMmE1NTc4YTFhYTRlODFmOWY5YjllNmM1MDA4Nzg4ODg5Njg2NDI1Zjk3MzdkYmFlNzg2YzNkZjI3NzYzOWY0In0%3D; XSRF-TOKEN=eyJpdiI6IjVWbGlOekVib1QycWFHMTlVb01ENnc9PSIsInZhbHVlIjoibjQzNXFkME95MmMzekJ4cUNOSldpQXY4dE95YVlxV3dsMFNZc1hGZHQySk9lSE5MTXRiS1FJSVNiXC9cL0V4VEFQb1V0Qnl1V1FFb0RhM0Roa2xCVk9zZz09IiwibWFjIjoiMjJmZGRlNzU0MDBmNzA1MzdhYTRmMWNkMjM5YjBmYjU2YzMwOWM1OGFkNmMwYzQ3YTIwMTYzYzY1M2M5ZGZiMiJ9; laravel_session=eyJpdiI6InVPWUplcE1GZnVHNUYxXC9YMWl1UmtnPT0iLCJ2YWx1ZSI6IlQxUkpmVllhb0R2dkpiZDFWd0xlWXg5WGxjQTY5dFY2R3BjdGNvTVhoc1pORnE5b0ttMXhcL2NZbFErOVwvMnUwTDAwcFFLXC9ySzdaMkxSR1wva3NEMW1mUT09IiwibWFjIjoiNGYxYmM2NmNhMjE1NjliNGYzYmFiYTdhZmY2ZWY5NzM1MmI5ZjQ3ZTdlY2JjMDg5ODkxMWQwOTBiNjM2MDQzZSJ9
    Host: local.something.com
    Referer: http://local.something.com/dashboard
    User-Agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
    X-CSRF-Token:s7FFvqtvSlYuQVmx5x7xkYzcAbCzlVlB1GIhtnji
    X-Requested-With: XMLHttpRequest
    X-XSRF-TOKEN: eyJpdiI6IjVWbGlOekVib1QycWFHMTlVb01ENnc9PSIsInZhbHVlIjoibjQzNXFkME95MmMzekJ4cUNOSldpQXY4dE95YVlxV3dsMFNZc1hGZHQySk9lSE5MTXRiS1FJSVNiXC9cL0V4VEFQb1V0Qnl1V1FFb0RhM0Roa2xCVk9zZz09IiwibWFjIjoiMjJmZGRlNzU0MDBmNzA1MzdhYTRmMWNkMjM5YjBmYjU2YzMwOWM1OGFkNmMwYzQ3YTIwMTYzYzY1M2M5ZGZiMiJ9
    
    Response Headers:
    
    Access-Control-Allow-Headers: Authorization, Content-Type, mobile-app
    Access-Control-Allow-Origin: *
    Cache-Control: no-cache, private
    Connection: Keep-Alive
    Content-Length: 12
    Content-Type: text/html; charset=UTF-8
    Date: Mon, 07 May 2018 06:22:00 GMT
    Keep-Alive: timeout=5, max=100
    Server: Apache/2.4.23 (Win64) PHP/7.2.4
    Set-Cookie: laravel_session=eyJpdiI6Im82TGNRVms0aUtSNHNVbzdKZXZYb0E9PSIsInZhbHVlIjoiY1wvTmZXV3o0SVYyRmVoMzRheWNaRHBDV29jWmI2S3JvQjNBOEVjNHlsQkpKMWlRMWdYWlU1ckdnbTRIOVllSmZIOVpud01BTExtSURXNHdDdkZZMDNnPT0iLCJtYWMiOiIyMzc4YjczNTFmYmJlNDg3N2UxZDJlODg0NDFjNjEyZjhhYWM4YTk4MTMzZDk0NjUyY2ZkNjY0MTUzZWZjYjVlIn0%3D; expires=Mon, 07-May-2018 08:22:01 GMT; Max-Age=7200; path=/; HttpOnly
    X-Powered-By: PHP/7.2.4
    X-RateLimit-Limit: 300
    X-RateLimit-Remaining: 299
```

This returns `401` Unauthorized, I am not sure why? The problem is with `API` calls which is made by my `own web-application` using `Ajax` only. For Mobile App and Third-Party apps, we're using `Authorization` header and everything seems working OK with it. Can anybody let me know what am I missing or how to fix this?

  [1]: https://laravel.com/docs/5.4/passport#consuming-your-api-with-javascript

**Comment by devendragohil** [comment]
After a lot of tracing, I found the issue was there with `app/Http/Kernel.php`. 
In  `protected $middlewareGroups` there are some `middlewares` added within `api` section like: 

```
protected $middlewareGroups = [
	'api' => [
		'throttle:300,1',
		\App\Http\Middleware\EncryptCookies::class,
		\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
		\Illuminate\Session\Middleware\StartSession::class,
		'bindings',
	],
];
```

These were encrypting the cookie hence it was returning `401 Unauthorised`. I have removed them like: 

```
protected $middlewareGroups = [
	'api' => [
		'throttle:300,1',
		'bindings',
	],
];
```

and the code started working.

**Comment by Tarasovych** [comment]
@devendragohil may I ask you about how do you handle with sending Cookies from server to your Angualr app?
Do you make `POST /login` to retreive them? I'm using Vue (I have SPA) and now I want to implement Cookies too because of they are more safe than storing token in `LocalStorage`.
