### ISSUE TITLE
'Key file "%s" permissions are not correct, should be 600 or 660 instead of %s'

### ISSUE THREAD

**Issue by ShyZhen** [laravel/passport#712]
你好，我在使用laravel5.3，passport1.0，windows环境，当我运行/oauth/authorize的时候，出现了`permissions are not correct, should be 600 or 660 instead of 666`这个错误，但是我使用的是windows系统，我根据错误信息找到了出问题的代码，在`vendor\league\oauth2-server\src\CyptKey.php`中，第50~59行
```
            $keyPathPerms = decoct(fileperms($keyPath) & 0777);
            if (in_array($keyPathPerms, ['600', '660'], true) === false) {
                // @codeCoverageIgnoreStart
                trigger_error(sprintf(
                    'Key file "%s" permissions are not correct, should be 600 or 660 instead of %s',
                    $keyPath,
                    $keyPathPerms
                ), E_USER_NOTICE);
                // @codeCoverageIgnoreEnd
            }
```

这里keyPathPerms确实是666，但是我不知道该如何去做，删掉这个判断可以正常使用，我需要一些建议。

---------
Hello, I'm using the laravel5.3, passport1.0, windows environment. When I run /oauth/authorize, there is a `permissions are not correct, should be 600 or 660 instead`, but I used the windows system, and I found the problem code based on the error information. In `vendor\league\oauth2-server\src\CyptKey.php`, row 50~59

```
            $keyPathPerms = decoct(fileperms($keyPath) & 0777);
            if (in_array($keyPathPerms, ['600', '660'], true) === false) {
                // @codeCoverageIgnoreStart
                trigger_error(sprintf(
                    'Key file "%s" permissions are not correct, should be 600 or 660 instead of %s',
                    $keyPath,
                    $keyPathPerms
                ), E_USER_NOTICE);
                // @codeCoverageIgnoreEnd
            }
```

And KeyPathPerms is really 666, but I don't know how to do it. If I delete this judgement, I can use it normally. I need some suggestions.Thank you.

**Comment by driesvints** [comment]
Heya, unfortunately Passport 1.0 isn't supported anymore. Please update to the latest version. Looks like you also moved this to the oauth2-server library so I'm going to close this.
