### ISSUE TITLE
Installation: Access to undeclared static property: Laravel\Passport\Passport::$client

### ISSUE THREAD

**Issue by mc0de** [laravel/passport#717]
Like half an hour everything were ok, broken installation?

Tried fresh deployment.

![screenshot from 2018-05-24 17-28-32](https://user-images.githubusercontent.com/8727992/40491963-1f31c08c-5f78-11e8-91a2-7a4aa6cfc223.png)

**Comment by Sephster** [comment]
I think it is a problem with the last PR. See the following lines:

https://github.com/laravel/passport/blob/34501fc575df863b77ca38f0682540a0b4397129/src/Passport.php#L406-L414

From a quick look, I don't think `$client` exists...

**Comment by kemalevren** [comment]
I have updated and now I am having the same problem.

**Comment by Donovan-H** [comment]
@Sephster looks like it... #718

**Comment by AustinPaquette** [comment]
Did a quick check, it only exists as an issue with `6.0.1` and not `6.0.0`, the PR (#718) does indeed fix the issue, so it'll just be a small hiccup. Reverted to a hard 6.0 dependancy version for the time being.

**Comment by AustinPaquette** [comment]
> searched for hours on Google no results shown

That's why I did a bit of digging, I wasn't able to find anything related to this issue on Google either so I assumed it was either unreported or brand new. Just wanted to bring a bit of clarity (and a solution) to the problem cause I know how us developers get when random deps all of a sudden break 🙃

**Comment by ThomHurks** [comment]
I can also confirm that Passport 6.0.1 is broken @taylorotwell

**Comment by jasonloeve** [comment]
Likewise, 6.0.1 seems to be broken, rolled back to 6.0.0

**Comment by alan51** [comment]
is do not work.....has broken!

**Comment by AustinPaquette** [comment]
This was fixed in #718 and can now probably be closed @mc0de

**Comment by driesvints** [comment]
Should be fixed now.
