### ISSUE TITLE
Implicit grant tokens issue

### ISSUE THREAD

**Issue by stesvis** [laravel/passport#721]
I am developing an app that allows to log in with google/facebook etc.
Once logged in, how can I generate a Bearer token to use with my API? I can't find an example..

I was looking at this:
https://laravel.com/docs/5.6/passport#implicit-grant-tokens

I am passing these parameters to oauth/authorize:

- client_id = my client id
- scope = *
- response type = token
- redirect_uri = whatever

**Problem**
I always get a "Page Expired" response.

What am I missing?

**Comment by stesvis** [comment]
Hi @Sephster thanks for the reply.
The log in with social media happens in a mobile app, once authenticated, i just want laravel passport to generate a bearer token, how can i do that?

If they log in with their credentials I use the password grant token, but in this case i just want the passport to give me a token.

**Comment by stesvis** [comment]
@Sephster , after they log in with Google/Facebook whatnot, I want them to be able to use resources from my API, which are protected, and need my own API Bearer token.
My problem is very common, since they don't have an account in my database, how can they access my API with a Bearer token after a successful login with google?

My process is this:

1. Login with Google
2. Retrieve their google email
3. Check if it exists in my database
4. Grant them access to my API

**Comment by Sephster** [comment]
Ahh sorry, I see now. As far as I'm aware, this should be possible. What is the full error message you are getting and HTTP return code?

I'm not too familiar with Socialite but I believe you should be able to retrieve user details from the token to create a user in your DB if required.

**Comment by stesvis** [comment]
According to the Passport docs it should be possible. For now I am just using Postman to test it, and the url is this:

{{base_url}}/oauth/authorize?client_id=2&response_type=token&redirect_uri={{base_url}}&scope=

where {{base_url}} is https://mywebsite.com

so i provide:

- client_id = 2
- response_type=token
- redirect_uri = {{base_url}}
- scope = ''

basically i am trying to do this:

```
Route::get('/redirect', function () {
    $query = http_build_query([
        'client_id' => 'client-id',
        'redirect_uri' => 'http://example.com/callback',
        'response_type' => 'token',
        'scope' => '',
    ]);

    return redirect('http://your-app.com/oauth/authorize?'.$query);
});
```

and I did enable this:
`Passport::enableImplicitGrant();`

What I get in return is a 500 error:

> InvalidArgumentException
> Route [login] not defined.

in R:\VeloGuide\Api\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php

**Comment by Sephster** [comment]
Hmm. This might sound daft but do you have a login route defined for your socialite OAuth Provider?

Something should be setup like follows:

```
Route::get('login/github', 'Auth\LoginController@redirectToProvider');
Route::get('login/github/callback', 'Auth\LoginController@handleProviderCallback');
```

**Comment by stesvis** [comment]
No I don't have a login route.
It's purely an API project and users log in by authenticating at /oauth/token.

All I want is to generate a token manually now, and i don't know how.

**Comment by Sephster** [comment]
How do your users login to Google/Facebook? I would have expected them to have a login route for that

**Comment by stesvis** [comment]
Well the problem is that I show the a platform (webview) to log in with facebook/google, and received their email, ID etc.
But i was stuck there, that was my whole issue.

I solved it now by creating a custom route in my API, where I pass email, id, client_id and client_secret, and then I check if there is a user that matches. If there is, then i manually create a token.

**routes/api.php**

```
    Route::group(['prefix' => 'oauth/social'], function () {
        Route::post('/token', ['as' => 'login.social', 'uses' => 'Auth\LoginController@socialToken']);
    });
```


**Controllers/Auth/LoginController.php**

```
    /**
     * Allows to log in, provided you are already authenticated with strava/facebook/google
     *
     * @param SocialLoginRequest $request
     * @return JsonResponse
     */
    public function socialToken(SocialLoginRequest $request)
    {
        try {

            // Make sure that the provided client_id and client_secret are present in the database
            $client = DB::table('oauth_clients')
                ->where('id', $request->client_id)
                ->where('secret', $request->client_secret)
                ->where('personal_access_client', 1)
                ->first();

            // Wrong passport credentials
            if ($client === null) {
                throw new \Exception('Passport authentication failed. No such client id and secret.');
            }

            // Correct passport credentials
            // Find a user that matches email, provider and id
            $user = \App\User::where($request->provider, $request->id)
                ->where('email', $request->email)
                ->first();
            \Auth::loginUsingId($user->id);

            $now = new \DateTime();

            // Manually create a token
            $token = $user->createToken('Social Token');
            $tokenDTO = new TokenDTO();
            $tokenDTO->token_type = 'Bearer';
            $tokenDTO->access_token = $token->accessToken;
            $tokenDTO->expires_in = $token->token->expires_at->getTimestamp() - $now->getTimestamp();

            return new JsonResponse($tokenDTO, Response::HTTP_OK);
        } catch (\Exception $e) {
            return new JsonResponse($e->getMessage(), Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
```

**Comment by Sephster** [comment]
Glad to hear you have arrived at a solution. I haven't seen a working example of socialite + passport but I would have expected that all you would need to do is have your login route initiate the socialite login process as normal. 

Anyways, glad this is working for you now. If you have a working solution, I guess you can go ahead and close this ticket. Cheers!

**Comment by stesvis** [comment]
I don't use socialite. The login with social providers happen in my mobile app, it has nothing to do with laravel and passport.
I use the laravel API only to authenticate my users AFTER the social media part.
Anyway, thanks for the help!
