### ISSUE TITLE
Force change password and force accept terms like Google for grant type authorization code

### ISSUE THREAD

**Issue by ehuebner** [laravel/passport#722]
Hello,
I am about to use Passport as authentication solution for our newest project.
After hours of research, I cannot figure out how to implement the authentication flow like in google apps:
1. I create a new google account in google admin console.
2. I type "drive.google.com" in the browser.
3. I get redirected to "accounts.google.com"
4. I type in user & password and authenticate successfully.
5. **I need to accept the terms.**
6. **I need to change my password.**
7. I think I get my authorization code.
8. I get redirected to "drive.google.com".

In Passport I can only change my user & password for an authorization code. But there is no possibility to authenticate successfully and force accept terms and change password (step 5 & 6) before I get the authentication code and redirect. Is there any chance to implement that behavior using Passport?

Thanks for your help in advance.

**Comment by Sephster** [comment]
Probably the easiest way to Add T's and C's would be to modify your authorization view accordingly:

https://github.com/laravel/passport/blob/6.0/resources/views/authorize.blade.php

Although to be honest, I'm not sure why you'd do this. The user should already have an account in your application and the client should already be registered. If your client has to accept some t's and c's it wouldn't make sense to display this during the authorization phase.

I'm also not clear why you need to change your password. This is not part of the OAuth 2 spec as there shouldn't be any reason to do this so I don't think this would ever be included in Passport.

Hope this helps

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks for replying @Sephster.
