### ISSUE TITLE
Laravel 5.3 Passport - Vue error: Error when evaluating expression

### ISSUE THREAD

**Issue by cc-sistemas** [laravel/passport#73]
Hola, disculpen, tengo el siguiente error, espero que me puedan ayudar.
`[Vue warn]: Error when evaluating expression "token.name": TypeError: Cannot read property 'name' of undefined (found in component: <passport-personal-access-tokens>)`
[https://laracasts.com/discuss/channels/vue/laravel-53-passport-vue-error-error-when-evaluating-expression](url)

Gracias.

**Comment by duccanh0022** [comment]
Hi, i have same problem. Did you fix it?

**Comment by xoco70** [comment]
I had the same issue, you can fix it with the link provided in the first post:

A quick fix, as suggested on the page is the following interceptor. It seems to fix this problem with laravel passport

 ```
Vue.http.interceptors.push((request, next ) => {
    next((response) => {
        if( 'Content-Type' in response.headers 
            && response.headers['Content-Type'] == 'application/json' ){
            if( typeof response.data != 'object' ){
                response.data = JSON.parse( response.data );
            }
        }

        if( 'content-type' in response.headers
            && response.headers['content-type'] == 'application/json' ){
            if( typeof response.data != 'object' ){
                response.data = JSON.parse( response.data );
            }
        }
    });
});
```
You can add this to your bootsrap.js or app.js untill an official update is released
