### ISSUE TITLE
what are different laravel passport tables and fields for?

### ISSUE THREAD

**Issue by naco99** [laravel/passport#733]
Hi,
I'm new to laravel passport, I installed it and making it work, But still have some question about it.
I dont really now yet what different tables are for, when they are used, can we delete some of them ( oauth_auth_codes seems not be useful in my case, because it is always empty)
and also for what the token name is usefull, is it required or not, should we use createToken or just issueToken.

thanks

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
