### ISSUE TITLE
Branch 4.0 behind on releases

### ISSUE THREAD

**Issue by shift-keshav-pudaruth** [laravel/passport#739]
Latest release is 4.0.3, which was on 24th September 2017.

@taylorotwell  A new release which incorporated all the recent fixes would be much appreciated.

We stumbled upon the issue whilst looking for a solution to #541 and is merged in the dev 4.0 branch.

**Comment by driesvints** [comment]
Heya, sorry but 4.0 isn't supported anymore. If you want the latest commit on this branch you can always require it manually like this:

`"laravel/passport": "dev-4.0",`
