### ISSUE TITLE
How can i use it with Laravel Voyager

### ISSUE THREAD

**Issue by destinyforeverr** [laravel/passport#743]
Hello Guys,

How can i use Laravel Passport with Laravel Voyager?

https://github.com/the-control-group/voyager

Many thanks in advance.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
