### ISSUE TITLE
Installation for spark

### ISSUE THREAD

**Issue by fwartner** [laravel/passport#75]
According to the newest spark release and the tweet i would like to know, how to use passport with spark. Because spark isn´t really comfortable with .vue files.. :/

**Comment by tao** [comment]
The latest release of Laravel (since Sep 10) now supports Spark. I have it working and you can follow along with my [own notes](https://gist.github.com/tao/fba880299bdfdcfd491582724ede9dd7) and see if you can get it working on your project.
