### ISSUE TITLE
Trying to get property 'revoked' of non-object when Refreshing Tokens

### ISSUE THREAD

**Issue by jonaselan** [laravel/passport#751]
When I try to retrieve a new token through the refresh token (passing a valid token refresh), I get the `Trying to get property 'revoked' non-object error at vendor/laravel/passport/src/Bridge/ RefreshTokenRepository.php: 91`. 

Going to `RefreshTokenRepository.php` I realize that` $refreshToken` is being treated as an object, not as an array. If I change and use `$refreshToken['revoked']` instead of `$refreshToken->revoked` it works. Is it a bug or am I doing something wrong?

thanks in advance

**Comment by driesvints** [comment]
I don't really understand what's going wrong here. It should be hydrated as an object. Let me know if the problem persists in the latest Laravel and Passport release.

**Comment by tranghaviet** [comment]
+1
Same issue here. I got this error when using grant type `refresh_token`. I use **"laravel/passport": "^7.0"**

**Comment by driesvints** [comment]
@tranghaviet which database type are you using? There are apparently some issues when using Mongo for example.

**Comment by tranghaviet** [comment]
@driesvints You are right. I use MongoDB. How can I fix this issue?

**Comment by jonaselan** [comment]
In the time I used Mongo too. Today I not work anymore on this project.

**Comment by driesvints** [comment]
Check the remarks here: https://github.com/laravel/passport/issues/848
