### ISSUE TITLE
Tokens Issued for `password_grant` Also Pass `CheckClientCredentials`

### ISSUE THREAD

**Issue by lloy0076** [laravel/passport#753]
## Issue / Question

Using the `Laravel\Passport\Http\Middleware\CheckClientCredentials` code from Passport (`laravel-passport: '^6.0'`), a token gotten via a `password_grant` also passes the mentioned middleware.

Should this be the case?

### Assumptions

You have a Laravel application properly configured with:

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/passport": "^6.0",
        "laravel/tinker": "^1.0"
    },
   // Snip the rests for brevity
```

`composer create-project lararvel/laravel my-project` will do the trick; then `composer require laravel/passport`. I doubt the version of PHP matters and this probably happens on earlier versions of Laravel and Laravel Passport but this is the version I noticed it on.

[composer.lock.zip](https://github.com/laravel/passport/files/2151781/composer.lock.zip) <-- to be precise.

Setup Passport and Laravel as per documentation.

Make sure to change the `auth:api` in `config/auth.php` to `passport` (it is probably `token` by default).

#### Verify Password Grant Works

1. See assumptions!
2. Make a user, any user
3. Issue yourself an Oauth token using a `password_grant`
4. Make sure that the route `YOUR_URL/api/user` gets the user.

#### Configure the CheckUserCredentials

See [the check client credentials page](https://laravel.com/docs/5.6/passport#client-credentials-grant-tokens).

Then change the middleware in `routes/api.php` to use `client` or whatever you called the middleware.

#### Look, Ma, It Still Works (Sort Of)

Do step (4) from `Verify Password Grant Works`. You won't get a user back - _this is expected and not a bug_. 

But it **DOES PASS**!

^^ that is the question - should it?

### Other Comments

I probably should read the specification - OAuth2 itself might specify that it should.

It looks like this issue might belong to the underlying Oauth2 server.

If it **is** a bug and it **is** fixed it **could** affect code in the wild; it probably shouldn't but let's say that "Johnny Dev has a route (or two) covered by `CheckClientCredentials` and users who usually use a token gained via `password_grant`. If this changed, so that users could no longer do so, the users would notice the difference (one would hope)."

**Comment by robbytaylor** [comment]
@lloy0076, see https://github.com/laravel/passport/issues/691

**Comment by driesvints** [comment]
Heya, thanks for reporting. If it's ok I'm going to close this in favor of https://github.com/laravel/passport/issues/691. Let's continue the discussion there.
