### ISSUE TITLE
Upgrade guide

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/passport#755]
I know this isn't really a place for questions but I couldn't find an answer anywhere else.
Where can I find an upgrade guide from Laravel Passport 5 to 6? Is version 6 compatible with version 5?

In the [framework upgrade guide](https://laravel.com/docs/5.6/upgrade) from 5.5 to 5.6 it says I should upgrade Passport to `^5.0`. Does that mean that Passport 6 is incompatible with Laravel 5.6?

**Comment by indigoram89** [comment]
Great question!

**Comment by jamesgraham** [comment]
I am also looking for this information

**Comment by KKSzymanowski** [comment]
Ping @themsaid @taylorotwell

**Comment by themsaid** [comment]
It is, framework 5.6 with passport 6.0

**Comment by KKSzymanowski** [comment]
I created a PR to fix the inconsistency. All is clear now, thanks.
