### ISSUE TITLE
Graceful handling for uploaded files above PHP's upload_max_filesize when CheckClientCredentials middleware is applied

### ISSUE THREAD

**Issue by JakeBooher** [laravel/passport#760]
After doing some debugging on my own via laravel/framework#24798 I've discovered that the error I'm getting there is actually coming from the `\Laravel\Passport\Http\Middleware\CheckClientCredentials` middleware, so figured this would be a more appropriate place for this issue

Passport version: 6.0.3
Laravel version: 5.6.26

Specifically seems to be triggered by this line in `\Laravel\Passport\Http\Middleware\CheckClientCredentials`:

`$psr = (new DiactorosFactory)->createRequest($request);`

**Comment by JakeBooher** [comment]
Ultimately boils down to `\Zend\Diactoros\ServerRequest` running:

`$this->validateUploadedFiles($uploadedFiles);`

Is there any way for us to bypass this as I'm only wanting to check the client credentials to ensure they're valid

**Comment by driesvints** [comment]
Think this is more an issue with DiactorosRequestFactory or the symfony implementation. Try asking there.

https://github.com/zendframework/zend-diactoros/issues/316
