### ISSUE TITLE
Password grant not working (Unable to determine authentication model from configuration.)

### ISSUE THREAD

**Issue by DREWtheBAWS** [laravel/passport#762]
Before i updated passport my client authentication was working flawlessly. Now, whenever i try to login with a registered user it gives me a status code 500 with "Unable to determine authentication model from configuration." in my body (postman call). 
I tried to rollback to a previous version but it still doesn't work

This is my postman call:
![image](https://user-images.githubusercontent.com/19063652/42578507-8bc36826-84f4-11e8-83c9-c6a09aeb7000.png)

I know the endpoint works because the moment i remove a required parameter i get a status code 400 with this message `"error": "invalid_request",
    "message": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
    "hint": "Check the 'username' parameter"`

**Comment by liranAtli** [comment]
solution?

**Comment by alexeycrystal** [comment]
Have you resolved this issue?

**Comment by BikashPokhrel** [comment]
Unable to determine authentication model from configuration. i am trying to solve this problem now :D damn i too can't find the solution for this yet

**Comment by kaushikkhambhadiya** [comment]
does anyone come to any solution?having same issue.after composer update ,i am getting Unable to determine authentication model from configuration error.

**Comment by bjrnblm** [comment]
Make sure in your `config/auth.php` you have the passport guard:

```
'api' => [
  'driver' => 'passport',
  'provider' => 'users',
],
```

Also make sure the guard name is `api` because it is [hardcoded](https://github.com/laravel/passport/blob/8.x/src/Token.php#L80).
