### ISSUE TITLE
Update client id to Uuid 

### ISSUE THREAD

**Issue by diadal** [laravel/passport#764]
how can I change client_id to Uuid form also

**Comment by runfan** [comment]
just change in the migration file

**Comment by mloberg** [comment]
You can achieve this by updating migrations and using model listeners. https://mlo.io/blog/2018/08/17/laravel-passport-uuid/

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
