### ISSUE TITLE
Problem with client_secret

### ISSUE THREAD

**Issue by v01061374** [laravel/passport#766]
Hi
Firstly, Excuse me if the issue is a duplicate, but i couldn't get what i wanted ...
I'm using the latest versions of Laravel and passport and I want to make an API to use as a back-end for my own website ajax requests, and also for "my mobile app". 
I guess I should use the password grant but i can't understand how to handle client_secret in a secure way. I don't want to save the client_secret in .env because the website itself is not the only consumer of the API.
I would be delighted if anyone can guide me...
:)

**Comment by v01061374** [comment]
any ideas?!!

**Comment by StevePorter92** [comment]
https://laravel.com/docs/5.6/passport#implicit-grant-tokens

It sounds like it would be best for you to use the implicit grant type if you have a frontend making XHR requests.

**Comment by v01061374** [comment]
@StevePorter92 tnx 
But i don't understand how i can get user/pass from requests in this grant type

**Comment by v01061374** [comment]
Also
As i read the OAuth docs, the client_secret is optional
Is it a way not to use it with password_grant

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
