### ISSUE TITLE
Client Credentials Grant Tokens problem

### ISSUE THREAD

**Issue by boneq** [laravel/passport#767]
Hello:
Why any key can request Client Credentials Grant Tokens, I don't really understand that I have 2 servers one is Oauth, the other is appserver, you can get token, I just want a specific appserver to operate the data on Oauth, rather than let all oauth_clients can use Client Cred Entials Grant Tokens to operate the API on my Oauth

**Comment by driesvints** [comment]
Closing this as a duplicate of #691
