### ISSUE TITLE
Add custom field to access tokens table

### ISSUE THREAD

**Issue by gildebrand** [laravel/passport#768]
Hi!

I'm working on an application where we need to add a custom field to the `oauth_access_tokens` table. More specifically, I want to add a field called `device_id`. This field should be optional, and take any string as a parameter. I can easily add the field to the database, but how can I make Passport persist the field if present in the authentication request? I've looked at extending the `AccessToken` and the `AccessTokenRepository` classes, but it seems like a massive task to do that.

What would be the right way of doing this?

**Comment by hareland** [comment]
Hi!

You could just use a migration in your laravel installation, e.g 
```
php artisan make:migration add_extra_passport_fields
```

As you can see in https://github.com/laravel/passport/tree/6.0/database/migrations all the migrations are dated 2016_06_01, this means if you create a migration today (or any day after that date) it will run AFTER the migration which creates the tables, thus we only need to add a column, make it something like this in its up and down methods:

```PHP
<?php
// database/migrations/2018_07_24_080303_add_extra_passport_fields.php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddExtraPassportFields extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('oauth_access_tokens', function (Blueprint $blueprint) {
            $blueprint->string('device_id')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('oauth_access_tokens', function (Blueprint $blueprint) {
            $blueprint->removeColumn('device_id');
        });
    }
}
```

Now all you have to do is run 
```
php artisan migrate
```



Hope this helped!

**Comment by driesvints** [comment]
Thanks @hareland for helping out 👍

**Comment by socheat1994** [comment]
Hey!. How can you add value to device_id column?.

**Comment by driesvints** [comment]
@socheat1994 try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
