### ISSUE TITLE
Fire Passport Events

### ISSUE THREAD

**Issue by mikemclin** [laravel/passport#77]
What about firing Passport events throughout the process?  There are several reasons why someone might be interested in these details. One might be for logging when someone gets a token (see: https://github.com/thephpleague/oauth2-server/issues/628).

For example: in `Laravel\Passport\Bridge\RefreshTokenRepository::persistNewRefreshToken()`, I added `event('passport.refresh', $refreshTokenEntity->getAccessToken()->getUserIdentifier());` to the bottom of the method, because I needed to know when a refresh token is created, and for whom.

It would be nice if Passport had these types of events natively.

**Comment by etelford** [comment]
I've submitted [PR #90](https://github.com/laravel/passport/pull/90) that would address events when creating Access Tokens.
