### ISSUE TITLE
Encrypted username oauth/token

### ISSUE THREAD

**Issue by khoude24** [laravel/passport#771]
Hi, I have a problem, I have a encrypted username,  encryption always return a differents string, so I can't use `findForPassport` in user model.  How can I make oauth/token work with my encrypted username?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
