### ISSUE TITLE
How can I get token from other oauth_clients_id

### ISSUE THREAD

**Issue by hhxiaohei** [laravel/passport#778]
```php
default token is create by client_id=1

$user->createToken('111')->accessToken

How can I get token without password from client_id =2 ?

```

Tks

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
