### ISSUE TITLE
Implicit grant redirect with wrong url format

### ISSUE THREAD

**Issue by ilvalerione** [laravel/passport#790]
Hi,
I'm trying to use "Implicit Grant Token" with my Passport installation. 
I follow subsequent steps:

- Enebled implicit grant in AuthServiceProvider by `Passport::enableImplicitGrant();`
- Send Authorization request to oauth server without `client_secret` and using `response_type="token"`

When OAuth server redirect to my app after click on `Authorize` button I see this url in the browser:

`http://localhost/callback#access_token=eyJ0eXAiOiJKV1Q....`

To receive access_token param correctly it needs to be attached in the query string using ` **?** ` instead ` **#** ` but this request is generated by Passport. 

How can i solve this issue?

**Comment by ilvalerione** [comment]
I'm exploring Passport package to justify this behavior. 

In the PHP League package there is ImplicitGrant class to represent the implicit grant type behavior where is specified as `queryDelimiter = '#'`

![immagine](https://user-images.githubusercontent.com/13559278/43706639-3c5b01c8-9966-11e8-8fa8-cb1abf74e761.png)

This delimiter is used in the `completeAuthorizationRequest` method to generate redirect URI.

**Comment by ilvalerione** [comment]
I solved this issue not enabling implicit grant using laravel passport flag but rewriting the implicit grant enable condition from laravel passport service provider.

In my AuthServiceProvider:

```php
public function boot()
    {
        $this->registerPolicies();

        Passport::routes();

        //Passport::enableImplicitGrant();
        $this->app->make(AuthorizationServer::class)->enableGrantType(
            $this->makeImplicitGrant(),
            Passport::tokensExpireIn()
        );
    }



    /**
     * Create and configure an instance of the Implicit grant.
     *
     * @return \League\OAuth2\Server\Grant\ImplicitGrant
     */
    protected function makeImplicitGrant()
    {
        return new ImplicitGrant(Passport::tokensExpireIn(), '?'); // <-- Here I can change the shit # with ?
    }
```

And (obviously) redirect works fine.

I can't judge if this is could be considered a bug of Laravel passport package. 

I would appreciate to keep in touch with me if you will decide to upgrade the package.

**Comment by Sephster** [comment]
The hash is a valid delimiter and is used so that the access token isn't passed back to the server as it would be if it was a query string.

**Comment by ilvalerione** [comment]
Do you know if is this for security? Or what else? 
So to catch the access_token do I need to parse the URL and not aspect a query string parameter?
thanks for your support

**Comment by Sephster** [comment]
Yes it is for security. Typically you would use the implicit grant with a JavaScript client which should be able to pick up the URL and extract the fragments without issue.

**Comment by ilvalerione** [comment]
Wow, really clear now!
Thanks @Sephster for your clear explanation!
