### ISSUE TITLE
Laravel 5.6.30 breaks passport

### ISSUE THREAD

**Issue by krve** [laravel/passport#795]
If you don't serialize the cookies this breaks passport authentication. On line 190 in `src/Guards/TokenGuard.php`. 

```php
/**
 * Decode and decrypt the JWT token cookie.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return array
 */
protected function decodeJwtTokenCookie($request)
{
    return (array) JWT::decode(
        // This line does not disable serialization per EncryptCookies.php
        $this->encrypter->decrypt($request->cookie(Passport::cookie())),
        $this->encrypter->getKey(), ['HS256']
    );
}
```

This is only the case if you make use of your passport api on your own site. (https://laravel.com/docs/5.6/passport#consuming-your-api-with-javascript)

**Comment by amacsmith** [comment]
The decrypt function in Illuminate\Encryption\Encrypter.php fails to unserialize the laravel_token from the request cookies. 

`/**
     * Decrypt the given value.
     *
     * @param  mixed  $payload
     * @param  bool  $unserialize
     * @return mixed
     *
     * @throws \Illuminate\Contracts\Encryption\DecryptException
     */
    public function decrypt($payload, $unserialize = true)
    {
        $payload = $this->getJsonPayload($payload);

        $iv = base64_decode($payload['iv']);

        // dd($this->cipher);

        // Here we will decrypt the value. If we are able to successfully decrypt it
        // we will then unserialize it and return it out to the caller. If we are
        // unable to decrypt this value we will throw out an exception message.
        $decrypted = \openssl_decrypt(
            $payload['value'],
            $this->cipher,
            $this->key,
            0,
            $iv
        );

        if ($decrypted === false) {
            throw new DecryptException('Could not decrypt the data.');
        }

        return $unserialize ? unserialize($decrypted) : $decrypted;
    }
`

This returns the exception

`unserialize(): Error at offset 0 of 209 bytes`

**Comment by philtweir** [comment]
Just to link in the context:
* https://laravel.com/docs/5.6/upgrade#upgrade-5.6.30
* https://github.com/laravel/framework/compare/9ed650cff69eee0def4a67f3033429e5e8a7ce59...v5.6.30#diff-de6296975e0aca009488e69826a54f33

**Comment by poxin13** [comment]
Had to add that to `EncryptCookies.php` as well. Same issue.

**Comment by themsaid** [comment]
Opened a PR to introduce a way to stop unserializing the cookie value:

https://github.com/laravel/passport/pull/796

**Comment by plakhin** [comment]
@themsaid please don't forger about laravel/passport 4.0, the latest one supported by Laravel 5.5 LTS

**Comment by themsaid** [comment]
@plakhin can you backport this PR to it?

**Comment by plakhin** [comment]
@themsaid I'm to busy until next week. If no one will do, then I do, but a bit later.

**Comment by clnt** [comment]
@themsaid I have opened a PR to the 4.0 branch: #797

**Comment by simondavies** [comment]
I had this for version 4.0 and tried to composer update but it did not download the update, I had to target it directly

`composer require laravel/passport:4.0.x-dev`

**Comment by prolonginc** [comment]
this was driving me nutts for a couple of hours. @simondavies  the version 5 will work just clear your cookies after adding in `protected static $serialize = true; `to the `EncryptCookies`.

**Comment by clnt** [comment]
@prolonginc Why would you do that? That is just disabling the security fix.

@taylorotwell Can we not just get a version 4.0.4 tagged on the 4.0 branch??

**Comment by amacsmith** [comment]
Could a artisan command be created to do this update for users? instead of breaking upon composer update?

**Comment by NastuzziSamy** [comment]
This issue made me tilt the whole day

**Comment by NastuzziSamy** [comment]
If you have updated Laravel\Passport you should follow this:

> Passport 6.0.7
>
> Passport 6.0.7 has been released with a new Laravel\Passport\Passport::withoutCookieSerialization() method. Once you have disabled cookie serialization, you should call this method within your application's AppServiceProvider.

Using `protected static $serialize = true;` create a security issue...
