### ISSUE TITLE
Personal Access Tokens with the same name break authentication

### ISSUE THREAD

**Issue by DCzajkowski** [laravel/passport#799]
## The issue
Creating two personal tokens with the same name and revoking one makes the second one not working.

## How to reproduce (in the UI)
1. Create a Personal Access Tokens called `ABCD`
2. Delete it
3. Create a Personal Access Tokens called `ABCD` again
4. Use it to make an API request

## What is expected?
Valid response should be returned

## What is happening instead?
Response is `{ "message": "Unauthenticated." }`

**Comment by driesvints** [comment]
Heya, thanks for sending this in. This works fine for me. Can you please update to the latest Laravel and Passport versions and check if the problem still happens?

**Comment by DCzajkowski** [comment]
WOW, it seems like Grammarly extension for Chrome breaks this modal. So what happens, is when you: create a token, press in the textarea, `cmd+a`, `cmd+c`, close modal, create whatever new token, old token persists in the textarea, even though it changed in the Vue component and in the DOM. Disabling Grammarly solves the issue.

I'm wondering if we can solve this on the framework level, by removing it from DOM instead of hiding with `display: none`.

**Comment by driesvints** [comment]
Since this problem is related to an extension we're probably not going to add anything in to disable that behavior, sorry.

**Comment by DCzajkowski** [comment]
Yeah, I get that, but Grammarly [has 6.9 million daily users](https://medium.com/swlh/how-grammarly-quietly-grew-its-way-to-6-9-million-daily-users-in-9-years-88e417dbfbdf), so the problem is on a large scale. Solution is pretty simple: there is an attribute `data-gramm_editor="false"` when appended to a textarea disables the extension. Maybe it's worth considering

**Comment by driesvints** [comment]
Sure but there's more extensions which are used even more. We won't be adding any extension specific functionality. If you really want this you can always override the Vue components.

**Comment by DCzajkowski** [comment]
I understand where you're coming from, but this issue may affect many users. Just something to consider 😉 Thanks for your time and work for Laravel 😊

**Comment by driesvints** [comment]
No worries. Appreciate you reporting it! 🙌
