### ISSUE TITLE
To get the access token that the refresh token was originally associated with in laravel

### ISSUE THREAD

**Issue by anususmi** [laravel/passport#800]
I am trying to get access token that was associated with refresh token in laravel. When the access token get unauthenticated i wand to get access token from calling refresh token.
Anyone help with this issue.
Thanks in advance.

**Comment by anususmi** [comment]
https://github.com/laravel/passport/issues/71

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
