### ISSUE TITLE
Passport won't throw error when CreateFreshApiToken fails

### ISSUE THREAD

**Issue by eaguad1337** [laravel/passport#806]
If you change your user_id column type to varchar for example and you do not update passport migrations you will get always an "Unauthenticated" message instead of "Cannot create Fresh Token because you defined a different column type for your model".

**Comment by Lander20** [comment]
Thanks,  looking forward to hearing from you ....

**Comment by driesvints** [comment]
I don't really see why this is a bug. It should be pretty obvious that if you don't use an integer for your user ids that you should update your Passport migrations as well.

I do however agree that this could be a note for the docs. I'll send in a PR later to add a note for the migration part about user ids.

Thanks for reporting.
