### ISSUE TITLE
How to issue an auth code for a user

### ISSUE THREAD

**Issue by gildebrand** [laravel/passport#809]
I've been going through the source code and reading through the documentation without getting this to work. I want to issue an auth code for a given user, that the user can exchange for an access token. I want to send the auth code in a welcome email.

How do I issue an auth code for a given user?

**Comment by rcovar00** [comment]
Passport can't send an email with the auth code. And I think that you should not send the auth code by email. Please read how is the flow in OAuth2 with authorization code grants, https://tools.ietf.org/html/rfc6749#section-1.2

Passport provides an implementation of this flow, you can find the endpoints here https://laravel.com/docs/5.6/passport#requesting-password-grant-tokens

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
