### ISSUE TITLE
FR: make used model configurable

### ISSUE THREAD

**Issue by kalessil** [laravel/passport#812]
Currently the only way to replace models is to use static functions:
```php
        Passport::useTokenModel(Token::class);
        Passport::useClientModel(Client::class);
        Passport::useAuthCodeModel(AuthCode::class);
        Passport::usePersonalAccessClientModel(PersonalAccessClient::class);
```

It works, but often conflicts with Coding Standards in companies.

It would be great to have configuration settings introduced ('models' => ['token' => ..., ...]), which enables implicit configuration and reduces amount of runtime magic.

**Comment by driesvints** [comment]
Hey @kalessil. Unfortunately we cannot account for every single coding standard in a company. This is how the Passport api works so you'll have to use it this way. 

If you want to work around this you can always move these usages to a separate class which is implemented by an interface so these implementations aren't in your main codebase.
