### ISSUE TITLE
Laravel Passport personal access token scope middleware

### ISSUE THREAD

**Issue by nuocgansoi** [laravel/passport#815]
- Laravel Version: 5.7
- PHP Version: 7.1.3
- Database Driver & Version: MariaDB 10.0.36

### Description:
**Laravel version 5.4:**
`Route::middleware(['scopes:api', 'auth:api'])`
work.

**Laravel version 5.7:**
`Route::middleware(['scopes:api', 'auth:api'])`
result: `{"message":"Unauthenticated."}`

When I check on `Laravel\Passport\Http\Middleware\CheckScopes::handle()`
`$request->user()` is null

**Laravel version 5.7:**
`Route::middleware(['auth:api', 'scopes:api'])`
work.

I think someone need this.

**Comment by driesvints** [comment]
Heya, thanks for reporting. Even though it seemed to work before, it makes more sense to first check for authentication and then for scopes so I don't consider this to be an actual bug.
