### ISSUE TITLE
Passport protected api access for mother application 

### ISSUE THREAD

**Issue by AbhayLodhi** [laravel/passport#818]
Hi sir i want to consume my apis for my own website, i follow all the steps give in doc and create api successfully and they work fine when i test them through postman tool. but i want to access these apis for my personal use without any authentication process on my site.

```php
Route::group([
    'namespace'=>'Product',
    'prefix'=>'product',
    'middleware' => 'auth:api'
],function(){
    Route::get('all','ProductApiController@allProducts');
});
```

when i comment the auth:api middleware then it return data as axios responce,but if i do this everyone can consume my api link without any auth process.

**Comment by qWici** [comment]
@AbhayLodhi its wrong way. Use Postman variables for set token to environment. Add this code to u login request.
```
var jsonData = JSON.parse(responseBody);
pm.environment.set("access_token", jsonData.token);
```
Then on "Authorization" tab choose "Bearer Token" and set this
```
{{access_token}}
```

Now you are just beginning to work with Postman send a login request and you will automatically have a token saved.

**Comment by driesvints** [comment]
>  but i want to access these apis for my personal use without any authentication process on my site.

It's either protected by the `auth:api` middleware or not. You can't have an unprotected route and then expect others not being able to access those routes.

You can use the `CreateFreshApiToken` middleware to issue a JWT for your api to consume when a user is logged in. This should make your API calls pass on a default Laravel installation. See https://laravel.com/docs/5.7/passport#consuming-your-api-with-javascript
