### ISSUE TITLE
auto logout

### ISSUE THREAD

**Issue by robertnicjoo** [laravel/passport#822]
I am using Laravel with vuejs and passport for authentication.

So i have a route group in my` api.php` file like:

```php
Route::group(['middleware' => 'auth:api'], function(){
//routes
});
```

The problem with this group is that is returning `401 error`.

## Why?

I guess my when my session  is expired and it return 401 error (while user is not aware of it).

# Question

- What should I do in order to logout user after session has expired so the next time user visits my site not get into `401 error` and know he/she is already logged out and need to login again?

### PS

I've made a middleware in order to check `session lifetime` and logout user if it's expire, but i can't get  lifetime value out of it.

```php
public function handle($request, Closure $next)
    {
        if ((time() - Session::activity()->put()) > (Config::get('session.lifetime') * 60))
        {
            $request->session()->flush(); // remove all the session data
            Auth::logout(); // logout user
        }
        return $next($request);
    }
```

Any idea?

**Comment by amitavroy** [comment]
Well robertnicjoo, i am assuming that you have a Laravel app and inside that, you have your vue app running. If that is the case, I would suggest you to wrap the axios call inside a common helper and in the catch of that helper, whenever you get a 401 you can either logout the user by doing the form submit how the logout button in Laravel is done. Or you can trigger an even and give user a pop up to login.

If you are working on an spa, then create that helper and on 401 just hit your logout route.

Let me know if this solution works for you.

**Comment by driesvints** [comment]
You'll indeed have to catch this in your JS. If you have the refresh token you can refresh the auth token to make new requests. See https://laravel.com/docs/5.7/passport#refreshing-tokens

**Comment by Haritsinh** [comment]
@driesvints this issue shouldn't be closed, why can't we just logout using Refresh Token?, i can do it in JWT already, but in passport i have to first refresh token and get access token and after that new access token i can logout, why can't i simply logout using refreshToken? please help someone.
