### ISSUE TITLE
401 Unauthorized on a fresh laravel install with existing database

### ISSUE THREAD

**Issue by obb12** [laravel/passport#824]
i created a new laravel app
followed the docs
and now its saying this on both Laravel Framework 5.7.3
Laravel Framework 5.5.43 (this is my current app)

**Comment by ajthenewguy** [comment]
Upgrade to Laravel 5.6 (at least) and upgrade Passport to 6.0.7 (if you use laravel/dusk: 4.0.0). Just follow the [Laravel upgrade guide](https://laravel.com/docs/5.6/upgrade); you will have to call a new Passport method in AppService Provider (I added it to the boot() method).

**Comment by obb12** [comment]
I did update to Laravel 5.7.3 like I said

**Comment by obb12** [comment]
what should i do next?

**Comment by obb12** [comment]
should i delete the ouath tables?

**Comment by lanphan** [comment]
please refer to this document in case you want to setup auth:
https://laravel.com/docs/5.7/passport

**Comment by obb12** [comment]
I did all that
I created
A database called test
And still

On Oct 14, 2018 18:18, Lan Phan <notifications@github.com> wrote:

please refer to this document in case you want to setup auth:
https://laravel.com/docs/5.7/passport

**Comment by lanphan** [comment]
1/ you got 401 for your web page, or for your ajax call?
2/ what's config in your config/auth.php ?
3/ what's content of your 'web' middleware group?
4/ do you have HasApiTokens trait for your User model?
5/ Would you please take a screenshot / detail about your request / response here, especially about cookie, csrf ...?

**Comment by obb12** [comment]
Ajax call
API token with auth works
Only setting the jwt cookie doesn't work and I have all the correct driver and middleware settings

On Oct 14, 2018 20:49, Lan Phan <notifications@github.com> wrote:

1/ you got 401 for your web page, or for your ajax call?
2/ what's config in your config/auth.php ?
3/ what's content of your 'web' middleware group?
4/ do you have HasApiTokens trait for your User model?
5/ Would you please take a screenshot / detail about your request / response here, especially about cookie, csrf ...?

**Comment by lanphan** [comment]
check this https://github.com/laravel/passport/issues/810 to see you did use other config or not (like csrf, cookie serialization)

**Comment by driesvints** [comment]
Please provide more info: responses from your api, headers, routes you're calling, JS you're using to call your API.

**Comment by obb12** [comment]
Now it works im on laravel 5.7 but on 5.6 it didnt work

**Comment by obb12** [comment]
@driesvints
