### ISSUE TITLE
How to add a redirectUrl to the login url?

### ISSUE THREAD

**Issue by stesvis** [laravel/passport#827]
When I try to access a page that is protected by Auth i am redirected to the login page.
After i successfully log in, i am always redirected to /home.

Is it possible, and how, to be redirected to the original url that i was trying to access?
Thanks

**Comment by driesvints** [comment]
Correct me if I'm wrong but I believe this was solved with this PR: https://github.com/laravel/laravel/pull/4805

Feel free to reach back if this is still a problem after implementing this change.
