### ISSUE TITLE
Solved axios authenticated issues for Larevel 5.7  + passport 7.0 

### ISSUE THREAD

**Issue by xiaolp** [laravel/passport#830]
If anyone occur the unauthenticated issue  at axios response 
message:{Unauthenticated}
try to add  this line           **\Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,**
add your default web middleware

    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
           \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,

        ],

**Comment by driesvints** [comment]
There's already docs about this: https://laravel.com/docs/5.7/passport#consuming-your-api-with-javascript

Please only use the issue tracker to report bugs or problems.
