### ISSUE TITLE
auth()->user() returns null on production but works in local

### ISSUE THREAD

**Issue by sharik709** [laravel/passport#833]
When i'm making ajax request. ```auth()->user()``` returns data on local dev area but when same code is uploaded to production. It returns 401 not authenticated and values of ```auth()->user()``` and other auth function returns null. but if I do auth()->check() on page reload it returns true. Problem is only when i make ajax request.

Below is a image of headers sent vie axios.
https://ibb.co/dQnUwp

```
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],
```

I've been stuck here from 2 days. Still not able to solve it. Please help.

**Comment by ZaidBarghouthi** [comment]
Have you tried `auth('api)-user()` ?

**Comment by lanphan** [comment]
Which version you're using (Laravel, Passport)?

I've just upgraded my Laravel from 5.6 to 5.7 (along with Passport 7.x), and all my authentication works well after some modifications following document here: https://laravel.com/docs/5.7/passport

2 main points:
1/ use auth:api middleware to authenticate all apis
2/ add CreateFreshApiToken to web middleware group, it'll help to include JWT token in cookie
'web' => [
    // Other middleware...
    \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
],

HTH.

**Comment by driesvints** [comment]
The screenshot you posted are headers from your local test env. Try at least to update the `Accept` header to `application/json` so the web app returns JSON for your client side to consume.

We'll need more info for this. Please post more code snippets from the parts that fail.

Going to close this off but feel free to respond if this is still a problem and I'll re-open.

**Comment by nesinervink** [comment]
Sorry to reopen an old topic, but I have been stuck on exactly the same situation for a couple of days, so I thought it might save some time for someone else.
I had same PHP/SQL major versions in both dev and production environments and yet in production env `Auth::User()` always produced `null`, with 6.4, 7.x and 8.x versions. The only significant difference that I did not take in for account was PHP running in FastCGI wrapper in production and that little note: https://laravel.com/docs/8.x/authentication#a-note-on-fastcgi
