### ISSUE TITLE
Passport for personal client auth:api returns Unauthenticated

### ISSUE THREAD

**Issue by danyal14** [laravel/passport#834]
Hi,

It's about now a week, I am trying to implement Passport with --personal client 
"laravel/framework": "5.6.*",
 "laravel/passport": "^7.0",

Followed https://laravel.com/docs/5.6/passport#personal-access-tokens

/api/login works fine and return token. But when requesting /api/user with headers as following

curl -X GET \
  http://content-api.local/api/user \
  -H 'Accept: application/json' \
  -H 'Authorization: Beraer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjI2YjlmYjhiYmI2OWYxM2IzOWFmYWVkNjE4NGI3NmQ4NTY4Yzk1YzYwMDMzYzI3ZDFmNDkyM2Q1ZjdlZjU3YTQ4OTFiOGMyMzAxY2ViYjE0In0.eyJhdWQiOiIxIiwianRpIjoiMjZiOWZiOGJiYjY5ZjEzYjM5YWZhZWQ2MTg0Yjc2ZDg1NjhjOTVjNjAwMzNjMjdkMWY0OTIzZDVmN2VmNTdhNDg5MWI4YzIzMDFjZWJiMTQiLCJpYXQiOjE1MzcxNDU0MDksIm5iZiI6MTUzNzE0NTQwOSwiZXhwIjoxNTY4NjgxNDA5LCJzdWIiOiIyNSIsInNjb3BlcyI6W119.I9cjdLGP6ugNO_rR0YxZr_zuIeQgdrjr6uaQ3bWoUbYAhEqiV8PsBDpQ1YtXbwDQ_9OjaQ9e92i-XbN1e2SY1WHaMb8ni_5rSSUzZzKXKW1bEHUMUbQ7qsyZdX6Gl3xSVNejungyXKE9rbJ8d_WbRzTm7j-ookkAnzlVKaUinnulKOOAhTYAs7BYaC3-_M9JOr3PoAoq-42UR3yGBmUNAdIkr7Zuh3QFA-P5kO-yfwmEjtdl3FHCkxcbbCKEXrFPKIaRZz39fMOYn62p0XEVu01RjXpja8iRhKPXbXZcVrNIXgAEtIOqv5asbicGvhFi86nxGfoEcOq8SCjS3gP8Qs9i2bVJj9Ys7XuCkR9M5JFdIDgZ4OpEnU2XYUFbe0W0n4l0i2XANSu7VrXzB89VuqWEsVmz8UK2nI06mckS1UbFKZTyASmb1gNIBoVVnokN5XrASbACy0XIhMAb4W7B5L7L995woNWE3k2HFi-VICc591s7OFApL9xdGEEQx5k8J8Dby0Hz9wpAwtMXMcEi-bSc-326sTyi3QTOaGbdrY1zNzL-HVJrXGRdx-8qu1l1bwFS5tmsDnNxUiVzviRPXHUBV1r1nSZpivhINiymfyOZ2Fhe_UvzQRyJksC3SPOf73lqErS-TZ9bs4qbEePWh_9tP0BwBP0JjAa0KkJ3w3U'

This request returns:
{
    "error": "Unauthenticated."
}

I have tried many different suggestions on both Ngiinx and apache but nothing solved.

**Comment by AlexeyTcapaev** [comment]
@danyal14 i think need add Authorization: Beraer $token

**Comment by danyal14** [comment]
@AlexeyTcapaev I am actually doing that already just forgot to put in the post :)

**Comment by xutl** [comment]
AuthServiceProvider file add `Passport::$ignoreCsrfToken = true;`

**Comment by driesvints** [comment]
Use `Bearer` instead of `Beraer`.
