### ISSUE TITLE
Auth via Cookie vs via Header

### ISSUE THREAD

**Issue by AlexeyTcapaev** [laravel/passport#835]
Сan anyone tell what type is better, because now I use authorization with the help of the header, but for this I have cookies that do not httponly look in the direction of authorization through the cookie, because there they are httponly, but came across that if steal app_key then it allows you to send the wrong cookie.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
