### ISSUE TITLE
Requests with different tokens return authenticate same user

### ISSUE THREAD

**Issue by ulfie22** [laravel/passport#836]
I am trying to test my Laravel 5.7/Passport 7.0 API. In my test suite, I sometimes simulate calls from several users to make sure that only users with the correct permissions can access data. Since updating (from 5.0) to 7.0, any API call after the first one will authenticate to the "first" authenticated user.

This gist is a test that can be run on a fresh Laravel 5.7/Passport 7.0 install with no other dependencies. The expected result is that the first two calls to `api/user` would produce unique users and the third request would fail, as it uses a non-existent token. The result I am seeing in all three calls return the first authenticated user.

https://gist.github.com/ulfie22/f42bcba974255e626e828214c1292402

Is there some way to "clear" the headers between calls? Is something getting cached somewhere? I'm not sure if this somehow represents a real security issue but it makes testing my API difficult (where it used to work). Thanks

**Comment by gabrielpeixoto** [comment]
At RequestGuard.php

```
    /**
     * Get the currently authenticated user.
     *
     * @return \Illuminate\Contracts\Auth\Authenticatable|null
     */
    public function user()
    {
        // If we've already retrieved the user for the current request we can just
        // return it back immediately. We do not want to fetch the user data on
        // every call to this method because that would be tremendously slow.
        if (! is_null($this->user)) {
            return $this->user;
        }

        return $this->user = call_user_func(
            $this->callback, $this->request, $this->getProvider()
        );
    }

```

The second request considers that the users was already loaded and returns the user. always the first user.

**Comment by ulfie22** [comment]
Thanks for the response, but I am still confused. The test in the gist shows separate requests with separate headers. I'm not sure why the server would think the requests are from the same user.

**Comment by gabrielpeixoto** [comment]
I guess that all requests are in the same session inside the testAPI method.

I tried this way and it works, could you try? (calling **$this->refreshApplication**)
```
        $u1_response = $this->withHeaders($this->headersWithToken($this->access_tokens['u1']))
            ->json('GET','api/v1/monitoramentos')
            ->assertStatus(200)
            ->decodeResponseJson();

        dump($u1_response);

        $this->refreshApplication();

        $u2_response = $this->withHeaders($this->headersWithToken($this->access_tokens['u2']))
            ->json('GET','api/v1/monitoramentos')
            ->assertStatus(200)
            ->decodeResponseJson();

        dump($u2_response);
```

https://stackoverflow.com/questions/28425830/multiple-http-requests-in-laravel-5-integration-tests

**Comment by driesvints** [comment]
You'll need to separate the calls in different test methods.
