### ISSUE TITLE
PKCE

### ISSUE THREAD

**Issue by ld-gary** [laravel/passport#837]
Given that PKCE is being pushed as a highly recommended strategy, are there plans to offer this flow with Passport? Would be lovely!

**Comment by Sephster** [comment]
It is already supported in League's OAuth2 server so it shouldn't be too hard to enable for Passport. The main thing worth noting is that the implementation in OAuth2 server has been changed for the as yet, unreleased version 8. Might be worth holding off until this is released to make implementation easier in terms of breaking changes

**Comment by Sephster** [comment]
No definite schedule as yet. Version 7 isn't very old so I wouldn't expect this until the end of the year. However, this will largely be dependent on development efforts. Sorry I can't give a more definitive answer at this time.

**Comment by driesvints** [comment]
Thanks for sending this in. I'll flag this as a feature request for now. We could add this once League releases their v8.

**Comment by stanislavhannes** [comment]
I want to implement the feature now, cause the phpleague OAuth Server already support the Authorization Grant Flow with the PKCE key. Any tips or something to consider?

**Comment by Sephster** [comment]
It might help if I give some more information about what the changes are between version 7 and 8 so @driesvints and @taylorotwell can make an informed decision. 

In version 7, there was a flag that needed to be set to enable PKCE. This put the control of PKCE authentication with the server.

In version 8, this flag has been removed. If a client sends a code challenge, PKCE will automatically be enacted, and if not, no PKCE verification will be performed. The caveat to this is that in future, the server will have the option to force public clients to use PKCE. To enable this, there has been a change to the client interface to allow  confidential/public clients to be identified as such.

My best guess at the moment is I will release version 8 around December/January time. Hope this helps

**Comment by james3041983** [comment]
I believe PKCE is now implemented in League @Sephster ? @driesvints would you be open to a PR, or is this something you're already working on?

I think this could be a strong addition with the wiser use of SPA's being used - and possible mobile apps.

**Comment by driesvints** [comment]
Is this released yet? Where is it implemented? Please provide some links. Thanks!

**Comment by atrauzzi** [comment]
Would definitely like to see passport support some more mobile/SPA friendly mechanisms.

**Comment by james3041983** [comment]
In the README.md it states that "PKCE RFC" is implemented?

**Comment by james3041983** [comment]
My bad, I can see that it has some unresolved issues before hitting 8.0.0 release.

**Comment by Sephster** [comment]
Technically there is PKCE functionality in version 7 of the oauth-server already but it had some issues which have been resolved in version 8. The changes in version 8 are breaking but conform better to the spec so I would recommend waiting until version 8 is released.

**Comment by september28** [comment]
The 8.0.0 release is basically going to remove the "enableCodeExchangeProof" flag and have this auto-enabled if a "code_challenge" parameter is supplied with the request.
Couldn't Passport therefore be changed with an "enableCodeExchangeProof" method in Laravel\Passport\Passport? We could then just add this in the AppServiceProvider or AuthServiceProvider alongside Passport::routes(); and Passport::enableImplicitGrant(); etc.
I'm sure the method could check for the presence of the enableCodeExchangeProof variable in league's Grant\AuthCodeGrant to avoid errs in versions >= 8.0.0.
This would mean that we maintain backwards compatibility with league's oauth server versions < 8.0.0. The oauth server version shipped currently is at v7.3.2 which already has fixes for the non-conformant pkce implementation so it looks like the only change to 8.0.0 will be the removal of the enableCodeExchangeProof flag?

Unfortunately, I'm not versed in submitting code to for merge but I'm sure someone could if this was acceptable?

**Comment by matt-allan** [comment]
Based on [this comment](https://github.com/thephpleague/oauth2-server/issues/1004#issuecomment-476621319) and @september28's comment above it sounds like it may be possible to enable PCKE and public client support in version 7?

If it's going to be awhile before V8 is released maybe we should explore that.  I'm seeing a lot of users confused about which grant they use because the only ones passport supports are considered insecure now.

**Comment by Sephster** [comment]
I'm learning the hard way not to estimate these things in public :) As there are enough people asking for this, I will look to see what I can do sooner rather than later.

**Comment by ld-gary** [comment]
> I'm learning the hard way not to estimate these things in public :) As there are enough people asking for this, I will look to see what I can do sooner rather than later.

Development time estimations are where the hardiest of morales go to die! Looking forward to this being rolled out as I'm sure many are...

**Comment by koenhoeijmakers** [comment]
Any info about the 8.0 release?, given the last ETA was around December 2018/January 2019 :)

**Comment by Sephster** [comment]
I've now released version 8 with the updated PKCE implementation. Thanks for everyone's patience. If anyone notices any issues please shout. Cheers

**Comment by driesvints** [comment]
@Sephster thanks. Now we can add this to Passport as well. If anyone wants to get this into Passport, feel free to send in a PR to the master branch.

**Comment by matt-allan** [comment]
I've started working on this. Hopefully I will have a PR up in the next few days.

**Comment by driesvints** [comment]
PR was merged. Thanks @matt-allan!

I'll probably look into releasing a new major version for passport in august somewhere.

**Comment by kevinpijning** [comment]
> PR was merged. Thanks @matt-allan!
> 
> I'll probably look into releasing a new major version for passport in august somewhere.

Do you have a new estimate? 🙈 @driesvints

**Comment by driesvints** [comment]
@kevinpijning I was gonna work in September on Passport but it's been a little too crazy with the 6.0 release the last couple of days 😐

I'll try to get started on it when I get back from vacation in 2 weeks.

**Comment by driesvints** [comment]
Hey @frekel. Sorry, still haven't been able to get to this. I'm gonna try to focus on v8 in November.

**Comment by frekel** [comment]
@driesvints 
Can we re-open this issue? We really want the PKCE!

We all know time is very limited, so just a reminder.... not trying to annoy you!

**Comment by driesvints** [comment]
@frekel it's implemented in the current release (8.x)

**Comment by frekel** [comment]
@driesvints GREAT NEWS!!!
I feel stupid I didn't see the new release :0

**Comment by obaid** [comment]
Is there any example of how to use PKCE in current version?

**Comment by driesvints** [comment]
@obaid https://laravel.com/docs/7.x/passport#code-grant-pkce

**Comment by ld-gary** [comment]
Somewhere down in my cold dead covid-soaked soul I like to think my prompting question played a little part in this, even though I did precisely nothing towards its realisation and the team clearly worked incredibly well to do so. Just want to say thanks to that team for keeping us all in quality framework goodness that makes our dev lives easier and more manageable!
