### ISSUE TITLE
Is there any way to overwrite TransientToken or TokenGuard

### ISSUE THREAD

**Issue by tott** [laravel/passport#838]
I would like to use the CreateFreshApiToken functionality to consume my API, but I would like to still be able to validate the token scopes / permissions the user will get to the API. Is there any way to inject another class than TransientToken to the TokenGuard or what would be the best way to achieve this?
I'd appreciate any pointers, as I could be doing something fundamentally wrong :)

**Comment by xutl** [comment]
我想你可以看看这个 https://github.com/mikemclin/passport-custom-request-grant

**Comment by driesvints** [comment]
You'll have to rebind the routes in `RouteRegistrar`. Anyway, this isn't the best place to ask this. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
