### ISSUE TITLE
Client Access Tokens (machine-to-machine). Does it really work?

### ISSUE THREAD

**Issue by JoaoPortella** [laravel/passport#842]
Laravel v5.7.9
Passport v7.0.2

I've tried everything and nothing works.

Steps to reproduce:
Using Postman.
1 - I log in using my credentials and I get the token normally.
2 - I use this token and I can access dozens of routes with no problems.
3 - When I try to use this same token to GET oauth/clients I get only unauthorized.

**Does anyone have any examples that might help?**

thanks in advance!

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by JoaoPortella** [comment]
Sorry @driesvints , respect his action to close this questioning, but as I said, even following all instructions, this feature simply does not work. And there are several questions about this subject and no solution. So the title of my question is objective. Does it really work? I do not think it's a support issue, but as I said, I respect your positioning.

**Comment by driesvints** [comment]
Ah sorry man. Misread it. Anyway, it seems like others are having this as well so going to keep it closed in favor of those other issues. Otherwise there's only lots of duplicates. I'll try to look into this soon.

**Comment by JoaoPortella** [comment]
many thanks!!

**Comment by cesarrss** [comment]
hey @JoaoPortella i passed soooo much time stuck trying to issuing client (POST oauth/clients). until, yesterday when i tried to read the compiled app.js compiled in public/js, then i search "oauth/clients" and the line that make request uses post('oauth/clients') . Here i change to complete url "localhost/**/public/oauth/clients". and also in get "oauth/clients" to get the list of tokens ID and Secret's created.
And now everything Work Fine... I hope to help with your issue.

**Comment by JoaoPortella** [comment]
This is good news, I'll try. thank you!!
