### ISSUE TITLE
laravel passport auth:api middleware token

### ISSUE THREAD

**Issue by b-cil** [laravel/passport#843]
Hi,

If I'm not wrong, currently a call to an api is processed in a two steps :
1) login user to grant access
2) request the api using the bearer authorisation header

I would be nice if passport could implement a one step only call using the basic authorisation header.

**Comment by driesvints** [comment]
That goes a little beyond what the middleware is trying to do. You can easily store the token during its lifetime so you can re-use it for other requests.
