### ISSUE TITLE
How to convert tokenId into access_token?

### ISSUE THREAD

**Issue by sowork** [laravel/passport#845]
I use passport~4.7 branch. I hope to store the generated access_token into the redis module in the AccessTokenCreated event. I don't know what to do. tks.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Passport 4 isn't supported anymore either. Please use the latest Passport release.
