### ISSUE TITLE
Trying to get property 'revoked' of non-object when Refresh Token

### ISSUE THREAD

**Issue by mustafatoker** [laravel/passport#848]
When i try to retrieve a new token through the refresh token, i get the error that "Trying to get property 'revoked' non-object error at vendor/laravel/passport/src/Bridge/ RefreshTokenRepository.php: 91."

i checked RefreshTokenRepository.php and i realize that $refreshToken variable is an array in isRefreshTokenRevoked method. So we can't access revoked attribute as $refreshToken->revoked because it throws exception. can u help?

**Comment by driesvints** [comment]
The most likely answer is that you're hydrating your query builder results to arrays instead of objects (which is the default in Laravel). What you can try to do is add the following line to your `database.php` file:

```php
'fetch' => PDO::FETCH_OBJ,
```

Which should set it back to the default. Can you try this? Feel free to respond back.

**Comment by mustafatoker** [comment]
it doesn't work. I use mongo. sorry i forgot to mention in first comment. As a temporary solution; I override RefreshTokenRepository class in service provider. I create a new class that extends RefreshTokenRepository class and I override isRefreshTokenRevoked method.

**Comment by mustafatoker** [comment]
> The most likely answer is that you're hydrating your query builder results to arrays instead of objects (which is the default in Laravel). What you can try to do is add the following line to your `database.php` file:
> 
> ```
> 'fetch' => PDO::FETCH_OBJ,
> ```
> 
> Which should set it back to the default. Can you try this? Feel free to respond back.

it doesn't work. I use mongo. sorry i forgot to mention in first comment. As a temporary solution; I override RefreshTokenRepository class in service provider. I create a new class that extends RefreshTokenRepository class and I override isRefreshTokenRevoked method.

**Comment by driesvints** [comment]
Ah ok. Since Mongo isn't an official supported driver I'm afraid we can't help you here.. I think the way you did it atm is the best way to solve this.

**Comment by tejas-k-sb** [comment]
> > The most likely answer is that you're hydrating your query builder results to arrays instead of objects (which is the default in Laravel). What you can try to do is add the following line to your `database.php` file:
> > ```
> > 'fetch' => PDO::FETCH_OBJ,
> > ```
> > 
> > 
> > Which should set it back to the default. Can you try this? Feel free to respond back.
> 
> it doesn't work. I use mongo. sorry i forgot to mention in first comment. As a temporary solution; I override RefreshTokenRepository class in service provider. I create a new class that extends RefreshTokenRepository class and I override isRefreshTokenRevoked method.

Hi, can you elaborate the solution? Even I'm facing the same issue. Thanks

**Comment by uriel2707** [comment]
@mustafatoker https://packagist.org/packages/webdecero/webdecero-package-laravel-passport
