### ISSUE TITLE
One Token Per Client & User Policy

### ISSUE THREAD

**Issue by Sixosable** [laravel/passport#849]
Hi everyone,

I've been playing around with Laravel Passport for a while and something that I've really noticed is that the Passport Server generates a new Token every time you would consume the API for the same user without revoking old ones. I was thinking of this and actually had the following thought:
Wouldn't it be safer and better if every client & user combo would only be able to have one active access_token?

In this way you know there are no other tokens that can be used and revoking access from one token will completely shut off the client from request data from the Passport server.

Either this or something like a per session / per machine token based policy/system could also be a thing.

Just brainstorming. Opinions are welcome.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by arthurlima96** [comment]
Hi, your question can be clarified in this link:
[](https://stackoverflow.com/questions/39881194/allow-one-concurrent-user-per-login-with-jwt)
