### ISSUE TITLE
Passport throws 401 error when no database connection

### ISSUE THREAD

**Issue by roitto** [laravel/passport#853]
Laravel version: **5.7.9**
Passport version: **v7.0.2**

When shutting down the database connection (i did `sudo /etc/init.d/mysql stop` in homestead
) or when there are connection error to the database, the laravel passport throws 401 error.

Should the error be something else? Client application can easily think that there are no valid tokens when there really are.

**Comment by driesvints** [comment]
I think this error is appropriate. If your DB is shut down, you have bigger issues I suppose. At the very least you're not leaking the details of the actual system errors to the consumers of your API so this might even be a better error that a connection error.
