### ISSUE TITLE
Tokens for specific "projects", not users

### ISSUE THREAD

**Issue by joaojoyce** [laravel/passport#856]
Hi,

I recognise that this might not be related to Passport itself, but I'm not sure. Sorry if I'm being intrusive.

I'm trying to implement an API that will be accessed by outside services. But the created tokens would only have access to specific *projects*.
The flow would be something like you would get when you create a Google Maps Token or Stripe tokens:

1. User creates a *project*.
2. The tokens are granted to the *project*, not to the user.
3. Outside services would make requests using that token and they can only affect that specific *project*.

After reading the documentation I was thinking about using Client Credentials Grant tokens but I'm not sure how to correctly scope the tokens to that particular *project*. 

- Is Passport and Client Credentials Grant tokens suitable for this use case? 
- Are the *project* restrictions something that can be done with "Scopes"?
- Should the project restrictions be implemented in another layer outside Passport?

EDIT: I can probably work around this by storing the tokens and extending CheckClientCredentials to add additional checks but I'm not sure if that is the best approach.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
