### ISSUE TITLE
Better Customization

### ISSUE THREAD

**Issue by Sixosable** [laravel/passport#864]
Hi there,

I've been fiddling with Laravel Passport for a while now and decided to look and see how good you can actually customize things with the Passport::useTokenModel() and similar functions.
After using them for a while I found out the following things:
- You're not able to rename certain tables as they are hardcoded (refresh_tokens, auth codes).
- You're not able to change any column names for most models as some things are force filled.
- Not able to change column names due to hardcoding of queries.
- Queries are made based upon tables and not based on the table of the models.

There might be some reason like compatibility with PHPLeague, but I don't see a reason to at least change some things.

## Goal
I'd say the goal of the issue is to making Passport customizable till the level where you only have to define your changes in the migrations, models and maybe some in the config.

## Examples
Hardcoded tables in: Bridge/AuthCodeRepository, TokenRepository, Bridge/RefreshTokenRepository
Force Fill Of Models: Bridge/AuthCodeRepository

Some of these changes are simple, some might need some more in-depth look.

**Comment by driesvints** [comment]
Heya. I agree that the table names shouldn't be hardcoded and should be provided through the model but for the column names I don't think we'll ever make it as flexible as that. That's just the way passport works and it would just require too much changes to allow everything to be customized.

**Comment by ArlonAntonius** [comment]
@driesvints To be honest, I somewhat agree with you and somewhat don't.
I worked on this for a bit, and have been able to customize almost all hardcoded things by adjusting queries, making database queries use default Laravel model queries instead of database queries etc.

You can see the fork / commit here: [ArlonAntonius/passport](https://github.com/ArlonAntonius/passport/commit/62384d64ebcae171a10afb61ddc083950f58e30f)

It's not done yet, but I have the feeling it's going somewhere.

**Comment by ArlonAntonius** [comment]
Got 2 problems before at least the models that are able to be customized with the Passport::useModel, are actually fully customizable.
Would need either a custom scope or magic method in order to get rid of the hardcoded 'expires_at' column dependency.

**Comment by driesvints** [comment]
@ArlonAntonius why do you want to customize these column names?

**Comment by ArlonAntonius** [comment]
@driesvints Was working on the references, might as well go all the way and support adjusting all of them?

In case people want to rename the column to: 'not_valid_after' or whatever.

**Comment by driesvints** [comment]
I don't think that "just in case" is a valid reason. Like I said: this is just how Passport works. Customizing everything just causes too much feature bloat. Let's just keep things simple. We probably won't ever provide that level of customization.

**Comment by ArlonAntonius** [comment]
@driesvints Simple question: How far do you want to go?
I think we should at least:
- Get rid of direct table references
- Use Laravel Model for actions (update for example)

And maybe:
- Remove the hardcoding of some basic column names for example 'id' and 'user_id'? (By using Laravel where methods)
- Prevent setRawAttributes() as it will force the column names? (Otherwise changing the AuthCodeModel has little to no use?)

**Comment by ArlonAntonius** [comment]
Will create a PR for at least the table references when I get back, thanks for all the feedback so far.

> Yes as well although only for updates. I wouldn't swap out the inserts.
Any reason not to swap out the inserts? I mean if we're going to switch the table, might as well switch them to full-on Laravel models and just save/ insert/update them?

At the end of the day, this is the **Laravel** implementation of an OAuth2 Server.

**Comment by driesvints** [comment]
> Any reason not to swap out the inserts?

You could try it everything would still work as before. Then I suppose it's ok. I was thinking it might not work with inserting an ID (see `persistNewRefreshToken` method`) but could be mistaken.

**Comment by ArlonAntonius** [comment]
I'll create several different PR's with each editing only a few things.
@driesvints and Taylor can then decided what PR's they want to accept and which ones not.

**Comment by driesvints** [comment]
@ArlonAntonius can't you just use the Passport model with the `getTable` call like you did in your PR?

**Comment by ArlonAntonius** [comment]
@driesvints Would be possible if the refreshToken model would exist in the first place?
It doesn't exist right now, so we would first have to simply define it, add some basic things.

That's basically what I just did in my [new branch](https://github.com/ArlonAntonius/passport/tree/newrefreshtoken)

Most of it is copied and adjusted from the normal Token model in Passport.

Still working on this.

**Comment by driesvints** [comment]
Ah gotcha. Yeah I think that's appropriate although a bit weird since the model isn't used anywhere.

**Comment by ArlonAntonius** [comment]
I just think it's the appropriate thing to do and the last thing to do before making sure we prevent direct DB queries and start using models as the basis.

Would allow to at least changes 2 DB queries to model queries.
The one in `persistNewRefreshToken` and `isRefreshTokenRevoked`.

It's also one of the last steps in customization I think.

**Comment by driesvints** [comment]
A PR was merged which will allow to customize the refresh token's table/model. This should be the last case of a hardcoded table name.

**Comment by Nyratas** [comment]
Hi!

I'm using custom models & table names for a project, and I'm encountering an issue due to hardcoded table names in [`Laravel\Passport\Bridge\RefreshTokenRepository`](https://github.com/laravel/passport/blob/7.0/src/Bridge/RefreshTokenRepository.php#L53). Should I make a PR or is this already planned for a new release soon?

Thanks for the great work, btw!

**Comment by Nyratas** [comment]
Update: the changes made to `RefreshTokenRepository` in the merged PR #966 do not seem to be applied to the file in the `7.0` branch, but they were merged into `master` last February. Is there a reason to this? Is it safe to use the `master` branch instead of the default `7.0`?

**Comment by driesvints** [comment]
@Nyratas you could use dev-master but we can't give any guarantees on it being stable enough until the final v8 release has been made.

**Comment by Nyratas** [comment]
Hi @driesvints,

Thanks for your feedback. Do you have an idea when v8 will be released?

Greetings from a fellow Belgian! :)

**Comment by driesvints** [comment]
I'll try to focus on v8 in November but not sure yet when it'll be released.
