### ISSUE TITLE
How to manually set and verify token?

### ISSUE THREAD

**Issue by zzzeee** [laravel/passport#878]
Hi~

Does passport provide a way to set token strings ?

`The same when you verify your account password`
```PHP
Auth::attempt([
    'email' => $email,
    'password' => $password,
]);

// eg:
Auth::attempt([
    'token' => $token,
]);
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
