### ISSUE TITLE
Key path "file:///secret/oauth-private.key" does not exist or is not readable Error on Homestead

### ISSUE THREAD

**Issue by ligne13** [laravel/passport#880]
Hi,

I'm trying to use the `Passport::loadKeysFrom` feature but I get the following error :

```
LogicException  : Key path "file:///secret/oauth-private.key" does not exist or is not readable
at /vendor/league/oauth2-server/src/CryptKey.php:45
```

However my `secret`directory has the same permissions than the default `storage`directory :

```
drwxr-xr-x 1 vagrant vagrant    136 Nov 13 11:56 secret  
drwxr-xr-x 1 vagrant vagrant    238 Nov 13 11:54 storage
```

And of course the files `oauth-private.key` and `oauth-public.key` do exist in the `secret` directory.

As both directories have already the same permissions, what can I do ? is this a bug in the /league/oauth2-server/src/CryptKey.php file ?

thanks

**Comment by Sephster** [comment]
I suspect this is a permissions issue. As you are using vagrant, I presume you are currently developing this locally. Can you temporarily change your permissions to 777 to see if the problem persists? This should confirm whether or not it is a permissions issue.

I suspect that the user your web server is running on doesn't have permissions to access the files.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
