### ISSUE TITLE
Why can't I set the personal token expiration time. 

### ISSUE THREAD

**Issue by noecs** [laravel/passport#881]
Why can't I set the personal token expiration time. The expiration time of the traditional web login can be set to 1 month or 1 week. Passprot is set by default for 1 year. Is it too long?What is the secret of this?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
