### ISSUE TITLE
The user adds the access_token custom data

### ISSUE THREAD

**Issue by sowork** [laravel/passport#883]
I want to be able to add extra values when generating access_token, and get access_token by parsing it through some method, such as when a multi-table user logs in, I need to add a token to access_token, and I can get it when the client sends it.thank you

**Comment by driesvints** [comment]
You can overwrite the migrations and a add more columns if you like. The Token is a model which is returned on the user after authentication or when being created you can use the `AccessTokenCreated` to retrieve it and update it as you see fit.

Adding extra columns natively in this package is something that has been requested a lot before but will not happen anytime soon, sorry.

**Comment by sowork** [comment]
What I might describe as problematic is that I want to get other values through JWT without going through the database.

For example, the rule + custom data generated for JWT might provide a method for me to add?

**Comment by sowork** [comment]
```
trait AccessTokenTrait
{
    public function convertToJWT(CryptKey $privateKey)
    {
        return (new Builder())
            ->setAudience($this->getClient()->getIdentifier())
            ->setId($this->getIdentifier(), true)
            ->setIssuedAt(time())
            ->setNotBefore(time())
            ->setExpiration($this->getExpiryDateTime()->getTimestamp())
            ->setSubject($this->getUserIdentifier())
            ->set('scopes', $this->getScopes())
            ->sign(new Sha256(), new Key($privateKey->getKeyPath(), $privateKey->getPassPhrase()))
            ->getToken();
      }
}
```
e.g
access_token = rule(original data)
now :  access_token = rule(original data + custom data)

**Comment by driesvints** [comment]
@sowork ah, I think what you're looking for in this case is https://github.com/laravel/passport/issues/94 ?

**Comment by fredsal** [comment]
https://github.com/thephpleague/oauth2-server/pull/1122

**Comment by driesvints** [comment]
@fredsal can you please not spam multiple issues?

**Comment by fredsal** [comment]
Not spam, just tagging related issues with the PR for easy access
