### ISSUE TITLE
auth:api 401 Unauthorized - TokenGuard::decodeJwtTokenCookie should not decrypt cookie values

### ISSUE THREAD

**Issue by benallfree** [laravel/passport#884]
If anyone is seeing the `auth:api` guard failing with 401 Unauthorized and you have already played with cookie serialization settings, don't worry - you are not crazy.  I think I know why.

I'm not an expert in this area of the framework, but I believe there is a bug in [this line](https://github.com/laravel/passport/blob/7.0/src/Guards/TokenGuard.php#L241) of `TokenGuard` because performs unnecessary decryption. Cookie decryption is handled by `EncryptCookie` middleware, so this code results in duplicate decryption:

```
    protected function decodeJwtTokenCookie($request)
    {
        return (array) JWT::decode(
            $this->encrypter->decrypt($request->cookie(Passport::cookie()), Passport::$unserializesCookies),
            $this->encrypter->getKey(), ['HS256']
        );
    }
```

Should be

```
    protected function decodeJwtTokenCookie($request)
    {
        return (array) JWT::decode(
            $request->cookie(Passport::cookie()),
            $this->encrypter->getKey(), ['HS256']
        );
    }
```

I think this bug was introduced because `TokenGuardTest` generates its own test values rather than using values from `ApiTokenCookieFactory::createToken`. If the test suite consumed values created by `ApiTokenCookieFactory`, this bug would become apparent in testing.

**Problem**

`auth:api` guard fails with 401 Unauthorized

**Diagnosis**

`TokenGuard` is attempting to decrypt cookie values generated by `ApiTokenCookieFactory`, which does not encrypt them in the first place.

**Solution**

1. Update `TokenGuardTest` to use test values produced by `ApiTokenCookieFactory`
2. Remove decryption from `TokenGuard`

See PR #886 for the fix. Previous attempt and discussion in PR #885.

**Comment by benallfree** [comment]
#885

**Comment by benallfree** [comment]
Reopening based on #885 discussion.

**Comment by driesvints** [comment]
FWIW: if I find some time I'll deep dive into this but feel free to add remarks and insights if you find some.

**Comment by benallfree** [comment]
Following up and closing. The issue is that `EncryptCookies` should not be used in the `api` group because it’s supposed to be stateless. 

I’d prefer to see a more compatible solution where cookie middleware can be used, but for now that’s the answer.
