### ISSUE TITLE
Laravel Passport - 401 unauthorised and specifying auth guard?

### ISSUE THREAD

**Issue by Adam-78** [laravel/passport#886]
I have a laravel 5.6.3 application with multiple guards as follows:

auth.php

    'guards' => [
        'web' => [
             'driver' => 'session',
             'provider' => 'users',
         ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],

        'admin' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],

I login using the admin guard.

I add the passport view components to a page only accessible by admin which has the following route: `http://127.0.0.1:8000/admin/passport/`

    <passport-clients></passport-clients>
    <passport-authorized-clients></passport-authorized-clients>
    <passport-personal-access-tokens></passport-personal-access-tokens>

When I load the page with the above components I am getting console errors as follows:

    http://127.0.0.1:8000/oauth/clients 401 (Unauthorized)
    http://127.0.0.1:8000/oauth/tokens 401 (Unauthorized)
    http://127.0.0.1:8000/oauth/personal-access-tokens 401 (Unauthorized)
    http://127.0.0.1:8000/oauth/scopes 401 (Unauthorized)

If I log in using the `web` guard and add the above vue components to a page accessible by web then it works fine.

Looking through the https://github.com/laravel/passport/blob/6.0/src/RouteRegistrar.php you will note the router group only has `web` and `auth` but no option to pass in a guard?

     public function forClients()
    {
         $this->router->group(['middleware' => ['web', 'auth']], function ($router) {
              //...
          });
     }

So the question is how can I get this to work if I'm logged in as admin - in otherwords how can I pass in an authentication gaurd?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by Adam-78** [comment]
Hi,

Already asked on multiple channels without any success:
https://stackoverflow.com/questions/52916900/laravel-passport-401-unauthorised-and-specifying-auth-guard

Is this even remotely possible - defining the auth guard?

**Comment by driesvints** [comment]
There's a feature request open to update middlewares to `['api', 'auth:api']` but I'm not sure if they'll ever get support for custom guards. That also shouldn't be necessary I believe because the clients are always created on a user level.

**Comment by Adam-78** [comment]
It would be useful because you could have two different types of users e.g. Jobseeker and Recruiter - the provider for both would be the users table but you might have different logins for each type of user using a dedicated auth guard:

    'guards' => [
        'jobseeker' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'recruiter' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
     ]

Using the out the box passport vue-components are rendered useless in the above scenario since you cant authenticate against a guard.

**Comment by driesvints** [comment]
@Adam-78 they're using the same provider?

Also: everything for the clients, etc shouldn't have different behavior. That's also a reason why the current middleware should be updated to the api one. It shouldn't behave differently for different types of guards. It's always connected to a user, regardless from what type it is.

**Comment by shawnfromportland** [comment]
I was able to resolve this error that dozens or hundreds of people report online, but none of the existing solutions worked for me. Laravel 5.8, following docs to set up Passport.
In my case, although I was including the csrf token in a meta tag, it was not being picked up as the Passport documentation says laravel will by default. from the docs (https://laravel.com/docs/5.8/passport#consuming-your-api-with-javascript):
>" the default Laravel JavaScript scaffolding instructs Axios to always send the X-CSRF-TOKEN and  X-Requested-With headers. "  
  
and then the example is provided:
```
// In your application layout...
<meta name="csrf-token" content="{{ csrf_token() }}">

// Laravel's JavaScript scaffolding...
window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest',
};
```

Well that would be great if it worked that way by default as the docs state, but in my case I had to explicitly set the axios default to include the contents of said csrf-token meta tag before making the axios request. like this:
```
window.axios.defaults.headers.common = {
						'X-Requested-With': 'XMLHttpRequest',
						'X-CSRF-TOKEN' : document.querySelector('meta[name="csrf-token"]').getAttribute('content')
				};
```  

In my case, this was the only thing that allowed me to get past the 401 unauthorized error, which seems to indicate either A) something in my project's configuration has altered the default behavior of axios requests by not setting them automatically include the csrf-token based on the meta tag if present or B) the docs are inaccurate on this one point, and in the present version of Laravel and Passport that is not the default behavior as stated. 



It sounds

**Comment by jareerzeenam** [comment]
> There's a feature request open to update middlewares to `['api', 'auth:api']` but I'm not sure if they'll ever get support for custom guards. That also shouldn't be necessary I believe because the clients are always created on a user level.
> 
> #379

Thank you so much, this worked !!

**Comment by dmoxyeze** [comment]
> 
> 
> > There's a feature request open to update middlewares to `['api', 'auth:api']` but I'm not sure if they'll ever get support for custom guards. That also shouldn't be necessary I believe because the clients are always created on a user level.
> > #379
> 
> Thank you so much, this worked !!

Please how did you implement this?
