### ISSUE TITLE
How to force passport to request scope when requesting token to oauth/token

### ISSUE THREAD

**Issue by richard457** [laravel/passport#889]
I have implemented OAuth so user can  create login with my service, but I do not want them to leave empty scope field I want to restrict them based on scope what and how can I do that?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
