### ISSUE TITLE
DB error while creating token

### ISSUE THREAD

**Issue by T0miii** [laravel/passport#890]
DB: Oracle
Laravel: 5.7

While i Passport is trying to persist the new Token for the User it gives following error and not creating any toke.

`Error Code : 1722 Error Message : ORA-01722: Invalid Number : 145 Statement : insert into "OAUTH_AUTH_CODES" ("ID", "USER_ID", "CLIENT_ID", "SCOPES", "REVOKED", "EXPIRES_AT") values (:p0, :p1, :p2, :p3, :p4, :p5) returning "ID" into :p6 Bindings : [da3315abd6a4fe597465898a76feb95fdf8e8116ee64c3889516842a6fa7418e4cf3e030fb8f3445,434,1,[],0,2018-11-22 13:00:44,0]`

Not sure if its an oracle issue, or if i am doing something wrong with the Passport setup, but dont think there are lot of things where it could go wrong while setup.

For me it seems there is an additional 0 at the end, not sure why tho. Anyone had a similar issue?

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
