### ISSUE TITLE
Use differente database for 'passport:install' command

### ISSUE THREAD

**Issue by vlauciani** [laravel/passport#891]
Hi all

To test passport, i'm using a `sqlite` database; the command `php artisan migrate` contains the possibility the set differente DB but `php artisan passport:install` doesn't.

For example:
```
# php artisan migrate --database=sqlite
Migrating: 2016_06_01_000001_create_oauth_auth_codes_table
Migrated:  2016_06_01_000001_create_oauth_auth_codes_table
Migrating: 2016_06_01_000002_create_oauth_access_tokens_table
Migrated:  2016_06_01_000002_create_oauth_access_tokens_table
Migrating: 2016_06_01_000003_create_oauth_refresh_tokens_table
Migrated:  2016_06_01_000003_create_oauth_refresh_tokens_table
Migrating: 2016_06_01_000004_create_oauth_clients_table
Migrated:  2016_06_01_000004_create_oauth_clients_table
Migrating: 2016_06_01_000005_create_oauth_personal_access_clients_table
Migrated:  2016_06_01_000005_create_oauth_personal_access_clients_table
#
```
works, but running `php artisan passport:install` I get an error because the default DB is `MySQL` and not `sqlite`. The option `--database=sqlite` on `php artisan passport:install` doesn't work.

My solution is:
- set `DB_CONNECTION=sqlite` in the `.env` file
- run `php artisan passport:install`
- restore `DB_CONNECTION=mysql` in the `.env` file

is there another clean solution?

**Comment by driesvints** [comment]
You could do `DB_CONNECTION=sqlite php artisan passport:install`

**Comment by driesvints** [comment]
Just want to say that the install command isn't meant to be used on different connections, that's why there isn't an option. But the above should give you a good alternative.
