### ISSUE TITLE
Allow to specify the guard provider

### ISSUE THREAD

**Issue by VinceG** [laravel/passport#902]
Will you guys be open for a PR to allow to set a custom guard provider rather than using the default 'api' one?

https://github.com/laravel/passport/blob/7.0/src/Bridge/UserRepository.php#L36

**Comment by driesvints** [comment]
Why would you want to do this? Can you give some more info how this would be useful?

**Comment by VinceG** [comment]
@driesvints Sure. For any application that needs to authenticate more than just the default guard and the default User provider (users table) using passport. 

For example, in our application we have 6 guards and 5 providers. We currently use JWT Laravel Package but would like to transition to Laravel Passport. Right now this seems to be an impossible task since laravel passport hard codes the auth guard it uses. There is no way for us to let passport know we would like to authenticate against a different provider rather than the default 'api' guard and the users provider.

Thank You.

**Comment by driesvints** [comment]
Can you share how you would solve this?

**Comment by VinceG** [comment]
@driesvints Ideally, we should be able to specify it in the 'auth:*' middleware declaration. So we can do 'auth:custom-guard' and Passport will use that guard and it's provider.

**Comment by driesvints** [comment]
Hmm I agree. @VinceG I'm gonna close this in favor of the issue linked by @koenhoeijmakers.
