### ISSUE TITLE
Found an error in the code. File AccessTokenRepository

### ISSUE THREAD

**Issue by andreyukraine** [laravel/passport#904]
Found an error in the code. File AccessTokenRepository public function persistNewAccessToken(AccessTokenEntityInterface $accessTokenEntity) line 64
'expires_at' => $accessTokenEntity->getExpiryDateTime(), 
if you get the key POST link oauth/token get the answer 
"**Call to undefined method DateTime::getTimezone()**".
Replace the line 64 string with  'expires_at' => $accessTokenEntity->getExpiryDateTime()->getTimestamp(),
I ask developers to correct the code. Thanks

**Comment by driesvints** [comment]
I can't really see how this could be broken as this piece of code is being used so much. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
