### ISSUE TITLE
Auth driver [passport] for guard [api] is not defined.

### ISSUE THREAD

**Issue by harishdurga** [laravel/passport#905]
Laravel Version: 5.7.14
Passport Version: ^7.0
In auth.php file:
`'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],` 
When I am trying to access the /api/user via postman I am getting this error.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
