### ISSUE TITLE
Consuming API by Business ID

### ISSUE THREAD

**Issue by Tarcisiofl** [laravel/passport#911]
Hello Everyone,

I have used passport as authenticator in some projects; However, now I got a new scenery where my users can be part of different Business, and they use the same login credentials to access them.
They change from one Business to another by selecting the desire installation.
Therefore, I need a way to associate each token with the selected installation.

Can Passport lead with it?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
