### ISSUE TITLE
Client ID is unsigned, client_ids are signed

### ISSUE THREAD

**Issue by tentus** [laravel/passport#912]
Wait wait wait, this isn't yet another of those requests about changing the key type. I just wanted to point out that the migrations, by default, create _signed_ integers for the `client_id` columns. This is out of line with the `increments` of `id` field in the `Client`, which is unsigned.

We someone to apply foreign keys after the fact, they'd need to change the columns to realign the possible values. This is as simple as calling `$table->unsignedInteger('client_id')->change();`, but it's a step that shouldn't be necessary.

**Comment by driesvints** [comment]
Ah, you're right. Good catch 👍 

I'll try to send in an update for this in.

**Comment by driesvints** [comment]
This was merged on 8.0 and cherry picked on 7.0. We'll probably release a patch soon, in the meantime you can overwrite the migrations.
