### ISSUE TITLE
Laravel API Authentication - Passport Token

### ISSUE THREAD

**Issue by manoelramos** [laravel/passport#915]
I'm building an API using Laravel. For authentication and security I am using Passport: https://laravel.com/docs/5.7/passport

I followed all the steps in the documentation. I am working with several profiles that pass through authentication, and I came across a problem, the token used by a middleware can be applied in other middleware.

In my config / auth.php file it looks like this:

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'user' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],

        'producer' => [
            'driver' => 'passport',
            'provider' => 'producers',
        ],

        'coordinator' => [
            'driver' => 'passport',
            'provider' => 'coordinators',
        ],
    ],

    

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'producers' => [
            'driver' => 'eloquent',
            'model' => App\Producer::class,
         ],

         'coordinators' => [
            'driver' => 'eloquent',
            'model' => App\Coordinator::class,
         ],
    ],

The Coordinator model looks like this:

    class Coordinator extends Authenticatable{

    use HasApiTokens, Notifiable;

    protected $table = 'coordinators';
    protected $guard = 'coordinator';

    protected $fillable = [
        'coordinator_name', 'email', 'password', 'cpf_cnpj', 'phone'
    ];

    protected $hidden = [
        'password',
    ];

    public function events(){
        return $this->belongsToMany('App\Event')->using('App\EventCoordinator');
    }}

And the Model Producer looks like this:

    class Producer extends Authenticatable{
    use HasApiTokens, Notifiable;

    protected $guard = 'producer';

    protected $fillable = [
        'name', 'email', 'password', 'cpf_cnpj', 'phone', 'street', 'neighborhood', 'city', 'state', 'number', 'zipcode', 'complement'
    ];

    protected $table = 'producers';

    protected $hidden = [
        'password',
    ];

    public function events(){
        return $this->hasMany('App\Event');
    }}

On the routes I'm using the middleware set in auth.php

    Route::middleware('auth:producer')->group(function() {
		Route::get('events', 'ProducerController@events');
	});

	Route::middleware('auth:coordinator')->group(function() {
		Route::get('events', 'CoordinatorController@events');
	});

And finally the events method in the CoordinatorController looks like this:

    public function events(){
        try{
            if(Auth::guard('coordinator')->check()){
                $events = Auth::user()->events;

                return response()->json(['events' => $events], 200);
            }else{
                return response()->json(['error' => ['message' => 'Usuário não autenticado.']], 421);
            }         
        }catch(\Exception $err){
            return response()->json(['error' => ['code' => $err->getCode(), 'message' => $err->getMessage()]], 400);
        }
    }

and in ProducerController: 

    public function events(){
        try{
            try{
            if(Auth::guard('producer')->check()){
                $events = Auth::user()->events;

                return response()->json(['events' => $events], 200);
            }else{
                return response()->json(['error' => ['message' => 'Usuário não autenticado.']], 421);
            } 
        }catch(\Exception $err){
            return response()->json(['error' => ['code' => $err->getCode(), 'message' => $err->getMessage()]], 400);
        }
    }

I am using Postman for testing, and when I use the Producer token to access the Coordinator method it works even though using different middleware in the route. Can anyone help? Something is missing?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
