### ISSUE TITLE
Manage Passport Clients Created by Users (Admin Perspective)

### ISSUE THREAD

**Issue by jtomek** [laravel/passport#923]
Hello everybody,

I have been looking for a way to oversee all clients in my applications. Initially, I wanted to reply to this #638 issue, but I think this question needs a separate threat for further reference.

In the #638 issue, @stefro was asking about the relationship between Clients and users and stated that users are not able to view other users' Clients and asked whether this was the expected behaviour. @itsUndefined replied that only the creator of the client can see it and used an example of a Facebook developer. That, of course, makes sense.

**But imagine you are not the end user but a responsible entity, how do you manage all the clients?** 

In my multi-tenant scenario, super users create clients on behalf of their organizations (tenants). All of the super users should know about the Passport Clients of the other super users in their organization and be able to manage them. It goes further with approval workflows that touch also regular users who should be able to read only, etc.; but that is beyond this question and a technicality once this is settled.

How can I manage Clients of the others that with Laravel Passport? Would simply creating a new model be the right way to go about this? What would be the consideration to keep in mind? Or does Laravel Passport ship this out of the box?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
