### ISSUE TITLE
Sudden access_token stopped working

### ISSUE THREAD

**Issue by ClickerTech** [laravel/passport#924]
Hi,

Sudden I am getting 401 even using fresh access_token. I have also tried the test using postman  but each time I am getting 401 {"error":"Unauthenticated."}

this is my route

Route::group([
    'middleware' => 'auth:api',
], function ($router) {
    Route::get('getwallet/{id}', 'UserApi\TransactionController@getWallet'); // ok
    Route::get('getorders/{id}', 'UserApi\OrderController@getOrders'); // ok
});

How to fix

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
