### ISSUE TITLE
Different Token expiration depending of Client Laravel Passport

### ISSUE THREAD

**Issue by loreberti89** [laravel/passport#925]
Hello, 
My questions is a help request.

I'm wondering, if it is possible change a expiration token depending on where I'm trying to make a login:

I have also opened a ticket on StackOverflow for my code.
https://stackoverflow.com/questions/54072921/different-token-expiration-depending-of-client-laravel-passport

What I want is know if is possible set different time expiration for token:

I have web app, android app, desktop app.

I want that tokens for web app will expire in 8h, instead the tokens from android and desktop will expire in 1 year.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
