### ISSUE TITLE
Can't uses policies with passport

### ISSUE THREAD

**Issue by slim1616** [laravel/passport#931]
when i use `$this->authorize('action', $model);` in my controller with web it's ok.
But when i use the same thing with Api middleware it not work.

in my policie class i have this method :

```
public function action(User $user, Model $model){
    return $user->id===$model->user_id;
 }
```

I think that  $user work with web but not with Api.

What do you think?
Have you any idea to resolve this problem?
thanks.

**Comment by koenhoeijmakers** [comment]
Are you using the proper guard? You must use the `auth:api` middleware or else the `web` guard is used, and you're probably not logged in to that when using the api.

**Comment by slim1616** [comment]
I'm using auth:api and I'm logged in.
But ont work.

Normally, it works even with the auth:api middleware?

**Comment by slim1616** [comment]
Hello,
I think that i have a solution : 
I replaced `$this->authorize('action', $model); `
with
`$this->authorizeForUser($request->user('api'),'action', $model);`
now i can pass the current user ($request->user('api')) for check autorisation with auth:api

**Comment by ulcuber** [comment]
What about `client_credentials` grant for `Laravel\Passport\Guards\TokenGuard` (machine-to-machine authentication)?

There is no user when authenticating:
```php
auth()->guard('passport')->user()
```
But there is client:
```php
auth()->guard('passport')->client()
```

If there is no user `Gate` checks as guest for nullable param so possible workaround is optional user:
```php
public function ability(?User $user, Model $model)
```
