### ISSUE TITLE
how to detect bearer token is valid ?

### ISSUE THREAD

**Issue by ShuiPingYang** [laravel/passport#934]
I have login the website,and turn to my home page .but if I Manual change url to login page  ,I want to the program turn to my home page ,but acturlly ,it still want me login , I get bearerToken at the login page ,I want to make a call to api to check if the bearer token valid , how to make that ?
```
    public function checkToken(Request $request)
    {
        $token = $request->bearerToken();
        # how to check if the bearer is valid ?
        return $this->outPutJson();
    }
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
