### ISSUE TITLE
Password Client is secure ?

### ISSUE THREAD

**Issue by christophemassin** [laravel/passport#936]
Hello, 

I've just set up a new api with oauth2 for a mobile app ( android and iphone ). I ve manage to set up the authentification using a password client, client_secret, etc , and i get the token back. 

However, i would like to know if the password is send encrypted or not. When doing my test with postman, i just type the password, same for the app, and i m wondering if they are going through the internet unencrypted, or if there is a magic behind that encrypt them in part of the oauth2 protocol or if i should secure it myself . 

I try to dig into the code of the accessToken, but couldn't find a place where there is a comparaison between the two. 

Thanks a lot !

**Comment by christophemassin** [comment]
thanks for the quick answer ;) 

only relying on https is quite poor as a security measure no ? I would have expected to have an hash or something like that that will simply compare on both side the hash , but not sure it would be the perfect way of doing it ( cause they would have to implement the same method on both side ) .

**Comment by Sephster** [comment]
All the core OAuth grants mandate HTTPS connections. It should be secure as if set up correctly, you should avoid MITM attacks and snooping. I don't think the password grant says anything about hashing the password etc so it would be up to you whether you want to do this or not for added security but https should be protection enough.

**Comment by christophemassin** [comment]
Yeah, i ve got though some documentation / channel, and people all say the same. Thanks for the help !
