### ISSUE TITLE
CreateFreshApiToken uses session token instead of csrf?

### ISSUE THREAD

**Issue by cagabi** [laravel/passport#944]
Hi,

I am having trouble using passport to authenticate api calls in my Laravel 5.7 application. It always return a 401.

Debugging I have found that the problem is that the csrf token encrypted in a cookie (once it is decrypted) doesn't match the csrf header from the request. I know it because I am dumping $this->validCsrf($token, $request) inside the getTokenViaCookie($request) method in [vendor/laravel/passport/src/Guards/TokenGuard.php](https://github.com/laravel/passport/blob/7.0/src/Guards/TokenGuard.php#L224) and it's value is false. 

This is the code in passport/src/Guards/TokenGuard.php:
```   
protected function getTokenViaCookie($request)
    {
        // If we need to retrieve the token from the cookie, it'll be encrypted so we must
        // first decrypt the cookie and then attempt to find the token value within the
        // database. If we can't decrypt the value we'll bail out with a null return.
        try {
            $token = $this->decodeJwtTokenCookie($request);
        } catch (Exception $e) {
            return;
        }
        // We will compare the CSRF token in the decoded API token against the CSRF header
        // sent with the request. If the two don't match then this request is sent from
        // a valid source and we won't authenticate the request for further handling.
        if (! Passport::$ignoreCsrfToken && (! $this->validCsrf($token, $request) ||
            time() >= $token['expiry'])) {
            return;
        }
        return $token;
    }
```

Having a deeper look into the code, I see that the token encrypted and saved into the cookie [seems to be the session token](https://github.com/laravel/passport/blob/7.0/src/Http/Middleware/CreateFreshApiToken.php#L54). In passport/src/Http/Middleware/CreateFreshApiToken.php:
``` 
public function handle($request, Closure $next, $guard = null)
    {
        $this->guard = $guard;
        $response = $next($request);
        if ($this->shouldReceiveFreshToken($request, $response)) {
            $response->withCookie($this->cookieFactory->make(
                $request->user($this->guard)->getKey(), $request->session()->token()
            ));
        }
        return $response;
    }
```
So it looks like my problem is that the token encrypted is the session one then it gets compared with the csrf header and of course the authentication fails. 

Is this the normal behaviour and I am missing something? Or is it wrong?

Thank you in advance.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
