### ISSUE TITLE
Silent error can occured when executing getTokenViaCookie

### ISSUE THREAD

**Issue by 100terres** [laravel/passport#947]
When using the api authentication with cookie we might have silent error. The `try/catch` in the `getTokenViaCookie` function on the `TokenGuard` class wraps the `decodeJwtTokenCookie` function, so an error occured while executing `decodeJwtTokenCookie` we won't know about it and it will return 
`{"error":"Unauthenticated."}`.

https://github.com/laravel/passport/blob/aadf603c1f45cfa4bbf954bfc3abc30cdd572683/src/Guards/TokenGuard.php#L224-L228

In my case it took me half a day to understand that the authentication was failling.

```
{
    "message": "Allowed memory size of 134217728 bytes exhausted (tried to allocate 65015808 bytes)",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/var/www/vendor/laravel/passport/src/Guards/TokenGuard.php",
    "line": 218,
    "trace": []
}
```

And I fixed the problem (for now) by adding: `Passport::$unserializesCookies = true;` in my `AuthServiceProvider`;

Anyway, it could be nice to know that something has failed :) (maybe I did something wrong during the install process)

**Comment by driesvints** [comment]
Hmm, yeah maybe we could improve this to log those errors before the return in a different catch.

**Comment by 100terres** [comment]
Maybe something like this?
https://github.com/laravel/passport/blob/afa4ec9047c489b14d18aa704e8ba81c7ac19c2b/src/Guards/TokenGuard.php#L173-L182

**Comment by driesvints** [comment]
Actually no, those are the errors you just want to let fall through. It's the other non-oauth exceptions you want to report.

**Comment by driesvints** [comment]
Going to close this as we've only received one report for this so far. Feel free to PR something if you want.
