### ISSUE TITLE
alway unauthenticated when check middleware scope: cope_name

### ISSUE THREAD

**Issue by lvtrong1993** [laravel/passport#948]
I have login() method
```
 public function login(Request $request)
    {
        $scopes =$this->getScopeString($request->email);
        // dd($scopes);
        $http = new \GuzzleHttp\Client;
        try{
            $response = $http->post(config('services.passport.login_endpoint'),[
                'form_params'=>[
                    'grant_type' =>'password',
                    'client_id' => config('services.passport.client_id'),
                    'client_secret' => config('services.passport.client_secret'),
                    'username'=>$request->email,
                    'password'=>$request->password,
                    'scope' => 'admin-rule'
                ]
            ]);
            return $response->getBody();
        }catch(\GuzzleHttp\Exception\BadResponseException $e){
            //error mesage
    }
```
It work well, i can get access token.
Then, i have an createPost route, that request middleware('scope: admin-rule').
`Route::middleware('auth:api')->post('/createPost ', 'Auth\AuthController@logout')->middleware('scope: admin-rule');`
When i run  createPost route, it alway response 403 status code (unauthenticated).

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
