### ISSUE TITLE
Passport::tokensExpireIn() set 1 year always by default

### ISSUE THREAD

**Issue by Baltimer** [laravel/passport#951]
I've tried to set the token expiration to 8 hours, but it's always set for 1 year.
In AuthServiceProvider:
```
$time = new \DateTime();
$time->add(new \DateInterval('P0Y0M0DT8H0M'));
Passport::tokensExpireIn($time);
```
This is executed when I log in into the application. Then, Laravel starts to build the app and end executing the `build` function ( `Illuminate\Foundation\Application->build`). When this code is executed:
```
if ($concrete instanceof Closure) {
    return $concrete($this, $this->getLastParameterOverride());
}
```
the `PassportServiceProvider->registerAuthorizationServer` is called and inside the `Passport::tokensExpireIn()` is executed at least 5 times, so since it's called without DateTime parameter it sets the tokens expire time to 1 year again.

I've validated that the first time it enters the `tokensExpireIn` function it set's the expiration time correctly, but then it execute the previous code and overrides it by 1 year.

Is there any issue with this or is there any way to set the expiration time after this `registerAuthorizationServer()` function?

**Comment by ankurk91** [comment]
> I've tried to set the token expiration to 8 hours, but it's always set for 1 year.
In AuthServiceProvider:


I don't see any issue.
```php
// AuthServiceProvider
// boot method
Passport::tokensExpireIn(now()->addDays(90));
Passport::refreshTokensExpireIn(now()->addDays(120));
```

![screenshot 2019-01-30 at 5 16 31 pm](https://user-images.githubusercontent.com/6111524/51979310-d5b99a00-24b2-11e9-8e0e-43644f09531f.png)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by gunjan-garanala** [comment]
I am facing the same issue. I have set Expire duration of 15 days, but when I check in DB it always shows expire_at after 1 year. 
![Select  oauth_access_tokens   10 2 1 92   Adminer](https://user-images.githubusercontent.com/16397125/54991804-b38c5600-4fe3-11e9-86b0-b07a124841c4.png)
