### ISSUE TITLE
Unable to access data from custom url

### ISSUE THREAD

**Issue by VirendraArekar** [laravel/passport#953]
I AM CREATING API WITH THE HELP OF PASSPORT FIRST TIME I LOGIN AND GET IT TOKEN BUT HOW CAN I ACCESS MY API URL RESPONSE URL WHEN I TRYING TO GET IT THEN RESPONSE IT SHOW ME UNAUTHORIZED SO WHICH WAY TO AUTHORIZED AND GET IT MY RESPONSE..PLEASE HELP ME

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
