### ISSUE TITLE
Authorization Code grant without client secret

### ISSUE THREAD

**Issue by d-luk** [laravel/passport#955]
I am implementing an OAuth 2.0 flow for my client application, meaning that I'm not able to use a client secret. I was going to implement an Implicit Grant flow until I found out that it is no longer considered best practice:

> It is generally not recommended to use the implicit flow (and some servers prohibit this flow entirely). In the time since the spec was originally written, the industry best practice has changed to recommend that public clients should use the authorization code flow with the PKCE extension instead. ([oauth2.net](https://oauth.net/2/grant-types/implicit/))

So I tried to call my `/oauth/token` endpoint using the Authorization Code grant type without providing the secret, but I got the following response:

```
{
    "error": "invalid_client",
    "message": "Client authentication failed"
}
```

Is there something that I need to change in my code in order to make this work or is this not the correct way to do this?

**Comment by driesvints** [comment]
Here's the PCKE issue: https://github.com/laravel/passport/issues/837
