### ISSUE TITLE
Access tokens: Change scope

### ISSUE THREAD

**Issue by jtomek** [laravel/passport#958]
Hello everybody,

How do you change a scope of a valid access token? I don't want to create a new token, just to add/remove permissions on a working one. I haven't found an answer on the internet.

If not possible out-of-box, do you think it would it be a good workaround to create a new model with the oauth_access_tokens table? 

```
class AccessToken extends Model
{
    protected $table = "oauth_access_tokens";

    protected $hidden = ['id'];

    protected $fillable = ['scopes'];
}

```
to then call it

```
$token = AccessToken::where('id', $tokenId)->first();
$token->scopes = '["manage-jobs","add-deliverables"]';
$token->save();
```

Thanks for any help!
Jakub

**Comment by Sephster** [comment]
Most of the time, you should just request a new token. If you are using the refresh token, you can request fewer scopes than on the original request, but never additional ones. In this situation, you would again, issue a new request from the client.

It should all usually be client driven as they are the ones giving permission.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by SagarNaliyapara** [comment]
@Sephster Is there any way we can migrate existing accessToken with blank (`[]`) scope to (`["*"]`) scope?

**Comment by Sephster** [comment]
No, not that I'm aware of. It would be easier to just generate a new token
