### ISSUE TITLE
ERR_UNSAFE_REDIRECT when redirect_uri point to a Chrome extension

### ISSUE THREAD

**Issue by RobyFerro** [laravel/passport#959]
I've found an issue when I try to authenticate a Chrome extension with a Passport server.
Chrome gives me an ERR_UNSAFE_REDIRECT error when Passport tries to redirect to my callback URL.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
