### ISSUE TITLE
Others grant types

### ISSUE THREAD

**Issue by ilvalerione** [laravel/passport#96]
I noticed that the package doesn't have support for `client_credentials` and `implicit` grant types.

Studying the OAuth2 standard I understand that these two grant types are needed for server to server authorization and are important to give access to our API by external software in a trusted way without user workflow. Furthermore implicit grant type is needed to issue the SDK to give access to external developers to develop frontend application based on our APIs.

Mine is just a curiosity which could also be the same of many others Laravel lovers: "Is the implementation of this grant types in the package to-do list?" 

Or in good Laravel style could be developed a workflow to extend OAuth server capability.

Thanks in advance if you want give us some anticipation.

**Comment by craigpaul** [comment]
The implicit grant type was actually already proposed in #63, but it was closed until thephpleague/oauth2-server#650 was accepted, which was a few days ago. So the pull request just needs to be reopened and merged.

**Comment by samuelvisscher** [comment]
Could anyone reopen this PR?

**Comment by themsaid** [comment]
PR was re-opened.
