### ISSUE TITLE
Using Passport::actingAs in tests

### ISSUE THREAD

**Issue by damcclean** [laravel/passport#960]
Hey,
I'm writing some tests using the `Passport::actingAs` method but I seem to be getting the error `Error: Call to a member function withAccessToken() on int` on the line where my Passport::actingAs stuff is.

This is my code:
```
$user = factory(User::class)->create();
Passport::actingAs($user->id);

$response = $this->get('/api/endpoint');
$response->assertStatus(200);
```

I am doing the same thing on my other tests, but this one just seems to break.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by ynsbleng** [comment]
Passport::actingAs($user);
