### ISSUE TITLE
CreateFreshApiToken don't create the laravel_token cookie

### ISSUE THREAD

**Issue by diar-k** [laravel/passport#961]
I've setup Passport as the documentation says. 
This is my AuthController:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;

class AuthController extends Controller
{
    public function signup(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|string|email|unique:users',
            'password' => 'required|string'
        ]);
        $user = new User([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);
        $user->save();
        return response()->json([
            'message' => 'Successfully created user!'
        ], 201);
    }

    public function signin(Request $request)
    {
        $request->validate([
            'email' => 'required|string|email',
            'password' => 'required|string'
        ]);
        $credentials = request(['email', 'password']);

        if(!Auth::attempt($credentials))
            return response()->json([
                'message' => 'Unauthorized'
            ], 401);

        $user = $request->user();
        $tokenResult = $user->createToken('Personal Access Token');
        $token = $tokenResult->token;
        $token->save();

        return response()->json([
            'message' => 'Successfully signed in!',
            'access_token' => $tokenResult->accessToken,
            'token_type' => 'Bearer'
        ])->cookie('access_token', $tokenResult->accessToken);
    }

    public function signout(Request $request)
    {
        $request->user()->token()->revoke();
        return response()->json([
            'message' => 'Successfully signed out!'
        ]);
    }

    public function test() {
        return response()->json([
            'message' => 'test'
        ]);
    }

    public function testtwo() {
        return response()->json([
            'message' => 'test'
        ]);
    }
}
```

And yes I have `    \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,` in Kernel.php.

No matter what I do I still dont get any cookie called "laravel_token". I login successfully. Then send a useless GET request to see if I get the "laravel_token" but to no success. I even created a cookie called "access_token" to see if there was a problem with cookies overall but no. I get the access_token in cookies. Does anyone have any clue why this isnt working properly?
I am using Angular 6 by the way.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

Also please check https://github.com/laravel/passport/issues/914 & https://github.com/laravel/passport/issues/564
