### ISSUE TITLE
Best way to ignore token expired exceptions being reported?

### ISSUE THREAD

**Issue by robjbrain** [laravel/passport#962]
What's the best way to avoid token expired errors being reported? If you've got an SPA then everytime someones token has expired it will fill up your log files/bugsnag etc.

It felt like a bad idea to add `OAuthServerException` to `$dontReport` in `Exceptions\Handler.php` since it handles alot of different types of error.

Instead I overwrote the `shouldntReport()` method like so:

```php
    /**
     * @param  \Exception  $e
     * @return bool
     */
    protected function shouldntReport(Exception $e)
    {
        // Do not report expired token errors
        if ($e instanceof OAuthServerException) {
            $ignoredCodes = [
                'invalid_refresh_token' => 8,
                'invalid_token' => 9
            ];

            if (in_array($e->getCode(), $ignoredCodes)) {
                return true;
            }
        }

        return parent::shouldntReport($e);
    }

```

Is this the best way to do it? If so I guess this issue will be useful to anyone searching via Google.

If not, what is the best way to stop these errors clogging up the logs? After all, they're not technically errors in the same way as other exceptions.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
