### ISSUE TITLE
Auth-Codes are reusable

### ISSUE THREAD

**Issue by DidierLmn** [laravel/passport#964]
[Section 4.1.2 of the OAuth2.0 spec](https://tools.ietf.org/html/rfc6749#section-4.1.2) states:

> The authorization code MUST expire shortly after it is issued to mitigate the risk of leaks. A maximum authorization code lifetime of 10 minutes is  RECOMMENDED.  
The client MUST NOT use the authorization code  more than once. 
 If an authorization code is used more than once, the authorization server MUST deny the request and SHOULD revoke (when possible) all tokens previously issued based on that authorization code. 

With Laravel-Passport I am however able to reuse the auth-code multiple times to generate multiple access-/refresh-token pairs. All of these token-pairs remain valid as I request more, nor is the auth-code in the database set to revoked or deleted.

**Comment by Sephster** [comment]
The code looks fine on the surface:

```
    public function revokeAuthCode($codeId)
    {
        $this->database->table(Passport::authCode()->getTable())
                    ->where('id', $codeId)->update(['revoked' => true]);
    }

    /**
     * {@inheritdoc}
     */
    public function isAuthCodeRevoked($codeId)
    {
        return $this->database->table(Passport::authCode()->getTable())
                    ->where('id', $codeId)->where('revoked', 1)->exists();
    }
}
```

There are no auth codes set to revoke in your entire db? Might be worth checking the `$codeId` being passed

**Comment by DidierLmn** [comment]
Thanks for the quick reply, it indeed appears to have been an issue on my part. 
In the model-overrides I used UUIDs, but the `$codeId` passed was not the UUID set in the DB, but rather the ID Laravel-Passport generated.
I will not use UUID for the AuthCodes anymore as that seems the simplest solution right now.

Thanks again.
