### ISSUE TITLE
Call to undefined method Illuminate\\Auth\\GenericUser::withAccessToken()

### ISSUE THREAD

**Issue by filjoseph1989** [laravel/passport#970]
I followed most of the set up as documented here: https://laravel.com/docs/5.5/passport

I have this class below and with registered url or route like  `http://my-local-domain.oo/api/v1/transaction/?id=1`

```
<?php

namespace HurricaneMedia\CrateClub\API\Http\Controllers;

use Corals\Foundation\Http\Controllers\BaseController;
use Corals\Modules\Subscriptions\Models\Plan;
use HurricaneMedia\CrateClub\Subscriptions\Classes\Subscription;
use HurricaneMedia\CrateClub\API\Http\Resources\APITokenResource;
use HurricaneMedia\CrateClub\API\Classes\TransacttionApi;
use HurricaneMedia\CrateClub\API\Http\Resources\TransactionResource;
use HurricaneMedia\CrateClub\API\Http\Resources\TransactionResourceTotalRefund;
use HurricaneMedia\CrateClub\CCPayments\Models\CCPayment;
use Illuminate\Http\Request;

class TransactionApi extends BaseController
{
    /**
     * Create instance
     */
    public function __construct()
    {
        $this->middleware('client');
    }

    /**
     * Return json data based on the given request
     * 
     * @param  Request   $request  
     * @param  CCPayment $ccpayment
     * @return Illuminate\Response
     */
    public function show(Request $request, CCPayment $ccpayment)
    {
        $ccpayment  = new TransacttionApi($ccpayment);

        if ($request->has('id')) {
            $id = $request->input('id');
            $ccpayment = $ccpayment->showUsingPlainId($id);
        }

        $ccpayment = $ccpayment->get();

        return TransactionResource::collection($ccpayment);
    }
}
```
I setup personal access token and put it in header request
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGc..
accept: application/json

Now using insomnia application for testing API I submitted a get request to `http://my-local-domain/api/v1/transaction/?id=1` locally and it returned the expected output. Locally I have this php version `PHP 7.3.2-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:43:57) ( NTS )`.

But using the same setup, `http://my-staging-domain/api/v1/transaction/?id=1` on staging in our part we called it dev instead. Here we have php version `PHP 7.1.20-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jul 25 2018 10:07:09) ( NTS )`

Got this response

```
  "message": "Call to undefined method Illuminate\\Auth\\GenericUser::withAccessToken()",
  "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
  "file": "path/to/vendor/laravel/passport/src/Guards/TokenGuard.php",
  "line": 148,
  "trace":
```

I know this is not a good idea but I tried to update the `\laravel\passport\src\Guards\TokenGuard.php`

this line `return $token ? $user->withAccessToken($token) : null;` to 

```
if ($token) {
    if (function_exists('withAccessToken')) {
        return $user->withAccessToken($token);
    }
}

return null;
```

And it worked! it return data that I need. But the problem of this is not always there every time I deployed on staging/dev environment or composer update.

I think its a bug

**Comment by driesvints** [comment]
You're using outdated docs (5.5). Can you try again with the latest docs? https://laravel.com/docs/5.8/passport

What Laravel version are you on?

**Comment by filjoseph1989** [comment]
I am using laravel 5.5.38

**Comment by filjoseph1989** [comment]
I know the problem now, I just make sure

the in config/auth.php

in 

```
'users' => [
            'driver' => 'eloquent',
            'model'  => User::class,
        ],

```
'model' is correctly set to the right user class
