### ISSUE TITLE
The resource owner or authorization server denied the request

### ISSUE THREAD

**Issue by ultimateakash** [laravel/passport#978]
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "hesto/multi-auth": "^2.0",
        "laravel/framework": "5.6.*",
        "laravel/passport": "^7.0",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "^5.6",
    },

Hello everyone.
I am getting this issue. please help me

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
