### ISSUE TITLE
Generate cookie name out of the app's name by default

### ISSUE THREAD

**Issue by andriihorpenko** [laravel/passport#981]
## Brief overview
The main purpose of this feature is to make Laravel Passport more "unified" with the main application.
## Detailed
The session token name is generating with the following formula:
`Str::slug(env('APP_NAME', 'laravel'), '_').'_session'`
And this is how the Passport is "making" the name:
`public static $cookie = 'laravel_token';`

Why not implement this thing to the Passport by default? This will likely remove most "cookie name override" needs.

Thanks in advance.

**Comment by driesvints** [comment]
Yeah, I could see the benefit here.

**Comment by driesvints** [comment]
Closing as the related PR was closed.
