### ISSUE TITLE
JWT encryption

### ISSUE THREAD

**Issue by juanm18** [laravel/passport#983]
I am using `laravel/passport` as a means of authentication for an `API` i am working on. I want to encrypt my access_token when it is generated. I have been looking over the documentation but there isn't a clear example on how to implement that. i have generated the private/public keys and stored them in `/storage/oauth-*` but not sure where to go after that. any ideas or link to examples?? Thanks!

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
