### ISSUE TITLE
Can't install laravel/passport in combination with sentry-laravel

### ISSUE THREAD

**Issue by Christophvh** [laravel/passport#988]
Hi,

I just updated to laravel 5.8 and can't seem to install passport:

It seems that Sentry-php requires zendframework/zend-diactoros ^1.4: https://github.com/getsentry/sentry-php/blob/master/composer.json

Is their something stopping passport from upping the zend-diactoros version? 

 Problem 1
    - Conclusion: don't install laravel/passport v7.2.1
    - Conclusion: remove zendframework/zend-diactoros 2.1.1
    - Installation request for laravel/passport ^7.2 -> satisfiable by laravel/passport[v7.2.0, v7.2.1].
    - Conclusion: don't install zendframework/zend-diactoros 2.1.1
    - laravel/passport v7.2.0 requires zendframework/zend-diactoros ~1.0 -> satisfiable by zendframework/zend-diactoros[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.10, 1.3.11, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.x-dev].
    - Can only install one of: zendframework/zend-diactoros[1.3.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.1, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.10, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.11, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.2, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.3, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.4, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.5, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.6, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.7, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.8, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.3.9, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.4.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.4.1, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.5.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.6.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.6.1, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.7.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.7.1, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.7.2, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.8.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.8.1, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.8.2, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.8.3, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.8.4, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.8.5, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.8.6, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.8.x-dev, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.0.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.0.1, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.0.2, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.0.3, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.0.4, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.0.5, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.1.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.1.1, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.1.2, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.1.3, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.1.4, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.2.0, 2.1.1].
    - Can only install one of: zendframework/zend-diactoros[1.2.1, 2.1.1].
    - Installation request for zendframework/zend-diactoros (locked at 2.1.1) -> satisfiable by zendframework/zend-diactoros[2.1.1].

**Comment by driesvints** [comment]
If it can be updated without breaking changes you're free to send in a PR to the current stable branch. Otherwise send in a PR to master.

**Comment by driesvints** [comment]
Pushed a commit that allows installation of both ~1.0 & ~2.0. New release should be tagged next tuesday
