### ISSUE TITLE
Potential for adding additional fields to OAuth Clients table

### ISSUE THREAD

**Issue by WyattCast44** [laravel/passport#990]
As always, a huge thanks for all the hard work and care you take in your packages :)

I was wondering if you'd be open to adding additional fields to the oauth_clients table? For example, a description field? Would allow the 'authorize' page to display a little more information about the application the user is considering granting authorization. 

Would love to get some feedback on this idea.

**Comment by driesvints** [comment]
Heya. The migrations are published to your app so you can modify them as you see fit. See "Migration Customization" here: https://laravel.com/docs/5.8/passport
