### ISSUE TITLE
Fire Method in RefreshTokenRepository.php CAUSES Error in L5.8.

### ISSUE THREAD

**Issue by lloy0076** [laravel/passport#991]
USES DEPRECATED FIRE METHOD (see https://laravel.com/docs/5.8/upgrade)

> 10348 [2019-03-19 12:08:50] local.ERROR: Call to undefined method Illuminate\Events\Dispatcher::fire() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Illuminate\\Eve      nts\\Dispatcher::fire() at C:\\laragon\\webroots\\syracuse-design\\calendar\\vendor\\laravel\\passport\\src\\Bridge\\RefreshTokenRepository.php:71)
> 10349 [stacktrace]
> 10350 #0 C:\\laragon\\webroots\\syracuse-design\\calendar\\vendor\\league\\oauth2-server\\src\\Grant\\AbstractGrant.php(449): Laravel\\Passport\\Bridge\\RefreshTokenRepository->persistNewRefreshToken(Object(Laravel\\Passport\\Bridge\\R      efreshToken))
> 10351 #1 C:\\laragon\\webroots\\syracuse-design\\calendar\\vendor\\league\\oauth2-server\\src\\Grant\\PasswordGrant.php(60): League\\OAuth2\\Server\\Grant\\AbstractGrant->issueRefreshToken(Object(Laravel\\Passport\\Bridge\\AccessToken)      )
> 10352 #2 C:\\laragon\\webroots\\syracuse-design\\calendar\\vendor\\league\\oauth2-server\\src\\AuthorizationServer.php(187): League\\OAuth2\\Server\\Grant\\PasswordGrant->respondToAccessTokenRequest(Object(Zend\\Diactoros\\ServerReques      t), Object(League\\OAuth2\\Server\\ResponseTypes\\BearerTokenResponse), Object(DateInterval))

**Comment by driesvints** [comment]
This was fixed in https://github.com/laravel/passport/commit/145c152199ce2020123bd26bbdb0aaed2d86be00 and released in v7.2.0. Please upgrade.

**Comment by lloy0076** [comment]
I just noticed 👍
