### ISSUE TITLE
^3.0 compatibility with dependency broken

### ISSUE THREAD

**Issue by soundsgoodsofar** [laravel/passport#992]
In zendframework/zend-diactoros 1.8.6, they made a breaking change in src/MessageTrait.php

https://github.com/zendframework/zend-diactoros/commit/ee4bcdc43b6d60cd2b1256809903b8620a7257c7#diff-5abca4d9d5693da46d10a54795b1192d

This change means that the following line in ServerBag.php results in an exception being thrown for an empty header.

```php
$headers['PHP_AUTH_PW'] = isset($this->parameters['PHP_AUTH_PW']) ? $this->parameters['PHP_AUTH_PW'] : '';
```

Propose to change that line to:

```php
if (isset($this->parameters['PHP_AUTH_PW'])) {
    $headers['PHP_AUTH_PW'] = $this->parameters['PHP_AUTH_PW'];
}
```

**Comment by driesvints** [comment]
This line seems to be in place in Symfony's HttpFoundation's `ServerBag` class. So it would have to be fixed there instead.
