### ISSUE TITLE
"oauth/token/refresh" always returning unauthenticated

### ISSUE THREAD

**Issue by ujjaldey** [laravel/passport#993]
Hi,
I am trying to use Laravel passport for one of my api based application. I followed the documentation as per the wiki. I am able to login and generate both the access_token and refresh_token using client_id 2. I am able to retrieve the user details using the api api/me. However, whenever I try to refresh the token (even when both the tokens are not expired), I am getting 401 unauthenticated error from AuthenticationException class. Here is my request via postman:

![image](https://user-images.githubusercontent.com/16843102/54752502-56765600-4c19-11e9-9273-7188b058798f.png)

Can anyone please guide me what's wrong and how to fix it? Many thanks in advance.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
