### ISSUE TITLE
Can't install on Laravel 5.8

### ISSUE THREAD

**Issue by livevasiliy** [laravel/passport#994]
I can't install Laravel/Passport package on Laravel 5.8.*
Artisan give me error, when use next command
`composer require laravel/passport`
>Using version ^7.2 for laravel/passport
>./composer.json has been updated
>Loading composer repositories with package information
>Updating dependencies (including require-dev)
>Nothing to install or update
>Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
>Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post->autoload-dump event terminated with an exception
>
>
>  [UnexpectedValueException]
>  Overloading of string functions using mbstring.func_overload is not supported by phpseclib.

I try set value 2 for mbstring.func_overload on my local server (use Laragon last version)
This is my mbstring config current project on laravel 5.8.*
![image](https://user-images.githubusercontent.com/15705591/54809860-eeb61e80-4c9d-11e9-8d7e-c5f246eab358.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
