### ISSUE TITLE
Storing public/private key in .env for Laravel 5.8+

### ISSUE THREAD

**Issue by rennokki** [laravel/passport#997]
I am currently running Laravel app on a multi-node infra and i cannot keep the keys locally, i need to find a way to centralize 'em.

Since 5.8, Laravel got shipped with https://github.com/vlucas/phpdotenv/releases/tag/v3.0.0 - support for multi-line .env, i think that would be a great choice to load the public & private keys from variables in the .env file:

```
PASSPORT_PUBLIC_KEY="------BEGIN PUBLIC KEY-----MJNHFGBASIYEYRA..."
PASSPORT_PRIVATE_KEY="-------BEGIN RSA PRIVATE KEY-----ASFOANasdara..."
```

Any thoughts?

**Comment by driesvints** [comment]
I'm not sure tbh. At one point I'd like to say yes because it's obviously easy to do so but at another point these really are separate key files in essence. It just seems weird to prop everything into an `.env` file.

**Comment by rennokki** [comment]
Seems weird that the env might just get bloated with a spaghetti string. I was thinking that maybe having keys on just one machine and running a command just on that machine to cache the keys during deployment or smth, but this looks like a potential security issue

**Comment by rahimnathwani** [comment]
Storing keys in environment variables is a good option when using a hosting environment without a persistent filesystem (e.g. Heroku).

I'm using the workaround from [this comment](https://github.com/laravel/passport/issues/242#issuecomment-296477065), i.e.

- Storing the keys in environment variables, configured in Heroku's dashboard
- Creating the key files `composer.json` / `post-install-cmd`

**Comment by rahimnathwani** [comment]
@rennokki 
What you're asking for appears to already exist, as of a year ago:
[passport.php](https://github.com/laravel/passport/blob/master/config/passport.php)

**Comment by driesvints** [comment]
@rahimnathwani that's for file paths, not actual keys.

**Comment by rahimnathwani** [comment]
@driesvints It looks like #683 added the ability to store actual keys in those config variables.

**Comment by driesvints** [comment]
@rahimnathwani aha, good find. I'll try to document this 👍
